### ISSUE TITLE
Add loader for Vue.js

### ISSUE THREAD

**Issue by weaverryan** [symfony/webpack-encore#1]

**Comment by mneuhaus** [comment]
Here's the official webpack-simple variant provided by vue-cli that could be used as a starting place: https://github.com/vuejs-templates/webpack-simple/blob/master/template/webpack.config.js

**Comment by ByScripts** [comment]
Is it possible to configure Encore in any way to add Vue Loader manually?

**Comment by ByScripts** [comment]
Ok I managed to make it work. Here is how I done.

I replaced this:

```
module.exports = Encore.getWebpackConfig()
```

With this:

```
let webpackConfig = Encore.getWebpackConfig()

webpackConfig.module.rules.push({
  test: /\.vue$/,
  loader: 'vue-loader'
})

module.exports = webpackConfig
```

Then ran:

```
yarn add vue-loader vue-template-compiler
```

**Comment by weaverryan** [comment]
The latest version now supports vue, including inline styles in .vue files (which is the really tricky part!). Have fun and be dangerous!

**Comment by simonjcarr** [comment]
@weaverryan Can you point me to anywhere tutorial that explains how VueJS can be incorporated into a Symfony 3 app. I'm not sure where to start or what is possible, i.e. can I load .vue files from a controller.

Maybe you could include something on KNP University if there is nothing already out there.

I know that I can just include the vue.js cdn in my head tag and then add Vue code, but I don't get ES2015 or SCSS capabilities.
