### ISSUE TITLE
Vue Component Not Rendering Inside Nested Twig

### ISSUE THREAD

**Issue by Seamus-Ohhhh** [symfony/webpack-encore#1016]
Hey, not sure if this is the correct place to ask, if it's not could I be pointed in the correct direction.

Currently we are looking to transition from Symfony + Twig + JQuery over to Symfony + Vue application. We are looking to remove twig components one by one. We are in the testing phase so just seeing how everything ties together. 

I have created an app entry point using webpack-encore and this is being mounted onto the app div in the base.html.twig file.

If I register a simple vue component in the app.js file and place this in the base twig file it renders perfectly, can add as many instances of the component that I want. 

The issue comes when I add this component into any other twig files that are rendered in the body. When these pages are called the component just shows as a HTML tag with nothing in it. 

app.js
````
import Vue from 'vue';    
import BaseTest from './components/BaseTest.vue';    
Vue.component('basetest', BaseTest);    
new Vue({
	delimiters: ['${', '}$'],
}).$mount('#app')
````

base.html.twig (component displays)
````
<div id="app">
	{% block body %}{% endblock %}
	<basetest></basetest>
</div>
````

example twig (component doesn't display)
````
{% block body %}
<basetest></basetest>
{% endblock %}
````

What is seen in inspector
<img width="1010" alt="Screenshot 2021-07-14 at 18 57 07" src="https://user-images.githubusercontent.com/5973509/125669941-37c304be-984e-498a-ada8-3c1c12bb3345.png">

Any help or even pointing in the right direction would be greatly appreciated.

**Comment by jetzemeilink** [comment]
I'm not that familiar with Symfony but have you thought about using Vue Router to load new Components of the app?

**Comment by Seamus-Ohhhh** [comment]
@jetzemeilink The issue there is that we are replacing sections of the application at a time meaning inside the mounted instance of Vue there has both twig templates and Vue components side by side. I don't know a way to use the router to get this working.

**Comment by Seamus-Ohhhh** [comment]
Closing issue as information not required anymore and it's not a bug. Issue was opened to allow us to use the Vuetify framework within Symfony. As this framework requires the <v-app> component be a parent to all Vuetify components and doesn't support multiple isolated instances of Vuetify on a page. We have chosen not to use Vuetify and instead use multiple isolated instances of Vue to replace current components.
