### ISSUE TITLE
webpack-dev-server@4.0.0-rc.0

### ISSUE THREAD

**Issue by emmanuelballery** [symfony/webpack-encore#1017]
Hi!

`webpack-dev-server@4.0.0-rc.0` is released and I encountered 2 errors when installing a new app using Encore :
1. a doc change : `firewall` was renamed (reported here symfony/symfony-docs/issues/15542)
2. there is no `host` property in the `client` option [see code](https://github.com/symfony/webpack-encore/blob/main/lib/config-generator.js#L606) / [see related issue](https://github.com/symfony/webpack-encore/issues/931#issuecomment-784483725)
![image](https://user-images.githubusercontent.com/1687685/126326534-6c4ff959-4b8a-4128-9e1d-93fc7d4ae647.png)

https://github.com/symfony/webpack-encore/issues/1017#issuecomment-883409898 ~The last one cannot be changed without forcing `webpack-dev-server` to stay at `4.0.0-beta.3`.~

Have a nice day!

**Comment by tocsinde** [comment]
Concerning the second error: I fixed it by using

```

Encore
    .configureDevServerOptions((options) => {
        
        // hotfix for webpack-dev-server 4.0.0rc0
        // @see: https://github.com/symfony/webpack-encore/issues/951#issuecomment-840719271
        
        delete options.client;
    })
```

**Comment by hailwood** [comment]
Just to add on here, deleting `options.client` caused my WS connections to fail,
So instead I had to do 

```js
Encore.configureDevServerOptions(options => ({
    allowedHosts: 'all',
    client: {
      webSocketURL: 'wss://localhost:8080'
    },
}));
```

**Comment by mfu-aroche** [comment]
@hailwood it's strange, @tocsinde workaround is working just fine for us, even with websockets and HMR/hot reload

**Comment by hailwood** [comment]
@mfu-aroche are you accessing your site from a localhost address? E.g. localhost:3000? That would work. My change is needed if you're using a non localhost url like Lando or similar 👍

**Comment by bobvandevijver** [comment]
I'm using the following configuration, which seems to work just fine:

```js
Encore.configureDevServerOptions(options => {
      options.allowedHosts = 'all';
      options.https = {
        cert: '/etc/apache2/ssl/domain.dev/fullchain.pem',
        key: '/etc/apache2/ssl/domain.dev/privkey.pem',
      };

      delete options.client.host;
    })
```

The HMR server is access through https://localhost.domain.dev:8999/.

**Comment by jkabat** [comment]
There seems to be more issues when I have encore in separate container as main application.

For webpack-dev-server@4.0.0 I had to use "setPublicPath" with absolute path + domain, and setmanifestKeyPrefix. I needed to setup --keep-public-path and --client-web-socket-url also, but for some reason I still cant make hot reloading to work...

I have tried almost anything to get rid "...hot-update.json  not found" error...

**Comment by Mareva-dev** [comment]
I've been working on this issue for two days now. I'm using Symfony 5 (webpack-encore) with React JS.

Initially i had the following issue:
![image](https://user-images.githubusercontent.com/78365814/131482680-b0e00cf8-8c41-4ffa-ba10-a3b4bba8c827.png)

I tried a lot of things but last one is : 
```javascript
.configureDevServerOptions(options => ({
        ...options,
        allowedHosts: 'all',
        client: {
          webSocketURL: 'wss://localhost:8080/ws'
        },
    })      
    )
```
But i got 
**WebSocketClient.js:13 WebSocket connection to 'wss://localhost:8080/ws' failed: 
index.js:529 [webpack-dev-server] Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}**

Could you please explain me how to deal with it ?? I'm getting mad over it

**Comment by jkabat** [comment]
@Mareva-dev webSocketUrl should with "ws:" not with "wss:".

**Comment by weaverryan** [comment]
Hi everyone!

Could I have a few of you hack in the fix from #1031 to see if it works for you? 

Thanks!

**Comment by leevigraham** [comment]
@weaverryan 

setting `allowedHosts: 'all',` and implementing the fix in #1031 resolved the start up issues for me.

**Comment by leevigraham** [comment]
@weaverryan My final method looks like:

```
.configureDevServerOptions((options) => {
    options = {
      ...options,
      // firewall: false,
      allowedHosts: "all",
      host: options.client.host,
      https: {
        key: fs.readFileSync(process.env.SSL_KEY),
        cert: fs.readFileSync(process.env.SSL_CERT),
      },
      // liveReload and static are used to reload the whole page
      // when anything in templates changes
      liveReload: true,
      static: {
        directory: path.resolve(__dirname, "templates"),
        publicPath: "/",
        serveIndex: true,
        watch: true,
      },
    };
    delete options.client.host;
    return options;
  });
```

**Comment by jkabat** [comment]
> I have tried almost anything to get rid "...hot-update.json not found" error...

Seems like I'm running into this issue: https://stackoverflow.com/questions/62974405/webpack-hmr-browser-not-outputting-hot-update-json

When I update an asset (with error in console and browser reloading all the time), files are recompiled and hot-update.json is finally generated. It is not generated when containers are launched for the first time... Any help?
