### ISSUE TITLE
[Bug] Some Webpack devServer settings not available: support newer webpack-dev-server versions?

### ISSUE THREAD

**Issue by TropicalRaisel** [symfony/webpack-encore#1023]
Settings like `publicPath` and `writeToDisk` are not available in the dev server API schema used by Webpack Encore.
Maybe this is a design choice, since this project is intended to be used alongside templating engines that support injecting helpers, but it would be nice to configure these options in environments that do not support such engines or do not have any available.

**Comment by versedi** [comment]
`publicPath` is configurable via https://webpack.js.org/configuration/dev-server/#devserverstatic

```
    static: {
      directory: path.resolve(__dirname, 'public'),
      publicPath: path.join(__dirname, 'public'),
      watch: true,
    },
```


Write to disk can be achieved via CopyWebpackPlugin

**Comment by TropicalRaisel** [comment]
Ok; just a couple more quick questions if you don't mind:
1. How can the `index.html` path be updated? I see that the dev server is sending 404 errors to `index.html`, but there is no such file. Trying to create the file at my project root, drive base, and public folder doesn't render the page either.
2. Is the `config.client.host` schema option that causes crashes OOTB going to be removed?
```
  .configureDevServerOptions((config) => {
    // fixes cors header issues
    config.allowedHosts = 'all'

    // https://github.com/symfony/webpack-encore/issues/1017#issuecomment-887264214
    delete config.client.host
  })
```

**Comment by versedi** [comment]
1. Could you provide minimal repository reproducing the issue? 

Encore can be used in pretty much anything, it's up to the user how to implement it. 

2.

```
    config.allowedHosts = 'all'
```

This doesn't resolve CORS issue since few updates of webpack. Use option in headers for dev-server:

```
devServer: {
    https: true,
    headers: {
        "Access-Control-Allow-Origin": "*",
    },
    // ....
}
```

I'm not a maintainer, but I don't use the workaround provided by in the recent issues and it still works for me.

I need to dig deeper if it's dependency matter of its config related, will update soon.

**Comment by TropicalRaisel** [comment]
1. All I'm saying is that when serving the dev server, `index.html` is set to handle 404 errors, and I'm not sure how to change its path or filename. That's what I want to know how to solve.
2. If you're referring to the client host variable deletion, that needs to stay in for me. My project is here if that helps: https://github.com/TropicalRaisel/django-encore-webapp
All the dev server features work, I just can't access an index like that the one that usually gets automatically opened in a browser.
