### ISSUE TITLE
Variable "global" is not present?

### ISSUE THREAD

**Issue by TropicalRaisel** [symfony/webpack-encore#1040]
I'm trying to use the variable "global" to expose a function that reads data inserted into HTML by a templating engine. This was working at some point and now is no longer working.

Specifically, I'm getting this error:
```
Uncaught ReferenceError: global is not defined
    at Module../assets/javascripts/home.js (home.js:102)
    at __webpack_require__ (bootstrap:24)
    at __webpack_exec__ (home.js:102)
    at home.js:102
    at Function.__webpack_require__.O (chunk loaded:23)
    at home.js:102
    at webpackJsonpCallback (jsonp chunk loading:522)
    at home.js:2
```
After doing this in `home.js`:
```javascript
global.myFtn = myFtn;
```

**Comment by stof** [comment]
this was working in webpack 4 thanks to the built-in polyfilling of node.js APIs. webpack 5 removed the node.js polyfills. The standard way to do that is `globalThis`, not `global`.
