### ISSUE TITLE
[regression] dev-server --public option failure

### ISSUE THREAD

**Issue by gorghoa** [symfony/webpack-encore#1044]
Hi, 

The option `encore dev-server --public` used to work to specify which host to use in the manifest.json symfony assets file.

But in the current version (1.6.1), this option fails:

```shell
ban@na:/var/www/html$ ./node_modules/.bin/encore dev-server --public http://192.168.1.22:8000
Running webpack-dev-server ...

[webpack-cli] Error: Unknown option '--public'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

Looking at webpack-encore code, apparently this is expected to be still working (at least it’s tested):

https://github.com/symfony/webpack-encore/blob/8c2752afd4d63d0e72c757b96af6ae2c2d3c85cf/test/config/parse-runtime.js#L96-L101

### Versions

| Package | Version |
|-----|-----|
|webpack-encore| `1.6.1`|
|webpack-dev-server|`4.1.1`|

### Notes about our use case

We use webpack-encore in a docker-compose environment. With the encore dev-server running in its own container, and the symfony app in another.

This setup works very well (serving assets and livereload) as long as the browser shares the same host as the docker containers (0.0.0.0, or localhost is ok). But, we are testing with real devices on the local network (with ips like 192.168.0.12, or even virtualhosts), and currently it seems that we cannot specify the public host to put in the manifest.json.

Thanks :)

**Comment by gorghoa** [comment]
Maybe related to https://github.com/symfony/webpack-encore/issues/1014 ?

**Comment by StudioMaX** [comment]
Just for information, `public` option has been removed since webpack-dev-server 4.0.0 (https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md):

---
- `public`, `sockHost`, `sockPath`, and `sockPort` options were removed in favor `client.webSocketURL` option:

v3:

```js
module.exports = {
  devServer: {
    public: "ws://localhost:8080",
  },
};
```

```js
module.exports = {
  devServer: {
    sockHost: "0.0.0.0",
    sockPath: "/ws",
    sockPort: 8080,
  },
};
```

v4:

```js
module.exports = {
  devServer: {
    client: {
      // Can be `string`:
      //
      // To get protocol/hostname/port from browser
      // webSocketURL: 'auto://0.0.0.0:0/ws'
      webSocketURL: {
        hostname: "0.0.0.0",
        pathname: "/ws",
        port: 8080,
      },
    },
  },
};
```
---

So this definitely needs some kind of fix.
