### ISSUE TITLE
[Stimulus] Problem updating Stimulus

### ISSUE THREAD

**Issue by karaka200** [symfony/webpack-encore#1057]
Hi

The following warning is displayed when I use `yarn outdated` command to check for outdated packages:

(Warning color is red)
```
yarn outdated v1.22.17
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package  Current Wanted Latest Package Type    URL
stimulus 2.0.0   2.0.0  3.0.1  devDependencies https://stimulus.hotwired.dev
Done in 3.85s.
```

Is it possible to update the Stimulus to the new version or do I have to wait for  `symfony/webpack-encore`  update?

**Comment by stof** [comment]
See https://github.com/symfony/stimulus-bridge/pull/48

**Comment by weaverryan** [comment]
All good now :)
