### ISSUE TITLE
Feature request: use esbuild 

### ISSUE THREAD

**Issue by ankurk91** [symfony/webpack-encore#1061]
Hi,

[esbuild](https://esbuild.github.io/) is an extremely faster alternative to [terser-js](https://github.com/terser/terser) and [css-nano](https://github.com/cssnano/cssnano)

Webpack plugins now supports esbuild officially

- [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin/pull/426) PR
- [css-minimizer-webpack-plugin](https://github.com/webpack-contrib/css-minimizer-webpack-plugin/pull/122) PR

esbuild is stable enough and being used by many popular tools, for example:

* [vite.js](https://vitejs.dev/)
* [angular-cli](https://github.com/angular/angular-cli)
* [rails](https://github.com/rails/jsbundling-rails)
* [snowpack](https://www.snowpack.dev/posts/2021-01-13-snowpack-3-0)

esbuild can reduce memory usage and time to 50% :rocket:

esbuild can also replace babel-loader :wink:

Additional:
* https://www.npmjs.com/package/browserslist-to-esbuild
* https://www.npmjs.com/package/esbuild-loader
* [Next.js is using SWC instead of esbuild](https://nextjs.org/blog/next-11-1#adopting-rust-based-swc)

**Comment by weaverryan** [comment]
This sounds promising to me. I don't know much about it, but it definitely looks worth attempting :)

**Comment by sarim** [comment]
@ankurk91 This probably should've been kept open?

In my opinion the future of symfony ux build tool should be vite. The problem with webpack is webpack itself is slow, using esbuild inside webpack won't be much help in this regard.

I found this: https://github.com/lhapaipai/vite-bundle

**Comment by sarim** [comment]
> Next version of encore will be written with Vite. :)

@ankurk91 Umm how do you know that? Was there any official decision made? source?

**Comment by AntoineKM** [comment]
De toute facon, turbopack remplacera webpack et vite, il implémentera également un système de migration

https://turbo.build/pack/docs/migrating-from-webpack

**Comment by AntoineKM** [comment]
Anyway, turbopack will replace webpack and quickly, it will also implement a migration system

https://turbo.build/pack/docs/migrating-from-webpack

**Comment by Kocal** [comment]
FYI it is already possible to use esbuild to minify javascript and css contents : 

```js
const TerserPlugin = require('terser-webpack-plugin');
const CssMinimizerPlugin = require('css-minimizer-webpack-plugin');

    Encore
        //...
        .configureTerserPlugin((options) => {
            options.minify = TerserPlugin.esbuildMinify;
        })
        .configureCssMinimizerPlugin((options) => {
            options.minify = CssMinimizerPlugin.esbuildMinify;
        })
````

**Comment by arnaubuch** [comment]
Here's how I replaced Babel with ESBuild, for anyone that may need it (make sure to install `esbuild-loader` first!):

```js
Encore
    //...
    .configureLoaderRule('javascript', loaderRule => {
        loaderRule.use = {
            loader: 'esbuild-loader',
            options: {
                target: 'es2015'
            }
        }
    })
```

**Comment by sovetski** [comment]
> FYI it is already possible to use esbuild to minify javascript and css contents :
> 
> ```js
> const TerserPlugin = require('terser-webpack-plugin');
> const CssMinimizerPlugin = require('css-minimizer-webpack-plugin');
> 
>     Encore
>         //...
>         .configureTerserPlugin((options) => {
>             options.minify = TerserPlugin.esbuildMinify;
>         })
>         .configureCssMinimizerPlugin((options) => {
>             options.minify = CssMinimizerPlugin.esbuildMinify;
>         })
> ```

interesting, it does not work for me, how do you test it on your side? I have 0 minified file
