### ISSUE TITLE
The # sign (number sign/hash) appears in the z-index after build assets

### ISSUE THREAD

**Issue by ahmadertarizqi** [symfony/webpack-encore#1066]
Hi,
I have a problem after build assets, that is # (hash) appears in the z-index property css. I'm using SASS, postcss-loader, and autoprefixer

and the result looks like this:
![encore-1](https://user-images.githubusercontent.com/31134292/146395216-d0d620a9-100c-47c4-9f32-a1a15b920665.PNG)
![encore-2](https://user-images.githubusercontent.com/31134292/146395254-df7a30c4-8027-4629-b7b3-0aaeac8db5aa.PNG)

This happens only during build production

**Comment by stof** [comment]
without a reproducer, there is nothing we can do to help

**Comment by Kocal** [comment]
Looks like the same as #984, no ?

**Comment by stof** [comment]
This indeed looks like a duplicate. And the issue has already been fixed in cssnano so running `yarn upgrade` should fix your issue

**Comment by ahmadertarizqi** [comment]
Yes, this issue is the same as #984 .
Thanks @Kocal and @stof for helping.
