### ISSUE TITLE
How to pass a global variable from a twig file to a vue file

### ISSUE THREAD

**Issue by fisherspoons** [symfony/webpack-encore#1071]
Hi, I have a global localization variable that is declared in a twig file and I use it inside a single file component vue.

<img width="504" alt="Снимок экрана 2022-01-10 в 20 06 11" src="https://user-images.githubusercontent.com/54633510/148816400-d146c0c0-3ef6-438a-8cef-1a968eaad910.png">

<img width="213" alt="Снимок экрана 2022-01-10 в 20 06 44" src="https://user-images.githubusercontent.com/54633510/148816463-4c16614b-e04b-416e-8c30-766e7eba42d7.png">

All this works fine, but if I run the tests vtu then he swears that this variable is equal to (locale is not defined). Perhaps there is a way to declare it differently using WebpackEncore?

**Comment by weaverryan** [comment]
Hi!

I'm not sure if this is the problem, but usually I do `window.locale = ` to make sure the variable is global. But more commonly, I leverage data attributes - e.g. add `<body data-locale="...">` then read that from my code.

Anyways, this doesn't relate to Encore - there is nothing special about passing variables around in the Encore world :).

Cheers!
