### ISSUE TITLE
Eslint webpack plugin version

### ISSUE THREAD

**Issue by mmarton** [symfony/webpack-encore#1077]
Hi!

since encore has `"webpack": "^5.35",` in it's dependencies I see no reason to only support eslint-webpack-plugin ^2.

Other than a warning it works fine so far
>  WARNING  Webpack Encore requires version ^2.5.4 of eslint-webpack-plugin. Your version 3.1.1 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.

**Comment by hockdudu** [comment]
Apparently this was fixed with the new 2.0.0 release: https://github.com/symfony/webpack-encore/releases/tag/v2.0.0

> `eslint-webpack-plugin` Minimum version increased from `2.5` to `3`
