### ISSUE TITLE
Drop support for old node versions

### ISSUE THREAD

**Issue by stof** [symfony/webpack-encore#1079]
Node 10 is EOL and Node 12 is reaching EOL at the end of April: https://nodejs.org/en/about/releases/

As many packages are now requiring node 12+ (and many of them will require node 14+ after April), I think it makes sense for Encore to bump its min node version in order to be able to use maintained versions of the tools.
With the node 12 EOL being almost there, I suggest bumping to 14+ directly.

Note: due to the way node compatibility is working in the npm ecosystem (it is not taken into account to choose the version of the dependency being installed, but reported after the fact), dropping support for some node versions requires a new major version.

Regarding the distributions, the dev version of Ubuntu 22.04 is still shipping node 12 for now (which will reach EOL around the date of the Ubuntu 22.04 release, which looks like a bad idea from the Ubuntu maintainers). Looking at the packaging repo, it seems like debian/experimental is upgrading to node 16, so maybe this will still change before the 22.04 LTS.
In any case, the node project is providing its own packaging through deb.nodesource.com which has uptodate packages

**Comment by stof** [comment]
Projects stuck on using the ubuntu package using the EOL node 10 could also keep using Encore 1.x (if they accept using an unmaintained language runtime, they should also accept using unmaintained packages on that runtime)

**Comment by nicolas-grekas** [comment]
We should not minimize the work done by Ubuntu maintainers: Node 10 *is* maintained, when used via Ubuntu LTS.

(But I'm fine with the RFC)

**Comment by stof** [comment]
well, they fix security issues indeed, but that's all. And they don't provide maintenance for the whole npm ecosystem where packages drop support for old node versions once they are EOL and stop maintaining their own old versions.

**Comment by weaverryan** [comment]
I'm thinking we bump to require Node 14 for Encore 2.0, which would primarily include #1033. 

As Stof said, Encore 1.x would still be available for Node 12 and 10.

**Comment by weaverryan** [comment]
In #1033, at the moment, I've bumped to Node 12. That's quite old... but Ubuntu 22.04 was just released (the new LTS), and I believe it ships with Node 12.

However, Stof is right. Node 12 works fine today. However, at the end of this month (April), the entire ecosystem will ship new major versions simply to drop Node 12 support - it happens every time. This means we could release Encore 2.0 today with Node 12 support... and then it would quickly become a problem. But... that's still probably what we should do

**Comment by stof** [comment]
but then should Encore 3.0 come soon after Encore 2.0 ?

**Comment by weaverryan** [comment]
I was wondering about this as well. I don't see a big downside. Release 2.0 with all the updated dependencies (so Node 12 users have access to all of that), then potentially bump to 3.0 fairly quickly.
