### ISSUE TITLE
Babel doesn't traspile .mjs extension files

### ISSUE THREAD

**Issue by minimit** [symfony/webpack-encore#1081]
Hello I've a problem, I'm importing from node_modules, so I added

```
.configureBabel(function () {}, {
  includeNodeModules: ['xtendui'],
})
```

But on the version where I switched to .mjs files babel doesn't traspile the imported `.mjs` files.

I think it's because the babel-loader is not set to work with mjs files. Is there an option where I can add that?

**Comment by stof** [comment]
@weaverryan I suggest updating the list of extensions in Encore itself to include `.mjs` instead of forcing users to customize that (which is not easy)
