### ISSUE TITLE
Webpack-dev-server does not support Node 10

### ISSUE THREAD

**Issue by LucaGallinari** [symfony/webpack-encore#1099]
Hi, i found out that webpack-dev-server ^4.0.0 requires node >= 12.13.0 ([link](https://github.com/webpack/webpack-dev-server/blob/v4.0.0/package.json#L13)) but in your package.json you require webpack-dev-server@^4.0.0 but still support node 10 ([link](https://github.com/symfony/webpack-encore/blob/main/package.json#L26)).
Am i wrong, or the minimum required version for Node should be >=12.13 on webpack-encore too?

Maybe it's related to https://github.com/symfony/webpack-encore/issues/1079

**Comment by ArnaudLier** [comment]
Fixed by 993e3649b533d9533f012d86f778c348ba21f297
