### ISSUE TITLE
Support for option useJsx in vue 3

### ISSUE THREAD

**Issue by iyashpal** [symfony/webpack-encore#1103]
As of now version 3 become the default version of VueJS. And it supports JSX too. 
![image](https://user-images.githubusercontent.com/19922707/159109340-7eb9da5d-5653-4636-834a-309d64a8e413.png)

Also want to put your attention on this warning.
![image](https://user-images.githubusercontent.com/19922707/159109455-8b5c1c2a-48d6-4da6-a8b0-20fbf6a7c5d6.png)

I used vue-loader 17.0.0 in many projects without any errors so I think we should get support for this too.

**Comment by Kocal** [comment]
Oh, I didn't know this issue existed! :o 

This has been added in #1295, and available in [Encore 4.7.0](https://github.com/symfony/webpack-encore/releases/tag/v4.7.0)
