### ISSUE TITLE
DEP_WEBPACK_DEV_SERVER_HTTPS

### ISSUE THREAD

**Issue by jscptman** [symfony/webpack-encore#1119]
I am prompted to update to the devServer.server option when I use the devserver.https: true option, 
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/48516756/168461914-1c243433-e578-4d4e-925e-f223d0179a05.png">
However, when I updated to this option and started my Vue project, an error was reported:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/48516756/168461943-26c72e72-a2d1-454a-a44e-6fd93fae987d.png">

**Comment by weaverryan** [comment]
Yes, use `devserver.server = { type: 'https' }`. Or you can (after #1118) pass `--server-type=https` at the command line.
