### ISSUE TITLE
Encore 11.0 bug "cannot resolve dev"

### ISSUE THREAD

**Issue by Growiel** [symfony/webpack-encore#112]
Hello,

Using the same config as I did with Encore 0.9.1, when I updated to 0.11.0 and tried to run it, this happened:

```
./node_modules/.bin/encore dev
Running webpack ...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                              4:02:12 PM


 error

Entry module not found: Error: Can't resolve 'dev'
```

Did I do something wrong ?

**Comment by weaverryan** [comment]
Hey @Growiel!

Hmm, that's very interesting. I can't repeat it locally, but it looks legit. Can you post your `webpack.config.js` file and also your `yarn.lock` file?

Cheers!

**Comment by weaverryan** [comment]
Nevermind, @bocharsky-bw just helped me get it locally - I'm checking into this now :)

**Comment by weaverryan** [comment]
See #114

**Comment by weaverryan** [comment]
Ok - try upgrading to `0.12.0` - `yarn upgrade`.

If you're still have an error, let me know!

Cheers!
