### ISSUE TITLE
Make the function global

### ISSUE THREAD

**Issue by nickharris08** [symfony/webpack-encore#1143]
Hi, is it possible to make a function inside a file global using webpack encore capabilities?

**Comment by weaverryan** [comment]
Yup - it's just a "webpack" thing:

```js
global.iAmAGlobalVariable = function() {

}
```

Put that in app.js and you will now have a global function called `iAmAGlobalVariable` anywhere else.

**Comment by stof** [comment]
or even better `globalThis.iAmAGlobalVariable` to use the standard way of doing this (using `global.iAmAGlobalVariable` relies on the node polyfills, which are disabled by default in webpack 5)

**Comment by nickharris08** [comment]
I have a function inside a file that will be built with webpack encore
some assets/main.js
in this file there is a function that I want to make global
let fn = function fn(){}

the only working option is the window assignment
window.fn = fn;

I meant it

**Comment by stof** [comment]
@nickharris08 `globalThis.fn = fn` should work (and then also be compatible with the case where you import your file in a worker script, where `window` does not exist).

And assigning the function to the global scope is the standard JS way of declaring a global variable.

**Comment by nickharris08** [comment]
> @nickharris08 `globalThis.fn = fn` should work (and then also be compatible with the case where you import your file in a worker script, where `window` does not exist).
> 
> And assigning the function to the global scope is the standard JS way of declaring a global variable.

Thanks for the help!
