### ISSUE TITLE
[yarn upgrade] unmet peer dependency "webpack@^5.0.0"

### ISSUE THREAD

**Issue by arderyp** [symfony/webpack-encore#1145]
```
$ yarn upgrade
yarn upgrade v1.22.19
...
warning " > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > sass-loader@13.0.2" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-loader@9.3.1" has unmet peer dependency "webpack@^5.0.0".
```

doing `yarn add webpack@^5.0.0` resolved those warnings but produces a new warning during encore build:

```
$ yarn encore production
yarn run v1.22.19
...

 WARNING  Webpack is already provided by Webpack Encore, also adding it to your package.json file may cause issues.
 DONE  Compiled successfully in 23703ms 
```

Is this something to be concerned about or to address?

**Comment by Kocal** [comment]
See #1142

**Comment by arderyp** [comment]
Thanks @Kocal, should I close this?

**Comment by Kocal** [comment]
Until the PR is not merged, I don't think so

**Comment by arderyp** [comment]
@Kocal do you think that PR will resolve this? If so, does it require changing something in my `packages.json`?

**Comment by Kocal** [comment]
Yeah it will resolves the issue since you will be required to install webpack by yourself (and so update your package.json)

**Comment by Kocal** [comment]
Can be closed since Encore v4.
