### ISSUE TITLE
Less-Loader, we need the "relativeUrls" option !

### ISSUE THREAD

**Issue by damienfa** [symfony/webpack-encore#118]
The Less-loader has the option ''.
I need to use it to use a library where assets(fonts, images...) are not relative.

to make it work, I can modify your file 'lib/loaders/less.js' and add `relativeUrls: false,`.
Example : 
```
...cssLoader.getLoaders(webpackConfig, ignorePostCssLoader),
            {
                loader: 'less-loader',
                options: {
                    relativeUrls: false,
                    sourceMap: webpackConfig.useSourceMaps
                }
            },
``` 

I would be nice if that option could be an option of your 'enableLessLoader' function ! 
Example : 
```
.enableSassLoader(function(sassOptions) {}, {
        relativeUrls: false
    })
```

**Comment by weaverryan** [comment]
+1 we just need to make a PR to add this! It's not missing on purpose, just needs to be added!

**Comment by damienfa** [comment]
I've tried a : 
```
.enableLessLoader(function(lessOptions) {
        lessOptions.relativeUrls = false;
    })
```
and it works like a charm ! 
Thanks !
