### ISSUE TITLE
The SASS @forward and @use functions do not work with sass-loader and WebpackEncore.

### ISSUE THREAD

**Issue by LuckyFox31** [symfony/webpack-encore#1186]
After installing the `node-sass` and `sass-loader` packages, enabling `.enableSassLoader()` in `webpack.config.js` and importing `app.scss` file into `app.js`, I realized that compiling the `@forward` and `@use` functions was not working.

My devs dependencies :
```js
"devDependencies": {
        "@babel/core": "^7.17.0",
        "@babel/preset-env": "^7.16.0",
        "@hotwired/stimulus": "^3.0.0",
        "@symfony/stimulus-bridge": "^3.2.0",
        "@symfony/webpack-encore": "^4.0.0",
        "core-js": "^3.23.0",
        "node-sass": "^8.0.0",
        "regenerator-runtime": "^0.13.9",
        "sass-loader": "^13.2.0",
        "webpack": "^5.74.0",
        "webpack-cli": "^4.10.0",
        "webpack-notifier": "^1.15.0"
    },
```

I use Dart Sass `1.58.1`.

## Illustration of the problem
```scss
/* styles/app.scss */
@forward "base";

/* styles/base/_index.scss */
@forward "one";
@forward "two";
@forward "three";
```

```css
/* public/build/app.css */
@forward "base";
```

The SCSS to CSS build does not seem to take into account `@forward` and `@use`.

Has anyone encountered this problem before?

**Comment by stof** [comment]
`node-sass` does not support Sass modules. You need to use the `sass` package instead to use the modern compiler coming from dart-sass.

**Comment by LuckyFox31** [comment]
I replaced `node-sass` with `sass` and it works! 

Thanks!
