### ISSUE TITLE
How to manage with created files ?

### ISSUE THREAD

**Issue by webmasterpf** [symfony/webpack-encore#1210]
Hello,
I'm new to use webpack encore and I wonder how can I manage files created by the build run like: application.ec811ae4.css , because of the variable part of the name.
Idem for images, that are moved to another folder, I would to keep my original image folder, is it possible to avoid this action ?

Thanks

**Comment by weaverryan** [comment]
Hi!

Are you using Encore with Symfony, or something else? The answer is that Encore also outputs a `manifest.json` file, which is a map from the original filename to the final, versioned filename. You should write a small utility that finds your original filename and returns the final one. If you're using Symfony, this can be done for you with this config, which is added if you install WebpackEncoreBundle -https://github.com/symfony/recipes/blob/main/symfony/webpack-encore-bundle/2.0/config/packages/webpack_encore.yaml#L35

Cheers!

**Comment by webmasterpf** [comment]
I use Webpack encore to build CSS for a Drupal theme, so not directly linked to Symfony. Drupal 9 use Symfony and Twig. Actually I have installed @symfony/webpack-encore@4.3.0 via NPM. So do I need to prefer the composer way ? I'm afraid by coflict with drupal composer modules, so I didn't choose this way yet.

**Comment by webmasterpf** [comment]
Hi. The actual issue, is the versionned files, that I could rename after a prod build. And more important, the assets path ( images). Because actually, none images are available.

**Comment by webmasterpf** [comment]
Feedback. I disabled the versioning like this:
`//.enableVersioning(Encore.isProduction())`
then I restart the task with: 
```
npm run watch
> starter_d9_2022@1.0.0 watch
> encore dev --watch
```
but files names didn't change int the dist folder:
```
ls -la ~/www/pfdev/xxx/starter-d9-2022/css/dist/images/
 Jul 13 15:11 BG_Filtres_Exposes.66ba4066.png
 Jul 13 15:11 lieux@3x.0acefa89.png
 Jul 13 15:11 motif_img_overlay.9130e282.png
 Jul 13 15:11 stripe_rosepale_violet_pastel.c2b82e9f.png
 Jul 13 15:11 stripe_vert_vert_pastel.7fa13d9e.png
 Jul 13 15:11 zebra-gros-clair.45fce67a.gif

```
What I need to do more ?

**Comment by webmasterpf** [comment]
After digging, I see the path in CSS file is wrong. For example, 
`background-image: url(/dist/images/stripe_rosepale_violet_pastel.c2b82e9f.png);`  would be 
`background-image: url(../dist/images/stripe_rosepale_violet_pastel.c2b82e9f.png);`
I try to change this into webpack encore config, 
```
.setPublicPath('/dist')
    // only needed for CDN's or sub-directory deploy
    .setManifestKeyPrefix('../dist')
``` with no effects
