### ISSUE TITLE
semver vulnerable to Regular Expression Denial of Service

### ISSUE THREAD

**Issue by mohamedTaiebBsf** [symfony/webpack-encore#1213]
When utilizing the webpack-encore bundle, an issue arises when attempting to assess the vulnerabilities of JavaScript packages using the "yarn audit" command. The generated report indicates a vulnerability in the semver library, specifically pertaining to Regular Expression Denial of Service. It is important to note that semver serves as a dependency for @babel/core, @babel/preset-env, and @symfony/webpack-encore.

I kindly request guidance on resolving this matter and effectively addressing the aforementioned vulnerability.

**Comment by stof** [comment]
webpack-encore depends on semver `^7.3.2`, which allows to install the patched 7.5.2 version (`yarn upgrade` will install it).

For the usage of semver 6.x coming from Babel packages, we cannot do anything about it. This has to be requested to the Babel project (but it looks like there is already a discussion about backporting the fix to older major versions, so maybe you just need to wait a bit for that to happen).
