### ISSUE TITLE
jQuery ui is not loading

### ISSUE THREAD

**Issue by neovea** [symfony/webpack-encore#122]
Hi there, I'm wondering if I'm getting it all well about the webpack configuration file.
Actually, I defined it like so : 
```
// webpack.config.js
var Encore = require('@symfony/webpack-encore');
var three = require('three');

Encore
// directory where all compiled assets will be stored
  .setOutputPath('./web/build/')

  // what's the public path to this directory (relative to your project's document root dir)
  .setPublicPath('/build')

  // empty the outputPath dir before each build
  .cleanupOutputBeforeBuild()

  // Shared libraries
  .autoProvidejQuery()
  // will output as web/build/app.js
  .addEntry('private-top', [
      './app/Resources/private/js/lib.js',
      './vendor/friendsofsymfony/jsrouting-bundle/Resources/public/js/router.js',
      './node_modules/dropzone/dist/dropzone.js',
      './node_modules/js-cookie/src/js.cookie.js',
      './node_modules/bootstrap-toggle/js/bootstrap-toggle.js',
      './app/Resources/private/js/vendor/waves.js',
      './node_modules/waypoints/lib/jquery.waypoints.js',
      './node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.js',
      './node_modules/bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr.min.js',
      './node_modules/select2/dist/js/select2.full.js',
      './node_modules/bootstrap-select/dist/js/bootstrap-select.js',
      './app/Resources/private/js/vendor/custom.min.js',
      './app/Resources/private/js/vendor/jquery.dataTables.min.js',
      './node_modules/snapsvg/dist/snap.svg.js',
      './node_modules/owl.carousel/dist/owl.carousel.min.js',
      './app/Resources/private/js/common.js',
      './node_modules/magnific-popup/dist/jquery.magnific-popup.js',
      './app/Resources/private/js/magelan3d.js',
      './app/Resources/private/js/vendor/CSS2DRenderer.js',
      './app/Resources/private/js/vendor/JDLoader.min.js',
      './app/Resources/private/js/vendor/hammer.js',
      './app/Resources/private/js/configure-jquery.js',
      './app/Resources/private/js/3d-jquery.js',
      './app/Resources/private/js/collector.js',
      // './web/js/translations/front/fr.js',
  ])
  // This is required by SNAPsvg
  .addLoader({
    test: require.resolve('snapsvg'),
    loader: 'imports-loader?this=>window,fix=>module.exports=0'
  })
  .createSharedEntry('vendor', [
      './node_modules/jquery/dist/jquery.min.js',
      './node_modules/jquery-ui-dist/jquery-ui.min.js',
      './node_modules/bootstrap/dist/js/bootstrap.js',
      //'./app/Resources/private/js/vendor/html.sortable.min.js',
      './vendor/willdurand/js-translation-bundle/Resources/public/js/translator.min.js',
  ])
  .configureBabel(function(babelConfig) {
      babelConfig.presets.push('es2017');
  })
  .enableReactPreset()
  .addEntry('react-components', './assets/js/main.js')

  // will output as web/build/global.css
  .addStyleEntry('private-style', [
    './app/Resources/private/css/font-awesome.css',
    './node_modules/bootstrap/dist/css/bootstrap.css',
    './node_modules/bootstrap-toggle/css/bootstrap-toggle.css',
    './node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.css',
    './node_modules/bootstrap-select/dist/css/bootstrap-select.css',
    './app/Resources/private/css/dataTables.bootstrap.min.css',
    './node_modules/animate.css/animate.css',
    './node_modules/magnific-popup/dist/magnific-popup.css',
    './app/Resources/private/css/spinners.css',
    './app/Resources/private/css/style.css',
    './node_modules/owl.carousel/dist/assets/owl.carousel.css',
    './node_modules/owl.carousel/dist/assets/owl.theme.default.min.css',
    './app/Resources/private/css/feb.css',
    './app/Resources/private/css/dev.css',
    './app/Resources/private/css/magelan3d.css',
    './app/Resources/private/css/magelanConfigurator.css',
    './node_modules/select2/dist/css/select2.css',
    './app/Resources/private/css/dashboardMageland2.css',
    './app/Resources/private/css/operationMageland2.css',
    './app/Resources/private/css/clientMageland2.css',
    './app/Resources/private/css/styleMageland2.css',
    './app/Resources/private/css/icons.css',
    './app/Resources/private/css/workflow.css',
    './app/Resources/private/css/dropzone.css'
  ])
  .addStyleEntry('global', './assets/scss/global.scss')

  // allow sass/scss files to be processed
  .enablePostCssLoader()
  .enableSassLoader()

  .enableSourceMaps(!Encore.isProduction())

  // create hashed filenames (e.g. app.abc123.css)
  // .enableVersioning()
  ;

// export the final configuration
module.exports = Encore.getWebpackConfig();
```
As you can see, I have defined `jquery` and `jquery-ui`in `createSharedEntry` method.
In defined my `lib.js` file which contains some `jquery-ui` widgets.

Both files are of course déclared in my html, but my app fails with $(...).ajasxrefresh() is not a function. Even defering my script load when `typeof $.ui != 'undefined'`fails.

My `lib.js` file contains : 
```
(function ($) {
    $.widget("magelan.ajaxrefresh", {

        options: {
            onRefresh: function () {
            }
        },

        _create: function () {
            this.options.onRefresh(this.element);
        },

        refresh: function () {
            var ajaxrefresh = this;
            var elt = this.element;
            elt.fadeTo(500, 0.20, function () {
                $.get(elt.data("refresh"), function (data) {
                    elt.html($(data));
                    ajaxrefresh.options.onRefresh(elt);
                    ajaxrefresh._trigger("complete");
                    elt.fadeTo(500, 1);
                });
            });
        }

    });
});
```
Did I miss something ?

By the way other stuff don't work, like fos route js, routes are not accessible to other scripts...

All of this used to work when it was processed with gulp.

Any help on this would be greatly appreciatied :)

Thanks

**Comment by loceric** [comment]
Hi @neovea,

Have you tried to use the source file instead of the minimized version?

**Comment by stof** [comment]
For FOS JS Routing, you only load the router, not the route definitions. So you have a router with no routes.

Have you tried putting a requirement for jQuery UI in your file ? As you don't have it, Webpack may not evaluate the jQuery UI module before loading your own file.

**Comment by stof** [comment]
the big difference between a Gulp-based and a Webpack-based process is that Webpack is a module bundler, while Gulp is not. Gulp will just concatenate file after each other, and files will be loaded without any module system (relying on global variables to access code from other libraries). Webpack is about modules, and modules are not evaluated until they are needed for the first time.

**Comment by davidmpaz** [comment]
I would suggest to use https://www.npmjs.com/package/jquery-ui-dist

And then add an alias to be able to require it easily, otherwise you will
need to reference full path to module file.

There are some discussions about jquery-ui module being used as core
development only, not meant to be used by third party applications, since
first you need to build the package.

That is not usefull when you just want to require and use. Later I can give
you some example on how we use it.

Hope it helps

Am 03.08.2017 16:21 schrieb "Christophe Coevoet" <notifications@github.com>:

**Comment by davidmpaz** [comment]
In order to import like: `jquery-ui`, we have this:

```
webpackConfig.resolve.alias = Object.assign(webpackConfig.resolve.alias, {
    'jquery-ui': 'jquery-ui-dist/jquery-ui.js',
    'jquery-steps': 'jquery-steps/build/jquery.steps.js'
});
```
after exporting webpack configuration. Things I have noticed is that you are making reference to relative path of: 
`./node_modules/jquery-ui-dist/jquery-ui.min.js`, it should not be needed. 

Other thing is that you are using minimized version, have you tried to use the not minimized one? Don't know why, but I have in mind some discussion in GitHub about that also.

hope it helps

**Comment by stof** [comment]
the official npm package for jQuery UI is `jquery-ui`, not `jquery-ui-dist`. You should use it, as they have official support for usage in a commonJS environment like webpack. See https://github.com/jzaefferer/webpack-jquery-ui for a demo

**Comment by davidmpaz** [comment]
@stof then would you say that including the complete library from one files is not as better (or maybe it belongs to past?) as requiring each component/widget separately as they are needed ?

**Comment by weaverryan** [comment]
@neovea To follow up on Stof's original comment, I'm not sure the exact problem, but you're not using Webpack in the way it's meant - you're actually making your life a bit more difficult than it needs to be :). Typically, your entry would only be one `.js` file - like `lib.js`. Then, inside each `.js` file, you should require all the dependencies you need. For example, I'd like `lib.js` to look a bit more like this:

```js
// the self-executing function is not needed in a module environment
//(function ($) {

// you need jquery - so require it and set the $ variable
const $ = require('jquery');
// it looks like you're also relying on the Magelan JS to be included (not 100% sure about this)
require('./app/Resources/private/js/magelan3d.js');
// you could also require the CSS for magelan right here too

    $.widget("magelan.ajaxrefresh", {

        options: {
            onRefresh: function () {
            }
        },

        _create: function () {
            this.options.onRefresh(this.element);
        },

        refresh: function () {
            var ajaxrefresh = this;
            var elt = this.element;
            elt.fadeTo(500, 0.20, function () {
                $.get(elt.data("refresh"), function (data) {
                    elt.html($(data));
                    ajaxrefresh.options.onRefresh(elt);
                    ajaxrefresh._trigger("complete");
                    elt.fadeTo(500, 1);
                });
            });
        }

    });
//});
```

We're creating a KnpU screencast about these philosophical differences in Webpack. Here are some relevant pages so far:

* https://knpuniversity.com/screencast/javascript-webpack/watch-require-jquery <-- important to understand how libraries act in a module environment
* https://knpuniversity.com/screencast/javascript-webpack/legacy-global-jquery
* https://knpuniversity.com/screencast/javascript-webpack/provide-plugin
* https://knpuniversity.com/screencast/javascript-webpack/require-css

I hope this helps!

**Comment by neovea** [comment]
Hi Im still following this thread and I thank you all for your feedback. As I working on another projet, I can't test various solutions proposed. But I soon come back to it. 
Thanks again

**Comment by richcore2018** [comment]
try require('jquery-ui/ui/widgets/sortable');
