### ISSUE TITLE
Two different builds for two versions of Vue.js app

### ISSUE THREAD

**Issue by erikas-tranauskas** [symfony/webpack-encore#1257]
I need to load two separate builds which is Vue.js version 2 and Vue.js version 3. 

I have version 2.7.16 installed as main vue package along with vue-loader 15.10.0 (this version is used for Vue.js 2) and also I have installed the updated versions of these packages:

```
"vue-loader-v3": "npm:vue-loader@^17.4.2",
"vue3": "npm:vue@^3.4.15",
```
Now I try to use these updated packages for the build of Vue.js 3, this is the webpack.config.js

```
const Encore = require('@symfony/webpack-encore');
const dotenvFlow = require('dotenv-flow');
const { VueLoaderPlugin } = require('vue-loader-v3');

Encore.setOutputPath('public/build/vue2_build/')
  .setPublicPath('/build/vue2_build')
  .addEntry('main-v2', './assets/js/main.ts')
  .splitEntryChunks()
  .enableSingleRuntimeChunk()
  .cleanupOutputBeforeBuild()
  .enableBuildNotifications()
  .enableSourceMaps(!Encore.isProduction())
  .enableVersioning(Encore.isProduction())
  .configureBabelPresetEnv((config) => {
    config.useBuiltIns = 'usage';
    config.corejs = 3;
  })
  .enableSassLoader()
  .enableTypeScriptLoader()
  .enableVueLoader()
  .configureDefinePlugin((options) => {});

const vue2config = Encore.getWebpackConfig();
vue2config.name = 'vue2config';

Encore.reset();

Encore.setOutputPath('public/build/vue3_build/')
  .setPublicPath('/build/vue3_build')
  .addEntry('main-v3', './assets/js/src/main.ts')
  .splitEntryChunks()
  .enableSingleRuntimeChunk()
  .cleanupOutputBeforeBuild()
  .enableBuildNotifications()
  .enableSourceMaps(!Encore.isProduction())
  .enableVersioning(Encore.isProduction())
  .configureBabelPresetEnv((config) => {
    config.useBuiltIns = 'usage';
    config.corejs = 3;
  })
  .enableSassLoader()
  .enableTypeScriptLoader()
  .enableVueLoader(() => {}, { version: 3 })
  .addPlugin(new VueLoaderPlugin());

const vue3config = Encore.getWebpackConfig();

vue3config.name = 'vue3config';

module.exports = [vue2config, vue3config];
```
The vue3config uses main.ts file with vue3 package loaded. Now I get the following warnings while building the app:
```
 WARNING  Webpack Encore requires version ^3.2.14 of vue, but your version (2.7.16) is too old. The related feature will probably *not* work correctly.
 WARNING  Webpack Encore requires version ^17.0.0 of vue-loader, but your version (15.11.1) is too old. The related feature will probably *not* work correctly.
```
as Webpack builds the vue3config on top of old vue and vue-loader packages, while I need it to be running on vue3 and vue-loader-v3.

Is this possible?

vue2config builds fine.

**Comment by stof** [comment]
Well, using `.enableVueLoader(() => {}, { version: 3 })` will make Encore attempt to register the `vue-loader` plugin (even if you also added a separate `vue-loader-v3` package that you register manually.

You should remove this line and perform the while vue3 configuration as custom config given that you want it to use a non-standard package name for the loader.

**Comment by erikas-tranauskas** [comment]
> Well, using `.enableVueLoader(() => {}, { version: 3 })` will make Encore attempt to register the `vue-loader` plugin (even if you also added a separate `vue-loader-v3` package that you register manually.
> 
> You should remove this line and perform the while vue3 configuration as custom config given that you want it to use a non-standard package name for the loader.

Yes that's one of the things I tried.

```
  .addLoader({
    test: /\.vue$/,
    use: 'vue-loader-v3',
  })
```
Using .addLoader instead of .enableVueLoader makes sense, but this way it doesn't load something else and it brings up an error:

```
Module build failed (from ./node_modules/vue-loader-v3/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
```

**Comment by erikas-tranauskas** [comment]
Solved this by using yarn with workspaces enabled instead of npm. It installed all the packages as it should.
