### ISSUE TITLE
Warning for postcss-loader v8.1.0 to be too new

### ISSUE THREAD

**Issue by DanielaPockNiceshops** [symfony/webpack-encore#1260]
Hello, 

I get this warning when I run my program:

WARNING  Webpack Encore requires version ^7.0.0 of postcss-loader. Your version 8.1.0 is too new. The related feature may still work properly. If you have issues, try downgrading the library, or upgrading Encore.

I have not encountered any issues until now, so I ignore the warning at the moment.

Just wanted to inform you and ask if you already work on an upgrade?

**Comment by karpilin** [comment]
@DanielaPockNiceshops there is a PR #1258 that updates less-loader, postcss-loader, stylus and stylus-loader to latest versions. I'm sure it will be included in the next release.

**Comment by DanielaPockNiceshops** [comment]
Thanks for info! I'll wait for the update :)

**Comment by WebMechanic** [comment]
also waiting for PR https://github.com/symfony/webpack-encore/pull/1258 to be solved and merged

thank you
