### ISSUE TITLE
Yarn upgrade : version no longer supported

### ISSUE THREAD

**Issue by keichitokuna** [symfony/webpack-encore#1288]
Hello,

I work on a Symfony 7.0 project.
I did all the upgrades to Symfony 7.1, including recipes.

Then I updated composer with no issue but when i try to upgrade yarn, i have this :

````
keichi@DSN-EDAM ~/app-proj-num  master ±  yarn upgrade
yarn upgrade v1.22.22
[1/4] 🔍  Resolving packages...
warning @symfony/webpack-encore > webpack-dev-server > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @symfony/webpack-encore > clean-webpack-plugin > del > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
warning @symfony/webpack-encore > webpack-dev-server > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @symfony/webpack-encore > clean-webpack-plugin > del > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @symfony/webpack-encore > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @symfony/webpack-encore > clean-webpack-plugin > del > globby > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @symfony/webpack-encore > webpack-dev-server > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Rebuilding all packages...
success Saved lockfile.
success Saved 513 new dependencies.
````

I am unsure, how to resolve it properly ?

Here the full log from the beginning:
[full logs - yarn upgrade issue.txt](https://github.com/user-attachments/files/16713509/full.logs.-.yarn.upgrade.issue.txt)

Thanks,

K.

**Comment by stof** [comment]
the first question is whether `webpack-dev-server` and `clean-webpack-plugin` have newer versions available that don't use those old versions. the next step depends on the answer:

- if they don't, the next step is to contribute to them to make them use a supported version of their dependency (allowing to change the answer to that question when restarting the process)
- if they do, the next step is to contribute to webpack-encore to make it support the newer version of those packages.

Note however that these are just warnings. Older versions of the package still work even though they are not maintained anymore.

**Comment by keichitokuna** [comment]
Hello stof,

Thanks for the quick reply.
I know that it is just warnings, but i try to understand it and cleared it along the way.

As my understanding :

- **webpack-dev-server** is actively supported and do have a newer version (5.0.4, [here](https://classic.yarnpkg.com/en/package/webpack-dev-server)). But if i do : 
````
yarn add webpack-dev-server
````
It doesn't replace the current version i use (webpack-dev-server@^4.8.0) in my yarn.lock.
It add a second up to date version, and the warnings remain.


- **clean-webpack-plugin** : is at the latest version and wasn't updated since September 1, 2021.

I checked @symfony/webpack-encore which seems to have these two plugins as dependencies.
The current version is 4.6.0 ([here](https://classic.yarnpkg.com/en/package/@symfony/webpack-encore)), but in my yarn.lock, i only have the 4.0.0.
And :
````
yarn upgrade @symfony/webpack-encore
````
has no effect.

Thanks again,

K.

**Comment by stof** [comment]
@keichitokuna you cannot just add a newer version of `webpack-dev-server` in your project. As I said, it needs to be upgraded in webpack-encore (and then a release being published).

**Comment by stof** [comment]
I created #1289 and #1290 to resolve those 2 cases in the next version of webpack-encore. So I'm closing this issue for now.
