### ISSUE TITLE
Production build CSS/JS files are not minified

### ISSUE THREAD

**Issue by sovetski** [symfony/webpack-encore#1305]
Hi,

I just discovered that my production css/js files are not minified.

Is it normal? (if yes why?)

My project is on Symfony 6.3 with `"@symfony/webpack-encore": "^4.6.1",`

The final JS code looks compiled like function names etc. are short but the file is not minified

Thanks in advance

**Comment by Kocal** [comment]
Hi @sovetski, what is your Webpack configuration? how do you run Encore to compile your assets for production? Do you have a `NODE_ENV` env variable already defined outside of Enore?

**Comment by sovetski** [comment]
Finally it is ok, I checked the content of the assets from Chrome and as it displayed in several lines I thought that it was not minified but in the end yes, by checking with FTP and also by looking with Chrome that there are only 2 number of lines that reassures me, I had checked wrong 😅
![image](https://github.com/user-attachments/assets/605eaacc-6202-48d8-942e-09f6e9e3762d)

**Comment by sovetski** [comment]
Finally it is ok, I checked the content of the assets from Chrome and as it displayed in several lines I thought that it was not minified but in the end yes, by checking with FTP and also by looking with Chrome that there are only 2 number of lines that reassures me, I had checked wrong 😅
![image](https://github.com/user-attachments/assets/605eaacc-6202-48d8-942e-09f6e9e3762d)

**Comment by Kocal** [comment]
Perfect then 🫡
