### ISSUE TITLE
Can not build Admin CMS due to symfonyRouting isues

### ISSUE THREAD

**Issue by nereafidenet** [symfony/webpack-encore#1354]
### Actual Behavior

SULU interface doesn't correctly build

### Expected Behavior

SULU interface to build and load successfully

### Steps to Reproduce

Run npm i and npm run build inside CLI

### Possible Solutions
Changing the webpack.config.js file that is located in vendor/sulu/sulu does not solve the issue

**Currently using:**
Node v14.21.3
NPM 6.14.18

Logs for version ~2.5.11:

> sulu-skeleton@ build /var/www/html/assets/admin
> webpack --mode production

   1812 modules

WARNING in ./node_modules/sulu-admin-bundle/services/ResourceRequester/registries/resourceRouteRegistry.js 28:4-18
"export 'default' (imported as 'symfonyRouting') was not found in 'fos-jsrouting/router'

WARNING in ./node_modules/sulu-admin-bundle/services/ResourceRequester/registries/resourceRouteRegistry.js 41:11-25
"export 'default' (imported as 'symfonyRouting') was not found in 'fos-jsrouting/router'

WARNING in ./node_modules/sulu-admin-bundle/services/ResourceRequester/registries/resourceRouteRegistry.js 51:11-25
"export 'default' (imported as 'symfonyRouting') was not found in 'fos-jsrouting/router'

WARNING in ./node_modules/sulu-admin-bundle/stores/metadataStore/metadataStore.js 27:18-32
"export 'default' (imported as 'symfonyRouting') was not found in 'fos-jsrouting/router'

WARNING in ./node_modules/sulu-admin-bundle/containers/Badge/stores/BadgeStore.js 87:11-25
"export 'default' (imported as 'symfonyRouting') was not found in 'fos-jsrouting/router'

WARNING in ./node_modules/sulu-admin-bundle/views/List/toolbarActions/UploadToolbarAction.js 154:11-25
"export 'default' (imported as 'symfonyRouting') was not found in 'fos-jsrouting/router'

WARNING in ./node_modules/sulu-media-bundle/containers/ImageMap/ImageRenderer.js 97:11-25
"export 'default' (imported as 'symfonyRouting') was not found in 'fos-jsrouting/router'

**Comment by Kocal** [comment]
@alexander-schranz any help? :D

**Comment by alexander-schranz** [comment]
This issue was fixed see https://github.com/sulu/sulu/issues/7661#issuecomment-2484894553.

PS: Sulu does not use Webpack Encore for its admin build, it uses Webpack Encore directly.

**Comment by Kocal** [comment]
Thanks Alexander :)
