### ISSUE TITLE
How to manually add entries to manifest.json?

### ISSUE THREAD

**Issue by havvg** [symfony/webpack-encore#140]
Hi there,

I've got somewhat legacy (huge dumped JS arrays) code. Without Encore I can do this:

```js
new ConcatPlugin({
    uglify: true,
    useHash: true,
    sourceMap: false,
    fileName: 'shipdev-data.js',
    filesToConcat: ['./frontend/shipdev/data/modules.js', './frontend/shipdev/data/ships.js']
})
```

I would like to keep it this way for now, because it works. I tried using `addEntry` but this runs for ages (I cancelled after 10minutes). Now using Encore, I am adding this:

```js
addPlugin(new ConcatPlugin({
    uglify: true,
    useHash: true,
    sourceMap: false,
    fileName: 'shipdev-data.js',
    filesToConcat: ['./frontend/shipdev/data/modules.js', './frontend/shipdev/data/ships.js']
}))
```

Which works fine to the point that the file is available and contains the content as it should. Now I would like to have this entry being added to the `manifest.json`. Is there an elegant way with Encore?

My current workaround is just defining `useHash: false`, which works for `asset('shipdev-data.js')` with `framework.assets.base_path` configured.

**Comment by weaverryan** [comment]
Hey @havvg!

Hmm. This initially sounds like a bug or missing feature in the ManifestPlugin. In theory, it would see this newly output file and use it in the manifest. There's actually a similar issue when using the CopyWebpackPlugin: copied assets aren't in the manifest. In this situation, the ManifrstPlugin guys would like to fix it.

So I believe the answer right now is no. We'd need to possibly open this issue upstream.

Btw, if this .js file is just data, one alternative is to convert it into a JSON file. Then require that from an entry .js file. Webpack is able to load JSON, and it should be fast. It's possible it still may be too slow during uglification or something, but might be worth a try :).

Cheers!

**Comment by mastilver** [comment]
Will **probably** be solved by: https://github.com/danethurber/webpack-manifest-plugin/pull/75
