### ISSUE TITLE
How to configure Webpack-Encore outside a Symfony project?

### ISSUE THREAD

**Issue by ethyde** [symfony/webpack-encore#147]
Hi,

I would like to try webpack-encore because it seem's to have a lot of very interesting feature (specialy possibility to load twig template in a nodeJS environnement) but I don't find documentation about how to configure where are templating files, or path for assets if i'm not in a Symfony environnement.
I have to mimic an SF files&folders structure ?

Thanks for your help.

**Comment by stof** [comment]
webpack-encore has nothing specific to Symfony (and nothing to do with templating btw). It is just a higher-level API for webpack.

The webpack-encore tooling will build the JS and CSS files based on your config, and then you can use them the way you want, depending on how your backend code looks like (if your backend framework has an integration with webpack manifest files for asset versioning, you can use it btw, as this is still webpack doing the work)
