### ISSUE TITLE
The entry names between addEntry() and addStyleEntry() must be unique.

### ISSUE THREAD

**Issue by yoh-m** [symfony/webpack-encore#153]
Hi, I just moved to v0.14 and wanted to use the new `Encore.configureFilenames()` method you added, here is the config I used:
```
Encore
    .setOutputPath('web/assets/')
    .setPublicPath('/assets')
    .cleanupOutputBeforeBuild()
    .configureFilenames({
        css: 'css/[name]-[contenthash].css',
        js: 'js/[name]-[chunkhash].js'
    })

    .addEntry('admin', './app/Resources/assets/js/admin.js')
    .addEntry('main', './app/Resources/assets/js/main.js')

    .addStyleEntry('admin', './app/Resources/assets/scss/admin.scss')
    .addStyleEntry('main', './app/Resources/assets/scss/main.scss')
...
```

I thought it wouldn't be a problem since JS and CSS files are compiled in different directories (the objective being to have a `web/assets/js/admin.js` and a `web/assets/css/admin.css` files), but I had this error:
```
Error: The "admin" passed to addStyleEntry() conflicts with a name passed to addEntry(). The entry names between addEntry() and addStyleEntry() must be unique.
```

Just wondering if that's really causing a problem to have the same name, it's not a really big problem to change it, I just found that weird!

**Comment by stof** [comment]
Webpack only has entries. `addStyleEntry` is just here to allow you to make the Encore config more readable. But in the end, it is just a normal entry (you could use `addStyleEntry('js', './app/Resources/assets/js/main.js')` even though this would be insane)

**Comment by yoh-m** [comment]
Ok, I'll just stick with `addEntry('js/main', './app/Resources/assets/js/main.js')` then, it does what I want (separating JS & CSS files in subfolders), even though the `cleanupOutputBeforeBuild()` doesn't clean subfolders that's not a big problem.

Thanks for the answer!

**Comment by Lyrkan** [comment]
Another way to solve that is to avoid calling `addStyleEntry` and directly require CSS files from JS files.

For instance:

```js
// webpack.config.js
const Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('build/')
    .setPublicPath('/')
    .cleanupOutputBeforeBuild()
    .configureFilenames({
        css: 'css/[name]-[contenthash].css',
        js: 'js/[name]-[chunkhash].js'
    })
    .enableVersioning()
    .enableSassLoader()
    .addEntry('main', './src/main.js')
    .addEntry('admin', './src/admin.js')
;

module.exports = Encore.getWebpackConfig()
```

```js
// src/main.js
require('./main.scss')

// (...)
```

```js
// src/admin.js
require('./admin.scss')

// (...)
```

![2017-09-05_13-45-41](https://user-images.githubusercontent.com/850046/30059729-9e7594f0-9240-11e7-855c-41492266551d.png)

**Comment by weaverryan** [comment]
Yes - excellent suggestion! Requiring your CSS from your js is the proper solution. The addStyleEntry() is a bit of a hack to help in some cases :)

**Comment by Sydney-o9** [comment]
@Lyrkan,  is `configureFilenames()` documented? This is an amazing feature, I could not find it in the docs. Apologies if I have missed it somehow.

**Comment by Lyrkan** [comment]
@Sydney-o9 I don't think there is something about it in the Symfony docs, but you can refer to the index.js file to see how to use it:

https://github.com/symfony/webpack-encore/blob/master/index.js#L680-L701
