### ISSUE TITLE
Possibility to disable babel loader

### ISSUE THREAD

**Issue by wtorsi** [symfony/webpack-encore#154]
Hi, 
Could you add possibility to disable babel loader. 
For example, when using dev env it is not needed, and in this case rebuild is faster.

**Comment by weaverryan** [comment]
@wtorsi Is it a huge difference? We enable some babelrc caching... so I thought (but never really tested) that after the first build, future builds would not be too much slower (as much of the transformation would already be cached). I'm just trying to avoid adding options if possible, but I see your use-case :).

**Comment by Calinou** [comment]
See [this issue](https://github.com/symfony/webpack-encore/issues/214) for improving the performance of source map generation.

Also, isn't Babel always needed the second you add `import` statements to your code, considering no browser supports ES6 modules natively yet?

**Comment by stof** [comment]
no, because webpack itself knows about `import`. Bundling modules is done by webpack, not by babel

**Comment by Calinou** [comment]
@stof Thanks for the clarification, I forgot about this.

**Comment by mdzzohrabi** [comment]
Hi,
I want to disable babel too, because im using **TypeScript** and don't need babel, currently babel edit my typescript outputs and change **async/await** behaviors.
How can i disable babel ?

**Comment by mdzzohrabi** [comment]
I found a solution by clear babel config presets : 
```js
.configureBabel(config => {
        config.presets = [];
})
```

**Comment by weaverryan** [comment]
Hmm, that's clever. I think we should document that :)

**Comment by mdzzohrabi** [comment]
@weaverryan Yes, it works fine for me , but one thing that we must notice, when you disable babel, you must target **TypeScript** to **ES5** at most , because of **Uglify** in build in **production** env.

If you target TypeScript build to after ES5 Uglify may error on somethings like Arrow Functions !
Uglify  ES6 support issue in Webpack repo : [Issue](https://github.com/webpack/webpack/issues/2545)

**Comment by weaverryan** [comment]
Note: the Uglify part of this issue should not be a problem in the latest version of Encore

Cheers!
