### ISSUE TITLE
Duplicate entire name error isn't showing the correct entrie name

### ISSUE THREAD

**Issue by MUCHZER** [symfony/webpack-encore#178]
Hello,
here how to reproduce the error
```js
// webpack.config.js
// ....
.addEntry('js/core', [
	'./assets/bundles/core/js/input.js',
])

// Duplicated entries
.addStyleEntry('css/core', './assets/bundles/manager/scss/style.scss')
.addStyleEntry('css/admin', './assets/bundles/admin/scss/style.scss')
.addStyleEntry('css/core', './assets/bundles/core/scss/main.scss')
.addStyleEntry('css/admin', './assets/bundles/admin/scss/style.scss')
// ....
```
This error will show up on build
` Error: Duplicate name "js/core" passed to addEntry(): entries must be unique.`
https://github.com/symfony/webpack-encore/blob/master/lib/WebpackConfig.js#L231

**Comment by Lyrkan** [comment]
Hi @MUCHZER,

I can't reproduce it on my side with the following `webpack.config.js`:

```js
// webpack.config.js
const Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('build/')
    .setPublicPath('/')
    .cleanupOutputBeforeBuild()
    .addEntry('js/core', ['./assets/bundles/core/js/input.js'])
    .addStyleEntry('css/core', './assets/bundles/manager/scss/style.scss')
    .addStyleEntry('css/admin', './assets/bundles/admin/scss/style.scss')
    .addStyleEntry('css/core', './assets/bundles/core/scss/main.scss')
    .addStyleEntry('css/admin', './assets/bundles/admin/scss/style.scss')
;

// export the final configuration
module.exports = Encore.getWebpackConfig();
```

It displays the following (and expected) error:

```
Error: Duplicate name "css/core" passed to addStyleEntry(): entries must be unique.
```

Nothing seems weird in the `addEntry()` code from `WebpackConfig.js` either.
Do you have something else in your `webpack.config.js` that could be related to that issue?

**Comment by MUCHZER** [comment]
Hello @Lyrkan, thanks for your help.
I tried your config and I still got the same error with the wrong entrie name.


**I found the problem, I was using an outdated version of Encore (^0.12.0).**
