### ISSUE TITLE
Syntax Error in manifest.json

### ISSUE THREAD

**Issue by hanwoods** [symfony/webpack-encore#183]
Hello There!

I am new to web packs/encore but I seem to be stuck on an issue, I'm trying to load an image asset but the console of my chrome is showing this error:
"Uncaught SyntaxError: Unexpected token :" on manifest.json:2

I think this error is preventing me from being able to call the path from the asset() method

My manifest.json: 
```
{
  "build/app.js": "/build/app.js",
  "build/fonts/glyphicons-halflings-regular.eot": "/build/fonts/glyphicons-halflings-regular.f4769f9b.eot",
  "build/fonts/glyphicons-halflings-regular.ttf": "/build/fonts/glyphicons-halflings-regular.e18bbf61.ttf",
  "build/fonts/glyphicons-halflings-regular.woff": "/build/fonts/glyphicons-halflings-regular.fa277232.woff",
  "build/fonts/glyphicons-halflings-regular.woff2": "/build/fonts/glyphicons-halflings-regular.448c34a5.woff2",
  "build/images/glyphicons-halflings-regular.svg": "/build/images/glyphicons-halflings-regular.89889688.svg",
  "build/images/school_logo.png": "/build/images/school_logo.c3f8883e.png",
  "build/manifest.js": "/build/manifest.js",
  "build/theme.css": "/build/theme.css",
  "build/vendor.css": "/build/vendor.css",
  "build/vendor.js": "/build/vendor.js"
}

```
My webpack.config.js

```
// webpack.config.js
var Encore = require('@symfony/webpack-encore');

Encore
// directory where all compiled assets will be stored
	.setOutputPath('web/build/')

	// what's the public path to this directory (relative to your project's document root dir)
	.setPublicPath('/build')

	// empty the outputPath dir before each build
	.cleanupOutputBeforeBuild()


	//create shared resources
	.createSharedEntry('vendor', [
		'jquery',
		'bootstrap-sass', //load boostrap/js
		'bootstrap-sass/assets/stylesheets/_bootstrap.scss'//load bootstrap/css,
	])

	// will output as web/build/app.js
	.addEntry('app', './app/Resources/assets/js/main.js')

	// will output as web/build/theme.css
	.addStyleEntry('theme', './app/Resources/assets/style/theme.scss')

	// allow sass/scss files to be processed
	.enableSassLoader()

	// allow legacy applications to use $/jQuery as a global variable
	.autoProvidejQuery()

	.enableSourceMaps(!Encore.isProduction())

	//for manifest.json
	.addLoader({ test: /\.json$/, loader: "json" })

// create hashed filenames (e.g. app.abc123.css)
// .enableVersioning()
;

// export the final configuration
module.exports = Encore.getWebpackConfig();
```

My base.html.twig:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block javascripts %}
            <script src="{{ asset('build/manifest.js') }}"></script>
            <script src="{{ asset('build/vendor.js') }}"></script>
            <script src="{{ asset('build/app.js') }}"></script>
            <script src="{{ asset('build/manifest.json') }}"></script>
        {% endblock %}
        {% block stylesheets %}
            <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
            <link rel="stylesheet" href="{{ asset('build/theme.css') }}">
            <link rel="stylesheet" href="{{ asset('build/vendor.css') }}">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% endblock %}
        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>
```

**Comment by Lyrkan** [comment]
Hi @hanwoods,

Your `manifest.json` file looks fine to me, the error message comes from the fact that you are trying to load it from your `base.html.twig` as a script (which is invalid since this is not a JS file).

I see that you have a `manifest.js` file referenced in the `manifest.json`, maybe you were trying to load that one instead?

Anyway, removing/replacing that line that should make that error go away.

**Comment by hanwoods** [comment]
Oh! Must have missed that. Thank you for taking a look!

**Comment by weaverryan** [comment]
No worries - cheers!

**Comment by trsteel88** [comment]
@weaverryan do you have a link to documentation around manifest.js? Why is this file required and what does it do?

I have a defer async on my main js and run into errors every now and again if it loads before manifest.js

p.s loving webpack encore!

**Comment by weaverryan** [comment]
Hey!

Hmmm. It’s a bit complex, but basically, the contents of manifest.js change fairly frequently, do to some Webpack internal stuff. We *could* combine these contents into your shared entry, js elminate the need for manifest.js entirely. But then, the contents of your shared entry would change more frequently, even when all the files that make up your shared entry do not change. Because these files are quite large, this is bad for caching. That’s why we chose to split the frequently changing manifest.js stuff out of the shared entry.

**Comment by trsteel88** [comment]
Thanks for getting back to me. Do you have any documentation that explains it in more detail - would love to look into it a bit more. If it had a callback when it loaded that would be good as we could then use defer async on the one file (which then loads the others).

**Comment by weaverryan** [comment]
I don’t have more docs, but this is a standard strategy with Webpack version 3 and earlier.
