### ISSUE TITLE
Webpack Encore and Tree Shaking

### ISSUE THREAD

**Issue by a-s-y-n-c** [symfony/webpack-encore#192]
Hi, I am quite new to Webpack, and I was wondering if Tree Shaking is enabled in Encore by default?

From the looks of it, it seems that all exported objects from a module are always bundled, only sometimes you can come across such comments:
```
/*! exports used: email, required, sameAs */
```
Do I understand it correctly that unused code is not removed during minification (only listed as unused)? Is it something I could set up? I could not find any documentation on that.

Thank you very much for your answers.

**Comment by Lyrkan** [comment]
Hi @a-s-y-n-c,

Tree shaking should be working by default.

For instance if you have the following files:

```js
// src/imports.js
export function testA() {
  console.log('Test A');
}

export function testB() {
  console.log('Test B');
}
```

```js
// src/index.js (entry point)
import { testA } from './imports';

testA();
```

Running `yarn encore dev` should generate something similar to this (among other things):

```js
/***/ "./src/imports.js":
/*!************************!*\
  !*** ./src/imports.js ***!
  \************************/
/*! exports provided: testA, testB */
/*! exports used: testA */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (immutable) */ __webpack_exports__["a"] = testA;
/* unused harmony export testB */
function testA() {
  console.log('Test A');
}

function testB() {
  console.log('Test B');
}

/***/ }),
```

However if you run `yarn encore production` the `/* unused harmony export testB */`  comment will be picked up by `UglifyJs` which will then remove the related export during minification. In this case you shouldn't be able to find the string "Test B" in the generated file:

```js
!function(e){function t(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}var n={};t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{configurable:!1,enumerable:!0,get:r})},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="/",t(t.s="lVK7")}({dxJD:function(e,t,n){"use strict";function r(){console.log("Test A")}t.a=r},lVK7:function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var r=n("dxJD");Object(r.a)()}});
```

**Comment by a-s-y-n-c** [comment]
Great, thank you for the answer :)
