### ISSUE TITLE
Document how/when to enable polling

### ISSUE THREAD

**Issue by weaverryan** [symfony/webpack-encore#194]
See: https://github.com/symfony/webpack-encore/issues/191#issuecomment-340377542

... and perhaps, we should even add something to our API to make this easier.

**Comment by vkryukov76** [comment]
Full Encore API reference would be very useful.

**Comment by weaverryan** [comment]
Hmm... I agree!

**Comment by Kocal** [comment]
I've opened https://github.com/symfony/symfony-docs/pull/11398 that should resolve the issue.
