### ISSUE TITLE
How to import multiple js files?

### ISSUE THREAD

**Issue by peyman-mohamadpour** [symfony/webpack-encore#199]
**node**: 8.7.0
**npm**: 5.5.1
**yarn** : 1.2.1
**webpack-encore**: 0.17.0

Googled a lot with little or no success.
I need to PACK multiple separated js files into one `app.js`. How is that possible, using encore?

This is my `webpack.config.js` :
```
Encore
   ...
   .addEntry('app', './web/assets/js/main.js')
   ...
```

and This is `main.js` :

```
var $ = require('jquery');
window.$ = $;
window.jQuery = $;

importScripts(['./web/assets/vendor/semantic/semantic']);
importScripts(['./web/assets/js/tablesort']);

```

I need a functionality like `@import`, inside `.scss` files.

**Comment by weaverryan** [comment]
Hey @peyman-mohamadpour!

This is exactly what the `require` keyword is for :). You're already packaging `jquery.js` into `app.js` by requiring it :). So, something like:


```js
var $ = require('jquery');
window.$ = $;
window.jQuery = $;

require('./web/assets/vendor/semantic/semantic');
require['./web/assets/js/tablesort');
```

Those libraries may or may not return a value (the `jquery` module returns a value, for example) - so you may or may not need to set them to a variable. But by requiring them, they will be inside your final, built file.

Let us know if that helped! Cheers!

**Comment by peyman-mohamadpour** [comment]
This is what I get:

` ERROR  Failed to compile with 2 errors`

These relative modules were not found:

```
* ./web/assets/js/tablesort in ./web/assets/js/main.js
* ./web/assets/vendor/semantic/semantic in ./web/assets/js/main.js
```

**Comment by weaverryan** [comment]
Hey @peyman-mohamadpour!

It looks like the file paths to those files are just incorrect :). Where do the `tablesort.js` and `semantic.js` files live? The `require` statement (much like `@import`) accepts a file path to the JavaScript file (but the `.js` suffix is optional). If you pass the wrong path, you'll get this error.

Cheers!

**Comment by peyman-mohamadpour** [comment]
Could you please help me out of this?

files:
```
/Users/peyman/sites/newnarmafzam/web/assets/vendor/semantic/semantic.js
/Users/peyman/sites/newnarmafzam/web/assets/js/tablesort.js
```
`webpack.config.js` location (project root):
```
/Users/peyman/sites/newnarmafzam
```
What's the correct way of using `require`?

**Comment by Lyrkan** [comment]
Hi @peyman-mohamadpour,

The paths are relative to the location of the file you add them in.

In your case:

```js
require('../vendor/semantic/semantic.js');
require('./tablesort.js');
```
