### ISSUE TITLE
Add Vendors CSS support

### ISSUE THREAD

**Issue by nietzscheson** [symfony/webpack-encore#20]

**Comment by stof** [comment]
Please give more details about what you expect

**Comment by nietzscheson** [comment]
Inside the [documentation](http://symfony.com/doc/current/frontend/encore/shared-entry.html) is an example of how to load the vendors' .js (jQuery | Bootstrap).

- .createSharedEntry ('vendor', ['jquery', 'bootstrap'])

I want to know how I can load the styles (.css | .scss) example, from Boostrap:

- .createStyleSharedEntry ('vendor', ['bootstrap']) (?)

**Comment by anacona16** [comment]
It's a good question, for example, is possible to add **sweetalert** as a vendor?

**Comment by weaverryan** [comment]
Ah, so it should already be possible (though it's not explicitly documented):

```js
.createStyleSharedEntry ('vendor', [
    'jquery',
    'bootstrap-sass/assets/stylesheets/_bootstrap.scss',
   // ...
])
```

When you do this, in addition to having a `vendor.js`, you will also now have a `vendor.css`, which you will need to include on your page.

Is that what you're asking about? You're interested in how you can "extract" commonly-used CSS into a single file, correct?

**Comment by nietzscheson** [comment]
Thank you, @weaverryan. Just what I needed ... But, not to confuse the others, `createStyleSharedEntry` was a method that I believed believing that the assest .css were loaded. The right way is: `.createSharedEntry ('vendor', ['jquery', 'bootstrap', 'bootstrap-sass / assets / stylesheets / _bootstrap.scss'])`

**Comment by weaverryan** [comment]
@nietzscheson Ah, thank you for noticing my typo - I fixed my comment not to confuse others. 

I've just opened a PR on the docs: https://github.com/symfony/symfony-docs/pull/8055. Thanks for opening the issue - it'll definitely help others :)
