### ISSUE TITLE
Webpack is not packing my assets ?!

### ISSUE THREAD

**Issue by MM-Psiiirus** [symfony/webpack-encore#202]
Hi,
i'm using a the config below and was wondering why it is not packing my linked images inside my main.less file properly. 

Should'nt it move files out of a url() call into the /web/builds folder and rewrite it the url()-path ?

```
...
background-image: url(/project_root/src/WebsiteBundle/Resources/images/bg.jpg)
...
```
to something like
```
...
background-image: url(/build/bg.asd7asd76.jpg)
...
```

webpack.config.js
````
var Encore = require('@symfony/webpack-encore');

Encore
// directory where all compiled assets will be stored
    .setOutputPath('web/build/')

    // what's the public path to this directory (relative to your project's document root dir)
    .setPublicPath('/build')

    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()
    
    // will output as web/build/app.js
    .addEntry('app', './src/WebsiteBundle/Resources/assets/script.js')

    // will output as web/build/global.css
    .addStyleEntry('global', './src/WebsiteBundle/Resources/less/screen.less')
        
    // allow sass/scss files to be processed
    .enableLessLoader(function(options) {
        // https://github.com/webpack-contrib/less-loader#examples
        // http://lesscss.org/usage/#command-line-usage-options
        options.relativeUrls = false;
    })
    .enablePostCssLoader()

    // allow legacy applications to use $/jQuery as a global variable
    .autoProvidejQuery()

    .enableBuildNotifications()

    .enableSourceMaps(!Encore.isProduction())
// create hashed filenames (e.g. app.abc123.css)
    .enableVersioning()
;
```

**Comment by Lyrkan** [comment]
Hi @MM-Psiiirus,

I think the Less loader is expecting you to give URLs that are relative to the file you are using them in.

For instance if you have `assets/images/bg.jpg` and you want to use it in `styles/screen.less` you should write something like this:

```less
// styles/screen.less
background-image: url(../assets/images/bg.jpg);
```

**Comment by MM-Psiiirus** [comment]
Thanks, gonna try, hope it will fix it but thought relativeUrls = false would change this behaviour.

```
    .enableLessLoader(function(options) {
        // https://github.com/webpack-contrib/less-loader#examples
        // http://lesscss.org/usage/#command-line-usage-options
        options.relativeUrls = false;
    })
```

**Comment by weaverryan** [comment]
Let us know if that works! As a best practice, using relative URLs is best. Though, reading the docs on the `relativeUrls` option, I agree that it *seems* like that is supposed to convert the absolute paths to relative - but I'm not sure!

**Comment by Lyrkan** [comment]
I think it's more about keeping it relative to the file you are using it or not.

For instance if you have two files:

```less
// styles/entry.less
@import './subfolder/imported.less';
```

```less
// styles/subfolder/imported.less
.test {
  background: url(./image.png);
}
```

* with `relativeUrls = true` Less will expect the image to be at `styles/subfolder/image.png`
* with `relativeUrls = false` Less will expect the image to be at `styles/image.png`

Most of the time the first approach will probably feel more natural.

**Comment by Lyrkan** [comment]
Hi @MM-Psiiirus,

Did you solve your issue?

**Comment by MM-Psiiirus** [comment]
@Lyrkan sorry I have to hit a deadline which doesn't give me the spare time to finish my webpack encore playings. :-/

**Comment by weaverryan** [comment]
Closing - issue is old. Please open a new issue if needed! Thanks!
