### ISSUE TITLE
Installation Webpack ?

### ISSUE THREAD

**Issue by thibzh** [symfony/webpack-encore#210]
I'm new with Webpack and javascript application. 
I try to install Webpack encore to add react page to my website.

I am configuring a new symfony application to test it and it does not work.

I followed 5 times the step by step process here : 
https://symfony.com/doc/current/frontend/encore/simple-example.html
or here https://medium.com/a-young-devoloper/symfony-encore-an-awesome-library-4c7da3301139

Here the principal steps : 
1. Install symfony : symfony new React
2. cd React
3. yarn add @symfony/webpack-encore --dev
4. create folder assets, assets/css, assets/js under the react folder
5. create app.scss under assets/css and app.js under assets/js
6. create webpack.config.js with the parameters here https://symfony.com/doc/current/frontend/encore/simple-example.html
7. yarn run encore dev
Webpack say that I need to install sass loader.
8. yarn add sass-loader node-sass --dev
9. yarn add webpack-notifier --dev
10. yarn add jquery --dev
11. create the js files with the content here : https://symfony.com/doc/current/frontend/encore/simple-example.html 
11. yarn run encore dev

yarn run v1.3.2
warning package.json: No license field
$ /Applications/MAMP/htdocs/react5/node_modules/.bin/encore dev
Running webpack ...

 DONE  Compiled successfully in 984ms                                                                                  15:12:44

 I  2 files written to web/build
✨  Done in 1.85s.

When I go to the localhost web folder, I've got a blank page.

Do I miss something ?

[webpack.config.js.zip](https://github.com/symfony/webpack-encore/files/1484675/webpack.config.js.zip)
[assets.zip](https://github.com/symfony/webpack-encore/files/1484676/assets.zip)

**Comment by javiereguiluz** [comment]
The steps you followed seem correct. The blank page is probably an error unrelated to Webpack Encore (maybe a permission issue?). To see if Encore is working, checkout the the contents of the `web/build/` dir. You should see the CSS and JS files generated by Encore.

**Comment by thibzh** [comment]
Thanks for your very quick answer :)

I've got these two files in the folder web/build 
[Archive.zip](https://github.com/symfony/webpack-encore/files/1484681/Archive.zip)

**Comment by javiereguiluz** [comment]
Everything looks OK (don't worry about how ugly `app.js` looks ... when you compile them for production (`./node_modules/.bin/encore production`) everything is minified).

So Webpack Encore is working as expected and then this is another issue:

1) If you see a completely blank page, that's probably a permission issue. Check out this guide if you need it: https://symfony.com/doc/current/setup/file_permissions.html and check the log messages of the application in var/logs/
2) If the page is displayed without styles, you still need to link the assets generated with Encore to your page. Use the asset() Twig function as explained in https://symfony.com/doc/current/frontend/encore/simple-example.html

**Comment by thibzh** [comment]
If I write "hello world" in the base.html.twig I see "hello world".
An I have the toolbar in app_dev.php.
But it seems that the application does not read the app.js application.
[base.html.twig.zip](https://github.com/symfony/webpack-encore/files/1484686/base.html.twig.zip)

<img width="1440" alt="capture d ecran 2017-11-18 a 15 57 40" src="https://user-images.githubusercontent.com/10027756/32981695-3d2b3fba-cc79-11e7-8deb-772f181b9060.png">

**Comment by thibzh** [comment]
[dev.log](https://github.com/symfony/webpack-encore/files/1484697/dev.log)

I've got one error with the scss file. There is no file in the build folder. 
Actually my app.sccs file is empty. 

Do you think that I see nothing because the scss file is empty ?

**Comment by javiereguiluz** [comment]
I just realized this is an error in Symfony Docs (https://github.com/symfony/symfony-docs/pull/8375). The JavaScript code is looking for an `<h1>` element in the template ... but there's no `<h1>` ... so nothing works. Add a `<h1>` in the template and the JavaScript code should work as expected.

**Comment by thibzh** [comment]
Ok it works

**Comment by thibzh** [comment]
thanks.

I will now try with react

**Comment by javiereguiluz** [comment]
Closing then as fixed. Cheers!
