### ISSUE TITLE
[documentation] possible error in yarn run command

### ISSUE THREAD

**Issue by andrewtch** [symfony/webpack-encore#213]
Official docs - http://symfony.com/doc/current/frontend/encore/simple-example.html say to run webpack-encore with:

```yarn run encore dev --watch```

shouldn't it be 

```yarn run encore dev -- --watch``` as otherwise `yarn` will not pass parameters to the command?

**Comment by Lyrkan** [comment]
Hi @andrewtch,

The double dash is not required (nor advised) anymore by `yarn` since its v1.0, so the doc was modified accordingly.

Related commit: https://github.com/symfony/symfony-docs/commit/c44d9132831517b378745a9b1851f168c0c6f369
