### ISSUE TITLE
Webpack and Assetic in the same project

### ISSUE THREAD

**Issue by Aminaxago** [symfony/webpack-encore#219]
Hello guys,

We have a big project made with Symfony and using Assetic for asset management. We want to transition to Webpack Encore. Is it possible to use Webpack and Assetic at the same time while the transition is being made? Are there any possible conflicts?

**Comment by stof** [comment]
yes, you can use them at the same time. However, they won't be aware of each other (so if you include jQuery in your asset processed by Assetic, webpack might still bundle it in its own assets for instance)

**Comment by Lyrkan** [comment]
@Aminaxago Does that answer your question?

**Comment by Aminaxago** [comment]
@Lyrkan Yes, it does. Thank you @stof .
