### ISSUE TITLE
Invalid option "resolveUrlLoader" passed to enableSassLoader(). Valid keys are resolve_url_loader

### ISSUE THREAD

**Issue by metaer** [symfony/webpack-encore#226]
I add
```
    .enableSassLoader(function(sassOptions) {}, {
        resolveUrlLoader: false
    })
```

When I try run command:
`yarn run encore dev`

I get

> Invalid option "resolveUrlLoader" passed to enableSassLoader(). Valid keys are resolve_url_loader

Screenshot from this documentation:
http://symfony.com/doc/current/frontend/encore/bootstrap.html
![c2fea9486b](https://user-images.githubusercontent.com/6103208/34084403-bfd388ea-e390-11e7-8ccb-aaed8d7763c6.png)

If I change resolveUrlLoader to resolve_url_loader everything is ok.

**Comment by Lyrkan** [comment]
Hi @metaer,

Which version of Encore are you using? `resolve_url_loader` has been replaced by `resolveUrlLoader` in v0.15.0 by #159.

**Comment by metaer** [comment]
Here is strings from my package.json:
```
  "name": "@symfony/webpack-encore",
  "version": "0.12.0",
```

I run
`composer require encore`
with symfony flex

**Comment by Lyrkan** [comment]
The Flex recipe looks outdated, it uses `^0.12.0` which only allows versions matching `0.12.*`.

Try running `yarn upgrade @symfony/webpack-encore` to get the latest version (0.17.0).

**Comment by metaer** [comment]
Thank you. Now resolveUrlLoader works.
Should I open new issue "Flex recipe is outdated" ?

**Comment by Lyrkan** [comment]
Great :)

You can either open an issue in the symfony/recipes repository or directly send a PR that increments the version number there: 

https://github.com/symfony/recipes/blob/5314397ba6743c9defb3ecf467e7bf34bff66290/symfony/webpack-encore-pack/1.0/package.json#L3

**Comment by fabpot** [comment]
@weaverryan Wouldn't it make sense to release 1.0 now?
