### ISSUE TITLE
Conflicts with a named pass

### ISSUE THREAD

**Issue by Sydney-o9** [symfony/webpack-encore#228]
Hi Team,

```
Encore
    //..
    .addEntry('app', './assets/js/app.js')
    .addStyleEntry('app', './assets/css/app.scss')
```

![image](https://user-images.githubusercontent.com/1480617/34318914-58c01a56-e827-11e7-809b-5fb1621ee415.png)

Is there a particular reason why we can't do the above? Just wondering because, in most cases, if people don't use react for example, or CSS modules, embedding `.css` in `.js` doesn't really make sense.

**Comment by Lyrkan** [comment]
Hi @Sydney-o9,

Yes there is a reason for that check :)
The ability to add stylesheets as entry points separately from js entry points isn't actually a feature from Webpack but something added in Encore.

If you look at how the actual [`entry` property](https://webpack.js.org/concepts/entry-points/) is generated by Encore, you'll see that normal entries (from `Encore.addEntry()`) and style entries (from `Encore.addStyleEntry()`) are handled the exact same way, which prevents using the same names:

https://github.com/symfony/webpack-encore/blob/bcfbbfd6ab684197b2315f850dcb2db56172ea34/lib/config-generator.js#L95-L109

So why two separate methods? Well, if you add a style file with `Encore.addEntry()` you'll end-up having two generated files: `name.js` and `name.css`. But if you add it using `Encore.addStyleEntry()` instead, Encore will take care of removing that extra JS file:

https://github.com/symfony/webpack-encore/blob/c6057af7521594d9d76cfd072b1f2421591e4a3f/lib/plugins/delete-unused-entries.js#L22-L28

**Comment by Sydney-o9** [comment]
Hi @Lyrkan Thank you for taking the time to explain.
