### ISSUE TITLE
ERROR Failed to compile

### ISSUE THREAD

**Issue by nietzscheson** [symfony/webpack-encore#23]
If I need a dependency the system warns me of the error and tells me what to do:
```console
To install them, you can run: npm install --save font-awesome
```
If I run: `npm install --save font-awesome` and I need to compile again with Encore:
```console
- ./node_modules/.bin/encore dev
- No such file or directory: ./node_modules/.bin/encore
```

**Comment by weaverryan** [comment]
Hi there!

Interesting! Can you post your package.json file? Also, if you completely remove the node_modules directory and run "yarn install", does that fix things?

**Comment by nietzscheson** [comment]
My package.json:

```json
{
  "dependencies": {
    "bootstrap": "4.0.0-alpha.6",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "sweetalert2": "^6.6.5",
    "tether": "^1.4.0"
  },
  "devDependencies": {
    "@symfony/webpack-encore": "^0.7.2",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6"
  },
  "scripts": {
    "dev": "./node_modules/.bin/encore dev",
    "watch": "./node_modules/.bin/encore dev --watch",
    "prod": "./node_modules/.bin/encore production"
  }
}
```
I have configured some commands in the json package as npm run dev and throw me:

```console

> @ dev /home/vagrant/projects/payex
> encore dev

sh: 1: encore: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ dev: `encore dev`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
These are the files in node_modules, after installing the new dependency:
![encore](https://user-images.githubusercontent.com/1699198/27343954-3b6525ba-55aa-11e7-97af-b4c8e82dade0.png)

**Comment by weaverryan** [comment]
@nietzscheson Hmm, yea, everything looks ok - obviously except for the empty `.bin` directory. Yarn should absolutely put putting the `encore` executable there. What if you:

```
rm -rf node_modules
yarn install
```

Does this re-populate the `node_modules/.bin` directory, or is it still empty after this?

Cheers!

**Comment by stof** [comment]
As I see vagrant in the screenshot, this might be related to a bad behavior of symlinks in the vagrant shared folder (see https://github.com/npm/npm/issues/7308 for such report in the past).

On a side note, your scripts entry in the package.json could be `encore dev` only, as the `node_modules/.bin` folder is added in the PATH by npm/yarn when running scripts (and it helps making your `scripts` section portable, by avoiding the need of a directory separator to access the executable)

**Comment by nietzscheson** [comment]
The problem continues. The `.bin` folder within `node_modules` is easily deleted ...

**Comment by weaverryan** [comment]
@nietzscheson What do you mean by "node_modules is easily deleted". What is deleting it? Do you originally see this directory... and then later it is missing? How is your file sharing setup in Vagrant? And what is your host operating system?

Thanks for the info!
