### ISSUE TITLE
How to compile JavaScript in HTML files?

### ISSUE THREAD

**Issue by wwwd3v** [symfony/webpack-encore#234]
Hi, I am implementing Vue.js in my Twig templates. I need to transpile ES6 to ES5 inside the `script` tag.

```
<!-- ... -->
        <div id="my_form">
            {{ form_widget(form.username, {'attr': {'v-model': 'username'}}) }}
        </div>

        <script>
          new Vue({
            el: '#my_form',
            data: {
              username: {{ form.username.vars.value }},
            },
          });
        </script>
    </body>
</html>
```

Why inline JS? Because I need TWIG functions/directives to be accessible inside the Vue component's scope. (You cannot do `{  username: {{ form.username.vars.value }} }` inside a separate .js file).

Is there some reason I could hook it up? Thank you very much for your help!

**Comment by Lyrkan** [comment]
Hi @a-s-y-n-c,

Twig files are not handled by Encore/Webpack, so you can't apply any transformation inside of them.

So you can either:

* transpile your code to ES5 manually using babel before adding it to your Twig
* put your code inside a JS file processed by Webpack and pass the values you want to it from your Twig templates (there are multiple ways to do that, one of them being explained on the following page: https://symfony.com/doc/current/frontend/encore/server-data.html)

**Comment by vkryukov76** [comment]
@a-s-y-n-c 

For one of my projects I wrote simple module.

It iterates over specific elements on page and initializes Vue components in them.

https://gist.github.com/vkryukov76/5c85de6122083b77181aca3baee0c15e

**Comment by weaverryan** [comment]
Closing - issue is old. Please open a new issue if needed! Thanks!
