### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by jboisgontier** [symfony/webpack-encore#235]
Hi, 
I'm using Symfony 3.3 and WebPack for assets management. I'm actually getting issues with fonts which are not decoding properly :

`Failed to decode downloaded font: http://website.local/build/fonts/opensans-bold-webfont.ttf
(index):1 
Failed to decode downloaded font: http://website.local/build/fonts/opensans-regular-webfont.ttf
2(index):1 
Failed to decode downloaded font: http://website.local/build/fonts/icomoon.woff
2(index):1 
Failed to decode downloaded font: http://website.local/build/fonts/icomoon.ttf
`

I can't figure what I'm doing wrong.. 
Furthermore, I configured exactly the same on a side project with Symfony 4 version, and everything is doing fine.

Here is the actual configuration :

**strucure for assets folder :** 

- css
-- app.scss
- fonts
-- all fonts files here
- js
-- app.js

**package.json :** 

`{
  "devDependencies": {
    "@symfony/webpack-encore": "^0.12.0",
    "jquery": "^3.2.1",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "select2": "^4.0.6-rc.1"
  },
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "dev-server": "encore dev-server",
    "dev": "encore dev",
    "watch": "encore dev --watch",
    "build": "encore production"
  }
}`

**webpack.config.js :** 

var Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('web/build/')
    .setPublicPath('/build')
    .addEntry('app', './assets/js/app.js')
    .enableSassLoader()
    .autoProvidejQuery()
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
;

module.exports = Encore.getWebpackConfig();

**app.scss :** 

This is imported in app.js file with require('../css/app.scss'); 

@font-face {
  font-family: 'opensans';
  src: url('../fonts/opensans-regular-webfont.woff') format('woff');
  src: url('../fonts/opensans-regular-webfont.eot');
  src: url('../fonts/opensans-regular-webfont.eot?#iefix') format('embedded-opentype'),
  url('../fonts/opensans-regular-webfont.ttf') format('truetype'),
  url('../fonts/opensans-regular-webfont.svg#open_sansregular') format('svg');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'opensans_bold';
  src: url('../fonts/opensans-bold-webfont.woff') format('woff');
  src: url('../fonts/opensans-bold-webfont.eot');
  src: url('../fonts/opensans-bold-webfont.eot?#iefix') format('embedded-opentype'),
  url('../fonts/opensans-bold-webfont.ttf') format('truetype'),
  url('../fonts/opensans-bold-webfont.svg#open_sansbold') format('svg');
  font-weight: bold;
  font-style: normal;
}

@font-face {
  font-family: 'icomoon';
  src: url('../fonts/icomoon.eot');
  src: url('../fonts/icomoon.eot?#iefix') format('embedded-opentype'),
  url('../fonts/icomoon.woff') format('woff'),
  url('../fonts/icomoon.ttf') format('truetype'),
  url('../fonts/icomoon.svg#open_sansbold') format('svg');
  font-weight: normal;
  font-style: normal;
}

Thanks for your help !

**Comment by Lyrkan** [comment]
Hi @jboisgontier,

Did you try loading `http://website.local/build/fonts/opensans-bold-webfont.ttf ` (for instance) in your browser to check if it downloads the right file?

**Comment by jboisgontier** [comment]
I did, it is downloading fine.

**Comment by Lyrkan** [comment]
And if you open it does your font viewer displays it correctly?

I'm kinda lost there because you says that it works with Symfony 4... but Encore is not really tied to Symfony, the files created by Webpack should be the same in both cases.

I found [this issue](https://github.com/webpack-contrib/file-loader/issues/38) on the file-loader repository but I'm not sure that's related. Do you also have some other messages in your Chrome console about why the decoding fails?

**Comment by jboisgontier** [comment]
Problem solved : I found the solution by deleting font files in the font directory and replacing them by the original ones... 
Thanks anyway for your help !
