### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by eldiablo62** [symfony/webpack-encore#245]
Hi, 

I have an error when i run node_modules/.bin/encore dev --watch
`/var/www/myproject/node_modules/@symfony/webpack-encore/index.js:120
    configureDefinePlugin(definePluginOptionsCallback = () => {}) {
                                                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/myproject/webpack.config.js:2:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
`
This is my webpack.config.js
`// webpack.config.js
var Encore = require('@symfony/webpack-encore');
Encore
// the project directory where all compiled assets will be stored
    .setOutputPath('web/build')

    // the public path used by the web server to access the previous directory
    .setPublicPath('/build')

    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()

    .addEntry('js/app', './assets/js/app.js')
    .addEntry('js/bundles', './assets/js/bundles.js')

    .addStyleEntry('css/app', './assets/css/app.css')
    .addStyleEntry('css/bundles', './assets/css/bundles.scss')

    // allow sass/scss files to be processed
    //.enableSassLoader()

    .enableSassLoader(function(sassOptions) {}, {
        resolveUrlLoader: false
    })

    // allow legacy applications to use $/jQuery as a global variable
    .autoProvideVariables({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery'
    })

    .enableSourceMaps(!Encore.isProduction())

    // show OS notifications when builds finish/fail
    .enableBuildNotifications()

// create hashed filenames (e.g. app.abc123.css)
// .enableVersioning()
;
// export the final configuration
module.exports = Encore.getWebpackConfig();
`
I'm using phpstorm on ubuntu 16.04 my nodejs version is 4.2.6.
Thank you for you help

**Comment by Lyrkan** [comment]
Hi @eldiablo62,

Encore doesn't support your version of Node (which lacks some JS features that we're using), you'll have to update it to a newer one:

https://github.com/symfony/webpack-encore/blob/00e4051eb0ef18786a9d6abe2f9f2e73c887e8fa/package.json#L24-L26

I guess you installed it with npm which only displays a warning in case of an engine incompatibility (whereas Yarn throws an error):

* Using npm:

![image](https://user-images.githubusercontent.com/850046/35285459-bb470f9c-005d-11e8-813a-94a00efd495b.png)

* Using Yarn:

![image](https://user-images.githubusercontent.com/850046/35285430-a8e1f812-005d-11e8-94d1-1f4dd9a3b7d4.png)
