### ISSUE TITLE
Webpack Encore does not extract svg fonts.

### ISSUE THREAD

**Issue by Sydney-o9** [symfony/webpack-encore#257]
I've noticed it doesn't 

```js
// Keep folder structure for images
Encore.configureFilenames({
    fonts: './fonts/[name].[hash:8].[ext]'
});
```
![image](https://user-images.githubusercontent.com/1480617/35842054-089e1280-0b54-11e8-87da-4a4feb91529d.png)

**Comment by Lyrkan** [comment]
Aren't they copied into your "images" build directory by any chance?

Only files with the woff, woff2, ttf, eot or otf extension are treated like fonts:

https://github.com/symfony/webpack-encore/blob/2684b7a907ed1351e5cd9439011cb811802af428/lib/config-generator.js#L159-L174

SVG files are supposed to be handled by the loader used for images:

https://github.com/symfony/webpack-encore/blob/2684b7a907ed1351e5cd9439011cb811802af428/lib/config-generator.js#L142-L157

**Comment by weaverryan** [comment]
Closing - issue is old. Please open a new issue if needed! Thanks!
