### ISSUE TITLE
Vue Loader not processing .vue files

### ISSUE THREAD

**Issue by hermann8u** [symfony/webpack-encore#259]
Hi,

After two hours playing with Vue, Symfony and Webpack encore, I finally found where was my problem. I wanted to use this structure to init my App component (where my App component is a .vue file).

```
new Vue({
  el: '#app',
  router,
  components: { App },
  template: `<App/>`
})
```

turning to this to make it work (basicaly export my component in inline component):

```
new Vue({
    el: '#app',
    router,
    name: 'app',
    template: `
    <div id="app">
        <h1>My App</h1>
        <div class="container">
          <router-view/>
        </div>
    </div> `
})
```

Even like this, my component depending on the route is not working properly (the css is not used at all).

My conclusion is that the .enableVueLoader() (which should allow to read .vue files) in my webpack config is not working as expected.

Am I missing something?
Thanks

**Comment by Lyrkan** [comment]
Hey @hermann8u,

I don't think there is an issue with the `vue-loader`, we've a test that basically does the same thing than your first example using these files: https://github.com/symfony/webpack-encore/tree/master/fixtures/vuejs

What error(s) do you get with your first snippet? Do you import your `.vue` file correctly?
As for your CSS issue: could you provide more detail about how you set it up and how you include it into your page?

**Comment by hermann8u** [comment]
I found why this issue append! The problem was that my entry file app.js add the same name that my root component App.vue. Webpack had problem to understand the difference between them during import and the export default of my App.vue file was not found because of this...

sorry for inconvenience
