### ISSUE TITLE
Dev files present in a package from npm 

### ISSUE THREAD

**Issue by eXtreme** [symfony/webpack-encore#261]
So while debugging some configuration problems in my setup, I browsed to encore in my node_modules and notices some "strange" test/debug/dev files and folders:

![image](https://user-images.githubusercontent.com/197671/36072426-d0e30a6a-0f1f-11e8-8a7c-34d8c27674e4.png)

See: `.idea`, `test_tmp`, `_notes` and even a `webpack.config.js` with `//Encore.foo();` and `node_modules` - which are not present in the repo here (in 0.17.1 there was also `yarn-error.log` for example). At first I thought I somehow have an old version installed or something but I've double checked that and it latest 0.17.1 (well, it is 0.18.0 right now because you've just released it 😄). 

You can browse through package files on yarnpkg: https://yarnpkg.com/en/package/@symfony/webpack-encore?files and you can clearly see that these folders and files are indeed in the package. 

Is everything ok with the publishing proces here?

**Comment by weaverryan** [comment]
Hi there!

Thanks for opening the issue. Indeed, I think there *is* a problem with the packaging process: npm appears to take local, uncommitted files from my machine when running “npm publish”.

I’ll check into this and update or process.

**Comment by weaverryan** [comment]
I just published a new release that should be better :).
