### ISSUE TITLE
blueimp/Gallery Failed to compile

### ISSUE THREAD

**Issue by ibasaw** [symfony/webpack-encore#267]
hi,
With https://github.com/blueimp/Gallery, webpack failed to compile

```
* ./blueimp-gallery in ./vendor/ibasaw/ibasaw-sylius-0.18/src/Sylius/Bundle/WebBundle/Resources/public/js/jquery.blueimp-gallery.min.js
* ./blueimp-gallery-video in ./vendor/ibasaw/ibasaw-sylius-0.18/src/Sylius/Bundle/WebBundle/Resources/public/js/jquery.blueimp-gallery.min.js
* ./blueimp-helper in ./vendor/ibasaw/ibasaw-sylius-0.18/src/Sylius/Bundle/WebBundle/Resources/public/js/jquery.blueimp-gallery.min.js
```

How to bypass/override this ?

**Comment by stof** [comment]
from what I can see, blueimp/Gallery is supporting AMD and global variables, but does not support CommonJS by default.
But, their AMD build even looks messed up in their minified field, as it still tries to load some relative imports, which are not there in SyliusWebBundle. I don't know whether this is an issue in SyliusWebBundle not including the necessary files, or in blueimp/Gallery indeed messing their build file.

You could try to install blueimp-gallery from npm instead (which will install dependencies in a proper way for consumption) and make webpack import this version instead.

**Comment by ibasaw** [comment]
i will try this, thank you
