### ISSUE TITLE
jQuery plugins not exposed/provided

### ISSUE THREAD

**Issue by cvele** [symfony/webpack-encore#272]
When trying to initialize bootstrap-material-design jquery plugin it comes up as undefined.
`TypeError: $(...).bootstrapMaterialDesign is not a function`
Since that is the first plugin I try to execute it breaks there, however, if I skip it other plugins like datetime picker show the same symptoms.

I'm wondering how to get around this?

```javascript
// webpack.config.js
var Encore = require('@symfony/webpack-encore');

Encore
    ...
    .addEntry('js/jquery', './node_modules/jquery/dist/jquery.js')
    ...
    .addEntry('js/bootstrap-material-design', './node_modules/bootstrap-material-design/dist/js/bootstrap-material-design.js')
    ...
    .autoProvideVariables({
        $: "jquery",
        jQuery: "jquery",
        Popper: ['popper.js', 'default'],
        noUiSlider: 'noUiSlider'
    });

module.exports = Encore.getWebpackConfig();
```
I'm initializing plugins in the .js file managed by webpack like so:
```javascript
$(document).ready(function() {
    $('body').bootstrapMaterialDesign();
}
```
I'm guessing that I need to add them to autoProvideVariables somehow?

**Comment by cvele** [comment]
Adding `
require('bootstrap-material-design/dist/js/bootstrap-material-design.js');` on top of the init script solves it.

**Comment by Lyrkan** [comment]
Hi @cvele,

Indeed, you must require your libs where you use them (if they are not present in your `autoProvideVariables` call).

However make sure you don't call `addEntry()` for your vendors, that's not needed since they'll already be embedded in your bundle (you can call `createSharedEntry()` if you want to put them in a separate file).
