### ISSUE TITLE
isDevServer is missing

### ISSUE THREAD

**Issue by pribilinskiy** [symfony/webpack-encore#274]
I need to determine whether the build was invoked with `webpack-dev-server` in the same way as I can detect production environment with `Encore.isProduction()`

I've already looked in `process.env`

**Comment by pribilinskiy** [comment]
I've found a way

```js
const config = Encore.getWebpackConfig();
const isDevServer = 'devServer' in config;
```

Another option could be to look in the arguments [as described here](https://stackoverflow.com/questions/34887347/how-to-detect-if-webpack-dev-server-is-running), but:

```
./node_modules/.bin/encore dev-server

Running webpack-dev-server ...

[ '/usr/local/bin/node',
  '/var/www/public/node_modules/.bin/encore' ]
```

**Comment by weaverryan** [comment]
Thanks for posting your solution. We could add a method for this - I just never knew of a use-case :)
