### ISSUE TITLE
How to escape an allready minified js/css files

### ISSUE THREAD

**Issue by featuriz** [symfony/webpack-encore#278]
I'm working in symfony4 app, webpack is good . In many cases it fails.
I'm using this to combine all css/js files to one single file and minified. 
But there are more problems.

**Example:** 
1. If i'm using a jquery image gallery plugin. It has both css and js files. And both are minified allready. 
2. According to the plugin doc: To modify timing I have to write some js. Ex: baguetteBox.run('#gallery_freebie_grid');

**Problem:**
When i use _yarn run encore production_ It modifies the plugin and there is no **baguetteBox** name.

**Solutions:**

```
var baguetteBox = require('baguettebox.js');
window.baguetteBox = baguetteBox;
```

Write the above code in separate file(_init_bBox.js) and add 
`.addEntry('js/gallery', ['./assets/js/_init.js','./assets/js/_init_bBox.js', './assets/js/app.js'])`

**Suggestion:**
Escaping already minify files. Something like adding a key (true/false)

**Comment by featuriz** [comment]
Now I have a new Issue Google map problem cant find initMap()
When compressing it changed to something else.

**Comment by stof** [comment]
Well, when using webpack, you are supposed to use module imports to access libraries, not accessing global variables. So the code would look like that:

```js
var baguetteBox = require('baguettebox.js');

baguetteBox.run('#gallery_freebie_grid')
```

**Comment by elenitaex5** [comment]
I have the same problem with Google Maps API and Webpack Encore in Symfony 4. The problem is caused by calling order. initMap() function must be defined before Google Maps API script call, but is no possible. 
Anybody knows how to do it propertly calling maps api with API KEY included before initmap function?

**Comment by weaverryan** [comment]
If you need to expose something as a global function from inside of a Webpack-loaded file, use the `global` key word - e.g.

```js
global.initMap = function() {

}
```

Cheers!
