### ISSUE TITLE
Cannot get the function to work 

### ISSUE THREAD

**Issue by spyridonas** [symfony/webpack-encore#279]
I'm upgrading an app from assetic to encore and so far everything went well, until the execution time came...

The app requires some global js stuff and i have defined them like this

```
.autoProvideVariables({
        App: bundle + '/public/scripts/app.js',
        'window.App': bundle + '/public/scripts/app.js',
        moment: 'moment'
         ...
```
The question is while the App is defined and exists in the global window (maybe ?) it says 

TypeError: App.getResponsiveBreakpoint is not a function

the function is defined like this  inside app.js

```
 getResponsiveBreakpoint: function(size) {
          .
          .
          .
          .


```

how can i solve that ? it worked before with the assetic package...

**Comment by stof** [comment]
is `app.js` exporting things using either the CommonJS or the ES6 syntax ?

`autoProvideVariables` allows to make things work when your files are *accessing* a component as a global variable, by telling Webpack to use the right module for that. But it still expects that the code defining the variable supports being loaded as a module. When the file does not supports being loaded as a module, more work is required (webpack also have ways to do it, but I don't remember whether encore exposes an easy config for them)

**Comment by spyridonas** [comment]
App.js is part of a theme, Metronic Admin theme, and it starts like this 
```
var App = function() {
```
at the end it says

```
jQuery(document).ready(function() {    
   App.init(); // init metronic core componets
});
```
so i guess it doens't export anything

**Comment by nicolas-bastien** [comment]
@spyridonas Hi did you find a way to make it work ?

I try to integrate Metronic to but I don't see how to make all the js initialisation work.

Thanks a lot for your help

**Comment by spyridonas** [comment]
Hi @nicolas-bastien . I gave up on trying to migrate unfortunately so i didn't find any solution..
If you do find any solution please let me know, i will be very interested !

**Comment by Lyrkan** [comment]
If I understand correctly you're in this situation: https://webpack.js.org/guides/shimming/#global-exports

So you could probably do (I didn't test it at all so I may be wrong):

```js
Encore.addRule({
  test: require.resolve(bundle + '/public/scripts/app.js'),
  use: 'exports-loader?App'
});
```

Then the autoProvideVariables should work as intended (if it doesn't try importing `app.js` into one of your file and exposing it manually in `global`).
