### ISSUE TITLE
cleanupOutputBeforeBuild does not respect exclusions

### ISSUE THREAD

**Issue by webbertakken** [symfony/webpack-encore#284]
Trying to use `public/` as my build folder. It looks like webpack-encore is not respecting exclusions from the [johnagan/clean-webpack-plugin](https://github.com/johnagan/clean-webpack-plugin).

```javascript
Encore

  ...

  // The project directory where compiled assets will be stored
  .setOutputPath('public/')

  // The public path used by the web server to access the previous directory
  .setPublicPath('/')

  // Empty the output directory between each build
  .cleanupOutputBeforeBuild(['**/*'], (options) => {
    options.verbose = true;
    options.exclude = ['index.php', 'public/index.php'];

    return options;
  })

  ... ;


module.exports = Encore.getWebpackConfig();

````

output:

```
yarn run v1.5.1
$ encore dev-server
Running webpack-dev-server ...

clean-webpack-plugin: C:\Repositories\repo\symfony\public
\**\* has been removed.
 DONE  Compiled successfully in 6547ms
```

expected behaviour:

```
deleted everything except `index.php`
Compile succesful
```

Am i right that the expected behaviour should be actually ignore the excluded files?

**Comment by Lyrkan** [comment]
Hi @webbertakken,

Could you try this ?

```
Encore.cleanupOutputBeforeBuild(['public'], (options) => {
    options.verbose = true;
    options.root = __dirname;
    options.exclude = ['index.php'];
  })
```

**Comment by webbertakken** [comment]
That resolves the issue! I am now able to achieve my goal; to have nothing in the public folder except the etry file `index.php` and the generated assets.

```
yarn run v1.5.1
$ encore dev-server
Running webpack-dev-server ...

clean-webpack-plugin: C:\Repositories\repo\public has been removed.
clean-webpack-plugin: 1 file(s) excluded - index.php
 DONE  Compiled successfully in 4335ms
```

To share with other people that read this, there are two added upsides to this configuration:
- The public folder can now be ignored in git, with the exception of index.php, meaning the folder itself is greyed out in the IDE and there's no need to ever access the folder during development;
- As a developer you force yourself to generate all assets, which helps to not expose unnecessary static files.

**Comment by Lyrkan** [comment]
Great :)

As to why it works: in Encore by default the `root` options of that plugin is set to your output path. So if you do something like `cleanupOutputBeforeBuild(['directory'], ...)` and your output path is "public", it'll try to delete "public/directory".

The following code won't work either:

```js
Encore.cleanupOutputBeforeBuild(['**/*'], (options) => {
  options.exclude = 'index.php';
})
```

That can be explained by the way the `clean-webpack-plugin` handle file exclusions... it only allows them if the main path is a directory: https://github.com/johnagan/clean-webpack-plugin/blob/e9895d304f68a0c64eb4a89486074603d4937aef/index.js#L134-L135

**Comment by emulienfou** [comment]
If anyone has the same problem, this code is working for me:

```js
.cleanupOutputBeforeBuild(['public/build'], (options) => {
    options.verbose = true;
    options.root = __dirname;
    options.exclude = ['fos_js_routes.json'];
  })
```
