### ISSUE TITLE
Encore with PurgecssPlugin

### ISSUE THREAD

**Issue by kbond** [symfony/webpack-encore#285]
I am using encore with the PurgecssPlugin which does some css tree shaking. This plugin changes the content of the css but when building with versioning enabled, the filename hash doesn't change to respect the new content.

Any ideas how to solve this? I tried playing with plugin priorities with no luck...

**Comment by weaverryan** [comment]
Hey Kevin!

Sorry for the late reply. It's interesting... So we use the `[contenthash]` from https://github.com/webpack-contrib/extract-text-webpack-plugin to get the hashed filenames - so we're not doing anything too special. My guess (though I would expect there to be an issue somewhere) is that the changes made by `PurgecssPlugin` aren't playing well with that `[contenthash]` - i.e. `contenthash` is probably determined too early. In other words, most likely a bug with PurgeCssPlugin, and not something you'd be able to fix too easily.

I know, bad answer - but I hope it helps!

**Comment by kbond** [comment]
Hey! Thanks for looking into this. I came to the same conclusion. I ended up disabling versioning in Encore and created a simple SF command that versions the files. Not pretty but it gets the job done.

**Comment by stof** [comment]
@kbond you may use https://github.com/Incenteev/hashed-asset-bundle then
