### ISSUE TITLE
Is current ts-loader not work for encore?

### ISSUE THREAD

**Issue by TonyGao** [symfony/webpack-encore#289]
Hi, there. I'm just start using this component for typescript, and there is just a empty ts file and a empty tsconfig.json in entry. Then the command `yarn run encore dev` got a error `Module build failed: TypeError: Cannot read property 'afterCompile' of undefined`. 

Follow this [issue](https://github.com/TypeStrong/ts-loader/issues/729), I remove current ts-loader and re-add it in version 3.5.0, everything work well and it's compiled successfully.

**Comment by stof** [comment]
Encore currently uses Webpack 3. It is not yet migrated to webpack 4. Latest version of ts-loader is for Webpack 4 now.

**Comment by weaverryan** [comment]
Stof is correct! We're waiting on some upstream libraries (at least webpack-manifest-plugin) before we can support V4 :).

**Comment by Genarito** [comment]
Is there an aproximated date of Encore upgrade to webpack 4? Because I'm having troubles when compile `.tsx` files:

> Module build failed: TypeError: Cannot set property 'tsLoaderDefinitionFileVersions' of undefined
