### ISSUE TITLE
eyeglass sass integration

### ISSUE THREAD

**Issue by tarach** [symfony/webpack-encore#294]
I would like to integrate eyeglass-aware with encore
https://github.com/sass-eyeglass/eyeglass#building-sass-files-with-eyeglass-support

I'm having difficulties integrating it. Can't seem to find an entry point for it.

**Comment by tarach** [comment]
A bit ugly but it works. If you have a way to make it look/work better let me know. :)
```javascript
const webpackConfig = encore.getWebpackConfig();
let currentRules = webpackConfig.module.rules;
let newRules = currentRules;
let eyeglassOptions = {

};

for(const testNum in currentRules)
{
    if(!currentRules.hasOwnProperty(testNum) || typeof currentRules[testNum].test === 'undefined') {
        continue;
    }

    if(currentRules[testNum].test == '/\\.s[ac]ss$/') {

        for(const pluginIndex in currentRules[testNum].use)
        {
            if(currentRules[testNum].use[pluginIndex].loader == 'sass-loader') {
                let plugin = currentRules[testNum].use[pluginIndex];
                let newOptions = plugin.options;

                newOptions.eyeglass = eyeglassOptions;
                newRules[testNum].use[pluginIndex].options = eyeglass(newOptions);
            }
        }
    }
}

webpackConfig.module.rules = newRules;
module.exports = webpackConfig;
```

**Comment by stof** [comment]
note that you don't need to reassign `webpackConfig.module.rules` with `newRules`, as you modify the array in place.

And this is how it could look using a more functional way (thanks to the fact I don't need to re-assign stuff)

```js
webpackConfig.module.rules.forEach(rule => {
    if (rule.test != '/\\.s[ac]ss$/') {
        return;
    }

    rule.use.forEach(plugin => {
        if (plugin.loader != 'sass-loader') {
            return;
        }

        plugin.options = eyeglass(plugin.options);
    }
})
```

Things could be even easier if the Encore configuration callback for the sass loader could allow returning a new object for options instead of forcing to modify it by reference.

**Comment by stof** [comment]
This is how it could work in the future (this is not working yet):

```js
Encore.enableSassLoader(options => eyeglass(options))
```

**Comment by stof** [comment]
However, note that the webpack sass loader already has a syntax to import files from node_modules (it requires a `~` prefix, to avoid conflicts with same-folder imports)
