### ISSUE TITLE
Hot reload not working

### ISSUE THREAD

**Issue by Mrkisha** [symfony/webpack-encore#302]
I've tried to use Encore and hot reload, just like docs say and could not get it to work.
When I visit `localhost:8080` I get message that there is not /GET route.
If I check dev-toolbar I see 4xx error for the served content.

**Comment by weaverryan** [comment]
Hi there!

Can you post your webpack.config.js file and the command you’re running? Also, what port are you running Symfony on, 8000 (or some custom host)?

Cheers!

**Comment by Mrkisha** [comment]
```
let Encore = require('@symfony/webpack-encore');
const path = require('path')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

Encore
    // the project directory where compiled assets will be stored
    .setOutputPath('public/build/')
    // the public path used by the web server to access the previous directory
    .setPublicPath('/build')
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    // uncomment to create hashed filenames (e.g. app.abc123.css)
    .enableVersioning(Encore.isProduction())

    // uncomment to define the assets of the project
    .addEntry('js/app', './assets/js/app.js')
    .addStyleEntry('css/app', './assets/scss/app.scss')

    // uncomment if you use Sass/SCSS files
    .enableSassLoader(function (sassOptions) {}, {
      resolveUrlLoader: false
    })
    .enablePostCssLoader((options) => {
        options.config = {
            path: 'postcss.config.js'
        }
    })
    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()

    // show OS notifications when builds finish/fail
    .enableBuildNotifications()
    // uncomment for legacy applications that require $/jQuery as a global variable
    // .autoProvidejQuery()
;

var config = Encore.getWebpackConfig();

config.resolve = {
  alias: {
    'vue$': 'vue/dist/vue.esm.js',
    '@': resolve('assets/js/src'),
  }
}

module.exports = config;
```
Command:
`yarn run dev-server --hot`

**Comment by weaverryan** [comment]
Hey @Mrkisha!

Hmm, ok. So you see this page when you go to `http://localhost:8080', right?

<img width="241" alt="screen shot 2018-04-21 at 9 47 27 pm" src="https://user-images.githubusercontent.com/121003/39090450-9d489bb0-45ad-11e8-8d8d-88a261a8f5be.png">

What happens if you go to: http://localhost:8080/build/js/app.js

For me, it works (with your config exactly): it loads that file. If it doesn't work for you, *exactly* what is the error?

Cheers!

**Comment by pierre-moire** [comment]
I get the same error : 
Cannot GET /some_base_path/build/file.js

My dev-server is running on http://192.168.145.129:8080 and the firewall is stopped. Only the manifest file is created in the output folder, and not file.js. 

The intended behavior would be to display the file when I enter http://192.168.145.129:8080/some_base_path/build/file.js in the browser.

**Comment by pierre-moire** [comment]
Hi, thanks for your feedback.

The fact that the file is not present in the directory makes sense.

However the problem is according to your own exemple that if I enter http://localhost:8080/build/js/app.js in the browser it displays an error message (Cannot get /build/js/app.js ) even if it is mentioned in the manifest.json file

**Comment by weaverryan** [comment]
If you can push a reproducing repository to GitHub, we can take a look. The functionality of this feature is actually guaranteed in the tests. So, we’ll need your help to get us that reproducing project :). 

Cheers!

**Comment by pierre-moire** [comment]
Hi Ryan,

I could not reproduce it in a new repo. 

There is probably an edge case somewhere but if I isolate what creates the issue I will let you know.


By the way, why base_path is not taken into account when using the dev-server with hot reloading ?

With dev-server launched by the following command

`./node_modules/.bin/encore dev-server --host 192.168.145.129 --disable-host-check --config webpack.config.js --hot --progress --port 8081`

---
Case 1 : works
---------------

```
.setOutputPath('public/subfolder1/subfolder2/build/')
.setPublicPath('/subfolder1/subfolder2/build')
```
AND

`asset('subfolder1/subfolder2/build/main.js') `

=> The generated link is http://192.168.145.129:**8081**/subfolder1/subfolder2/build/main.js (dev-server)


---
Case 2 : doesn't work
---------------

```
.setOutputPath('public/subfolder1/subfolder2/build/')
.setPublicPath('/subfolder1/subfolder2/build')
```
AND

```
assets:
        base_path: /subfolder1/subfolder2
        json_manifest_path: "%kernel.project_dir%/public/subfolder1/subfolder2/build/manifest.json"
```
AND

`asset('build/main.js') `

=> The generated link is http://192.168.145.129:8080/subfolder1/subfolder2/build/main.js (php app itself)
and should be http://192.168.145.129:8081/subfolder1/subfolder2/build/main.js (dev-server)

**Comment by weaverryan** [comment]
> By the way, why base_path is not taken into account when using the dev-server with hot reloading ?

Ah, that's a very fair question. When you say `asset('build/main.js')` AND have `json_manifest_path` set, then Symfony looks in the `manifest.json` file for a *key* that exactly matches `build/main.js`. If it finds it, it uses that value as the final path. So yes, the `base_path` is not taken into account in this lookup. It's just not the way that system was designed.

But, if you DO want to just be able to say `asset('build/main.js')` and have it work, even though you have `.setPublicPath('/subfolder1/subfolder2/build')`, you can control the manifest key via:

```js
// ...
.setManifestKeyPrefix('/build')
```

With this, they kets in `manifest.json` should look more like `build/main.js`, and thus the simpler `asset('build/main.js')` will work.

Cheers!

**Comment by Isengo1989** [comment]
Trying to get this to work to. 

`    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/asset": "^4.0",
        "symfony/console": "^4.0",
        "symfony/expression-language": "^4.0",
        "symfony/flex": "^1.1",
        "symfony/form": "^4.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "^1.0",
        "symfony/process": "^4.0",
        "symfony/security-bundle": "^4.0",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.2",
        "symfony/translation": "^4.0",
        "symfony/twig-bundle": "^4.0",
        "symfony/validator": "^4.0",
        "symfony/web-link": "^4.0",
        "symfony/webpack-encore-bundle": "^1.0",
        "symfony/yaml": "^4.0",
        "white-october/pagerfanta-bundle": "^1.2"
    },
    "require-dev": {
        "symfony/debug-pack": "*",
        "symfony/dotenv": "^4.0",
        "symfony/maker-bundle": "^1.9",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*",
        "symfony/web-server-bundle": "^4.0"
    },`

with the command  **yarn encore dev-server --port 9000 --hot** but I am always getting **Cannot GET /** when I am calling **http://localhost:9000/**

I can access http://localhost:9000/build/app.js just fine. I read somewhere that this is caused because I am not using the right entry html/php file. Anyone a tip?

**Comment by ajv-developer** [comment]
I got "Cannot GET /" until I let Symfony open the webpage with the command
 **symfony open:local**
It opened on https://127.0.0.1:8000
