### ISSUE TITLE
Desktop Notification should also fire on incremental success

### ISSUE THREAD

**Issue by Defcon0** [symfony/webpack-encore#304]
Hello,

using `Encore.enableBuildNotifications()` we can have notifications after initial build and after an error occurred. But in fact we don't get any notification if a subsequential (incremental) build has been finished. But this would be very nice since than I wouldn't have to hit "Refresh" multiple times becuase then I would know, when the build process has finished.

Is that already possible? Am I doing something wrong or is it a feature request?

I'm using ubuntu 16.04.

Bye Defcon0

**Comment by Lyrkan** [comment]
Hi @Defcon0,

I think you have to enable the ["alwaysNotify"](https://github.com/Turbo87/webpack-notifier#always-notify) mode of `webpack-notifier`:

```js
Encore.enableBuildNotifications(true, (options) => {
    options.alwaysNotify = true;
});
```

**Comment by Defcon0** [comment]
@Lyrkan Works like a charm, thanks!
