### ISSUE TITLE
How to load versioned images from a React component

### ISSUE THREAD

**Issue by Aerendir** [symfony/webpack-encore#309]
I'm putting my images under version controle as described here: https://github.com/symfony/symfony-docs/issues/9565

Basically I do this:

```javascript
// This copies all images to the public/build folder (it is required by Encore)
const imagesCoreContext = require.context('./images', true, /\.(png|jpg|jpeg|gif|ico|svg|webp)$/);
imagesCoreContext.keys().forEach(imagesCoreContext);
```

This makes `Encore` able to move images to the `public` folder and apply versioning hashes to their names.

Now I'd like to use one of these images directly in one of my React components:

```javascript
import React from 'react';
import { UncontrolledDropdown, DropdownToggle, DropdownItem, DropdownMenu, Nav } from 'reactstrap';

const Account = () => (
  <Nav navbar>
    <UncontrolledDropdown nav inNavbar>
      <DropdownToggle nav caret>
        <img src="build/assets/images/Core/logos/Logo-black-small.png" />
      </DropdownToggle>
      <DropdownMenu>
        <DropdownItem>
          Option 1
        </DropdownItem>
        <DropdownItem>
          Option 2
        </DropdownItem>
        <DropdownItem divider />
        <DropdownItem>
          Reset
        </DropdownItem>
      </DropdownMenu>
    </UncontrolledDropdown>
  </Nav>
);

export default Account;

```

But the images is not shown as it is versioned. The real current name is in the `manifest.json` and has the hash.

So, how can I make React aware of the `manifest.json` file? Is something I have to do in Webpack's config handled through `Encore`? Or should have I to do other things?

**Comment by stof** [comment]
Webpack itself handles it:

```js
const logoPath = require('images/Core/logos/Logo-black-small.png')
```

Requiring an image gives you the path to it in the build folder.

btw, if you reference all your images from the JS, you don't need the `require.context` trick (as webpack already knows about them being required)

**Comment by Aerendir** [comment]
@stof , so stupid question! 😓

Yes, I know that requiring them makes Webpack able to handle them, but there are a lot of other images, so I don't like the idea.

But only for the logo is good...

Now I have to see what happens when the same image is both required and moved through `require.context`...

**Comment by Aerendir** [comment]
Ok: the image is moved only once and is correctly loaded! Thank you @stof !
