### ISSUE TITLE
Expose Encore.isProduction as global variable

### ISSUE THREAD

**Issue by benito103e** [symfony/webpack-encore#317]
How can I access Encore.isProduction outside of webpack config ?

I would want to enable some debugs if running in dev environment.

**Comment by stof** [comment]
you cannot.

what you can do however is using webpack to pre-define some variables in your code based on `Encore.isProduction`. This is what React is doing for instance. Their source code has lots of `if (__DEV__)`, where `__DEV__` is replaced during the build process.

Encore even preconfigures such a variable based on a common convention in the frontend world: it will define `process.env.NODE_ENV` based on the `Encore.isProduction` status. So this will work without any extra config:

```js
if (process.env.NODE_ENV !== 'production') {
    // Dev-only stuff goes here
}
```

Note that this has no runtime impact. Webpack will replace `process.env.NODE_ENV` with `"production"` or `"development"` when processing the build. And then, UglifyJS will even be able to resolve the condition at build-time for production builds when performing dead-code elimination.

If you prefer using `__DEV__`, here is the way to go:

```js
Encore.configureDefinePlugin((options) => {
    options.__DEV__ = JSON.stringify(Encore.isProduction());
})
```

**Comment by benito103e** [comment]
Thanks @stof for your precious answer.

Is the first solution reliable in time ?
I had found the definePlugin that seems to be a great solution for a lot of purposes.

**Comment by stof** [comment]
`process.env.NODE_ENV` ? Yes, it is meant to be reliable in time.

And btw, it is also based on the DefinePlugin. Try dumping `options` inside the callback and you will see that `NODE_ENV` is defined on it here. It is part of the default config (the only default config currently)

**Comment by benito103e** [comment]
Thanks, I close this issue.
