### ISSUE TITLE
dev-server over https is broken

### ISSUE THREAD

**Issue by Gamesh** [symfony/webpack-encore#319]
Just upgraded to v0.20.1 and when running `yarn encore dev-server --hot --https --host=host.dev --disable-host-check`
it seems to generate http links in the manifest
if i revert to v0.19 everything works fine again

**Comment by weaverryan** [comment]
Hi there!

When you upgraded, did you upgrade any other libraries or only encore?

**Comment by Gamesh** [comment]
i also upgraded other libraries using yarn upgrade, so encore dependencies also where upgraded

**Comment by pinoniq** [comment]
Possibly related to the .dev domain used. It's a domain owned by google that has certificate pinging. So all non-google certificates won't work. Try another domain

**Comment by Gamesh** [comment]
@pinoniq no it's not. also it does not have pining to google certificates it just has HSTS which requires it to have a valid SSL certificate. And i have those, i generated them and supplied to encore the key and the cert also imported them to my key store of the OS so it treats it as a valid SSL and works with 0.19 version of encore without any issues. 

also if you notice i said that it generates HTTP links in the manifest not HTTPS as it's supposed to

**Comment by Gamesh** [comment]
seams no longer reproducible in v0.23.0
