### ISSUE TITLE
BrowserslistError: Unknown browser 

### ISSUE THREAD

**Issue by vetalstar** [symfony/webpack-encore#322]
Hi there. I want to use autoprefixer with bootstrap 4.
But I get a strange error.
**package.json**
```
{
    "devDependencies": {
        "@symfony/webpack-encore": "^0.19.0",
        "autoprefixer": "^8.5.0",
        "bootstrap": "^4.1.1",
        "node-sass": "^4.9.0",
        "postcss-loader": "^2.1.5",
        "sass-loader": "^7.0.1"
    },
    "browserslist": [
        "last 1 major version",
        ">= 1%",
        "Chrome >= 45",
        "Firefox >= 38",
        "Edge >= 12",
        "Explorer >= 10",
        "iOS >= 9",
        "Safari >= 9",
        "Android >= 4.4",
        "Opera >= 30"
    ],
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production"
    }
}
```

**webpack.config.js**
```
var Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .addStyleEntry('css/app', './assets/scss/app.scss')
    .enableSassLoader()
    .enablePostCssLoader()
;

module.exports = Encore.getWebpackConfig();
```

**postcss.config.js**
```
module.exports = {
    plugins: {
        autoprefixer: {}
    }
};
```
`.\node_modules\.bin\encore dev`
Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser major
    at error (C:\OSPanel\domains\domain.ru\node_modules\caniuse-api\node_modules\browserslist\index.js:37:11)
    at Function.browserslist.checkName (C:\OSPanel\domains\domain.ru\node_modules\caniuse-api\node_modules\browserslist\index.js:320:18)
    at Function.select (C:\OSPanel\domains\domain.ru\node_modules\caniuse-api\node_modules\browserslist\index.js:438:37)
    at C:\OSPanel\domains\domain.ru\node_modules\caniuse-api\node_modules\browserslist\index.js:207:41

`npm ls autoprefixer`

```
+-- @symfony/webpack-encore@0.19.0
|  -- css-loader@0.26.4
|    -- cssnano@3.10.0
|      -- autoprefixer@6.7.7
 -- autoprefixer@8.5.0
```

`npm ls browserslist`

```
+-- @symfony/webpack-encore@0.19.0
| +-- babel-preset-env@1.6.1
| |  -- browserslist@2.11.3
|  -- css-loader@0.26.4
|    -- cssnano@3.10.0
|     +-- autoprefixer@6.7.7
|     |  -- browserslist@1.7.7
|      -- postcss-merge-rules@2.1.2
|       +-- browserslist@1.7.7
|        -- caniuse-api@1.6.1
|          -- browserslist@1.7.7
 -- autoprefixer@8.5.0
   -- browserslist@3.2.7

```

When I put browsers list to .browserslistrc that's alright.

May be need to update cssnano ?

**Comment by Lyrkan** [comment]
I think it doesn't work in both cases because it uses the version of `autoprefixer` required by `cssnano` (which uses `browserslist` v1.7.7), not the one you added manually to your project:

* if you put `last 1 major version`  into your  `package.json` file it fails because the `last n major versions` was only introduced in [browserslist 2.4](https://github.com/browserslist/browserslist/blob/master/CHANGELOG.md#24)
* if you put it in `.browserslistrc` that file is simply ignored because its support was only added in [browserslist 2.0](https://github.com/browserslist/browserslist/blob/master/CHANGELOG.md#20)

**Comment by vetalstar** [comment]
@weaverryan I removed `"last 1 major version",` from **package.json** and tried `.\node_modules\.bin\encore dev`

Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query `>= 1%`

**Comment by vetalstar** [comment]
@Lyrkan and I think about it too. I know that autoprefixer has been removed from cssnano in version 4.0.0

**Comment by iNfame** [comment]
@vetalstar try to `npm i css-loader@latest -D` (0.28.11 atm) - it solved the problem for me, getting no errors any more

**Comment by Lyrkan** [comment]
I'm a bit confused about why it works with css-loader 0.28.11...

From an empty directory:

```
$ yarn add css-loader@latest
yarn add v1.6.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 111 new dependencies.
(...)

$ yarn why browserslist
yarn why v1.6.0
warning package.json: No license field
[1/4] Why do we have the module "browserslist"...?
[2/4] Initialising dependency graph...
warning No license field
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "browserslist@1.7.7"
info Reasons this module exists
   - "css-loader#cssnano#postcss-merge-rules" depends on it
   - Hoisted from "css-loader#cssnano#postcss-merge-rules#browserslist"
   - Hoisted from "css-loader#cssnano#autoprefixer#browserslist"
   - Hoisted from "css-loader#cssnano#postcss-merge-rules#caniuse-api#browserslist"

```

From another empty directory:

```
$ yarn add @symfony/webpack-encore
yarn add v1.6.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 534 new dependencies.
(...)

$ yarn why browserslist                     
yarn why v1.6.0
warning package.json: No license field
[1/4] Why do we have the module "browserslist"...?
[2/4] Initialising dependency graph...
warning No license field
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "browserslist@1.7.7"
info Has been hoisted to "browserslist"
info Reasons this module exists
   - Hoisted from "@symfony#webpack-encore#css-loader#cssnano#postcss-merge-rules#browserslist"
   - Hoisted from "@symfony#webpack-encore#css-loader#cssnano#autoprefixer#browserslist"
   - Hoisted from "@symfony#webpack-encore#css-loader#cssnano#postcss-merge-rules#caniuse-api#browserslist"
info Disk size without dependencies: "48KB"
info Disk size with unique dependencies: "9.9MB"
info Disk size with transitive dependencies: "9.9MB"
info Number of shared dependencies: 2
=> Found "babel-preset-env#browserslist@3.2.7"
info This module exists because "@symfony#webpack-encore#babel-preset-env" depends on it.
info Disk size without dependencies: "76KB"
info Disk size with unique dependencies: "3.12MB"
info Disk size with transitive dependencies: "3.12MB"
info Number of shared dependencies: 2
```

As you can see both of them install the same version of browserslist for css-loader... so updating it in shouldn't change anything...

**Comment by iNfame** [comment]
@Lyrkan I know where the problem is. `css-loader` uses `cssnano`. `cssnano ^3` uses the `autoprefixer ^6` (and we need `^7` or `^8` because of our browserslist-expressions).
Look at this (https://github.com/webpack-contrib/css-loader/commit/c8db489c1e9e954d1005d8ccb924c73bfaf22cf2) commit. They've moved the `cssnano` from common block to "minimize"-case. So after `v2.8.0` we won't face with these errors because we don't need a minimize-functionality in this case.

If we (I mean app) don't require cssnano, it doesn't require old autoprefixer with old browserslist, so these two packages are being used from the node_modules root.

**Comment by Lyrkan** [comment]
@iNfame I see, but we do use the `minimize` option in production mode, so the issue would probably still be there in that case (unless you disable CSS minification explicitely... which is probably not a good idea):

https://github.com/symfony/webpack-encore/blob/92548f18d9468ae42a313702aa9b81ee70f0418f/lib/loaders/css.js#L26-L35

**Comment by iNfame** [comment]
@Lyrkan oh i didn't notice that `minimize` is still being used, sorry :/

So I think the best solution atm is to:
1. Use **.browserslistrc**-based config instead of **package.json**-based (it works with the `autoprefixer` and `browserslist` you install manually, not `cssnano`'s).
2. Wait for the `cssnano ^4` release and update this package as soon as it goes stable enough.
