### ISSUE TITLE
compatibility with vue-loader@^15.0

### ISSUE THREAD

**Issue by Rebolon** [symfony/webpack-encore#326]
The latest version of vue-loader working with 'encore' is the 14.2.2
When i try to upgrade to v15
then i got a lot of errors: vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config.

The message is clear :-) but i wonder if you plan to migrate to this version of vue-loader

Thanks

**Comment by stof** [comment]
Compatibility with vue-loader 15 is part of #324 when migrating to Webpack 4.

**Comment by Lyrkan** [comment]
Hi @Rebolon,

We also talked about it a bit in #311

Simply adding the `VueLoaderPlugin` to the generated conf caused some other issues because of the ExtractTextPlugin (which is not going to be there anymore after the Webpack 4 migration).

**Comment by Rebolon** [comment]
sorry i missed those issues when searching for vue-loader.
Thanks
