### ISSUE TITLE
Access to require(js) outside loaded files (from template) 

### ISSUE THREAD

**Issue by grekpg** [symfony/webpack-encore#327]
I have this code: 

```
<!DOCTYPE html>          
     <head>
     <script src="../dist/app.js"></script>   <-- webpack build here

        // how can I do a synchronous require() here, from something
        // inside the Webpack build?

     </script>
    </head>
    <body>
    </body>
    </html>
```

i also described question here https://stackoverflow.com/questions/50470591/symfony-webpack-encore-require

**Comment by stof** [comment]
As far as I know, you cannot. I don't think Webpack exposes its require implementation to the outside (and depending on the optimization being applied, it may not be able to do it at all, as it could inline some packages in the same scope)

**Comment by weaverryan** [comment]
Yep, Stof is correct.

From your StackOverflow:

> For ajax loaded content with javascript is necessarily to run js from template , or what is best practicle ? Example i load form in ajax with select2 now i have js in template it use requirejs then init select2

Basically, don't put your JavaScript into your template anymore - just put it in a real JavaScript file. The *only* complication of doing this is that, when your JavaScript is in your template, you can use Twig to put dynamic values into your JavaScript - e.g.

```twig
var ajaxUrl = '{{ path('my_route') }}';
var articleId = {{ article.id }};
```

We talk about alternative ways of passing data from Twig to your JavaScript in this article: https://symfony.com/doc/current/frontend/encore/server-data.html

Cheers!
