### ISSUE TITLE
babel-preset-env useBuildIns is true by default

### ISSUE THREAD

**Issue by Nemo64** [symfony/webpack-encore#328]
I noticed that babel-preset-env is set to true by default.
However, I haven't found a notice that says that you should use `import "babel-polyfill`.
https://babeljs.io/docs/plugins/preset-env/#usebuiltins

Isn't that kind of the point of that option?

**Comment by weaverryan** [comment]
Yep! I believe you're correct about that! Let's chat about it in #444
