### ISSUE TITLE
TypeError: Cannot set property 'tsLoaderFileVersion' of undefined

### ISSUE THREAD

**Issue by QuentinCaffeino** [symfony/webpack-encore#340]
Compilation with TS enabled fails with this error:

```
 ERROR  Failed to compile with 1 errors

 error  in ./somefile.ts

Module build failed: TypeError: Cannot set property 'tsLoaderFileVersion' of undefined
    at successLoader (/var/www/html/node_modules/ts-loader/dist/index.js:49:54)
    at Object.loader (/var/www/html/node_modules/ts-loader/dist/index.js:21:12)

```

Found only one [similar issue on github](https://github.com/TypeStrong/ts-loader/issues/748) and it says that latest ts-loader doesn't support webpack <4.
So how about an upgrade then?

**Comment by QuentinCaffeino** [comment]
Ok, I found that you have an open PR.

**Comment by Lyrkan** [comment]
Hello @QuentinCaffeino,

There already is a PR related to the Webpack 4 update (#324), but since this version deprecates/introduces a lot of things it takes a bit of time to do it right.

In the meantime you should be able to use an old version of the ts-loader without any issue.

**Comment by QuentinCaffeino** [comment]
Thanks
