### ISSUE TITLE
how to check if is in dev-server environment in runtime？

### ISSUE THREAD

**Issue by lichnow** [symfony/webpack-encore#347]
I can not determine if encore is in dev-server
```
const manifestConfigure = options => ({
    writeToFileEmit: true,
    filter: ({ isInitial, isModuleAsset }) => {
        return isInitial && !isModuleAsset
    },
    generate: (seed, files) => files.reduce(
        (manifest, { name, path }) => {
            let ext = path.split('.').pop()
            let key = ext ? `/${ext}/${name}` : `/${name}`
            return {
                ...manifest,
                [key]: Encore.isDevServer() ? path : path.replace(`${sourcePath}/`, '')
            }
        },
        seed
    )
})
```

**Comment by weaverryan** [comment]
Hey @lichnow!

Can you explain a bit more about what you're trying to do? You may be trying to hack around some functionality in Encore - i.e., there may be an easier way to accomplish what you want :). You typically should not need to change how the `manifest.json` file is generated.

I don't believe there is currently a way to do this. If there is a legit use-case, we can of course add something.

Cheers!

**Comment by Lyrkan** [comment]
Closing this since an `Encore.isDevServer()` method was added in #483.
