### ISSUE TITLE
Watch config

### ISSUE THREAD

**Issue by julienj** [symfony/webpack-encore#35]
Hello,
watch option doesn't work with docker machine and nfs.
cf : http://andrewhfarmer.com/webpack-watch-in-vagrant-docker/

How can I add this config 
 
`
watchOptions: {
  poll: true
}
`
Thank

**Comment by stof** [comment]
As Encore is a builder for the webpack config, you can easily alter the final config before exporting it:

```js
// webpack.config.js

var Encore = require('@symfony/webpack-encore');

// all Encore config here

var config = Encore.getWebpackConfig();

config.watchOptions = { poll: true };

module.exports = config;
```

**Comment by weaverryan** [comment]
We should doc this as the official approach of adding "extra" config. I don't think there's any benefit of adding another method on Encore to set things like this. I've opened and issue: symfony/symfony-docs#8067

Thanks!

**Comment by julienj** [comment]
Thank you
Is a good news
