### ISSUE TITLE
please offer a api to specify RuntimeChunk file name

### ISSUE THREAD

**Issue by lichnow** [symfony/webpack-encore#354]
to specify runtime chunck filename can be `configureRuntimeChunk(filename)`?

**Comment by Lyrkan** [comment]
Hi @lichnow,

Is there a specific reason why you'd need to change it?

You could probably modify the `optimization.runtimeChunk` setting before exporting the Webpack config object, but I'd recommend keeping the default name set by Webpack:

```js
// webpack.config.js
Encore
    .enableSingleRuntimeChunk()
   // ...
;

const config = Encore.getWebpackConfig();

config.optimization.runtimeChunk = {
    name: 'yourname'
};

module.exports = config;
```

**Comment by lichnow** [comment]
Yes,its right,thx
