### ISSUE TITLE
in prod environment entrypoints.json is not mapped right

### ISSUE THREAD

**Issue by lichnow** [symfony/webpack-encore#355]
after build in production envrivonment,the entrypoint.json which generated is mapped wrong.it has not `hash` of file.
```
{
  "app": {
    "js": [
      "modules/dashboard/runtime.js",
      "modules/dashboard/vendor.js",
      "modules/dashboard/app.js"
    ],
    "css": [
      "modules/dashboard/vendor.css",
      "modules/dashboard/app.css"
    ]
  }
}
```

but file name
`vendor.32e7d84c28656585c94c.js`
`runtime.d41d8cd98f00b204e980.js`
`app.a8afa9f84e5d178a8ef4.js`

my configure
```
.splitEntryChunks()
    .configureSplitChunks(function (splitChunks) {
        return {
            cacheGroups: {
                vendors: {
                    test: /[\\/]node_modules[\\/]/,
                    name: 'vendor',
                    chunks: 'all'
                },
                common: {
                    name: 'chunk',
                    minChunks: 2,
                    priority: -20,
                    chunks: 'initial',
                    reuseExistingChunk: true
                }
            }
        }
    })
```

**Comment by stof** [comment]
that's expected. entrypoints.json maps the entry point name to entrypoint assets. You should still use the manifest.json to find the versionned path for each of them (the idea being that you can read the entrypoints.json file and pass that info to the existing code dealing with versionned paths)

**Comment by lichnow** [comment]
yes,that right.so,with `entrypoints.json`,so i can read its content,and decode the json by php to a array.the foreach the array,and then read the `manifest.json` file's assets path by the key.

but another problem,`mainifest.json`'s asset key is not equal `entrypoints.json`,in webpack.config.js
the manifest configure is like this
```
.configureManifestPlugin(options => ({
        writeToFileEmit: true,
        filter: ({ isInitial, isModuleAsset }) => {
            return isInitial && !isModuleAsset
        },
        generate: (seed, files) => files.reduce(
            (manifest, { name, path }) => {
                let ext = path.split('.').pop()
                let key = ext ? `/${ext}/${name}` : `/${name}`
                return {
                    ...manifest,
                    [key]: path
                }
            },
            seed
        )
    }))
```
so i read `modules/dashboard/manifest.json` content
```
{
  "/css/app.css": "/modules/dashboard/css/app.5eb69e82b4666affd607.css",
  "/js/app.js": "/modules/dashboard/js/app.a8afa9f84e5d178a8ef4.js",
  "/css/vendor.css": "/modules/dashboard/css/vendor.e346bd5828db67fe6ce3.css",
  "/js/vendor.js": "/modules/dashboard/js/vendor.32e7d84c28656585c94c.js",
  "/js/runtime.js": "/modules/dashboard/js/runtime.d41d8cd98f00b204e980.js"
}
```

but `entrypoints.json` content is like this
```
{
  "app": {
    "js": [
      "modules/dashboard/runtime.js",
      "modules/dashboard/vendor.js",
      "modules/dashboard/app.js"
    ],
    "css": [
      "modules/dashboard/vendor.css",
      "modules/dashboard/app.css"
    ]
  }
}
```

because I can not set named by a callback for the `entrypoints`,so if I want to use `entrypoints` have to not set the `manifest key`?

If not any api to set value of `entrypoints.json` 's item,what else have any api to disabled to generate the `entrypoints.json`,

**Comment by weaverryan** [comment]
Hey @lichnow! Thanks for trying the master branch :).

Question: why are you configuring the `generate` option of the manifest plugin? Because you are doing this, I think that *you* are actually causing the values of `entrypoints.json` to not match the keys to `manifest.json`. That's not something I expected peopled to do - everything is setup to make those match, unless you mess with it :). So, what is causing you to need/want to do this?

**Comment by lichnow** [comment]
@weaverryan because I migrate a project developed by `laravel` to a new `laravel-modules` project.the old version compile assets use `vue-cli3.x`and,now i want to changed to be `encore`.because `encore`'s api is simple and so clear.but has many problem with it.
this problem which `in prod environment entrypoints.json is not mapped right` has been solved,i remove the configure of `manifest plugin`,and it work fine. thx and great for your work!

**Comment by weaverryan** [comment]
Cheers!

**Comment by deAtog** [comment]
I just experienced this issue, but only in a restricted case. If I call Encore.setManifestKeyPrefix with an empty string, my manifest.json file lacks the build/ prefix in the asset name. E.g. the entry to the public path of /build/index.js is given an asset name of index.js. However, the name provided the entrypoints.json file is /index.js. If I use anything but an empty string then then everything appears to function correctly. Nonetheless, I would prefer to refer to my assets without a prefix in the name,
