### ISSUE TITLE
enableEslintLoader not present

### ISSUE THREAD

**Issue by codejet** [symfony/webpack-encore#358]
I have strange issue with `enableEslintLoader` not being present in webpack-encore/index.js. I can see it here in your repo, and I have the latest version installed using yarn. But the method is not in the index.js inside my node_modules. And no eslint.js inside lib/loaders either.

I even ran `yarn upgrade @symfony/webpack-encore` despite my package.json already showing the latest version. But no luck.

I hope I'm not missing something obvious...

**Comment by Lyrkan** [comment]
Hey @codejet,

The `enableEslintLoader` method was added after the last release (`0.20.1`), you can see it is also missing in the `index.js` file there: https://github.com/symfony/webpack-encore/blob/v0.20.1/index.js

It should be part of the next version :)

**Comment by codejet** [comment]
OK, my bad then I guess :p 

Thanks a lot for the fast reply!
