### ISSUE TITLE
Make sure correct React preset version is being required

### ISSUE THREAD

**Issue by weaverryan** [symfony/webpack-encore#359]
See: https://github.com/symfony/webpack-encore/pull/324#issuecomment-406262179

In the new Webpack 4 integration, if you are using any library that doesn't match the version requirements of our `devDependencies`, you should get a warning. This may not have been happening in the above report.

/cc @arendjantetteroo :)

**Comment by arendjantetteroo** [comment]
I updated to 0.21 last week and all went without a hitch. Thanks!

So i think you can close this one @weaverryan .

**Comment by weaverryan** [comment]
Woohoo! Thanks for the feedback!
