### ISSUE TITLE
Possible problem with Webpack 4 shared entry creation: syntax error

### ISSUE THREAD

**Issue by weaverryan** [symfony/webpack-encore#360]
See: https://github.com/symfony/webpack-encore/pull/324#issuecomment-406281213

The "tmp" file looks like it is from the hack we do in Webpack4 to support shared entries.

**Comment by Lyrkan** [comment]
Hey @weaverryan,

It's probably the same issue than #352

**Comment by weaverryan** [comment]
You're right! Thanks :)
