### ISSUE TITLE
Multiple apps/package.json files

### ISSUE THREAD

**Issue by mikeyudin** [symfony/webpack-encore#365]
I have an app with a frontend (public) and an admin area (private).  

- The frontend client is built on bootstrap/jquery/etc, no SPA frameworks.
- The backend client is built using Vue.

Both clients have package.json files that are vastly different (devDeps and deps both different).  I am aware that Encore can have multiple configs in the same file, but that seems to require a single package.json file.

Does anyone have ideas on best practices for handling a situation where the dependencies are different across 2 clients?  It seems like bad practice to have 2 apps with different dependencies share the same package.json.

**Comment by Lyrkan** [comment]
Hi @mikeyudin,

I think the easiest way to deal with that kind of structure is probably to consider these clients as two distinct projects/applications (after all you have two `package.json` files) and build them separately.

**Comment by mikeyudin** [comment]
Yeah that's the approach I took.  Thanks!
