### ISSUE TITLE
Bootstrap dropdown and popper

### ISSUE THREAD

**Issue by raffo000** [symfony/webpack-encore#368]
Hello guys,
first of all i want to thank you all for webpack-encor, it's fantastic.
But i have a really big problem with Bootstap 4 and dropdown, as far i know Bootstrap 4^ need popper.js for the dropdown actions, so i in my app.js (used as base for every page) i did something like this:

```
require('../css/app.css');

window.$ = require('jquery');
window.Popper = require('popper.js');

require('bootstrap');

$(document).ready(function() {
    $('[data-toggle="tooltip"]').tooltip();
    $('[data-toggle="popover"]').popover();
});
```
finally i addded the line
```.autoProvidejQuery()```
webpack.config.js and installed all the needed dependencies with yarn (bootstrap, popper and soo on).

I fisnished up building a simple page with Bootstrap and everything is fine, but if I try to use the dropdown component it doesn't work, i have no errors inside the console.

Dropdown sample if needed:

```
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropdown button
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
    </div>
</div>
```

I don't know what can I do more. If anyone had the same issue I'd be glad to hear for a solution.

Thank you for your time.

**Comment by royklutman** [comment]
First, you don't actually have to require jQuery and Popper.js manually, Bootstrap requires them for you. I tested the following and the dropdown works just fine for me:
```javascript
// app.js
require('../css/app.css');
require('bootstrap');
```
```html
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropdown button
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
    </div>
</div>
```
Are you sure you re-ran Encore after you added `.autoProvidejQuery()` to `webpack.config.js`?

**Comment by Johann-S** [comment]
We added a file which embed Popper.js in Bootstrap so if you don't want to add Popper.js you can do : 
```js
require('bootstrap/dist/js/bootstrap.bundle');

**Comment by raffo000** [comment]
So i used the bundled version of bootstrap, the real problem was that I am using both yarn and npm, when i launch yarn install it download bootstrap with latest version, right after i runned npm install and it download the 3.3 version (for some strange reason).
Thanks a lot and keep the hard work,

Best regards.

**Comment by andrejusnec** [comment]
> We added a file which embed Popper.js in Bootstrap so if you don't want to add Popper.js you can do :
> 
> ```js
> require('bootstrap/dist/js/bootstrap.bundle');
> ```

Thank you, it worked for me!
