### ISSUE TITLE
When will webpack-encore with webpack 4 be published in npm?

### ISSUE THREAD

**Issue by Genarito** [symfony/webpack-encore#369]
Hi, I would like to know if there is an estimated publication date of this tool in the npm registry.

Thanks in advance!  Encore is the best!

**Comment by royklutman** [comment]
I don't know a date myself, but there is a PR that shows some to-do's: #324 and a milestone for Webpack 4 integration: https://github.com/symfony/webpack-encore/milestone/1

**Comment by Genarito** [comment]
I'm following that PR since a month ago, I saw that it had been merged into master and I wrongly thought that it has to be published.

Thank you!

**Comment by weaverryan** [comment]
Sorry for the delay guys - should be in the next few weeks - there are just a few minor todos plus documentation - we can’t releaese it until that’s ready :).

**Comment by dzounas** [comment]
Hey, is there any release date when we can expect new version with webpack4 included? I know u can't release it until everything is set and ready but it takes kinda long since w4 was released and all checkmarks in pull request except documentation was done, so?

**Comment by vazgen** [comment]
I have some issues with tree shaking RxJS with webpack 3. Webpack 4 seems solves the issue

**Comment by BernardA** [comment]
I just want to give my 2 cents on this. I have already worked some with webpack on its own, to be fair. 
As I was having a number of the issues mentioned above with encore. So I decided to just drop encore and use webpack directly. There were some hiccups, but it mostly went fairly smoothly and I never looked back.
So, I just question why one should have encore at all. Some of the reasoning that I see on the encore webpage may no longer be relevant. Yes, webpack is still complex but it improved quite a lot.  Why then spend the time to learn an abstraction ( encore ) which is not without its issues. Including having to wait quite a long time to get an update to major webpack versions. 
I understand the time constraints of the contributors. May be that will better spend this time somewhere else.

**Comment by vazgen** [comment]
Yeah, i was thninking about the same!

**Comment by dzounas** [comment]
We’ve already moved to webpack directly. Took some time but at the end the build is like 50% faster with webpack 4 than with encore. And with that slow releases it’s not relevant to keep using encore. And also if you find any bug on webpack u have bigger chance to find workaround than with encore.
