### ISSUE TITLE
Upgrade to 0.21.0

### ISSUE THREAD

**Issue by ultonic** [symfony/webpack-encore#370]
When you will add the 0.21.0 tag? I can't to upgrade package version neither via yarn or via npm. Can I use it at all?

**Comment by weaverryan** [comment]
Hey there! 

Sorry for the delay - probably a few more weeks, the tag is not ready, but it’s on my list :).

Cheers!

**Comment by royklutman** [comment]
You can however try it out with the `master` branch:
```bash
yarn update @symfony/webpack-encore@https://github.com/symfony/webpack-encore.git#master
```
Or add/edit the following line in `package.json`:
```json
"@symfony/webpack-encore": "git://github.com/symfony/webpack-encore.git#master"
```
If you do so, don't forget to check out the line about adding `Encore.enableSingleRuntimeChunk()` in the changelog: https://github.com/symfony/webpack-encore/blob/master/CHANGELOG.md

**Comment by mmarton** [comment]
Is there an estimated release date for 0.21?

**Comment by tristanbes** [comment]
Hello, any news ? this components is lagging in terms of release, we're waiting support for Webpack4 :)

**Comment by alexsegura** [comment]
Looks like it's coming 

bb11e7447998c42f55fc12d7e319271f697890b9

**Comment by Lyrkan** [comment]
And it's now [available](https://github.com/symfony/webpack-encore/releases/tag/v0.21.0)!
