### ISSUE TITLE
configureUglifyJsPlugin does'nt work as expected

### ISSUE THREAD

**Issue by HooK81** [symfony/webpack-encore#377]
Hi all,
I try to configure UglifyJsPlugin to remove console statements. 

I tried : As explained in https://github.com/symfony/webpack-encore/blob/c247131aa8ec4a4c1582fd3e862539461113402a/index.js 

```
# webpack.config.js
Encore.configureUglifyJsPlugin((options) => {
    options = {
        compress: {
            drop_console: true
        }
    };
});
```
The callback is well executed, but the console are still there.

I also tried to return the options object with no success:
```
Encore.configureUglifyJsPlugin((options) => {
    options = {
        compress: {
            drop_console: true
        }
    };
    return options;
});
```
In the generated webpack config plugins the compress if removed : 
```
     UglifyJsPlugin { options: { sourceMap: false } },
```

The only way to make it works it's the following but I'm not sure it's the good way because it add an another UglifyJsPlugin plugin instead of updating the default one: 
```
config.plugins.push(new webpack.optimize.UglifyJsPlugin({
    compress: {
        drop_console: true
    }
}));
```

What I'm doing wrong ?

**Comment by stof** [comment]
As of 0.20, returning an object should work too. Which version are you using ?

**Comment by HooK81** [comment]
I'm using Encore 0.20.1

The solution given by @yh1224  works well
