### ISSUE TITLE
How to use babel plugins?

### ISSUE THREAD

**Issue by MatthD** [symfony/webpack-encore#384]
I am not sure this is an issue but I did not found explanation about that,

I am trying to use class properties in my app, so I tried different things but it appears Webpack-encore is design for babel6 but plugins are design for babel 7 isn't it ?

How should I use in my configureBabel (Webpack.config.js) to be able to load the plugin?

**Comment by MatthD** [comment]
Ok I answer myself for other:

The right way with Webpack-encore to use class properties is:

`npm install --save-dev babel-plugin-transform-class-properties`

Then : 

```javascript
.configureBabel(function(babelConfig) {
        babelConfig.plugins.push('transform-class-properties'); 
    })
```

**Comment by arendjantetteroo** [comment]
@MatthD Would https://symfony.com/doc/current/frontend/encore/babel.html help enough to figure this out or you think this should get an extra mention of the above?
