### ISSUE TITLE
Installation guide does not work: could not find package symfony/webpack-encore

### ISSUE THREAD

**Issue by hshhhhh** [symfony/webpack-encore#387]
Based on issue https://github.com/symfony/webpack-encore/issues/376 26 days ago it worked, but not now:

```
% composer require webpack-encore 

  [InvalidArgumentException]               
  Could not find package webpack-encore.   

  Did you mean one of these?               
      symfony/webpack-encore-pack          
      rebolon/symfony-skeleton             
      knpuniversity/webpack-encore-bundle  
```

**Comment by Lyrkan** [comment]
Hi @hshhhhh,

You are probably following an installation guide that requires using Symfony Flex.
There should be a link for the non-Flex version at the top of that same page.

See this issue for more info: #386

**Comment by hshhhhh** [comment]
Sorry,  couldn't find this issue.

**Comment by phpcontrols** [comment]
so much for OOS
