### ISSUE TITLE
Is there a way to use assets versioning strategy outside of Symfony?

### ISSUE THREAD

**Issue by EliuTimana** [symfony/webpack-encore#395]
I'm using Encore in a non-Symfony project and we don't have the assets component, so we want to use assets versioning strategy with our files, everything works fine, encore generates the `manifest.json` file with the mapping information, but, how to use it? in Symfony all is done automatically, should we read that file and generate the proper HTML tags dynamically? thanks in advance.

**Comment by vkryukov76** [comment]
Hi @EliuTimana 

I write very basic class to work with `manifest.json` file and use it in my non-Symfony projects%

https://gist.github.com/vkryukov76/06258160f68a74e3ec1da23401dd9bf7

Hope it helps you.

**Comment by Lyrkan** [comment]
Hi @EliuTimana,

I would say that it depends on the kind of app you are trying to build.

If it's a single page application then you could use the [HTML Webpack Plugin](https://github.com/jantimon/html-webpack-plugin) to build your `index.html` page. You can add it to your Encore config with [`Encore.addPlugin(...)`](https://github.com/Lyrkan/ts-gb-web/blob/2eb942f6f769c5ac58aecc24493eb0c6a86da01a/webpack.config.js#L15).

If you are working on a multi-pages project then yes, you would need to read the `manifest.json` file using something like the assets component (note that you add it to any PHP project, not only Symfony ones).

**Comment by EliuTimana** [comment]
Thanks for your time, I got it working now, I have created a small C# class that maps the paths in the manifest file.

**Comment by javiereguiluz** [comment]
Let's close for now as "fixed", because it's hard to provide a generic solution that works in any kind of app and programming language. Thanks!
