### ISSUE TITLE
webpack vue-plugin error

### ISSUE THREAD

**Issue by Delari** [symfony/webpack-encore#398]
Hello, i use vue + element ui

have "vue-loader": "15.4.2",

try add vue-suggestions in project

all vue work fine, when i add this component (its plugin for site dadata)
https://github.com/evseevdev/vue-suggestions

code: 

    <template>
        <div>
            <VueSuggestions :model.sync="city"
                            :coordinates.sync="coordinates"
                            :placeholder="'Начните вводить'"
                            :class="form-control"
                            :options="suggestionOptions">
            </VueSuggestions>
        </div>
    </template>

i have this error

    Error: in ./node_modules/vue-suggestions/vue-suggestions.vue 1:0 
    Module parse failed: Unexpected token (1:0) You may need an appropriate loader to handle this file type.
    > <template> 
    | <input type="text" v-model="value"> 
    | </template>

package.json

    "devDependencies":
      ....
    "portfinder": "1.0.13",
    "postcss-import": "11.1.0",
    "postcss-loader": "2.1.6",
    "postcss-url": "7.3.2",
    "rimraf": "2.6.2",
    "sass-loader": "7.0.3",
    "script-ext-html-webpack-plugin": "2.0.1",
    "script-loader": "0.7.2",
    "semver": "5.5.0",
    "serve-static": "1.13.2",
    "shelljs": "0.8.2",
    "style-loader": "^0.19.1",
    "svg-sprite-loader": "3.8.0",
    "systemjs-plugin-babel": "0.0.25",
    "uglifyjs-webpack-plugin": "1.2.7",
    "url-loader": "1.0.1",
    "vue-loader": "15.4.2",
    "vue-style-loader": "4.1.2",
    "vue-suggestions": "1.4.0",
    "vue-template-compiler": "2.5.17",
    "vue2-filters": "^0.3.0",
    "webpack": "4.16.5",
    "webpack-bundle-analyzer": "2.13.1",
    "webpack-cli": "3.1.0",
    "webpack-dev-server": "3.1.5",
    "webpack-hot-middleware": "2.24.2",
    "webpack-merge": "4.1.4"
    },
    ...

webpack.config.js

    'use strict'
    const path = require('path')
    const webpack = require('webpack')
    const ExtractTextPlugin = require('mini-css-extract-plugin')
    const VueLoaderPlugin = require('vue-loader/lib/plugin')
    const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
    const bundleOutputDir = './wwwroot/dist'
    const OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')
    
    module.exports = () => {
      console.log('Building for \x1b[33m%s\x1b[0m', process.env.NODE_ENV)
    
      const isDevBuild = !(process.env.NODE_ENV && process.env.NODE_ENV === 'production')
      const extractCSS = new ExtractTextPlugin('site.css')
      const devMode = isDevBuild ? 'development' : 'production'
      return [{
        mode: devMode,
        stats: { modules: false },
        context: __dirname,
        entry: { 'main': './ClientApp/main.js' },
        devtool: 'source-map',
        watch: false,
        output: {
          path: path.join(__dirname, bundleOutputDir),
          filename: '[name].js',
          publicPath: '/dist/'
        },
        resolve: {
          extensions: ['.css', '.js', '.vue', '.json', '.scss', '.svg', '.png', '.jpe?e', '.gif', '*'],
          alias: isDevBuild ? {
            '@': path.resolve('ClientApp'),
            'vue$': 'vue/dist/vue',
            'components': path.resolve(__dirname, './ClientApp/components'),
            'views': path.resolve(__dirname, './ClientApp/views'),
            'utils': path.resolve(__dirname, './ClientApp/utils'),
            'api': path.resolve(__dirname, './ClientApp/store/api')
          } : {
            'components': path.resolve(__dirname, './ClientApp/components'),
            'views': path.resolve(__dirname, './ClientApp/views'),
            'utils': path.resolve(__dirname, './ClientApp/utils'),
            'api': path.resolve(__dirname, './ClientApp/store/api')
          }
        },
        plugins: [
          new VueLoaderPlugin(),
          new webpack.DefinePlugin({
            'process.env': {
              NODE_ENV: JSON.stringify(isDevBuild ? 'development' : 'production')
            }
          }),
          new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            Popper: ['popper.js', 'default']
          }),
          extractCSS,
          new webpack.DllReferencePlugin({
            context: __dirname,
            manifest: require('./wwwroot/dist/vendor-manifest.json')
          })
        ].concat(isDevBuild ? [
          new webpack.SourceMapDevToolPlugin({
            filename: '[file].map',
            moduleFilenameTemplate: path.relative(bundleOutputDir, '[resourcePath]')
          })
        ] : [
          new webpack.optimize.UglifyJsPlugin(),
          new ExtractTextPlugin({
            filename: devMode ? '[name].css' : '[name].[hash].css',
            chunkFilename: devMode ? '[id].css' : '[id].[hash].css',
            disable: isDevBuild
          }),
          new OptimizeCSSPlugin({
            cssProcessorOptions: {
              safe: true
            }
          })
        ]),
        optimization: {
          minimizer: [
    
            new UglifyJsPlugin({
              cache: true,
              parallel: true,
              uglifyOptions: {
                compress: false,
                ecma: 6,
                mangle: true
              },
              sourceMap: true
            })
          ]
        },
        module: {
          rules: [
            { test: /\.vue$/, exclude: /(node_modules)/, use: { loader: 'vue-loader' }},
            { test: /\.js$/, include: (path.resolve('ClientApp')), use: { loader: 'babel-loader?cacheDirectory' }},
            { test: /\.css$/, loader: ['style-loader', 'css-loader'] },
            { test: /\.scss$/, loader: ['style-loader', 'css-loader', 'sass-loader'] },
            { test: /\.svg$/, include: [path.resolve('ClientApp/icons')], use: { loader: 'svg-sprite-loader', options: { symbolId: 'icon-[name]' }}},
            { test: /\.(ttf|eot|woff|woff2)$/, use: { loader: 'file-loader' }},
            { test: /\.(png|jpe?g|gif|svg)(\?.*)?$/, exclude: [path.resolve('ClientApp/icons')], use: { loader: 'url-loader', options: { limit: 10000 }}},
            { test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/, exclude: /(node_modules)/, use: { loader: 'url-loader', options: { limit: 10000 }}},
            { test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/, exclude: /(node_modules)/, use: { loader: 'url-loader', options: { limit: 10000 }}},
            { test: /\.jsx$/, exclude: /(node_modules)/, use: { loader: 'babel-loader' }}
          ]
        }
      }]
    }

webpack.config.vendor.js

    const path = require('path')
    const webpack = require('webpack')
    const ExtractTextPlugin = require('mini-css-extract-plugin')
    const OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')
    
    module.exports = () => {
      const isDevBuild = !(process.env.NODE_ENV && process.env.NODE_ENV === 'production')
      const extractCSS = new ExtractTextPlugin('vendor.css')
      const devMode = isDevBuild ? 'development' : 'production'
    
      return [{
        mode: devMode,
        stats: { modules: false },
        resolve: { extensions: ['.js'] },
        entry: {
          vendor: [
            'jquery',
            'vue',
            'vuex',
            'axios',
            'vue-router'
          ]
        },
        module: {
          rules: [
            { test: /\.vue$/, use: { loader: 'vue-loader' }},
            { test: /\.js$/, include: (path.resolve('ClientApp')), use: { loader: 'babel-loader?cacheDirectory' }},
            { test: /\.css$/, loader: ['style-loader', 'css-loader'] },
            { test: /\.scss$/, use: [{ loader: 'style-loader' }, { loader: 'css-loader' }, { loader: 'sass-loader' }] },
            { test: /\.svg$/, include: [path.resolve('ClientApp/icons')], use: { loader: 'svg-sprite-loader', options: { symbolId: 'icon-[name]' }}},
            { test: /\.(ttf|eot|woff|woff2)$/, loader: 'file-loader' },
            { test: /\.(png|jpe?g|gif|svg)(\?.*)?$/, exclude: [path.resolve('ClientApp/icons')], use: { loader: 'url-loader', options: { limit: 10000 }}},
            { test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/, exclude: /(node_modules)/, use: { loader: 'url-loader', options: { limit: 10000 }}},
            { test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/, exclude: /(node_modules)/, use: { loader: 'url-loader', options: { limit: 10000 }}}
    
            // { test: /\.(sa|sc|c)ss$/, use: isDevBuild ? ['style-loader', 'css-loader'] : extractCSS.extract({ use: 'css-loader?minimize' }) },
            // { test: /\.(png|woff|woff2|eot|ttf|svg)(\?|$)/, use: 'url-loader?limit=100000' }
          ]
        },
        output: {
          path: path.join(__dirname, 'wwwroot', 'dist'),
          publicPath: '/dist/',
          filename: '[name].js',
          library: '[name]_[hash]'
        },
        plugins: [
          extractCSS,
          new OptimizeCSSPlugin({
            cssProcessorOptions: {
              safe: true
            }
          }),
          new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery', Popper: ['popper.js', 'default'] }), // Maps these identifiers to the jQuery package (because Bootstrap expects it to be a global variable)
          new webpack.DefinePlugin({
            'process.env.NODE_ENV': isDevBuild ? '"development"' : '"production"'
          }),
          new webpack.DllPlugin({
            path: path.join(__dirname, 'wwwroot', 'dist', '[name]-manifest.json'),
            name: '[name]_[hash]'
          })
        ].concat(isDevBuild ? [] : [
          new webpack.optimize.UglifyJsPlugin()
        ])
      }]
    }

**Comment by Lyrkan** [comment]
Hello @Delari,

It doesn't look like you are using Encore since you have raw Webpack config files, so I don't think this issue should be opened here.

Anyway, it probably doesn't work because the lib you are trying to add provides its own `.vue` templates in `node_modules/vue-suggestions/...`. but since you exclude the `node_modules` folder for the `vue-loader` in your `webpack.config.js` file, Webpack doesn't know what loader it should use.

**Comment by Delari** [comment]
oh, delete in vue-loader

    exclude: /(node_modules)/,

in config and project starting, need add css and all by fine

thx
