### ISSUE TITLE
Upgrade postcss-loader deps to 3.0

### ISSUE THREAD

**Issue by weaverryan** [symfony/webpack-encore#421]
https://github.com/postcss/postcss-loader has a new_ish) 3.0 version. I was notified by our nice new error:

>   WARNING   Webpack Encore requires version ^2.1.5 of postcss-loader. Your version 3.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.

Let's update that, and make sure things still work.

**Comment by stof** [comment]
According to the changelog, the only BC break is bumping the min node version to 6.x. So this should be fine for Encore (as 6.x is already our min version)

**Comment by Lyrkan** [comment]
Closing this since it was actually done in #389
