### ISSUE TITLE
Dart Sass? (Sass implementation customization)

### ISSUE THREAD

**Issue by Grawl** [symfony/webpack-encore#422]
[`sass-loader`](https://github.com/webpack-contrib/sass-loader) supports to specify Sass implementation to use: `node-sass`/`dart-sass`/`sass`

```js
// ...
    {
        loader: "sass-loader",
        options: {
            implementation: require("dart-sass")
        }
    }
// ...
```

[If I understand things right](https://symfony.com/doc/current/frontend/encore/css-preprocessors.html), I can customize `sass-loader` config like this:

```js
Encore.enableSassLoader(options => {
	options.implementation = require('sass')
})
```

But if I uninstall `node-sass` and install [`sass`](https://www.npmjs.com/package/sass) instead, I got an error because `Encore.enableSassLoader()` and `Encore.addStyleEntry` are limited to `node-sass` only

**Comment by ProtonScott** [comment]
You’re also going to want the fibers option so it plays nice with the way we pack plugins work:

>Note that when using Dart Sass, synchronous compilation is twice as fast as asynchronous compilation by default, due to the overhead of asynchronous callbacks. To avoid this overhead, you can use the fibers package to call asynchronous importers from the synchronous code path. To enable this, pass the Fiber class to the fiber option

[see here](https://github.com/webpack-contrib/sass-loader/blob/master/README.md)

**Comment by stof** [comment]
We should remove the check about `node-sass` being installed in case the `implementation` option is provided., as it is not necessary in that case. That should be an easy fix.

@ProtonScott the callback allows you to configure any option you want.
