### ISSUE TITLE
enabling Typescript support, compiling error wrong Webpack version

### ISSUE THREAD

**Issue by signmeuptwice** [symfony/webpack-encore#423]
enabling `.enableTypeScriptLoader()`

` ERROR  Failed to compile with 1 errors                                                                                                                      11:14:15 PM

 error  in ./src/FrontBundle/js/interface.ts

Module build failed: Error: You may be using an old version of webpack; please check you're using at least version 4
`

package.json
`{
    "devDependencies": {
        "@babel/core": "^7.0.0",
        "@babel/preset-env": "7",
        "@symfony/webpack-encore": "^0.20.0",
        "babel-loader": "^8.0.4",
        "copy-webpack-plugin": "^4.5.4",
        "jquery": "^3.3.1",
        "ts-loader": "^5.2.2",
        "typescript": "^3.1.3",
        "webpack-notifier": "^1.7.0"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production"
    }
}`

composer.json
`    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-json": "^1.5",
        "beberlei/DoctrineExtensions": "^1.1",
        "exercise/htmlpurifier-bundle": "^2.0",
        "sensio/framework-extra-bundle": "^5.2",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/asset": "^4.1",
        "symfony/console": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.1",
        "symfony/orm-pack": "^1.0",
        "symfony/swiftmailer-bundle": "^3.2",
        "symfony/templating": "^4.1",
        "symfony/twig-bundle": "^4.1",
        "symfony/web-server-bundle": "^4.1",
        "symfony/webpack-encore-pack": "^1.0",
        "symfony/yaml": "^4.1"
    },`

**Comment by umanshield** [comment]
https://github.com/TypeStrong/ts-loader#compatibility

```bash
     yarn remove ts-loader
     yarn install --dev ts-loader@^3
```

**Comment by Lyrkan** [comment]
Should be fixed by the [newly released version of Encore](https://github.com/symfony/webpack-encore/releases/tag/v0.21.0) that uses Webpack 4 :)
