### ISSUE TITLE
Compile error due to .mjs missing from resolve.extensions

### ISSUE THREAD

**Issue by msheakoski** [symfony/webpack-encore#430]
After upgrading to Encore 0.21, I received the error below. I was able to resolve it with:
```javascript
const config = Encore.getWebpackConfig();
config.resolve.extensions.unshift(".mjs");
```
but this should really be added by default since [webpack adds it by default](https://webpack.js.org/configuration/resolve/#resolve-extensions)
```
$ encore dev
Running webpack ...

 ERROR  Failed to compile with 175 errors                                                                           8:01:37 PM

 error  in ./node_modules/graphql/index.mjs

Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)

 error  in ./node_modules/graphql/index.mjs

Can't reexport the named export 'BreakingChangeType' from non EcmaScript module (only default export is available)

 error  in ./node_modules/graphql/index.mjs
```

**Comment by stof** [comment]
note having the `.wasm`, `.mjs` and `.json` extensions that webpack 4 has by default is indeed something we should fix here. I think webpack 3 had only `.js` by default, so the code adding the extra extensions was fine at that time, but it is not anymore.

**Comment by weaverryan** [comment]
Makes sense - let's fix this!
