### ISSUE TITLE
[0.21.0] shared js file content changes even if there is no code change

### ISSUE THREAD

**Issue by jfcherng** [symfony/webpack-encore#434]
# Problem

The js file content of shared entry (usually named as `app.HASH.js` or `vendor.HASH.js`) varies between builds even if there is no source code change.

# Reproduce

https://github.com/jfcherng/encore-shared-content-unstable

**Comment by weaverryan** [comment]
This stuff is very complex - so it's very possible. We should check into it - thanks for the reproducer!

By the way, do you see a new hash EVERY time you build... even if you literally change NOTHING? Or do you at least need to change *some* content, but these 2 files are unchanged, and so should not have a new hash?

Thanks!

**Comment by jfcherng** [comment]
@weaverryan

I may run the build process even if there is no js code change. Ideally, I hope the `vendor.HASH.js` remain the same file name and file content since I do not touch js codes.

Currently, the file content would change (due to file content changes in `_tmp_shared.HASH.js`) but the HASH remains the same. The generated codes still work fine though. 

The only inconvenience to me is that `vendor.HASH.js` would be marked as file content changed between builds in my assets version control.

**Comment by Lyrkan** [comment]
Maybe related to https://github.com/symfony/webpack-encore/issues/361#issuecomment-410190057?

**Comment by weaverryan** [comment]
Fixed in #441!

The issue was an internal detail of the "hack" that makes this work - a randomly-named file was created. This randomness caused the content/hash changed on `_tmp_shared.js`.
