### ISSUE TITLE
[0.21.0] Some 3rd-party plugins are not able to get correct/full vendor.js content

### ISSUE THREAD

**Issue by jfcherng** [symfony/webpack-encore#435]
Recently I am playing with [brotli-webpack-plugin](https://github.com/mynameiswhm/brotli-webpack-plugin) but I found that the generated pre-compressed `vendor.HASH.js.br` does not contain the content of `_tmp_shared.HASH.js`.

After searching in the source codes, I found that the content of `_tmp_shared.HASH.js` is appended to `vendor.HASH.js` at [the very last second](https://github.com/symfony/webpack-encore/blob/master/lib/webpack/shared-entry-concat-plugin.js#L81) (the `done` compiler hook). But the brotli-webpack-plugin (and many other webpack plugins?) [hooks](https://github.com/mynameiswhm/brotli-webpack-plugin/blob/master/index.js#L85) on the `emit` compiler hook so it just never gets the correct/full source. 

Ideally, "appending `_tmp_shared.HASH.js` to `vendor.HASH.js`" should be performed earlier?

**Comment by weaverryan** [comment]
Yes, that makes sense - I can't immediately think of a reason why we shouldn't append the content earlier.
