### ISSUE TITLE
Upgrade css-loader to 1.0

### ISSUE THREAD

**Issue by stof** [symfony/webpack-encore#438]
The version of css-loader used by encore currently relies on a buggy version of cssnano to optimize the CSS. Upgrading to the new version should be done: https://github.com/symfony/webpack-encore/issues/436#issuecomment-437263637

**Comment by Bonemeijer** [comment]
This would also fix the issue we're having where `cssnano@3.10.0` still relies on an old browserslist version `browserslist@1.7.7` and prevents browserslist targeting for `iOS`
