### ISSUE TITLE
Feature idea: enablePolyfills() to add usage-based polyfills

### ISSUE THREAD

**Issue by msheakoski** [symfony/webpack-encore#444]
With the following simple code, it is possible to modify Encore's babel config to provide automatic usage-based polyfills for stuff like `Promise, String.prototype.includes, Map, Set` through [@babel/polyfill](https://babeljs.io/docs/en/babel-polyfill) and core-js:
```bash
yarn add --dev @babel/polyfill
```
```javascript
// webpack.config.js
.configureBabel(function (babelConfig) {
    const preset = babelConfig.presets.find(([name]) => name === "@babel/preset-env");
    if (preset !== undefined) {
        preset[1].useBuiltIns = "usage";
    }
})
```
Polyfills are added based on 1. detected usage in your code and 2. your browserslist query in package.json. I think many users would find this convenient through an encore config option such as `enablePolyfills()` or whatever name seems more suitable.

**Comment by Lyrkan** [comment]
It seems that the `usage` option is still experimental though: https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage-experimental

Are we sure that it works fine enough? Since it has to infer variable types to work (which can't be perfect in JS) I'm wondering how we can be sure that it doesn't miss any needed polyfills or include a ton of them that are not really needed.

**Comment by msheakoski** [comment]
> It seems that the usage option is still experimental though: https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage-experimental

Yes, that is why I suggested putting it behind a deliberate command to enable/disable it vs having it on by default. If you add `debug: true` to the preset-env options, you will get output which shows the plugins and polyfills that are applied to your bundles. I have not looked through the code, but I imagine that it only enables polyfills which are obvious. Anything that is not detected can be added by importing from core-js at the top of your script.

```javascript
// webpack.config.js
.configureBabel(function (babelConfig) {
    const preset = babelConfig.presets.find(([name]) => name === "@babel/preset-env");
    if (preset !== undefined) {
        preset[1].useBuiltIns = "usage";
        preset[1].debug = true;
    }
})```

**Comment by msheakoski** [comment]
Thank you for adding this feature, @Lyrkan! I did not have a chance to work on it due to time constraints. Your approach looks great!
