### ISSUE TITLE
Getting path to entry file in dev mode

### ISSUE THREAD

**Issue by joshhornby** [symfony/webpack-encore#446]
Hi,

We are looking at Server Side Rendering some React into our PHP application using https://github.com/spatie/server-side-rendering.

Is it possible to get a relative path to a JS entry point file? For example in webpack we have `.addEntry('form-server', './assets/js/entry-server.js')` I'd like to be able get the path to this file so we can render in PHP side.

Apologies if this is the wrong place for this question.

**Comment by Lyrkan** [comment]
Hi @joshhornby,

The `entrypoints.json` file generated by Encore (in your build directory) should contain all the information you need. You'll only need to read it from your PHP code to retrieve the files required by your entrypoint.

**Comment by joshhornby** [comment]
Hi @Lyrkan 

Thanks for the response, although it's not quite what I'm looking for. For example I have `http://localhost:8080/build/entry-server.js` inside `entrypoints.json` but where does this file actually live on disk? It doesn't seem to be inside the `public/build` directory.

**Comment by Lyrkan** [comment]
Are you using `dev-server`?

If that's the case then you won't find the file anywhere because it won't be created on the disk but directly served from memory at the given URL instead.
