### ISSUE TITLE
Summernote with webpack encore

### ISSUE THREAD

**Issue by Rmy5** [symfony/webpack-encore#459]
I'm trying to use Summernote in webpack encore, I did:
1: **yarn add summernote**
2: **require('summernote');**

The compiler returns:
 warning  in ./node_modules/summernote/dist/summernote.js

4610:8-15 Critical dependency: **require function is used in a way in which dependencies cannot be statically extracted**

It's unclear, to me, how to properly install a plugin or a library in webpack encore.

**Comment by mertingen** [comment]
@Rmy5 You're supposed to refer [this page](https://www.npmjs.com/package/summernote-webpack-fix). I'm sure, it helps you about that.

**Comment by Rmy5** [comment]
@mertingen I see, tx very much !

**Comment by celsoandrade** [comment]
do we still need this forked package to get summernote to work with encore?
