### ISSUE TITLE
CSS Modules no longer work

### ISSUE THREAD

**Issue by Chesskingt** [symfony/webpack-encore#460]
Hey guys!

Just updated encore to latest version and noticed that VueLoader css modules no longer are being generated (raw classnames are being generated instead and `$style.className` no longer returns appropriate class)...

Was there something changed that broke CSS modules or is this an error?

Thanks!

**Comment by weaverryan** [comment]
Hey @Chesskingt!

Thanks for the report! Yes and no :). We did upgrade to Webpack 4 internally, and there could be some bug related to that, or you may be using a version of `vue-loader` (what version of `vue`, `vue-loader` and `vue-template-compiler` are in your project) that's not playing nicely.

Could you post your exact code and the expected output? We could turn that into a test case and find out easily if there is a bug or not.

Cheers!

**Comment by Lyrkan** [comment]
Hi @Chesskingt,

Did you enable CSS modules using `configureCssLoader()`?

```js
Encore.configureCssLoader(options => {
  options.modules = true;
});
```

**Comment by Chesskingt** [comment]
hi! Before, that worked right in Vue. Now, doing that works, BUT, there's an issue where ALL my css is now modualized. I use twig and Bootstrap so modularizing everything isn't an option. What ever happened to the basic vue-loader support for CSS modules within encore?

**Comment by Lyrkan** [comment]
Well, it seems that it now requires a more advanced config: https://vue-loader.vuejs.org/guide/css-modules.html#opt-in-usage

We may be able to add that to the `/\.css$/` rule generated by Encore (see [here](https://github.com/symfony/webpack-encore/blob/70f47f6795af73e66362080f4668e00b1e048df0/lib/config-generator.js#L229-L232) and [here](https://github.com/symfony/webpack-encore/blob/70f47f6795af73e66362080f4668e00b1e048df0/lib/loaders/css.js#L23-L38)) but we'll have to check if it doesn't break anything else first...

**Comment by epcliff** [comment]
Hi! I have a similar issue. I aded configureCssLoader and it's no longer empty but the actual styles doesn't apply. Is there any other configuration I need to do?

**Comment by Lyrkan** [comment]
Hi @epcliff, 

It's probably the same issue.

As I noted in my previous comment using "standard" CSS and CSS modules at the same time requires a more advanced configuration... which isn't easy to achieve in the current version of Encore (you would have to remove the default CSS loader and add the config given on Vue's website...)

I tried something in #508 that should help with that.
