### ISSUE TITLE
Support for the entrypoints.json with multiple webpack config

### ISSUE THREAD

**Issue by stof** [symfony/webpack-encore#466]
If webpack is used in multi-config mode (thanks to `Encore.reset()`), we would need to make the name of `entrypoints.json` to be configurable, so that each config can create its own file, without overriding the entrypoints created by the other config (and we will also need to add support for that in the WebpackEncoreBundle of course).

**Comment by stof** [comment]
hmm, actually, keeping it named `entrypoints.json` might be fine if we take care of using separate subfolders as output path for each config (which might be necessary to avoid conflicts between chunk files too)

**Comment by Alymbek** [comment]
hi, @stof!

I just try to make separate folders to output path, but get only single entrypoints.json and manifest.json for all of them.
and that files are incorrect,  see #477

**Comment by seyfer** [comment]
It is supported with webpack encore bundle
I guess closed by this one
https://github.com/symfony/webpack-encore-bundle/pull/17

**Comment by Lyrkan** [comment]
Yep, closing this since a new version of the WebpackEncoreBundle has been released with that feature :)
