### ISSUE TITLE
Possible incompatibility with `enableEslintLoader()` and eslint-vue-plugin

### ISSUE THREAD

**Issue by Kocal** [symfony/webpack-encore#473]
Hi, I am the [frontend dev that was blaming `webpack-encore` one year ago](https://github.com/symfony/webpack-encore/issues/277#issue-302738146) :eyes: 

First, let me congratulate you @weaverryan and the community, `webpack-encore` seems has become very mature over time. It's nice to have webpack 4, Babel 7 and ESLint working out of the box. 

Even if I still prefer using [`vue-cli`](https://github.com/vuejs/vue-cli) for a SPA (with Symfony as API) or a raw simple webpack config for smaller project, `webpack-encore` is really a must have for _more oriented_ Symfony projects. 

---

So I'm facing an issue with using the ESLint loader with [`eslint-plugin-vue`](https://github.com/vuejs/eslint-plugin-vue) for linting `.vue` files.

This is how I configure the `eslint-loader`:

```js
Encore.enableEslintLoader(config => {
  config.configFile = __dirname + '/.eslintrc';
});
```

This is my `.eslintrc`:

```json
{
  "extends": [
    "airbnb-base",
    "plugin:vue/recommended",
    "@yproximite/base"
  ],
  "rules": {
      ...
   }
}
```

And this is my ESLint dependencies:
```
❱Development❰ app@condictio.vm:/srv/app|⇒  yarn list --pattern eslint  
yarn list v1.12.3
├─ @yproximite/eslint-config-base@0.2.0
│  ├─ babel-eslint@10.0.1
│  └─ eslint-scope@3.7.1
├─ babel-eslint@8.2.6
│  └─ eslint-scope@3.7.1
├─ eslint-config-airbnb-base@13.1.0
├─ eslint-config-prettier@3.3.0
├─ eslint-import-resolver-node@0.3.2
├─ eslint-loader@1.9.0
├─ eslint-module-utils@2.2.0
├─ eslint-plugin-import@2.14.0
├─ eslint-plugin-prettier@3.0.0
├─ eslint-plugin-vue@5.0.0
├─ eslint-restricted-globals@0.1.1
├─ eslint-scope@4.0.0
├─ eslint-utils@1.3.1
├─ eslint-visitor-keys@1.0.0
├─ eslint@5.9.0
└─ vue-eslint-parser@4.0.3

```

And this is what happens when running `webpack-encore`:

![selection_007](https://user-images.githubusercontent.com/2103975/50288165-612c1e00-0465-11e9-9034-320dddfba3cb.png)

This is a `webpack-encore` issue because everything is fine when running ESLint manually:

![selection_008](https://user-images.githubusercontent.com/2103975/50288191-77d27500-0465-11e9-8338-885909c52b4b.png)

I followed the link [What is the "Use the latest vue-eslint-parser" error?](https://vuejs.github.io/eslint-plugin-vue/user-guide/#what-is-the-use-the-latest-vue-eslint-parser-error), and it's a problem of ESLint parser configuration.

We should do this to fix the problem:
```diff
- "parser": "babel-eslint",
  "parserOptions": {
+     "parser": "babel-eslint",
      "ecmaVersion": 2017,
      "sourceType": "module"
  }
```

But the `parser` options is hardcoded in [`loaders/eslint.js`](https://github.com/symfony/webpack-encore/blob/master/lib/loaders/eslint.js#L25):
![selection_009](https://user-images.githubusercontent.com/2103975/50288444-4017fd00-0466-11e9-95bb-5f10ada76e47.png)

So I updated my code and tried this:

```js
Encore.enableEslintLoader(config => {
  config.configFile = __dirname + '/.eslintrc';
  delete config.parser;
});
```

<details>
<summary>Screenshot</summary>

![selection_010](https://user-images.githubusercontent.com/2103975/50288581-9f760d00-0466-11e9-9371-d61490a75340.png)
</details>

or even this:

```js
Encore.enableEslintLoader(config => {
  config.configFile = __dirname + '/.eslintrc';
  config.parserOptions = Object.assign({}, config.parserOptions || {}, {
    parser: 'babel-eslint'
  });
  delete config.parser;
});
```

<details>
<summary>Screenshot</summary>

![selection_011](https://user-images.githubusercontent.com/2103975/50288585-a270fd80-0466-11e9-9a6b-a91928f382ce.png)
</details>

I have no more `eslint-loader` errors, but `eslint-loader` seems to not be working anymore :man_shrugging: 

Does someone already faced this issue? 
I will do more investigation and see if I can help more.

Thanks!

**Comment by Kocal** [comment]
That's really strange.
This is the final configuration that ESLint use (`console.log(config)` [here](https://github.com/eslint/eslint/blob/v5.9.0/lib/config.js#L331)) and this is what I got:
![selection_012](https://user-images.githubusercontent.com/2103975/50294617-93924700-0476-11e9-80c3-8c7260a46c3c.png)

Options `parser` and `parserOptions.parser` are correct, but `webpack-encore` still not displays ESLint warnings/errors :disappointed: 

This is what I have when running ESLint manually, and everything works fine:
![selection_013](https://user-images.githubusercontent.com/2103975/50294909-38148900-0477-11e9-9ab2-b82ad5b3f0e0.png)

**Comment by elmariachi111** [comment]
The problem is imho not in the configuration but rather in the loader rule setup: the eslint loader that encore configures never adds .vue files to its rules. Added it in my PR when eslint & vue loader are both active. With that patch you can 

.eslintrc.json
```
module.exports = {
    root: true,
    parserOptions: {
      parser: "babel-eslint",
      ecmaVersion: 2017,
      sourceType: 'module',
    },
    env: {
      browser: true,
    },
    extends: ["standard", "plugin:vue/recommended"],
    plugins: ['vue'],
  };
```

webpack.config.js
```
const eslintrc = require('./.eslintrc.json')
//...
.enableVueLoader()
  .enableEslintLoader(options => {
    return eslintrc
  })
//...
```

and I think these are all the dependencies:
`yarn add -D eslint eslint-config-standard eslint-loader eslint-plugin-import eslint-plugin-promise eslint-plugin-standard vue-eslint-parser`

plays well together with vscode's js language server when this is set:
```
{
    "eslint.validate": [
      "javascript",
      "javascriptreact",
      { "language": "vue", "autoFix": true }
    ],
    "vetur.validation.template": false,
    "eslint.alwaysShowStatus": true,
    "eslint.autoFixOnSave": true
  }
```

good luck!

**Comment by Kocal** [comment]
If someone has the same issue, since #509 you will be able to write this:

```js
Encore.configureLoaderRule('eslint', loader => {
    loader.test = /\.(jsx?|vue)$/
  });
```
