### ISSUE TITLE
runtime.js and encore_entry_script_tags twig function

### ISSUE THREAD

**Issue by bbuehrle** [symfony/webpack-encore#482]
This may be more of an issue with me being fairly new to webpack-encore in general so I'm not sure if this is a bug or if my n00b is showing.  

I've created a material-dashboard.js file:

```
// Need jQuery? Install it with "yarn add jquery", then uncomment to require it.
const $ = require('jquery');
const Popper = require('popper.js');

// any CSS you require will output into a single css file (material-dashboard.css in this case)
require('../css/material-dashboard.css');
require ('../dashboard/css/material-dashboard.css');
require ('font-awesome/scss/font-awesome.scss');
require ('../dashboard/js/core/bootstrap-material-design.min');
...
```

And I've defined the entry point in my `webpack.config.js` file:

```
var Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .addEntry('dashboard', './assets/js/material-dashboard.js')
    .enableSingleRuntimeChunk()
    .copyFiles([
        {
            from: './assets/dashboard/img',
            to: 'images/dashboard/[path][name].[ext]',
        },
        {
            from: './assets/images',
            to: 'images/[path][name].[ext]',
        }
    ])
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .enableSassLoader()
    .autoProvidejQuery()
;

module.exports = Encore.getWebpackConfig();
```
In my `base.html.twig` the `{{ encore_entry_link_tags('dashboard') }}` works fine, but I'm having issues with the `{{ encore_entry_script_tags('dashboard') }}` which renders `runtime.js` along with my `dashboard.js` and I receive the following console error in the browser:

`
Uncaught Error: Bootstrap dropdown require Popper.js (https://popper.js.org)
    at bootstrap-material-design.min.js:1
    at bootstrap-material-design.min.js:1
    at bootstrap-material-design.min.js:1
    at Object.<anonymous> (bootstrap-material-design.min.js:1)
    at Object../assets/dashboard/js/core/bootstrap-material-design.min.js (dashboard.js:2699)
    at __webpack_require__ (bootstrap:78)
    at Object../assets/js/material-dashboard.js (material-dashboard.js:15)
    at __webpack_require__ (bootstrap:78)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
`

If I use `<script src="{{ asset('build/dashboard.js') }}"></script>` as I did before I found the encore_* functions, then I don't receive the error.  Can you help point me in the right direction, please?

Thanks!

**Comment by weaverryan** [comment]
Hmmm, I don’t think you’re doing anything wrong - this strikes me as something possibly weird that material is doing.

As a workaround, trying removing the enableSingleRuntimeChunk() - that will remove this file

**Comment by bbuehrle** [comment]
Hey, Ryan.  Thanks for the fast response!  (BTW, love SymfonyCasts and the unique flair you bring!)  So, I commented out `.enableSingleRuntimeChunk()` which resulted in producing the error whether I was using the asset() function or the new encore_entry_script_tags().  

I tested in both Chrome and Firefox just to make sure the issue wasn't browser specific, and also tried `.disableSingleRuntimeChunk()` with the same error as removing the line entirely.

If there are any other files I can provide, please let me know (and keep up the good work!)

**Comment by stof** [comment]
I think bootstrap relied on Popper being available as a global variable, which is probably not the case in your project.

**Comment by bbuehrle** [comment]
Yes, that seems to have done the trick!  Thanks @weaverryan and @stof!

    // uncomment if you're having problems with a jQuery plugin
    // .autoProvidejQuery()
    .autoProvideVariables({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery',
        Popper: [
            'popper.js', 'default'
        ]
    })

**Comment by Lyrkan** [comment]
Closing the issue since it seems to be solved :)
Feel free to reopen it if you have more questions!
