### ISSUE TITLE
dev-server hot: createSharedEntry with sass fails if enableSourceMaps is enabled 

### ISSUE THREAD

**Issue by maibaumer** [symfony/webpack-encore#493]
When running **dev-server --hot** and having **enableSourceMaps** enabled it fails whenever I update a .scss file. It looks like it is stuck at `[WAIT] Compiling`. After I changed webpack `devServer.quiet = false`, I saw that I fails with an error:

`Error: Invalid number of files for chunk vendor - got vendor.js, vendor.469d3207de4d53a8a23b.hot-update.js`

in node_modules/@symfony/webpack-encore/lib/webpack/shared-entry-concat-plugin.js line 37

At first compile of dev-server --hot everything seems fine, when I only change something in a .js file as well.

Only when I make a change in any .scss file, the var **jsFiles** (in shared-entry-concat-plugin.js line 26) seems to contain two files. A **vendor.js** and a **vendor.xxxxx.hot-update.js**. When I disable **enableSourceMaps** in Encore the latter file isn't created and the error disappears (but so does the source maps functionality)

```
// webpack.config.js

var Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .setManifestKeyPrefix('build/')

    .createSharedEntry('vendor', './assets/js/webpack.shared_entry.js')

    .enableSingleRuntimeChunk()

    .enableSourceMaps(!Encore.isProduction())

    .enableSassLoader()
;

module.exports = Encore.getWebpackConfig();
```

```
// assets/js/webpack.shared_entry.js

require('../css/app.scss');
```

_@symfony/webpack-encore 0.22.4
symfony/webpack-encore-bundle 1.0.0_

**Comment by weaverryan** [comment]
Hmm, probably legit - the shared entry stuff is now done with a hack in Encore (because Webpack 4 doesn’t support it). It looks like we’re makijg some bad assumption with hot mode.

**Comment by Lyrkan** [comment]
Hi @maibaumer,

In case you're still having this issue I think I found a cleaner way to filter the `.hot-update.js` files by using `compilation.additionalChunkAssets` (see #523). Feel free to try it :)

**Comment by maibaumer** [comment]
Thank you @Lyrkan – it works like charm and doesn't feel as improvised as my workaround :)
