### ISSUE TITLE
Difference in CSS output bewteen dev and prod

### ISSUE THREAD

**Issue by MrMitch** [symfony/webpack-encore#498]
Hi,

I'm using wepack-encore in a Symfony project to build my assets. In one of my SASS stylesheets, I define a CSS rule to be applied on the first page of a printed document.

When this file is processed by webpack-encore, the CSS that is generated in production mode is not the same as the CSS that's generated in devevelopment mode (on the same machine), and the prod version is wrong. `node-sass` generates the right CSS output from the SASS input so I suspect that the issue is introduced when the CSS is minified (but I might be wrong). What follow is what I found while trying to debug this. I've included a repository at the end of the issue that you can use to reproduce the issue I'm presenting.

---

Specifically, the SASS instructions that are wrongly outputed in prod are : 
```sass
@media print {
  @page :first {
    margin-top: 0;
  }
}
```

I expect this to be compiled as 
```css
@media print{@page :first{margin-top:0}}
```

This works well when I run `yarn run encore dev`. The CSS output is : 
```css
@media print {
  @page :first {
    margin-top: 0;
  }
}
```

When I run `yarn run encore production`, the command doesn't fail but the CSS output is wrong. Notice the **`,`** before `first` instead of a **`:`** : 
```css
@media print{@page ,first{margin-top:0}}
```

Since the code in my SASS file is also valid CSS code, I thought I could work around this by putting the code inside a CSS file that I would then simply copy to my build directory using `Encore.copyFiles()`. This doesn't produce the expected result because the file is also minified when Encore is ran in production mode, and the same error happens (the `:` in `:first` is replaced with a `,`).

I'm currently using `v0.22.4` of webpack-encore, and I've managed to detect that this behavior only appeared in **`v0.21.1`** and has been present in every version since then. **`v0.21.0`** generates the right CSS output both in dev and in prod.

Looking at the diff between these 2 versions (https://github.com/symfony/webpack-encore/compare/v0.21.0...v0.21.1), and feeling like the issue happens during the minifying process, I came to think that the addition of the [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) might be the cause. It was added [here](https://github.com/symfony/webpack-encore/compare/v0.21.0...v0.21.1#diff-8ee2343978836a779dc9f8d6b794c3b2R6052), in commit 8f7ac59482ef3304413ace39fe3d1f39476bb79f. 
Please note that my assumption could be wrong, I'm not well versed in all things webpack. This is only a supposition.

---

I've created a small repository that you can clone to help you reproduce the issue : https://github.com/MrMitch/webpack-encore-page-first-issue

This project has 2 branches :
- a [master](https://github.com/MrMitch/webpack-encore-page-first-issue/tree/master) branch that contains the code with the issue I described here. **This code produces the wrong CSS output.**
- a [webpack-encore-0.21.0](https://github.com/MrMitch/webpack-encore-page-first-issue/tree/webpack-encore-0.21.0) branch that contains the **exact same code** but with a previous version of `webpack-encore` (v0.21.0). **This code produces the correct CSS output.**

Please let me know if there is anything more I can do to help get this resolved or any additional information I can provide.

Thank you for the work you put into this project, this is much appreciated.

**Comment by Lyrkan** [comment]
Hi @MrMitch,

That's a really great report! Thank you for all the details :)

I think that you're right about the commit that introduced this issue... the same package (`cssnano`) is used before and after the addition of `optimize-css-assets-webpack-plugin` in order to minify CSS files, but it got updated (from `^3.10.0` to `^4.1.0`).

I tried your example on [cssnano's playground](https://cssnano.co/playground/) and it gave me the same output:

![image](https://user-images.githubusercontent.com/850046/51404298-4ecffd80-1b53-11e9-8035-69f53e5b7faf.png)

I haven't had the time to look at the issues on [cssnano's repository](https://github.com/cssnano/cssnano/issues) yet but maybe someone already encountered the same problem?

Also, the CSS files being minified after going through `copyFiles` is not really intended... not sure how to fix that though.

**Comment by MrMitch** [comment]
Hi @Lyrkan,

Thank you for picking this up so quickly and narrowing things down.

I was hoping find where the problem came from in `cssnano`'s source code with `git bisect` but I couldn't really figure out how the project is structured and how to use/test it.

I've opened an issue (https://github.com/cssnano/cssnano/issues/677) in their repo hoping they can provide some guidance.

**Comment by Lyrkan** [comment]
Closing the issue since it was fixed in https://github.com/cssnano/cssnano/pull/678

Thank you for working on it @MrMitch :)
