### ISSUE TITLE
TypeError: Cannot read property 'minify' of undefined

### ISSUE THREAD

**Issue by ipf** [symfony/webpack-encore#510]
After upgrading to webpack-encore 0.23 I ran into the following error when running 
yarn run encore production in my Symfony / Vue project:
`TypeError: Cannot read property 'minify' of undefined`

This solution proposed in https://github.com/vuejs/vue-cli/issues/3407 worked for me:
Add 
```
  "resolutions": {
    "terser": "3.14.1"
  }
```
to your `package.json`. It seems the most current version of terser 3.16 broke something.

**Comment by jmsche** [comment]
Seems related to this: https://github.com/symfony/webpack-encore/issues/15#issuecomment-460039081

**Comment by Lyrkan** [comment]
It should be fixed in Terser now :)
