### ISSUE TITLE
Add support for custom attributes in encore_entry_link_tags

### ISSUE THREAD

**Issue by xbit** [symfony/webpack-encore#512]
Hello,

Currently, there is no way to add custom attributes when using `encore_entry_link_tags()` 
For example, i cannot add a `data-skin` attribute. 

    <link rel="stylesheet" href="assets/stylesheets/theme.min.css" data-skin="default">
    <link rel="stylesheet" href="assets/stylesheets/theme-dark.min.css" data-skin="dark"> 

I think this is very useful especially in use cases like above.

**Comment by jmsche** [comment]
Related to this one I think: https://github.com/symfony/webpack-encore-bundle/issues/10

**Comment by weaverryan** [comment]
Yep - let's have the discussion over on the bundle :). Thanks!
