### ISSUE TITLE
Child Node "output path" must be configured

### ISSUE THREAD

**Issue by Systemcheck** [symfony/webpack-encore#513]
Hello, i want to install webpack encore but i get the following error message:
```
script cache:clear returned with error code 1

in ArrayNode.php on line 228
The child node "output path" at path "webpack_encore"must be configured

script @auto-scriptswas called via post-update-cmd
```

important to know, i copied some files from existing project to a new project and then this error shows.

**Comment by Systemcheck** [comment]
Hello, i want to install webpack encore but i get the following error message:
```
script cache:clear returned with error code 1

in ArrayNode.php on line 228
The child node "output path" at path "webpack_encore"must be configured

script @auto-scriptswas called via post-update-cmd
```

important to know, i copied some files from existing project to a new project and then this error shows.

**Comment by Kocal** [comment]
You probably missed the [configuration file](https://github.com/symfony/webpack-encore-bundle#configuration) during your copy/paste.

You can copy it from another project, or follow the [installation steps](https://github.com/symfony/webpack-encore-bundle).
If you are using Symfony Flex, `composer require encore` will install the [WebpackEncoreBundle](https://github.com/symfony/webpack-encore-bundle) and will be [automatically configured](https://github.com/symfony/recipes/blob/master/symfony/webpack-encore-bundle/1.0/config/packages/webpack_encore.yaml)

**Comment by Systemcheck** [comment]
OK, i cant found the file which is missing, so i remove webpack and after that new require works.

```
composer remove webpack-encore
composer require webpack-encore
```
