### ISSUE TITLE
Can't compile webpack encore

### ISSUE THREAD

**Issue by Rmy5** [symfony/webpack-encore#515]
I installed webpack encore with:
```
composer require webpack-encore
yarn install
```
When I try to run encore I get the following error:

```
.../node_modules/webpack-cli/bin/cli.js:231
                                throw err;
                                ^
Error: custom keyword definition is invalid: data/errors should be boolean
```
I tried removing and reinstalling but still getting the same error.

Symfony version is: 4.2.3

package.json :
```
{
    "devDependencies": {
        "@symfony/webpack-encore": "^0.22.0",
        "webpack-notifier": "^1.6.0"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production --progress"
    }
}

```

**Comment by Lyrkan** [comment]
Hi @Rmy5,

The last update of [`ajv`](https://github.com/epoberezkin/ajv) released 3 hours ago broke some other packages, including Webpack: https://github.com/epoberezkin/ajv/issues/941

This will likely be fixed soon, but in the meantime you can use one of the workarounds given there, for instance by adding the following lines to your `package.json` file and running `yarn` again:

```
"resolutions": {
  "ajv": "6.8.1"
}
```

I'll keep this issue open for now in case other people encounter that problem.

**Comment by Rmy5** [comment]
Hi @Lyrkan,

Adding the lines didn't work for me. 
Although I tried setting up a new project (SF + encore), and it does compile ok. 
Either there was a fix in the meanwhile, or it might be some isolated bug.

Tx.

**Comment by Lyrkan** [comment]
Yep, a new version of `ajv` was released this morning.
A bit odd that the workaround didn't work though.
