### ISSUE TITLE
[improvement] add configure* options for all the loaders.

### ISSUE THREAD

**Issue by wujekbogdan** [symfony/webpack-encore#519]
I've just encountered some problems with  images loader and I wanted to change its default settings - then I found that there's no such a method as `configureImageLoader()` so I had to disable it and write the config on my own.

It would be great if all the loaders that webpack-encore support had a corresponding `configure_LOADER_NAME` method.

**Comment by Kocal** [comment]
Related to #509 I guess.

**Comment by Kocal** [comment]
Can we close this? 
Ping @Lyrkan  :)

**Comment by Lyrkan** [comment]
I guess we can
