### ISSUE TITLE
Question: deny extract css from entry js

### ISSUE THREAD

**Issue by slince** [symfony/webpack-encore#527]
Hello ,  i dont want to encore extract css into a separate file，Is this possible?

**Comment by Lyrkan** [comment]
Hi @slince,

Could you explain a bit more what you are trying to achieve ?
Do you want Webpack to add `<style>` tags instead ? Or maybe use CSS modules?

**Comment by slince** [comment]
@Lyrkan   Yes, i just want webpack add style tag. Because css is very simple, it is not necessary to send an http request to download it.

**Comment by Lyrkan** [comment]
I see, so you'd need to replace the `mini-css-extract-plugin` loader by the `style-loader`.

The bad news is: there is nothing built in the current version of Encore to do that... it may become a bit easier when #509 is released.

However you should be able to do it manually:

```js
// webpack.config.js
const Encore = require('@symfony/webpack-encore');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

Encore
  // (...)
;

// Retrieve the generated config
const config = Encore.getWebpackConfig();

// Replace the mini-css-extract-plugin loader by style-loader
for (const rule of config.module.rules) {
  if (rule.use && rule.use[0] === MiniCssExtractPlugin.loader) {
    rule.use[0] = 'style-loader';
  }
}

// Make sure you export `config` and not
// `Encore.getWebpackConfig()` here
module.exports = config;
```

**Comment by Kocal** [comment]
<sup>(I can't wait for #509 to be released :eyes:)</sup>

**Comment by slince** [comment]
TKS
