### ISSUE TITLE
createSharedEntry/copyFiles broken with the latest version of assets-webpack-plugin

### ISSUE THREAD

**Issue by Lyrkan** [symfony/webpack-encore#531]
I found out after creating #530 that the latest version of the `assets-webpack-plugin` (v3.9.9, released this afternoon) is not compatible with our "shared entry" and "copy files" hacks...

As already put in my first comment in that same PR it gives us the following stack trace:

```
Uncaught TypeError: Cannot read property 'integrity' of undefined
  at node_modules/assets-webpack-plugin/dist/index.js:97:55
  at Array.reduce (<anonymous>)
  at node_modules/assets-webpack-plugin/dist/index.js:87:30
  at Array.reduce (<anonymous>)
  at afterEmit (node_modules/assets-webpack-plugin/dist/index.js:74:27)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
  at AsyncSeriesHook.lazyCompileHook (node_modules/tapable/lib/Hook.js:154:20)
  at asyncLib.forEachLimit.err (node_modules/webpack/lib/Compiler.js:432:27)
  at node_modules/neo-async/async.js:2813:7
  at done (node_modules/neo-async/async.js:3521:9)
  at node_modules/graceful-fs/graceful-fs.js:45:10
  at FSReqWrap.oncomplete (fs.js:141:20)
```

This is more than likely caused by the following commit: https://github.com/ztoben/assets-webpack-plugin/commit/d69ac3ca027511f4228e0ef3a3984b86a038cddf

My best guess is that they get all the asset names from the `stats` object (which includes our deleted entries) and then expect `compilation.assets[asset]` to be an object [here](https://github.com/ztoben/assets-webpack-plugin/blob/d69ac3ca027511f4228e0ef3a3984b86a038cddf/index.js#L94).

But since we delete some assets from `compilation.assets` [here](https://github.com/symfony/webpack-encore/blob/853e0f97a20ee664143152078fd285f0cfd27bc1/lib/webpack/shared-entry-concat-plugin.js#L88) and [here](https://github.com/symfony/webpack-encore/blob/853e0f97a20ee664143152078fd285f0cfd27bc1/lib/webpack/delete-unused-entries-js-plugin.js#L31) they get `undefined` instead and then try to access an `.integrity` property on it.

I'm still not sure what we can do from our side yet apart from locking that plugin to `<3.9.9`...

Meanwhile, if someone gets that error, a workaround could be to add the following lines to your `package.json` file and run `yarn` again:

```
"resolutions": {
  "assets-webpack-plugin": "3.9.8"
}
```

/cc @ztoben

**Comment by ztoben** [comment]
I can put in an additional safety check around the existence of `compilation.assets[asset]` before trying to grab integrity off of it. I think that would be adequate?

**Comment by ztoben** [comment]
You mind trying `asset-webpack-plugin@3.9.10`? I think that should fix your issue.

**Comment by Lyrkan** [comment]
@ztoben I restarted the failing Travis job of #530 and it seems to be working perfectly again :)

Thanks for your reactivity, that's really appreciated!

I didn't open an issue on your repository since I was wondering if was really a bug on the plugin's side (we're doing some exotic things for those features...)
