### ISSUE TITLE
Encore.copyFiles() doesn't work for JSON files

### ISSUE THREAD

**Issue by Lyrkan** [symfony/webpack-encore#535]
As reported in https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/177#issuecomment-470941465, calling `Encore.copyFiles()` with a path/pattern that includes JSON files triggers the following error:

```
Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = __w...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = __w...'
```

This is caused by how JSON imports are now handled in Webpack 4, which removed the need of using the `json-loader` in most common cases but also prevents from using custom inline loaders for the `.json` extension.

Since `Encore.copyFiles()` internally uses `!file-loader?<params>` in `require.context()` calls, the output of the `file-loader` (which contains JS) is passed to that part of Webpack that processes JSON (which then throws the error).

From what I've read the only way to currently bypass that behavior is to set `rule.type`... which isn't possible from an inline call.

References:
* https://github.com/webpack/webpack/issues/6572
* https://github.com/webpack-contrib/file-loader/issues/259
* https://github.com/webpack/webpack/issues/7057
* https://github.com/webpack/webpack/issues/6586

**Comment by Kocal** [comment]
Encore does not use CopyWebpackPlugin for copying files?

**Comment by Lyrkan** [comment]
Nop, we tried to do that in #221 but we had some issues related to the manifest files.

The current implementation is the one from #409 (with some minor fixes).
