### ISSUE TITLE
Exclude in configureBabel not working

### ISSUE THREAD

**Issue by Defcon0** [symfony/webpack-encore#538]
Hello,

I have a node module which does some things and imports another module:

```
import {tns} from 'tiny-slider';

class TinySliderBundle {
//...
}
```

Now I want to use encore to transform the whole thing down to JavaScript usable without webpack. Therefore I use `yarn encore dev` with the following configuration:

```
var Encore = require('@symfony/webpack-encore');

const path = require('path');

Encore
    .setOutputPath('src/Resources/public/js/')
    .addEntry('contao-tiny-slider-bundle', '@hundh/contao-tiny-slider-bundle')
    .setPublicPath('/public/js/')
    .disableSingleRuntimeChunk()
    .configureBabel(() => {
    }, {
        exclude: (filePath) => {
            // Don't exclude files outside of node_modules
            if (!/node_modules/.test(filePath)) {
                return false;
            }

            // Don't exclude whitelisted modules
            const whitelistedModules = ['@hundh' + path.sep + 'contao-tiny-slider-bundle'].map(
                module => path.join('node_modules', module) + path.sep
            );

            for (const modulePath of whitelistedModules) {
                if (filePath.includes(modulePath)) {
                    return false;
                }
            }

            // Exclude other files
            return true;
        }
    })
    .enableSourceMaps(!Encore.isProduction())
;

module.exports = Encore.getWebpackConfig();
```

I use @symfony/webpack-encore 0.24. But even if I do a `return true` in the first line in the exclude function, *all* imported files (i.e. `tiny-slider` in this case) are copied to the resulting file which is exactly *not* what I want. My goal is to exclude everything but my code (class `TinySliderBundle`) from the resulting file.

Am I doing something wrong? Thanks in advance.

Update: When I do a `console.log()` in the exclude function, it is indeed called, so the function itself is called.

Bye Defcon0

**Comment by Lyrkan** [comment]
Hi @Defcon0,

I think that you may have misunderstood what thet `exclude` option does: it doesn't prevent files from being included into your build, it only makes Babel (which is mainly used for browsers-compatibility) not process them.

If you want to entirely exclude things from the build you may want to take a look at `Encore.addExternals`:

https://github.com/symfony/webpack-encore/blob/0facc4d0442003809a438e2537f5adffffb48d78/index.js#L383-L412

**Comment by Defcon0** [comment]
You were totally right. Externals have been the way to go. I works now :-)!

**Comment by Lyrkan** [comment]
> The default case is NOT that javascript files are processed using babel. Hence I had to do a return false to include it to babel.

They are, but not all of them, you can see the default rule here:

https://github.com/symfony/webpack-encore/blob/0facc4d0442003809a438e2537f5adffffb48d78/lib/WebpackConfig.js#L84

So, unless your files are located under `node_modules` or `bower_components` they should be included.

But if by "my files" you are talking about a lib of yours that's handled by Yarn/npm, I'd recommend using `includeNodeModules` instead of `exclude`:

https://github.com/symfony/webpack-encore/blob/0facc4d0442003809a438e2537f5adffffb48d78/index.js#L795-L797

**Comment by Defcon0** [comment]
Ah, I see. I'll take a look. Thanks for the hint.

**Comment by Defcon0** [comment]
Mhm, doesn't seem to work. I have:

```
var Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('src/Resources/public/js/')
    .addEntry('contao-tiny-slider-bundle', '@hundh/contao-tiny-slider-bundle')
    .setPublicPath('/public/js/')
    .disableSingleRuntimeChunk()
    .addExternals({
        'tiny-slider': 'tns'
    })
    .configureBabel(function (babelConfig) {
    }, {
        includeNodeModules: ['contao-tiny-slider-bundle']
    })
    .enableSourceMaps(!Encore.isProduction())
;

module.exports = Encore.getWebpackConfig();
```

Doesn't work. But

```
.configureBabel(function (babelConfig) {
    }, {
        exclude: (filePath) => {
            // do not exclude anything from babel!
            return false;
        }
    })
```

works.

**Comment by Defcon0** [comment]
OK, I got it working ;-) Thanks again!
