### ISSUE TITLE
Configuring the babel loader is not possible when using babelrc file

### ISSUE THREAD

**Issue by stof** [symfony/webpack-encore#543]
`configureBabel` currently has 2 arguments:

- a mandatory callback altering the Babel config
- an options argument allowing to configure some settings of the loader rule (excluding node modules or no for instance)

As the callback is incompatible with the usage of an external Babel config, this method throws an error when using it that way. But that means there is no way to configure options in such case.

**Comment by stof** [comment]
my use case for using an external config file is that `babel-eslint` requires it

**Comment by stof** [comment]
Oh, and of course, my project requires me to include *some* node modules in what gets processed by Babel (the material-components-web packages which use ES6 syntax in the modules), so I need the configuration of options.

**Comment by Kocal** [comment]
Not related to your issue, but:
> an options argument allowing to configure some settings of the loader rule (excluding node modules or no for instance)

Should we deprecate this functionality in favour of #509?

**Comment by stof** [comment]
Well, I still like the `include_node_modules` option talking a list of modules and building the actual rule internally. It would be a shame to loose it.
