### ISSUE TITLE
JS Module cache, webpackJsonp anyway to disable?

### ISSUE THREAD

**Issue by jRexhmati** [symfony/webpack-encore#548]
I use bootstrap remote modals with twig partials and this is the schema
A main page with some entry points a, b, c
Now I try to open a modal inside this page the modal get its content remotely from be
Content has one entry point d
1. Issue was that my d entry point which contains really small js and is not related with a, b or c included also js from a, b, c because of the runtime.js (I fixed that by removing script tag runtime.js)
2. Now JS that I have included gets executed only the first time I load the modal, if I close the modal (which I clear also its content) and open again the js will not load anymore

I think that webpack modules gets registered in some window variable (webpackjsonP) and after the first time that they are saved they will not get loaded anymore

Is there any way I could prevent this behaviour or unregister modules manually or clean some module cache?

Your help is very appreciated

**Comment by stof** [comment]
Well, modules being evaluated only once is the way they work in ES6. So there is no chance that webpack would implement a feature to break that rule.

What you need in your case is to write your code in a way where it can be triggered at a different time than during module initialization.

**Comment by jRexhmati** [comment]
Thank you very much for your fast response
That can be a little tricky for me, as I am migrating from a traditional app (where we only import js file and it gets executed) to webpack encore, and this means that now I have to trigger events when I load a modal other than the first time.

But I got the answer, thanks again :v:
