### ISSUE TITLE
Vue and JSX

### ISSUE THREAD

**Issue by Kocal** [symfony/webpack-encore#551]
Actually that's not an issue, but just an help if some people want to write JSX code with their Vue components. I'm planning to open a PR on [symfony/symfony-docs](https://github.com/symfony/symfony-docs) aswell.

The Vue team created a repo ([vuejs/jsx](https://github.com/vuejs/jsx)) that explains how to use [JSX with Vue](https://vuejs.org/v2/guide/render-function.html#JSX).

We should start to install dependencies:
```bash
$ npm install --save-dev @vue/babel-preset-jsx @vue/babel-helper-vue-jsx-merge-props
# with yarn
$ yarn add -D @vue/babel-preset-jsx @vue/babel-helper-vue-jsx-merge-props
```

And then configure Babel to use the preset `@vue/babel-preset-jsx`, this is how we do that with Encore:

```js
Encore.configureBabel(babelConfig => {
  babelConfig.presets.push('@vue/babel-preset-jsx')
}
```

And that's all. :smile: 

By the way, like it has been done for React (`.enableReactPreset()`) maybe we should consider adding a new method to Encore, like `.enableVueJSX()` that will mutate Babel config?

**Comment by Lyrkan** [comment]
Hi @Kocal,

> By the way, like it has been done for React (`.enableReactPreset()`) maybe we should consider adding a new method to Encore, like `.enableVueJSX()` that will mutate Babel config?

Wouldn't it be better to add that directly to `.enableVueLoader()`?
For instance:

```js
Encore.enableVueLoader(() => {}, {
  useJsx: true,
});
```

**Comment by Kocal** [comment]
Ah yep, even better! :)

**Comment by Kocal** [comment]
Oh also, I've just seen that the dev-server with HMR does not really work anymore when using JSX (or the `render` function in general?)

There is an issue https://github.com/vuejs/jsx/issues/13 which suggests to use [vue-jsx-hot-loader](https://github.com/skyrpex/vue-jsx-hot-loader). I will try it and put a feedback here.

**Comment by Lyrkan** [comment]
@Kocal That HMR issue is really weird, I couldn't reproduce it at all with your last repo.

But yeah, not related to Encore, so we should be fine without any additional loader :)

**Comment by Kocal** [comment]
Can I work on this or you already planned to? :)
