### ISSUE TITLE
Encore.copyFiles pattern ignores .js files

### ISSUE THREAD

**Issue by diabl0** [symfony/webpack-encore#556]
I'm trying to add hash (versioning), but only to js/css files copied using copyFiles method. For that i'm using this two config entries - one to copy everyting except js/css, and then seccond to copy js/css adding hash.
For some reason all works perfectly except `.js` extension (it works for css, png etc), wich are copied without hash (no mather if encore is launched with dev od production target

```js
    .copyFiles([
            {
                from: './assets/theme/dist/default/assets',
                to: 'theme/[path][name].[ext]',
                pattern: /^[^.]+$|\.(?!(css|js)$)([^.]+$)/
            },
            {
                from: './assets/theme/dist/default/assets',
                to: 'theme/[path][name]-[hash].[ext]',
                pattern: /\.(css|js)$/
            }
        ]
    )
```

manifest.json output:
```js
  "build/theme/vendors/base/images/jstree/throbber.gif": "/build/theme/vendors/base/images/jstree/throbber.gif",
  "build/theme/vendors/custom/jqvmap/jqvmap.bundle.css": "/build/theme/vendors/custom/jqvmap/jqvmap.bundle-af906f6bc803891b78d71ddb4bb86acd.css",
  "build/theme/vendors/custom/jqvmap/jqvmap.bundle.js": "/build/theme/vendors/custom/jqvmap/jqvmap.bundle.js"
```

full webpack.config.js:
```js
let Encore = require('@symfony/webpack-encore');
let ContextReplacementPlugin = require('webpack/lib/ContextReplacementPlugin');

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .enableSingleRuntimeChunk()

    .addEntry('app', './assets/js/app.js')
    .addEntry('registration', './assets/js/registration.js')
    .addEntry('news', './assets/js/news.js')

    .addExternals({jquery: 'jQuery'})

    .splitEntryChunks()

    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())

    .enableSassLoader()
    .enableLessLoader()

    .addExternals({jquery: 'jQuery'})
    .addPlugin(new ContextReplacementPlugin(/moment[\/\\]locale$/, /pl/))

    .copyFiles([
            {from: './assets/media', to: 'media/[path][name].[ext]'},
            {
                from: './assets/theme/dist/default/assets',
                to: 'theme/[path][name]-[hash:8].[ext]',
                pattern: /\.(css|js)$/
            },
            {
                from: './assets/theme/dist/default/assets',
                to: 'theme/[path][name].[ext]',
                pattern: /^[^.]+$|\.(?!(css|js)$)([^.]+$)/
            }
        ]
    )

    .enablePostCssLoader((options) => {
        options.config = {
            path: 'config/postcss.config.js'
        };
    })
    .configureUrlLoader({
        fonts: {limit: 4096},
        images: {limit: 4096}
    })
    .autoProvidejQuery()
;

module.exports = Encore.getWebpackConfig();

```

**Comment by Lyrkan** [comment]
Hi @diabl0,

Good news: I was able to reproduce your issue and kinda know where it's coming from
Bad news: No idea how to solve it properly yet

---

It seems that both of your `copyFiles` configs match JS files... even though the regular expressions are fine.

As a result, you'll probably have your JS files copied twice: one time with a hash, the other one without it (the manifest being able to only reference one of them).

This is most likely related to the [`resolve.extensions`](https://webpack.js.org/configuration/resolve/#resolveextensions) option of Webpack which allows to do import files without having to specify their extension.

Let's say that you are trying to copy files from a directory that contains `foo.js` and `bar.txt`:

* without using a regexp, Webpack will try to copy the following files:
  * `./foo` (which will copy `foo.js`)
  * `./foo.js`
  * `./foo.txt`

* by using `/\.(?!js$)([^.]+$)/` you'll still have `./foo`:
  * `./foo`
  * `./bar.txt`

* with `/\.(?!txt$)([^.]+$)/` however, `bar.txt` will be excluded correctly:
  * `./foo`
  * `./foo.js`

Currently Encore adds the following extensions by default, you'd probably encounter the same issue with them:

https://github.com/symfony/webpack-encore/blob/6e1b371a1a0542aa08bfec251ded6371d98f1070/lib/config-generator.js#L97

---

So, as I said before I sadly don't have a *real* fix for you yet, however if you don't need to handle files without an extension you may be able to tweak your regexp a bit, for instance: `/\.(?!(css|js)$)([^\/.]+$)/` (note the exclude slash at the end).

**Comment by DaPo** [comment]
Hi @Lyrkan I have quite the same issue : 
```    .copyFiles({
        from: './front/img',
        pattern: /\.(png|jpg|jpeg|gif)$/,
        to: 'images/[path][name].[hash:8].[ext]'
    }, {
        from: './front/img',
        pattern: /\.(?!(png|jpg|jpeg|gif)$)([^.]+$)/,
        to: 'images/[name].[ext]'
    })``` 

I try to hash all my PNG / JPG / JPEG / GIF file but not the SVG ones.

So I tried to exclude them on the second rule (so it will select the SVG files) and don't hash them. It seems like only the first rule is applied, not the second one.

From the first one I have also some SVG files that are hashed, but that's this current issue so we don't need to talk about it more than you've already did.

Anyway if I try with only the second rule:
```    .copyFiles({
        from: './front/img',
        pattern: /\.(?!(png|jpg|jpeg|gif)$)([^.]+$)/,
        to: 'images/[name].[ext]'
    })```

I have my SVG that are not hashed.

What can I do about it? 

Thank you!

**Comment by stof** [comment]
you are passing 2 arguments in your code, not an array of configs in the first argument.

**Comment by DaPo** [comment]
> you are passing 2 arguments in your code, not an array of configs in the first argument.

Oh LOL I didn't see the array in the doc… I'm too tired.

Thank you @stof! 😅

Have a nice one, sorry for that.
