### ISSUE TITLE
Can't build because of OptimizeCssAssetsWebpackPluginTypeError

### ISSUE THREAD

**Issue by RomainoSoko** [symfony/webpack-encore#577]
Hi everyone, i'm also using webpack encore for a project, my problem is that i can use dev commands but not build my project for production because i got an error : 

 "92% chunk asset optimization OptimizeCssAssetsWebpackPluginTypeError: Cannot read property 'toLowerCase' of undefined"

I've looked for many solutions but no one of them is looking like mine, so I turn to the community hoping that you can help me...

There is my package.json, just in case.

```
{
    "devDependencies": {
        "@symfony/webpack-encore": "^0.27.0",
        "@types/html-webpack-plugin": "^3.2.0",
        "@types/source-map": "^0.5.7",
        "@types/optimize-css-assets-webpack-plugin": "^1.3.4",
        "@types/webpack": "^4.4.27",
        "babel-core": "^7.0.0-bridge.0",
        "babel-loader": "^7.1.5",
        "fork-ts-checker-webpack-plugin": "^0.4.15",
        "ionicons": "^4.5.6",
        "lodash": "^4.17.11",
        "node-sass": "^4.12.0",
        "postcss-loader": "^3.0.0",
        "rellax": "^1.9.1",
        "sass-loader": "^7.1.0",
        "source-map": "^0.7.3",
        "ts-loader": "^5.4.3",
        "tslint": "^4.5.1",
        "typescript": "^3.4.5",
        "vue": "^2.6.10",
        "vue-loader": "^15.7.0",
        "webpack-notifier": "^1.6.0",
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "i": "npm install composer install php bin/console doctrine:database:create",
        "serve": "encore dev-server --hot",
        "dev": "encore dev",
        "build": "encore production --progress",
        "d-d-c": "php bin/console doctrine:database:create",
        "d-d-d": "php bin/console doctrine:database:drop --force"
    },
    "dependencies": {
        "autoprefixer": "^9.5.1",
        "axios": "^0.18.0",
        "browserslist": "^4.6.0",
        "caniuse-lite": "^1.0.30000969",
        "element-ui": "^2.8.2",
        "har-validator": "^5.1.3",
        "tailwindcss": "^0.7.4",
        "vue-property-decorator": "^7.3.0",
        "vue-scrollto": "^2.15.0",
        "vue-template-compiler": "^2.6.10",
        "vuex": "^3.1.0"
    }
}
```

**Comment by Lyrkan** [comment]
Hi @RomainoSoko,

I tried running our test suite again with the latest version of all the dependencies to make sure it wasn't an upstream issue and everything seems to be working fine.

Could you share more information about your setup? Maybe a small repro repository?

Also, I'm not sure if that could be related or not but I noticed that you have multiple dependencies that are already included in Encore. We don't recommend doing that since it can lead to version conflicts:

* `babel-core` (*that's especially important since it was replaced by `@babel/core`*)
* `babel-loader`
* `browserslist` (*not really an issue but unless you call it directly that's already a dependency of `optimize-css-assets-webpack-plugin` and `@babel/preset-env`*)
* `autoprefixer`(*not an issue either but that's already added by other dependencies*)

**Comment by RomainoSoko** [comment]
Hey @Lyrkan ! 

Thanks for replying, i finally found the solution during reproduction of the repo ;) !

The problem comes from tailwindcss config, that does not support kebabcase (i don't know why) during build !

It was not a problem from webpack encore,  thank you and sorry for the inconvenience. ;) !

**Comment by bjo3rnf** [comment]
@RomainoSoko I came across the same issue today. Could you please elaborate on how you fixed it or where the kebab-case issue is located in tailwind.config.js?

**Comment by adam1010** [comment]
@Lyrkan @RomainoSoko I've got an existing codebase with thousands of classes -- how did you go about figuring out which class was the culprit? Seems like something we should report on the Tailwind project.

**Comment by adam1010** [comment]
For my codebase the issue ended up being that I needed to use `.` instead of `-` for the color name, for CSS properties that have a dash:

```
.btn-outline-blue {
    color: theme('colors.blue-500');
    background-color: transparent;
    border-color: theme('colors.blue-500')
}
```
becomes
```
.btn-outline-blue {
    color: theme('colors.blue-500');
    background-color: transparent;
    border-color: theme('colors.blue.500')
}
```
