### ISSUE TITLE
copyFiles should allow glob patterns

### ISSUE THREAD

**Issue by trickeyone** [symfony/webpack-encore#582]
Since glob patterns are supported by the CopyWebpackPlugin, it should be allowed when passing a glob pattern in the `from` value and including a `context`. I'm getting an error `The "from" option of copyFiles() should be set to an existing directory but "**/*" does not seem to exist. Nothing will be copied for this copyFiles() config object.` and nothing is copied. This works when just passing the plugin with the config set.

**Comment by Lyrkan** [comment]
Hi @trickeyone,

Encore doesn't use the CopyWebpackPlugin but a custom implementation based on [Webpack's `require.context`](https://webpack.js.org/guides/dependency-management#requirecontext), so it doesn't take the same options: https://github.com/symfony/webpack-encore/blob/2f1c5f7e8b08eeacf10a953e5eec4d11dac56db9/index.js#L524-L537

That being said you can probably achieve similar results by using the right values in the `from`, `pattern` and `includeSubdirectories`  options.

**Comment by trickeyone** [comment]
Ah, ok. Didn't realize that. I kinda figured the whole purpose to using context + from was to be able to leverage something like a glob.

Thanks for the info!

**Comment by piotr-cz** [comment]
@Lyrkan as per https://github.com/symfony/webpack-encore/issues/582#issuecomment-497504899, could you give an example?

I'd like to copy font files from various packages in node_modules to `/fonts` folder, but it looks like it's too complex problem to handle.

Below is what I'm using now:

```js
Encore
  // ...
  .copyFiles([
    {
      from: path.resolve(__dirname, 'node_modules/@openfonts/montserrat_latin-ext/files'),
      pattern: /\.(woff|woff2)$/,
      to: 'fonts/[path][name].[ext]',
    },
    {
      from: path.resolve(__dirname, 'node_modules/@openfonts/open-sans_latin-ext/files'),
      pattern: /\.(woff|woff2)$/,
      to: 'fonts/[path][name].[ext]',
    },
  ]);
```

**Comment by Lyrkan** [comment]
@piotr-cz You'll have to move some parts of `from` into `pattern` and use `includeSubdirectories: true`, for instance:

```js
Encore.copyFiles([{
  from: path.resolve(__dirname, 'node_modules/@openfonts'),
  pattern: /\/(montserrat_latin-ext|open-sans_latin-ext)\/files\/.+\.(woff|woff2)$/,
  to: 'fonts/[path][name].[ext]',
  includeSubdirectories: true,
}])
```

Note that for fonts you'd usually not use `copyFiles(...)` but directly import them from your CSS.

**Comment by piotr-cz** [comment]
@Lyrkan 
Thank you.

I failed because I was not able to write RegExp that would work with Windows directory separator.
However I discovered that in this specific case it's not required to copy font files as they are included in css so webpack takes care of these.

Again thanks for preparing example
