### ISSUE TITLE
splitEntryChunks cause Bootstrap's Dropdown not working

### ISSUE THREAD

**Issue by Aerendir** [symfony/webpack-encore#586]
If I enable `splitEntryChunks()` in `webpack.config.js`, then the Bootstrap's dropdowns don't work on the frontend.

If I disable it, all works as expected.

Please, can you tell me what other information you need to better understand which is the problem, if any exist?

**Comment by javiereguiluz** [comment]
Check the contents of the generated `entrypoints.json` file to see if you see something strange. Also, check if the `encore_entry_script_tags()` Twig function is generating the right `<scrip>` tags in your template.

**Comment by stof** [comment]
I have bootstrap dropdowns working fine while using `splitEntryChunks()` in my own project. So this requires more details to reproduce this.

**Comment by Aerendir** [comment]
@javiereguiluz I'm not using the `encore_entry_script_tags()` function currently. Anyway I don't notice anything strange in `entrypoints.json`.

But as @stof has it working well, then I have to presuppose that is a problem of mine.

For the moment don't have the time to find the cause and fix it, so I will fix it later.

In the meantime I'm going to close this issue.

Thank you for your support!

**Comment by javiereguiluz** [comment]
@Aerendir in case you find it useful, you can check out how we use Webpack Encore in the Symfony Demo app (https://github.com/symfony/demo) because we always try to follow the recommended Symfony practices.

**Comment by Lyrkan** [comment]
@Aerendir If you are using `splitEntryChunks` multiple files can be created for each entry, which means that you have to add them into your page when needed:

As indicated in the description of the method this can be achieved by reading the `entrypoints.json` file:

https://github.com/symfony/webpack-encore/blob/b8f08a529900ae887841e96eee6115a9a185bddf/index.js#L595-L599

That's what the Webpack Encore Bundle does in its `encore_entry_script_tags(...)` function, so unless you have your own implementation of it you may be missing some files.
