### ISSUE TITLE
Add a .postcss test in enablePostCssLoader

### ISSUE THREAD

**Issue by hawezo** [symfony/webpack-encore#592]
I'm not sure how to format this issue, but everything is explained in this ticket: https://github.com/vuejs/vetur/issues/1330

Adding the following loader solves my issue:

```js
.addLoader({
    test: /\.postcss$/,
    use: [
        'vue-style-loader',
        {
            loader: 'css-loader',
            options: { importLoaders: 1 }
        },
        'postcss-loader'
        ]
})
```

I don't think I should *have to* add this manually. This loader is related to both `Vue` and `PostCSS`, so maybe a new method would solve the problem.

**Comment by Lyrkan** [comment]
Hi @hawezo,

Instead of adding a loader could you try doing the following?

```js
Encore.configureLoaderRule('css', loaderRule => {
    loaderRule.test = /\.(postcss|css)$/,
});
```

If that works we could eventually add it automatically when `enablePostCssLoader()` is called.

**Comment by hawezo** [comment]
`.configureLoaderRule()` seems to be working correctly: 

![](https://i.imgur.com/GbwgViR.png)

I think automatically adding it would be a great solution, but the warning should probably be hidden in this case.

**Comment by Lyrkan** [comment]
Perfect :)

If we add it automatically calling `configureLoaderRule()` won't be needed so you won't get a warning either.
