### ISSUE TITLE
Warning: Compiled with 0 warnings - Not seeing warnings from postcss-loader

### ISSUE THREAD

**Issue by uturnr** [symfony/webpack-encore#593]
When compiling, I typically see the following warning:

`WARNING  Compiled with 0 warnings`

A desktop notification appears showing the start of a warning, which I believe to be a postcss warning.

When compiling a different webpack (non-encore) config with the same postcss settings, I am correctly receiving 10 warnings, looking something like the below, when compiling.

```
WARNING in ./assets/scss/main.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js!./assets/scss/main.scss)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(1320:5) IE does not support align-items on grid containers. Try using align-self on child elements instead: .c-banner-search__content > * { align-self: center }
 @ ./assets/scss/main.scss 2:14-172 21:1-42:3 22:19-177
 @ ./storybook/stories/index.stories.js
 @ ./storybook/stories sync \.stories\.js$
 @ ./storybook/.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./storybook/.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```

**Comment by Lyrkan** [comment]
Hi @uturnr,

Would you be able to share a repro?

**Comment by uturnr** [comment]
Hi @Lyrkan, yes:

https://github.com/uturnr/webpack-encore-repro-issue-593

**Comment by Lyrkan** [comment]
Thanks!

It may be related to https://github.com/geowarin/friendly-errors-webpack-plugin/issues/84 but I'm not sure that's the case...

What happens is that the `stats.hasWarning()` returns `true` (so Webpack is telling there is one or more warnings) but `stats.compilation.warnings` (used by the `friendly-errors-webpack-plugin`) is empty... so maybe the issue comes frome somewhere else.

**Comment by Lyrkan** [comment]
Should be fixed by https://github.com/geowarin/friendly-errors-webpack-plugin/pull/93

**Comment by Lyrkan** [comment]
Closing this issue since the fix was released in `friendly-errors-webpack-plugin` and should also be available in the latest version of Encore.
