### ISSUE TITLE
upgrade packages

### ISSUE THREAD

**Issue by dvdknaap** [symfony/webpack-encore#596]
Hi,

I've update my url-loader package to 2.0.0 but when i run yarn build i get the warning message that webpack encore requires version ^1.0.1.

Could you upgrade the packages to the newest versions to fix these errors?

Thanks,

**Comment by Lyrkan** [comment]
Will be fixed by #599.

Note that what you currently get is only a warning, everything should work fine if you use `url-loader@^2`.
