### ISSUE TITLE
Building css results in Unknown word error 

### ISSUE THREAD

**Issue by plebada-ro** [symfony/webpack-encore#597]
Following the symfony 4 webpack encore documentation i have an app.css and an app.js which includes the app.css:

- app.js

```
require('../css/app.css');
const $ = require('jquery');
require('popper.js');
require('bootstrap');
require('animsition');
require('slick-carousel');
require('magnific-popup')
import { slickCustom } from './slick-custom'
import { main } from './main'
```

- app.css

```
@import "~bootstrap";
@import "~hamburgers";
@import "~fontawesome";
@import "~material-design-iconic-font";
@import "~animsition";
@import "~slick-carousel";
@import "animate";
@import "main.css";
@import "util.css";
```

- webpack.config.js

```
var Encore = require('@symfony/webpack-encore');

if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .copyFiles({
        from: './assets/images',
        to: 'images/[path][name].[hash:8].[ext]',
        pattern: /\.(png|jpg|jpeg)$/
    })
    .addEntry('app', './assets/js/app.js')
    .splitEntryChunks()
    .enableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .enableSassLoader();

module.exports = Encore.getWebpackConfig();

```

- Upon running `npm run watch` i get the 'Unknown word' error:

```
Failed to compile with 1 errors                                                                                                                                                                12:42:07 PM

 error  in ./assets/css/app.css

Syntax Error: ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:1) Unknown word

> 1 | var path = require("path");
```

The problem might be on the app.css part, because if i remove every import except for ~boostrap and utils.css, main.css which are my stylesheets(not from npm node_modules) the building is successful.

I got no idea what i do wrong, couldn't find any answer on google, so maybe you can help me out please?

Node v10.15.3
NPM 6.9.0
Let me know if you need some more info, thank you.

**Comment by Lyrkan** [comment]
Hi @plebada-ro,

You're getting this error because you're importing JS files into your `app.css`.

Doing `@import '~bootstrap'` works because they are declaring their stylesheet in their `package.json`: `"style": "dist/css/bootstrap.css"`.

However for `hamburgers` (I didn't check the other ones, so they may have the same issue), there is only a `"main": "index.js"`... so when you `@import "~hamburgers"` it imports `index.js`.

What you want to do is probably something like `@import "~hamburgers/dist/hamburgers.css";`

**Comment by plebada-ro** [comment]
Yep, that was the problem... now i feel stupid :(
