### ISSUE TITLE
Service workers  + sw_precache

### ISSUE THREAD

**Issue by tawfekov** [symfony/webpack-encore#61]
Hello Symfonyians,
is there any plans to add service workers + sw precache  support ? it would be very handy feature

**Comment by stof** [comment]
AFAIK, there is nothing special to do to support service workers. Your worker script would be a separate entry (it might be more complicated if you used shared entries, as it might require #48 instead, but I have not tried it)

**Comment by weaverryan** [comment]
I haven't used service workers yet, but it looks like https://github.com/NekR/offline-plugin is the standard solution? If so, that plugin can be added manually at the bottom of your `webpack.config.js` file (e.g. http://symfony.com/doc/current/frontend/encore/advanced-config.html). 

If there's something special we need to do to enable this in Encore... including potentially #48 or some small documentation, I'm interested.

**Comment by tawfekov** [comment]
Hey @stof , @weaverryan 

thanks for your points , I agree with @stof , it can get complicated with shared entries as #48  mentions but I think it should be handled sooner or later . 

about offline webpack plugin : 
1.https://github.com/goldhand/sw-precache-webpack-plugin which seems poplar as I see in  npm.org download stats 
2.https://github.com/NekR/offline-plugin  as @weaverryan mentioned I wasn't aware of it before today 


I'm going to prepare a demo on one of them , If it worked with me , I'll write a simple how to and create a pull request to the docs repo 

here is my ideas about what `encore` needs to be aware of :  **todo**  
people uses service workers mainly for 3 things : 

1. Service worker cache (AppCache)
2. Offline-optimized experience  
3. Web Push Notifications

**Comment by tawfekov** [comment]
here is a config that `kinda`  worked for me , I was able to register a service worker  + cache what I want to cache  ,  I'm working locally but I was my assets in chrome's / firefox application cache section
<img width="1435" alt="screen shot 2017-07-02 at 11 22 47 pm" src="https://user-images.githubusercontent.com/94997/27773207-7cb1297e-5f7d-11e7-938f-271043e70983.png">


here my `webpack.config.js` contents 


```
var Encore = require('@symfony/webpack-encore');
// require offline-plugin
var OfflinePlugin = require('offline-plugin');


Encore
// directory where all compiled assets will be stored
    .setOutputPath('web/build/')
    // what's the public path to this directory (relative to your project's document root dir)
    .setPublicPath('/build')
    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()
    // will output as web/build/app.js
    .addEntry('app', './web/assets/js/main.js')
    // will output as web/build/global.css
    .addStyleEntry('global', './web/assets/scss/global.scss')
    // allow sass/scss files to be processed
    .enableSassLoader()
    // allow legacy applications to use $/jQuery as a global variable
    .autoProvidejQuery()
    .enableSourceMaps(!Encore.isProduction())
    // create hashed filenames (e.g. app.abc123.css)
    //.enableVersioning()
    ;

// fetch webpack config, then modify it!
var config = Encore.getWebpackConfig();
// push offline-plugin
config.plugins.push(new OfflinePlugin({
    "strategy": "changed",
    "responseStrategy": "cache-first",
    "caches": {
        "main": [
            '*.css', //offline plugin doesn't know about build file , if I added build in it , it will show something like : OfflinePlugin: Cache pattern [build/images/*] did not match any assets
            '*.js',
            'fonts/*',
            'images/*'
        ]
    }
}));
// export the final and modified configuration
module.exports = config;
```

**Comment by tawfekov** [comment]
I'm closing this issue since #111 is more in depth about it
