### ISSUE TITLE
copy a file twice and how the mapped file in manifest.json is determined?

### ISSUE THREAD

**Issue by jfcherng** [symfony/webpack-encore#613]
# Problem

I would like to have `favicon.png` and `favicon.HASH.png` in `public/build/images/`. The versioned one is for Twig so users can see the icon change immediately if I modify it. The non-versioned one is for other websites that may want to embed my favicon.

Thus I have the following configuration.
```js
// copy all images and hash their names
Encore.copyFiles([{
  from: 'assets/images',
  to: 'images/[path][name].[hash:8].[ext]',
  pattern: /\.(jpe?g|png|gif|ico|svg|webp)$/,
}]);

// copy non-hashed favicon for other site's uses
Encore.copyFiles([{
  from: 'assets/images',
  to: 'images/[path][name].[ext]',
  pattern: /favicon\.png$/,
  includeSubdirectories: false,
}]);
```

After building, there are `favicon.png` and `favicon.HASH.png` in `public/build/images/` indeed. But in the `manifest.json`, the mapped one is non-hashed.

```js
{
  "build/app.js": "/build/app.e8f3ba31.js",
  "build/runtime.js": "/build/runtime.e59078a6.js",
  "build/images/favicon.png": "/build/images/favicon.png", // <------- oops
  "build/images/social.png": "/build/images/social.e43027bf.png"
}
```

I try to swap the order of configuration.

```js
// copy non-hashed favicon for other site's uses
Encore.copyFiles([{
  from: 'assets/images',
  to: 'images/[path][name].[ext]',
  pattern: /favicon\.png$/,
  includeSubdirectories: false,
}]);

// copy all images and hash their names
Encore.copyFiles([{
  from: 'assets/images',
  to: 'images/[path][name].[hash:8].[ext]',
  pattern: /\.(jpe?g|png|gif|ico|svg|webp)$/,
}]);
```

But the built result remains the same. 

# Expected Result

- Having `favicon.png` and `favicon.HASH.png` in `public/build/images/`
- In `manifest.json`, `build/images/favicon.png` is mapped to `/build/images/favicon.80f67853.png`

```js
{
  "build/app.js": "/build/app.e8f3ba31.js",
  "build/runtime.js": "/build/runtime.e59078a6.js",
  "build/images/favicon.png": "/build/images/favicon.80f67853.png", // <------- hashed one
  "build/images/social.png": "/build/images/social.e43027bf.png"
}
```

# Reproducer

https://github.com/jfcherng/Symfony-Encore-copyFiles-hash-problem

**Comment by stof** [comment]
The issue is that both assets (the favicon copied by the specific rule and the favicon copied by the generic rule) are using the same source `build/images/favicon.png`. And the manifest cannot store both (duplicate keys are not possible). Which one wins depend on the internal implementation of webpack and the involved plugins, and there is no guarantee that the order of definition is relevant for this implementation (and your report seems to indicate it is indeed not how they make one win).

If you want to get the non-hashed image in the manifest, I suggest you to change your `copy all images` rule to become a `copy all images except favicon` rule, by excluding it from the pattern.

**Comment by jfcherng** [comment]
@stof Thanks for hinting that. I have the output dir changed as a workaround now. :smiley:

```js
// copy all images and hash their names
Encore.copyFiles([{
  from: 'assets/images',
  to: 'images/[path][name].[hash:8].[ext]',
  pattern: /\.(jpe?g|png|gif|ico|svg|webp)$/,
}]);

// copy non-hashed favicon for other site's uses
Encore.copyFiles([{
  from: 'assets/images',
  to: 'external/images/[path][name].[ext]', // <------------------ output dir changed
  pattern: /favicon\.png$/,
  includeSubdirectories: false,
}]);
```
