### ISSUE TITLE
Different versioning strategy possible?

### ISSUE THREAD

**Issue by XWB** [symfony/webpack-encore#615]
```js
Encore
    .addStyleEntry('css/main', './assets/less/main.less')
    .enableVersioning(Encore.isProduction())
;
```

The current versioning strategy generates a hash and inserts it into the file name of the asset.

So in this example, `main` would become:

`main.87a8afff.css`

Is it possible to change this behavior? Like placing a query parameter behind each file? So we can get files like:

`main.css?1563717939`

**Comment by jfcherng** [comment]
this? https://symfony.com/doc/current/frontend/custom_version_strategy.html

**Comment by XWB** [comment]
> ah. you want the query string and parameter directly in the manifest.json.

Indeed. Not sure if that's possible?

**Comment by Lyrkan** [comment]
Hi @XWB,

You can do that by calling `Encore.configureFilenames()`, for instance:

```js
Encore.configureFilenames({
  js: '[name].js?[contenthash:8]',
  css: '[name].css?[contenthash:8]'
});
```

**Comment by Kocal** [comment]
Does webpack will be able to write files with a `?`, or it will write `[name].js` and the query will be present only in the manifest.json?

**Comment by Lyrkan** [comment]
Note that having the hash directly in the filename is sometimes a better choice though.

Having it in the query string doesn't alwyas prevent retrieving a wrong version of a file (especially if you use async chunks) whereas a different filename should.

@Kocal It should write into `[name].js`:

https://github.com/symfony/webpack-encore/blob/9a3cb43e880f10c54e8319b76433058137da78d2/test/functional.js#L427-L456

**Comment by Kocal** [comment]
Ah great!

**Comment by XWB** [comment]
Indeed, you don't want the query parameter to be part of the physical file. So I added the `configureFilenames` call as provided by @Lyrkan and it does exactly that:

![image](https://user-images.githubusercontent.com/1032281/61593916-1f737980-abe6-11e9-9861-1f9ea1fbd2ed.png)

![image](https://user-images.githubusercontent.com/1032281/61593923-33b77680-abe6-11e9-865d-7f653d049d0b.png)

Thanks for the support!

**Comment by Lyrkan** [comment]
@XWB Wait... is the first screenshot the content of your `manifest.json`? Because the keys should *not* contain the hash (that would be an issue).

In the test I linked in my previous response we don't observe that behavior, and I also tested it on a small project which gave the following output:

```
{
  "build/main.css": "/build/main.css?05866dcd",
  "build/main.js": "/build/main.js?2b800789",
  // (...)
}
```

**Comment by XWB** [comment]
@Lyrkan Indeed, that's my `manifest.json`. For some reason the keys include the hash as well:

![image](https://user-images.githubusercontent.com/1032281/61594640-7c732d80-abee-11e9-8375-62e9ef712d16.png)

Note that only the JavaScript files 0 to 16 have the hash in the key. Not sure what those files are?

**Comment by Lyrkan** [comment]
Oh, those are splitted chunks because you probably also call `Encore.splitEntryChunks()` or use async imports.

Not an issue then, I was worried because you only included them in the first screenshot...  they'll be automatically be added to your page by the Webpack Encore Bundle (using the content of the `entrypoints.json`, not the `manifest.json`) or at runtime by Webpack (for async chunks).

**Comment by XWB** [comment]
> Oh, those are splitted chunks because you probably also call Encore.splitEntryChunks() or use async imports.

I use async imports indeed.

> Not an issue then

Good the hear :)

Thanks for the support!
