### ISSUE TITLE
Comma missed in index.js

### ISSUE THREAD

**Issue by nandakumardevadas** [symfony/webpack-encore#62]
Hi Guys,

Comma missed in the latest tag of index.js at line 360. Encore was not running.

Please do the changes at.
enableTypeScriptLoader(callback) {
        webpackConfig.enableTypeScriptLoader(callback);
}

Getting error message SyntaxError: Unexpected identifier 
enableVueLoader(vueLoaderOptionsCallback = () => {}) {

**Comment by robertfausk** [comment]
Was also wondering yesterday when giving webpack encore a try.
