### ISSUE TITLE
Encore @media(max-width: 768px) does not work

### ISSUE THREAD

**Issue by tezmanian** [symfony/webpack-encore#620]
I've made a react site and moved it to encore. In chrome the @media(max-width: 768px) rule does not work. The last max-size which works in media rule is 1000px. Means @media(max-width: 1000px) works.

If I use webpack without encore all media rules work, for the same js/css.

I've testet it with the following project https://github.com/tezmanian/EncoreMax-widthProblems in chrome use inspector on body element.

**Comment by Lyrkan** [comment]
Hi @tezmanian,

I can't reproduce the issue using your repository:

![image](https://user-images.githubusercontent.com/850046/62212544-39a91680-b3a1-11e9-81f5-fc72529db5de.png)

Running `yarn encore prod` gives the following file which contains the media query:

```
body{background-color:#d3d3d3}@media (max-width:1680px){body{font-size:14pt}}@media (max-width:1280px){body{font-size:12pt}}@media (max-width:1000px){body{font-size:10pt}}@media (max-width:768px){body{font-size:8pt}}
```

Is that also the case for you?

**Comment by tezmanian** [comment]
It's a little bit strange I think. Now I can create booth results, one with the 768 works one with not. 

The difference is, if I resize the window like you, it works. But If I use the tool to test responsive design(Toggle device toolbar) it will stuck on 1000px, only when I use encore. 
If I use webpack seperatly it will work. 

In mobile chrome or firefox on my smartphone it will not work, there will be the 1000px version and not the version for lower resolution.

**Comment by tezmanian** [comment]
@Lyrkan 

![symtest png](https://user-images.githubusercontent.com/880689/62239794-dbe2f180-b3d5-11e9-8ec1-3d1e501464d2.png)

This is what I mean, it will not work in device toolbar mode or in mobil chrome on my smartphone.

**Comment by Lyrkan** [comment]
@tezmanian Did you try adding something like [`<meta name="viewport" content="width=device-width, initial-scale=1">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) to your code? It really doesn't seem to be an issue related to Encore but rather an incorrect width applied to your page (you could probably check that by looking at the computed properties of your `body`).

**Comment by tezmanian** [comment]
@Lyrkan Sorry, you are right, I've forgotten to save the edit in my base template. Thank you for your help. 

It was crazy, because firefox on my desktop has done the right job, only chrome has made trouble, which made me a little bit confused.
