### ISSUE TITLE
Webkpack Encore : ERROR Failed to compile with 0 errors

### ISSUE THREAD

**Issue by pierresis** [symfony/webpack-encore#621]
Hello,

I have this error :  `ERROR  Failed to compile with 0 errors`

which is hard to debug but Webpack Encore displays this message when i use a dynamic variable path : 

app.js

`const includeJsPath = require('../../templates/' + jsPath);`

or

`const includeJsPath = require(`../../templates/${jsPath}`);`

jsPath return a string 'component/menu/menu'.

My package.json : 
```
"dependencies": {
    "dotenv": "^8.0.0",
    "moment": "^2.24.0",
    "package.json": "^2.0.1"
  },
  "devDependencies": {
    "@symfony/webpack-encore": "^0.27.0",
    "autoprefixer": "^9.6.1",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.6",
    "babel-preset-env": "^1.7.0",
    "copy-webpack-plugin": "^5.0.4",
    "mini-css-extract-plugin": "^0.8.0",
    "node-sass": "^4.12.0",
    "postcss-loader": "^3.0.0",
    "sass-loader": "^7.0.1",
    "webpack-notifier": "^1.8.0",
    "webpack-version-file": "^0.1.3"
  },
  "scripts": {
    "dev-server": "encore dev-server",
    "dev": "encore dev",
    "watch": "encore dev --watch",
    "build": "encore production"
  }
```

webpack.config.js

```
const Encore = require('@symfony/webpack-encore');
const VersionFile = require('webpack-version-file');
const CopyWebpackPlugin = require('copy-webpack-plugin');

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')

    .addEntry('app', './front/v4/assets/js/app.js')

    .addStyleEntry('css/app', './front/v4/assets/scss/app.scss')

    .enableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .enableSassLoader()
    .enablePostCssLoader()
    // .enableBuildNotifications()

    .addPlugin(
        new VersionFile({
            data: {
                date: new Date()
            }
        })
    )
    .addPlugin(
        new CopyWebpackPlugin([{
            from: './front/ja-v4/assets/images',
            to: 'image'
        }])
    )
;

var config = Encore.getWebpackConfig();
module.exports = config;
```

I don't know if it's a webpack encore bug or other!

Any ideas ?

**Comment by Lyrkan** [comment]
Hi @pierresis,

This is most likely a duplicate of #593 which should be fixed on the next version of Encore. If that's the case it means that there actually *is* an error but it is not displayed properly.

In order to see the error you can either use the version of Encore from this git:

```
$ yarn remove @symfony/webpack-encore
$ yarn add git://github.com/symfony/webpack-encore.git#master
```

Or temporarily change you webpack.config.js in order to have a more verbose output:

```diff
// webpack.config.js
const Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    // (...)

const config = Encore.getWebpackConfig();

+ // Force Webpack to display errors/warnings
+ config.stats.errors = true;
+ config.stats.warnings = true;

module.exports = config;
```

Also, note that you don't need to (and probably shouldn't) add dependencies that [are already provided by Encore](https://github.com/symfony/webpack-encore/blob/a3be46e7509ba2065919f08b699701f2d4fee3da/package.json#L27-L58), for instance `babel-core` *(replaced by `@babel/core`)*, `babel-loader`, `babel-preset-env` *(replaced by `@babel/preset-env`)* and `mini-css-extract-plugin`.

**Comment by pierresis** [comment]
Hi @Lyrkan 
Thanks for your response.

Yeah, i'm not using babel and mini css plugin, i will delete this from the package.json :)

I saw the #593 issue but i thought it was related to friendly-errors-plugin.

Btw, i have a message error now :)
Many thanks!

**Comment by pierresis** [comment]
Hi @Lyrkan 
Thanks for your response.

Yeah, i'm not using babel and mini css plugin, i will delete this from the package.json :)

I saw the #593 issue but i thought it was related to friendly-errors-plugin.

Btw, i have a message error now :)
Many thanks!
