### ISSUE TITLE
Add support for separate type checking in Type Script

### ISSUE THREAD

**Issue by davidmpaz** [symfony/webpack-encore#63]
According to [this section](https://github.com/TypeStrong/ts-loader#loader-options) we can improve significantly the compilation speed by setting `transpileOnly = true`, though this require using another plugin for the type checking which does it in a separate process.

Until now I have been using [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin). I was planning to make a PR for adding it.

Today I also found [ts-checker-webpack-plugin](https://www.npmjs.com/package/ts-checker-webpack-plugin) but plugin doesn't seem to be as healthy as the other one, still exists to solve some issues with the previous.

Could we discuss to bring ideas to the table?

thanks in advance.

**Comment by weaverryan** [comment]
I would use whatever is officially recommended by TS, which is `fork-ts-checker-webpack-plugin` (since it's included in their ts-loader examples): https://github.com/TypeStrong/ts-loader

Other than that, it seems to make sense. If the user opts into this... then we can add the plugin :). To opt in... it seems like we're taking Encore down this path of having Encore-specific options after the callback:

```js
.enableTypeScriptLoader(function() {}, {
    fork_ts_checker_plugin: true
});
```

As perfectly consistent as that is, other ideas are welcome :).

**Comment by davidmpaz** [comment]
Which plugin to use is then clear. Regarding implementation I had in mind 2 solutions:

1. Add the plugin automagically when user configure `ts-loader` with `transpileOnly: true`. Options would have sensible defaults.
2. Add explicit API for `enableForkedTypesChecking(pluginConfig)`. This would enforce settings in `ts-loaders` for instance: `transpileOnly: true`. As well as any validation needed.

My point .1 I think would be problematic the same as your proposed solution in the way that plugin configuration will be hard (point 1) or we will be duplicating options on the way (Encore-specific options after the callback). Still would be the easiest way to use out of the box.

Point 2 add more verbosity and allow for more plugin configuration later on. Calling the API would store options and flag and when configuring `ts-loader` plugin would be added.

**Comment by weaverryan** [comment]
I like option 2!
