### ISSUE TITLE
this dependency was not found jquey-tags-input

### ISSUE THREAD

**Issue by sesmor** [symfony/webpack-encore#631]
Hello,
I tried to use jquery-tags-input. When I installed jquery-tags-input, using yarn add. But when I run yarn run encore, I have the following error:  **"This dependency was not found:
* jquery-tags-input in ./assets/js/objetForm.js"**
I use: **import('jquery-tags-input');** 
as suggested in the encore's FAQ, I tried: import('./jquery-tags-input/dist/jquery-tags-input.js');
Nothing works.

**Comment by Johann-S** [comment]
Did you tried `import('jquery-tags-input/dist/jquery.tagsinput.min.js')` ?

**Comment by stof** [comment]
`./` at the beginning means it is a relative path. If installing with yarn or npm, you need to reference the package, not a relative path from your source. So please try the suggestion from @Johann-S

**Comment by sesmor** [comment]
Thanks, I misreaded the faq, I don't know I have added a point .
Now, it works, thanks.
