### ISSUE TITLE
encore production outputs dev files

### ISSUE THREAD

**Issue by BenMorel** [symfony/webpack-encore#632]
First of all sorry if I'm missing something obvious. I've been following the [SymfonyCast on webpack-encore](https://symfonycasts.com/screencast/webpack-encore), and could not get the `encore` command to output production files. Whether I run:

```
yarn build
```

or directly:

```
encore production --progress
```

I get the development files outputted to `public/build`.

The problem seems to lie in the `NODE_ENV` environment variable not set:

```js
// webpack.config.js

console.log(process.env.NODE_ENV); // undefined

if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

console.log(Encore.isProduction()); // false
```

If I manually set the environment variable, it works as expected:

```
NODE_ENV=production encore production --progress
```

I'm not sure what can cause this issue. If anything, because of [a bug in vmware shared folders](https://github.com/vmware/open-vm-tools/issues/90#issuecomment-524587107), I'm using `encore` and `webpack` from a global install, instead of locally from `node_modules`; I can't see how this could affect this issue, though.

**Comment by Lyrkan** [comment]
Hi @BenMorel,

Encore does not really support being executed from a global install (and I wouldn't recommend it since your project can be tied to a specific version of Encore/Webpack/...).

In your case the runtime config is probably not initialized correctly which causes the code placed in your `if(!Encore.isRuntimeEnvironmentConfigured())` to be executed.

At this point it should basically do the same thing than directly running `webpack` (instead of the `encore` executable) with that `webpack.config.js` file.

**Comment by Lyrkan** [comment]
@BenMorel I just read the your comment on the vmware issue... if it is related to the `./node_modules/.bin` folder symlinks couldn't you directly execute `./node_modules/@symfony/webpack-encore/bin/encore.js` after installing your dependencies with `--no-bin-links`?

**Comment by BenMorel** [comment]
@Lyrkan Indeed, the problem does lie with the global installation. I tried your suggestion and it works fine, without setting the environment variable manually.

I actually replaced the `scripts` in package.json to make my life easier:

```json
"scripts": {
    "dev-server": "./node_modules/@symfony/webpack-encore/bin/encore.js dev-server",
    "dev": "./node_modules/@symfony/webpack-encore/bin/encore.js dev",
    "watch": "./node_modules/@symfony/webpack-encore/bin/encore.js dev --watch --watch-poll",
    "build": "./node_modules/@symfony/webpack-encore/bin/encore.js production --progress"
}
```

*Note the `--watch-poll` argument, also necessary when using vmware shared folders!*

Thank you!
