### ISSUE TITLE
CopyFiles bundle scss images

### ISSUE THREAD

**Issue by bvdham** [symfony/webpack-encore#635]
Having some issues to use inline scss image from within a bundle.
For example i've an LayoutBundle 

**LayoutBundle**
- Resources
  - assets
    - images
      - logo.jpg
    - scss
      - logo.scss
      - default.scss
    - js
      - layout.js

Entry in webpack.config.js app

``` js
    .addEntry('test', [
        './vendor/company/bundle/src//LayoutBundle/Resources/assets/js/layout.js'
    ])
```

``` js
#layout.js
"use strict";

import '../scss/default.scss';

// ... js code here
```

``` scss
#default.scss
@import "logo"
```

``` scss
#logo.scss
background: url("../images/logo.jpg");
```

How could i use copyFiles and scss images, could not find a way to make it work ?

**Comment by stof** [comment]
you should not need to copy the image at all here. As the image is referenced inside a Scss file processed by webpack, it should already be part of the build.

**Comment by bvdham** [comment]
@stof 
When running yarn watch getting the error
Module not found: Error: Can't resolve '../images/logo.jpgg' in ........'
