### ISSUE TITLE
CopyFiles from vendor bundle with Symlink creates underscores folders

### ISSUE THREAD

**Issue by bvdham** [symfony/webpack-encore#636]
I'm trying to copy files from a bundle stored in vendor. In this case the bundle is an Symlink.

**Project**
- lib
  - LayoutBundle (Symlink)
- public
- ....
- vendor
  - company
    - LayoutBundle

My webpack.config.js looks like
```js
    .copyFiles([
        { from: './vendor/company/layout_bundle/src/Company/LayoutBundle/Resources/assets/images/', to: 'images/layout/[path][name].[hash:8].[ext]' },
    ])
```

Built result, see image below. Its creating all underscore directories.
In image below the cookie-notice sub image folder is an copy from node-modules package. This is working correctly

![image](https://user-images.githubusercontent.com/7288381/64242226-74085500-cf05-11e9-893f-e50413aec925.png)

**Comment by bvdham** [comment]
Solved by editing the resolve symlinks options

```js
const config = Encore.getWebpackConfig();
config.resolve.symlinks = false;

module.exports = config;
```

**Comment by martinszeltins** [comment]
> Solved by editing the resolve symlinks options
> 
> ```js
> const config = Encore.getWebpackConfig();
> config.resolve.symlinks = false;
> 
> module.exports = config;
> ```

I had the same issue and this worked for me! But it would be better if Webpack/Encore warned about this and suggested this option automatically. A lot of wasted time otherwise trying to figure out what was the issue.
