### ISSUE TITLE
CssSyntaxError - css-loader

### ISSUE THREAD

**Issue by st0nebridge** [symfony/webpack-encore#643]
Hi,

I have 2 issues, an error when building my CSS, and I'm unable to parse url() links in webpack.

**main.js:**
`require('style-loader!css-loader!./css/style.css');`

I had the same issue using addRule/addLoader().

I'm using encore 0.28.0, when I try and parse a css file with the css-loader I get the error:

```
error  in ./assets/css/style.css

Syntax Error: CssSyntaxError

(1:1) Unknown word

> 1 | // extracted by mini-css-extract-plugin
    | ^
```

This comment appears to be added by mini-css-extract-plugin/loader.js:152:
`let resultSource = "// extracted by ${pluginName}";`

If I changed the comment from // to /* */ I can webpack successfully, however my url('') aren't being resolved still... (I am using a manifest.json also)

Any suggestions? is this related to a recent change?

**webpack.config.js:**
```
var Encore = require('@symfony/webpack-encore');
const path = require('path');

// Manually configure the runtime environment if not already configured yet by the "encore" command.
// It's useful when you use tools that rely on webpack.config.js file.
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore

    // output
    .setOutputPath('public/assets/')
    .setPublicPath('/assets')
    .setManifestKeyPrefix('assets/')

    .splitEntryChunks()
    .configureSplitChunks(function(splitChunks) {
        splitChunks.cacheGroups = {
            default: false,
            vendors: false,
            // vendor chunk
            vendor: {
                name: 'vendor',
                // sync + async chunks
                chunks: 'all',
                // import file path containing node_modules
                test: /node_modules/
            }
        }
     })
    .enableSingleRuntimeChunk()

    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())

    .autoProvidejQuery()
    // .enableSassLoader()

    // enables @babel/preset-env polyfills
    .configureBabel(() => {}, {
        useBuiltIns: 'usage',
        corejs: 3
    })

    .addAliases({
        'jquery': require.resolve('jquery')
    })

    // loaders
    .addLoader({
        test: /\.(cur)$/,
        loader: 'file-loader',
        options: {
            name: 'cursors/[name].[ext]?[hash:8]', // Output below
            publicPath: '../'
        }
    })

    // entries
    .addEntry('libs', './assets/libs.js')
    .addEntry('main', './assets/main.js')

    // revolution css
    .addStyleEntry("revolution", [
        './assets/revolution/css/settings.css',
        './assets/revolution/css/layers.css',
        './assets/revolution/css/navigation.css'
    ])

    // copy assets
    .copyFiles([
        {
            // responsive images
            from: './assets/images/stock/responsive',
            pattern: /\.(png|svg|jpe?g|gif|ico|cur)$/,
            to: 'images/responsive/[path][name].[hash:8].[ext]'
        },
        {
            // static images (logo etc)
            from: './assets/images/static',
            pattern: /\.(png|svg|jpe?g|gif|ico|cur)$/,
            to: 'images/static/[path][name].[hash:8].[ext]'
        },
        {
            // favicons
            from: './assets/images/favicons',
            pattern: /\.(png|svg|jpe?g|gif|ico|cur|xml|webmanifest)$/,
            to: 'favicons/[path][name].[ext]'
        },
        {
            // revolution js
            from: './assets/revolution',
            pattern: /\.(js)$/,
            to: 'js/revolution/[path][name].[ext]?[contenthash]',
            includeSubdirectories: false
        },
        {
            // html5shiv - conditionally loaded for IE
            from: path.resolve('node_modules', 'html5shiv/dist'),
            pattern: /html5shiv\.min\.js/,
            to: 'js/[path][name].[ext]?[contenthash]',
            context: path.resolve('node_modules', 'html5shiv/dist')
        }
    ])

    // add hash after file name'
    .configureFilenames({
        js: 'js/[name].js?[chunkhash]',
        css: 'css/[name].css?[contenthash]',
        images: 'images/[name].[ext]?[hash:8]',
        fonts: 'fonts/[name].[ext]?[hash:8]'
    })
;

var config = Encore.getWebpackConfig();

// custom config
config.output.chunkFilename = 'js/[name].js';

module.exports = config;
```

**Comment by Lyrkan** [comment]
Hi @st0nebridge,

Encore already includes a rule that is triggered on all `.css` files, so since you are using `require('style-loader!css-loader!./css/style.css');` the `css-loader` is applied twice.

If you want to use the `style-loader` globally instead of the `mini-css-extract-plugin` you can call `Encore.disableCssExtraction()` from your `webpack.config.js` file.

If that's not the case and you only want to use the `style-loader` for *some* imports you can disable the normal loaders by prepending the string by exclamation points (https://webpack.js.org/concepts/loaders/#inline):

> * Prefixing with ! will disable all configured normal loaders
> `import Styles from '!style-loader!css-loader?modules!./styles.css';`
> * Prefixing with !! will disable all configured loaders (preLoaders, loaders, postLoaders)
> `import Styles from '!!style-loader!css-loader?modules!./styles.css';`
> * Prefixing with -! will disable all configured preLoaders and loaders but not postLoaders
> `import Styles from '-!style-loader!css-loader?modules!./styles.css';`

**Comment by st0nebridge** [comment]
Hi @Lyrkan,

Thanks for getting back to me, I tried your suggestion but I was still unable to get webpack to parse the url() lines from the css and replace them with the appropriately versioned path.

I've tried with the style-loader/css-loader and the min-css-extract-plugin as per your suggestions.

I created a minimal working example of the behaviour at: https://github.com/st0nebridge/webpack-issue-20191003

In previous versions of webpack, just using the css-loader should've sufficed to move the images to the output folder, can you advise me what I'm doing wrong?

Many thanks,
B

**Comment by Lyrkan** [comment]
@st0nebridge Did you try using a relative path (without leading slash) here?
```css
background-image: url(/../images/static/image-icon1.png);
```

From `css-loader` documentation (https://github.com/webpack-contrib/css-loader#url):

> Absolute URLs and root-relative URLs are not resolving.

**Comment by st0nebridge** [comment]
@Lyrkan - thanks for your help, it's working now.

using: `background-image: url(../images/static/image-icon1.png);`

although I would've expected it to work with: `background-image: url(/assets/images/static/image-icon1.png);`
