### ISSUE TITLE
Object spread transform not working

### ISSUE THREAD

**Issue by wtorsi** [symfony/webpack-encore#644]
Hi everyone,
I'm trying to build assets for old browsers and unexpectedly discover that `@babel/plugin-proposal-object-rest-spread` does not transform object `...` to valid syntax.

My package.json
```
 "devDependencies": {
    "@babel/cli": "^7.6.2",
    "@babel/core": "^7.6.2",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-object-rest-spread": "^7.6.2",
    "@babel/plugin-proposal-unicode-property-regex": "^7.6.2",
    "@babel/plugin-transform-spread": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "@symfony/webpack-encore": "^0.28.0",
    "autoprefixer": "^9.6.1",
    "image-webpack-loader": "^6.0.0",
    "node-sass": "^4.12.0",
    "postcss-loader": "^3.0.0",
    "sass-loader": "^8.0.0",
    "url-loader": "^2.1.0",
    "webpack-notifier": "^1.8.0"
  },
```

.babelrc
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false,
        "targets": {},
        "useBuiltIns": "usage",
        "corejs": {"version": "3"},
        "forceAllTransforms": true
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-spread",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

I'm really need your help how to solve this problem or the way how to discover it.
My thoughts that other loaders break this transformation, but I don't know how to determinate them.

**Comment by Lyrkan** [comment]
Hi @wtorsi,

Does the spread operator comes from a vendor? By default Babel is not applied on things from `node_modules`, you have to whitelist them manually or change the exclude rule using `Encore.configureBabel()`:

https://github.com/symfony/webpack-encore/blob/5640271a87e63048b8ae261d210922b4972cab69/index.js#L836-L853

**Comment by wtorsi** [comment]
Yes, your are right, thanks a lot.
Morning problem solved.
