### ISSUE TITLE
Can't compile with webpack encore: relative modules were not found

### ISSUE THREAD

**Issue by Rmy5** [symfony/webpack-encore#660]
Hello,

Compiling fails when running `yarn run encore dev --watch` returning:

> These relative modules were not found:
>* ../../images/lipton.png in ./node_modules/css-loader??ref--5-2!./node_modules/resolve-url-loader??ref--5-3!./node_modules/sass-loader/dist/cjs.js??ref--5-4!./assets/scss/app/app.scss
>* ../fonts/GillSans-01.ttf in ./node_modules/css-loader??ref--5-2!./node_modules/resolve-url-loader??ref--5-3!./node_modules/sass-loader/dist/cjs.js??ref--5-4!./assets/scss/app/app.scss

This is my package.json:

```
{
    "devDependencies": {
        "@symfony/webpack-encore": "^0.20.0",
        "bootstrap": "^4.1.3",
        "jquery": "^3.3.1",
        "material-design-icons": "^3.0.1",
        "node-sass": "^4.9.3",
        "popper.js": "^1.14.4",
        "sass-loader": "^7.1.0",
        "webpack-notifier": "^1.6.0"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production"
    },
    "dependencies": {
        "@danielfarrell/bootstrap-combobox": "^1.1.8",
        "apexcharts": "^2.2.1",
        "codemirror": "^5.41.0",
        "datatables.net": "^1.10.19",
        "datatables.net-bs4": "^1.10.19",
        "datatables.net-buttons": "^1.5.4",
        "datatables.net-responsive": "^2.2.3",
        "datatables.net-responsive-bs4": "^2.2.3",
        "daterangepicker": "^3.0.3",
        "jquery.typewatch": "^3.0.0",
        "moment": "^2.22.2",
        "paginationjs": "^2.1.4",
        "pdfmake": "^0.1.39",
        "select2": "^4.0.6-rc.1",
        "sticky-kit": "^1.1.3",
        "summernote": "^0.8.10"
    }
}
```
This is my webpack.config.js:

```
var Encore = require('@symfony/webpack-encore');

Encore
    // directory where compiled assets will be stored
    .setOutputPath('public/build/')
    // public path used by the web server to access the output path
    .setPublicPath('/build')
    // only needed for CDN's or sub-directory deploy
    //.setManifestKeyPrefix('build/')

    /*
     * ENTRY CONFIG
     *
     * Add 1 entry for each "page" of your app
     * (including one that's included on every page - e.g. "app")
     *
     * Each entry will result in one JavaScript file (e.g. app.js)
     * and one CSS file (e.g. app.css) if you JavaScript imports CSS.
     */
    .addEntry('js/app', './assets/js/app/app.js')
    .addEntry('js/login', './assets/js/login.js')
    .addEntry('js/stats', './assets/js/stats.js')
    .addEntry('js/faqs', './assets/js/faqs.js')
    .addEntry('js/gen', './assets/js/gen.js')
    .addEntry('js/cat', './assets/js/cat.js')
    .addEntry('js/trs', './assets/js/trs.js')
    .addEntry('js/tools', './assets/js/tools.js')
    .addEntry('js/admin', './assets/js/admin.js')
    .addEntry('js/admin-stats', './assets/js/admin-stats.js')
    .addEntry('js/admin-trs', './assets/js/admin-trs.js')
    .addEntry('js/tools-edit', './assets/js/tools-edit.js')
    .addEntry('js/contact', './assets/js/contact.js')
    .addStyleEntry('css/app', ['./assets/scss/app/app.scss'])
    .addStyleEntry('css/tools', ['./assets/scss/tools.scss'])

    /*
     * FEATURE CONFIG
     *
     * Enable & configure other features below. For a full
     * list of features, see:
     * https://symfony.com/doc/current/frontend.html#adding-more-features
     */
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    // enables hashed filenames (e.g. app.abc123.css)
    .enableVersioning(Encore.isProduction())

    // enables Sass/SCSS support
    .enableSassLoader()

    // uncomment if you use TypeScript
    //.enableTypeScriptLoader()

    // uncomment if you're having problems with a jQuery plugin
    // .autoProvidejQuery()
;
var config = Encore.getWebpackConfig();

config.module.rules.unshift({
    parser: {
        amd: false,
    }
});

module.exports = config;
```

I tried deleting yarn lock, but didn't seem to fix it.

**Comment by Lyrkan** [comment]
Hi @Rmy5,

Are both of the paths given in the error message correct?
Does importing other files from your SCSS work?

A repro would also be really helpful if you can create one.

**Comment by Rmy5** [comment]
Webpack is buliding the project fine on an install using Yarn 1.10.1 and Node 10.11.0.
On an other install (Yarn 1.19.1 and Node 12.12.0) `yarn install` is failing for the project with 

> gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/admin/Serv/pepsia/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command \"/usr/local/Cellar/node/12.12.0/bin/node\" \"/Users/admin/Serv/pepsia/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/admin/Serv/pepsia/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/admin/Serv/pepsia/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=5\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/admin/Serv/pepsia/node_modules/fsevents
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Deleting the yarn.lock file solves the `gyp ERR`, but I do get some warnings:

> warning @symfony/webpack-encore > extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
warning @symfony/webpack-encore > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @symfony/webpack-encore > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @symfony/webpack-encore > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @symfony/webpack-encore > css-loader > cssnano > postcss-merge-rules > postcss-selector-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".

Then when I run `yarn run encore dev --watch` I get the missing modules errors.

In my SCSS sources if I change \:
`background: url('../../images/lipton.png');` to background: url('/images/lipton.png');
and
`src: url('../fonts/GillSans-01.ttf') format('truetype');` to  src: url('../../fonts/GillSans-01.ttf') format('truetype');
then it's building ok, all other assets are building ok, but then they won't on the other install !

**Comment by Lyrkan** [comment]
> In my SCSS sources if I change : `background: url('../../images/lipton.png');` to `background: url('/images/lipton.png');`

Root-relative URL (starting with a `/`) are not processed so it's "normal" you don't have an error after that change. The file probably won't be copied anymore though.

> and `src: url('../fonts/GillSans-01.ttf') format('truetype');` to `src: url('../../fonts/GillSans-01.ttf') format('truetype');`

That one is a bit weird... where is `GillSans-01.ttf` located?
* `./assets/scss/fonts/`: the first path is correct
* `./assets/fonts`: the second one is

> Webpack is buliding the project fine on an install using Yarn 1.10.1 and Node 10.11.0.
> On an other install (Yarn 1.19.1 and Node 12.12.0) yarn install is failing for the project with

Since you deleted the `yarn.lock` file on the second install you may not have the same dependencies than on the first one, which could explain why it behaves differently... did you try using the new `yarn.lock` on the first environment?

Note that you also have an old version of Encore, I'd suggest updating it (even if that'll require a bit of work because of BC breaks).
