### ISSUE TITLE
copyFiles with strange subfolders when they come from node_modules

### ISSUE THREAD

**Issue by cgahmann** [symfony/webpack-encore#661]
Is there a single solution so that there aren't such strange subfolders?

style.css
```css
@import "~photoswipe/dist/photoswipe";
@import "~photoswipe/dist/default-skin/default-skin";
```

app.js
```javascript
import PhotoSwipe from 'photoswipe';
import PhotoSwipeUI_Default from 'photoswipe/dist/photoswipe-ui-default';

global.PhotoSwipe = PhotoSwipe;
global.PhotoSwipeUI_Default = PhotoSwipeUI_Default;
```

webpack.config.js
```javascript
.copyFiles([
    {from: './assets/img', to: 'images/[path][name].[ext]'},
    {from: './assets/customers/xyz/img', to: 'images/[path][name].[ext]'}
])

.configureFilenames({
    images: 'images/[path][name].[ext]',
    fonts: 'fonts/[name].[ext]'
})

.configureUrlLoader({
    images: {
        limit: 1,
        context: './assets/img'
    }
})
```

![Bildschirmfoto 2019-10-23 um 09 39 10](https://user-images.githubusercontent.com/13014767/67369446-4fca0b80-f579-11e9-9bf5-79db8aa9c16c.png)

Something like:
```
images
├── default-skin
├── lightbox
├── overlays
├── svg
...
```

**Comment by Lyrkan** [comment]
Hi @cgahmann,

Based on your `webpack.config.js` these files are not handled by `Encore.copyFiles()` (which has a `context` option to change that kind of thing) but by the loader handling images imports.

The strange paths come from the fact that you are using `images/[path][name].[ext]` as a filename pattern (in `Encore.configureFilename()`) and `./assets/img` as a context (in `Encore.configureUrlLoader()`). So for a file coming from `node_modules` you have to go up two directories from `assets/img`, hence the two `_`.

There are multiple solutions to that:
* remove `[path]` from the filename (which is what Encore does by default): everything will be flattened
* change the context to `./`: you won't have the two `_` anymore but that'll also add `assets/img`
* remove the default images loader using `Encore.disableImagesLoader()` and add your own `file-loader`/`url-loader` configs: you'll need at least one for images coming from `node_modules` and another one for the rest (with a different `context` value)

**Comment by cgahmann** [comment]
Hi @Lyrkan,

Thanks for your help. I have found another way. With: **[folder]**
```javascript
    .configureFilenames({
        images: 'images/[folder]/[name].[ext]',
        fonts: 'fonts/[name].[ext]'
    })
```
