### ISSUE TITLE
Invalid name generation vendor chunk

### ISSUE THREAD

**Issue by onEXHovia** [symfony/webpack-encore#667]
Not sure if this is an webpack-encore or webpack error. For example, for each page there is a separate entry which is stored in the directory `pages`. Next, add entries to the page

```
{{ encore_entry_script_tags('pages/page1') }}
<!--- Another page --->
{{ encore_entry_script_tags('pages/page2') }}
```
When enabled `splitEntryChunks` vendor chunk name generated in a weird way. File contents entrypoints.json

```
{
  "entrypoints": {
    "app": {
      "js": [
        "/build/runtime.js",
        "/build/vendors~app.js",
        "/build/app.js"
      ]
    },
    "./pages/page1": {
      "js": [
        "/build/runtime.js",
        "/build/vendors~./pages/page1~./pages/page2.js",
        "/build/./pages/page1.js"
      ]
    },
    "./pages/page2": {
      "js": [
        "/build/runtime.js",
        "/build/vendors~./pages/page1~./pages/page2.js",
        "/build/./pages/page2.js"
      ]
    }
  }
}
```

I created a separate repository where this error is reproduced https://github.com/onEXHovia/encore-reproduce

**Comment by Lyrkan** [comment]
Hi @onEXHovia,

I'm not entirely sure that's an issue: Webpack uses the entrypoints names (the first parameter of `Encore.addEntry()`) to decide which names it should use for the output files.

So if you have the directory separator or things like dots in them, they'll be kept and you'll get intermediate directories (you can see that it also happen without splitted chunks for `/build/./pages/page1.js` or `/build/./pages/page2.js`).

In the case of splitted chunks the default settings for dev builds (production ones do not work the same way) will cause Webpack to merge those names using `~` which makes the paths look even more weird... but they should actually be valid: if you try opening `build/vendors~./pages/page1~./pages/page2.js` from the `public` folder it should work.

If you don't want that kind of paths though, you can either:

* not use `.` or `/` in your entrypoint names
* also disable splitChunks name generation in dev ([or replace it with a custom function](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksname)), this won't change anything for main chunks though:

```diff
- module.exports = Encore.getWebpackConfig();
+ const config = Encore.getWebpackConfig();
+ config.optimization.splitChunks.name = false;
+ module.exports = config;
```

**Comment by onEXHovia** [comment]
@Lyrkan thanks for the explanation.
