### ISSUE TITLE
Dev Server failed to compile with 1 errors

### ISSUE THREAD

**Issue by blachawk** [symfony/webpack-encore#673]
Within my Windows 10 system here is my current Symfony information:

```powershell

$ php bin/console about
 -------------------- ----------------------------------
  Symfony
 -------------------- ----------------------------------
  Version              4.3.8
  End of maintenance   01/2020
  End of life          07/2020
 -------------------- ----------------------------------
  Kernel
 -------------------- ----------------------------------
  Type                 App\Kernel
  Environment          dev
  Debug                true
  Charset              UTF-8
  Cache directory      ./var/cache/dev (19.6 MiB)
  Log directory        ./var/log (0 B)
 -------------------- ----------------------------------
  PHP
 -------------------- ----------------------------------
  Version              7.2.18
  Architecture         64 bits
  Intl locale          n/a
  Timezone             UTC (2019-11-21T14:39:27+00:00)
  OPcache              false
  APCu                 false
  Xdebug               false
 -------------------- ----------------------------------
  Environment (.env)
 -------------------- ----------------------------------
  APP_ENV              dev
  APP_SECRET           0d0e871a7cdfea1bbba4ecb83ea96aa8
 -------------------- ----------------------------------
```

I am having the toughest time trying to figure out why encore dev-server fails to resolve my localhost site when it attempts to run `http://localhost:8080/`.  Attached is a screenshot that speaks better than any words I can say right now...

<p><img class="img-fluid" src="https://lh3.googleusercontent.com/Q58DS01lbjEaFjdQDsSTab3mRRrJ7nCQyts7fT0BY0fTdtdFHR-A9-yG_9HWmmlN70pkT40p516VDQ5B3GjS7FOwkNkFAaY4V3ckWcFCPayHSQWZp2Dwuqz-eMOKRry-PrnZ7QhoZ1NZv3njnrb36or4rmmdBV8cD0bujQusG9F1Uo6NDL2fPY8SmuOoXQrMT6edPvc4A1kkrZCFwI5khoYh-kxIMb_NWubtFrI0-oFZrJ16zFTIhWIgfvX0EU-bnxumLxynhiEbjBlCK3_Nb3_41Gqt5xicZzPZhAA4c12-7ag2sm2AJ0f5HWt0AfhMCsE3ONt-RTTwETYebihan1Bg2Xt7wPHSEZmV-OAP3c70OKfKFonS0KPFKKjdIn7hvxR9jLZ379RoWC3H8lxf16Av9FqtDOylfATpBk8PKW38sMODhd_QysHe_SC-UYfuqSRgk4pJZVKVNGrpuv-hKth9WGlh0FaSjB1X0j8AoyayDTO-hzWWfzav9KrwMUnL5bL9A4tHIeIH0cFdwdb3tOvLmW8ze97R1pdF7_JP5uvhS5Y3ZNitgIljvGLi7rpTaOSaBeBXxe2fiVjP_qNxHomBbbN-fQ633DX1pTUxFJszXJUgelD--4EPu8L_k6DuZOPqPKCEUARdXzhdKzBtwNenBy-kIh5d4kIbuLZ2N_9CdkQAeg2-gy08Sdn2BMouOexk0t-cguii5wzwwPycjxKiUQh1SA_VyGii8uP7HIQ0IxA=w639-h654-no?.jpg" alt=""></p>
<hr>

* From the terminal, the following runs, but when I access the browser, it gives me a blank page with a message on top that says `Cannot Get /`.
```poweshell
npm run dev-server
```
* From the terminal, the following fails to compile with `1 errors in the terminal` as shown above.
```powershell
npm run dev-server --host http://symf.train04.wip/
```

* From the browser, the following URI can be easily accessed and I can view my Symfony project.
```powershell
http://symf.train04.wip/
```

**Comment by Kocal** [comment]
Option [`host`](https://webpack.js.org/configuration/dev-server/#devserverhost) only takes an host, not an URL, you can try to use `--host symf.train04.wip`.

**Comment by blachawk** [comment]
Thank you @Kocal for the super fast response.  But that fails in the same way as shown in my screenshot above.

**Comment by Lyrkan** [comment]
Hi @blachawk,

When running scripts with `npm` you need to add an additional `--` before custom arguments (see https://docs.npmjs.com/cli/run-script):

```
$ npm run dev-server -- --host symf.train04.wip
```

**Comment by blachawk** [comment]
@Lyrkan thank you so much on that educational part with custom arguments.  My bad on not knowing that.  Now I do.  That eliminates the terminal error I was seeing, but when I actually go to the browser, the only issue left is getting beyond the blank screen error, as shown below:

<img class="img-fluid" src="https://lh3.googleusercontent.com/wWxVqPxgxKnN3___8eXbvLbyKxPjdzymsfd0XxXJcCpNbtFeItPTmtUDP57NTs0xFzidqbnuXMtXb0ldaJgeG2FwZiPE4N9q1hihl6gKK2GI4_KBkrBdXy1G_IEXe4t4KXGMmMMPlLANaE33RldRr9mm5kCWxMFtHKxlB2MzFSbOeN5qwYsnnHeuS2X9BElNHgJdCXeoxWUxvJGMSstAgwxxVtfCJhkf4sfizDMMW_EKGzr8STi2FMPRS4Oe-bdCYN35ohT5MIArGxqM3SFhmuyarpRaHpRgebdK6g4M36TSyyQBnH9kLyREfiS6NumpoE200_YsHfEM-RMjMWLluGoCdUTBZdcfma0ECnZLXRgm2rs488zGo742AsvM93cv1HBT4_T0xJpZp-vfxsWgw1UDd_RpHrUESy_OkLTdlCRWIiipjAD151nGe52ZraSYv-FpfSSzBmMBbYFGGkjBKVb9sWkq1CYHoij_oR6RSsICPoL-E3yCCTBhK98XpPtr2VDTSJUAGkDiugYuAJ_U-FxuFXLmvcsPoFGvVD843ZvI3DLkuEnAhnWtjxJC0Xj4MDeb36Ey01WWi3GqrokhJqfaUvGLW2YSrX7UWwrYCdw3T5tUnIRDfbgAh9gC-lGXpChc9_4rwljsyQ6bRXCSaYz-O8HtbConpDMN-aqzc03Fx9DXEBRmyw=w861-h455-no?.jpg" alt="">

Is this due to setting that I need to configure in my webpack.config.js file? or is this already reported as an internal bug?  Thanks for helping me understand more.

**Comment by Lyrkan** [comment]
Unless you have an `index.html` file in the public path I don't see anything weird with the screenshot from your last post.

The compiled assets (JS, CSS, ...) should be available at the URLs present in the `manifest.json`/`entrypoints.json` files.

**Comment by blachawk** [comment]
As far as I can see, looking at my explorer tree, the entrypoints.json and manifest.json file, I do not have an index.html in the public path.  Perhaps there is more going on here than we think.  I would love to get some more ideas on what I can possibly do to resolve the situation...

This is what my virtual host setup looks like....
```


<VirtualHost *:80>
  DocumentRoot "c:/Users/xxx/Documents/mTraining/php/symfony/train04/public"
  ServerName symf.train04.wip
   DirectoryIndex index.php
  <Directory "C:/Users/xxx/Documents/mTraining/php/symfony/train04/public">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
    Order allow,deny
    allow from all
       <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ /index.php [QSA,L]
        </IfModule>
  </Directory>
</VirtualHost>
```

**Comment by Lyrkan** [comment]
I think you misunderstood about what the dev-server does: it only handles static files/compiled assets, not your PHP project.

Nothing prevents you from loading those assets from your Symfony app running on Apache/Nginx though... that should even be the case automatically if you're using the Webpack Encore Bundle (since it uses the `entrypoints.json` file).

**Comment by blachawk** [comment]
I now see the light. Thank you for helping me understand better on the tools i am using.  That answers all of my struggles.  Many thanks!
