### ISSUE TITLE
Build fail but does not return shell error code

### ISSUE THREAD

**Issue by aminnairi** [symfony/webpack-encore#682]
Hi there,

I'm trying to use `eslint` in order to validate the JavaScript code style. I have some errors in my source-code that ESLint successfully manage to catch. I also have read what is said [here](https://github.com/symfony/webpack-encore/issues/621) to enable Webpack errors (I also think this should be mentionned somewhere on the documentation). But unfortunately, echoing the `$?` does not return something different than `0`. This means I cannot put it in my CI since it will not report errors on the shell.

Is it possible to have WebpackEncore return a shell error on build errors?

**Comment by Lyrkan** [comment]
Hi @aminnairi,

> I also have read what is said here to enable Webpack errors (I also think this should be mentionned somewhere on the documentation)

That was a temporary fix that shouldn't be needed in recent versions of Encore.

If your packages are all up-to-date and some errors are still hidden could you give more information about your setup so we can fix that issue?

> But unfortunately, echoing the $? does not return something different than 0. This means I cannot put it in my CI since it will not report errors on the shell.

By default eslint errors/warnings won't cause the build to fail, you'll have to use the [`failOnError`](https://github.com/webpack-contrib/eslint-loader#failonerror) and [`failOnWarning`](https://github.com/webpack-contrib/eslint-loader#failonwarning) options.

They can be added to your conf when calling `Encore.enableEslintLoader()`.

**Comment by aminnairi** [comment]
This is now working as intended thanks to this option: `failOnError`. Thanks for your help.
