### ISSUE TITLE
Issue with SourceMap and Firefox

### ISSUE THREAD

**Issue by DaPo** [symfony/webpack-encore#690]
Hi folks,

I may have an issue with Webpack Encore. I'm not sure if that's from Encore or Webpack itself. Feel free to tell me what you're thinking about.

So, I'm using Firefox for a few months now, I've been on Chrome before that. I have this weird issue where I write some CSS and Firefox completly break the CSS I see in the inspector.

For example, given the CSS from my code editor:

```css
.suggests {
    margin-bottom: 0;
    padding: 0 10px;
    border-radius: 4px;
    list-style: none;
    background: var(--grey-50);
    box-shadow: 0 4px 14px 0 rgba(0,0,0,0.10);
}

.searchMenu .suggests {
    position: absolute;
    top: calc(100% + 15px);
    left: 0;
    width: 496px;
}
```

May be shown in the Firefox devtool's inspector like this:

![ss_ 1183](https://user-images.githubusercontent.com/1059657/73760507-b4e2ef00-476d-11ea-901b-0368e9e832bd.jpg)

I have other examples of glitches like this one, like this one

![vgOdC5HSs7](https://user-images.githubusercontent.com/1059657/73760697-012e2f00-476e-11ea-98e1-4880ad6fd889.jpg)

Or I have this on Sublime Text:

![image](https://user-images.githubusercontent.com/1059657/73760754-13a86880-476e-11ea-9e65-06964cd7f0e2.png)

I see this in the inspector: 

![image](https://user-images.githubusercontent.com/1059657/73760772-1e62fd80-476e-11ea-8d0d-49ea33961364.png)

And this CSS is coming from this:

![image](https://user-images.githubusercontent.com/1059657/73760796-2753cf00-476e-11ea-9d8f-ea20cfc19a63.png)

It drives me crazy! The only thing I can do to fix that is to reboot Firefox in [Safe Mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode) then reboot it again without the safe mode and it works for a while. You'll say to desactivate all of my addons to see if this bug is still here and the answer is yes. I don't think it's coming from my addons since I have the issue right now and I don't have any of my addons activated.

Here is my webpack's conf:

```js
var Encore = require('@symfony/webpack-encore');
var CopyWebpackPlugin = require('copy-webpack-plugin');

Encore
    // directory where compiled assets will be stored
    .setOutputPath('./web/built/frontend/')
    // public path used by the web server to access the output path
    .setPublicPath('/built/frontend/')

    .addEntry('core-tracking', [
        './assets/frontend/js/tracking.js',
        './assets/frontend/js/core.js',
    ])

    .addEntry('base', [
        './assets/frontend/js/entryPoints/commons.js',
        './assets/frontend/js/lang/fr.js',
        './assets/frontend/js/forms.js',
        './assets/frontend/js/trackingcontrol.js',
        './assets/frontend/js/billing-profile.js',
        './assets/frontend/js/base.js',
    ])

    //… more addEntry … 

    // When enabled, Webpack "splits" your files into smaller pieces for greater optimization.
    .splitEntryChunks()
    .enableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())

    .configureBabel(() => {}, {
        useBuiltIns: 'usage',
        corejs: 3
    })

    .enableSassLoader()

    .copyFiles([{
        from: './assets/frontend/img',
        pattern: /\.(png|jpg|jpeg|gif)$/,
        to: 'images/[path][name].[hash:8].[ext]'
    }, {
        from: './assets/frontend/img',
        pattern: /\.(svg)$/,
        to: 'images/[path][name].[ext]'
    }])

    .addPlugin(new CopyWebpackPlugin([
        { from: './node_modules/moment/moment.js', to: 'javascript/'},
        { from: './node_modules/moment/locale/fr.js', to: 'javascript/'},
        { from: './node_modules/chart.js/dist/Chart.min.js', to: 'javascript/'},
        { from: './node_modules/autosize/dist/autosize.min.js', to: 'javascript/'},
    ]))

    .autoProvidejQuery()

    .enableIntegrityHashes(Encore.isProduction())
;

const frontend = Encore.getWebpackConfig();

if (!Encore.isProduction()) {
    frontend.devtool = 'eval-source-map';
}

frontend.name = "frontend";

Encore.reset();

Encore
    .setOutputPath('./web/built/backend/')
    .setPublicPath('/built/backend/')
    .splitEntryChunks()
    .enableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())

    // … Some addEntry / addStyleEntry … 

    .addPlugin(new CopyWebpackPlugin([
        { from: './assets/backend/css/bootstrap-datepicker3.min.css', to: 'css/'},
        { from: './node_modules/select2/dist/css/select2.min.css', to: 'css/'},
        { from: './node_modules/select2/dist/js/select2.full.min.js', to: 'javascript/'},
        { from: './node_modules/autosize/dist/autosize.min.js', to: 'javascript/'},
        { from: './node_modules/taggle/src/taggle.js', to: 'javascript/'},
        { from: './assets/backend/js/*.js', to: 'javascript/', flatten: true},
    ]))

    .configureBabel(() => {}, {
        useBuiltIns: 'usage',
        corejs: 3
    })

    .copyFiles([{
        from: './assets/backend/images',
        pattern: /\.(png|jpg|jpeg|gif)$/,
        to: 'images/[path][name].[hash:8].[ext]'
    }])

    .enableSassLoader()

    .enableIntegrityHashes(Encore.isProduction())
;
const backend = Encore.getWebpackConfig();

backend.name = "backend";

module.exports = [frontend, backend];
```

```json
  "devDependencies": {
    "@symfony/webpack-encore": "^0.27.0",
    "babel-preset-es2015": "^6.24.1",
    "copy-webpack-plugin": "^5.0.3",
```

Does anyone have any clue on what's happening here?

Thank you for your answers.

Cheers!

**Comment by Kocal** [comment]
Hi 👋

Hum this is not an easy issue.
Do you have this problems on Chrome too? Did you tried with another Firefox version?
Does it happen for your backend and/or frontend entries?

What about removing this code: 
```js
if (!Encore.isProduction()) {
    frontend.devtool = 'eval-source-map';
}
```

?

**Comment by DaPo** [comment]
Yep, not easy at all. I'm not sure at all that's an issue from Encore neither from Webpack as it's indeed working fine with Chrome.

I tried with the main Firefox, Firefox Developer and Nightly and I have the same results for all of them.

I don't know about the backend entry because I'm not working a lot on the backend part. But I'll test it tomorrow.

About the `eval-source-map`, the bug was there before I test to change the devtool. But obviously with or without it won't change anything.

**Comment by DaPo** [comment]
Another proof that's something is very buggy here:

Firefox: 
![ss_ 1189](https://user-images.githubusercontent.com/1059657/73826500-28ccd800-47fe-11ea-83b1-7e72c5ffb2d3.jpg)

Chrome:
![ss_ 1190](https://user-images.githubusercontent.com/1059657/73826516-2d918c00-47fe-11ea-984b-fa7c5c33a754.jpg)

😭

**Comment by DaPo** [comment]
So I tried to make Firefox repair itself and I have no longer this issue, I guess I can close it.

**Comment by versedi** [comment]
> So I tried to make Firefox repair itself and I have no longer this issue, I guess I can close it.

By repair itself what process exactly do you mean?

I've seen the issue on both Firefox Dev Edition and Stable in office.
Switching to Chrome was a workaround, but an actual fix would be nice.

**Comment by DaPo** [comment]
> @DaPo By repair itself what process exactly do you mean?

[I mean this](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings).

I can't figure if the problem comes from Firefox itself that have a problem with sourceMaps or if it's Webpack or Encore that don't create sourceMaps that are good enough for Firefox or something else.

When I see this bug I repair Firefox and it's good to go waiting for the next time I see this bug.
