### ISSUE TITLE
Can we get a configureDevServer option?

### ISSUE THREAD

**Issue by hailwood** [symfony/webpack-encore#692]
We have a specific setup where we have the location to our webpack https key/cert in environment variables. This allows each developer to store them wherever the heck they want (these are mkcert keys so they're valid for localhost).

This means that in a normal webpack.config.js we have something like

```js
{
  devServer: {
    https: {
      key: process.env.WEBPACK_KEY ? fs.readFileSync(process.env.WEBPACK_KEY) : null,
      cert: process.env.WEBPACK_CERT ? fs.readFileSync(process.env.WEBPACK_CERT) : null,
    },
  }
}
```

And it works great.

Unfortunately encore relies on the presence of the `--https` flag to set urls and things.
Which means we end up using the `https` flag and doing something hacky like

```js
const encoreConfig = Encore.getWebpackConfig();
encoreConfig.devServer = {...encoreConfig.devServer, ...{
    https: {
      key: process.env.WEBPACK_KEY ? fs.readFileSync(process.env.WEBPACK_KEY) : null,
      cert: process.env.WEBPACK_CERT ? fs.readFileSync(process.env.WEBPACK_CERT) : null,
    },
}};
```

to merge in the custom webpack devServer config over the top of the encore devServer config.

It would feel much nicer if we had an option for 

```js
Encore.configureDevServer(config => {
    config.https = {
      key: process.env.WEBPACK_KEY ? fs.readFileSync(process.env.WEBPACK_KEY) : null,
      cert: process.env.WEBPACK_CERT ? fs.readFileSync(process.env.WEBPACK_CERT) : null,
    };
});
```

**Comment by Kocal** [comment]
Hi ✋ 

Yes I think it would be possible, and it would be a great new feature.

However we should be careful about the method `Encore.configureWatchOptions()` which configure watching options in watching mode and dev-server mode. 
Should `Encore.configureWatchOptions` be the last one to configure watching options? Can `Encore.configureDevServer()` takes the priority in dev-server mode?
