### ISSUE TITLE
Importing of JSON files not working.

### ISSUE THREAD

**Issue by bitterdev** [symfony/webpack-encore#699]
I'm using Webpack Encore version 0.28.2 (latest) which is using Webpack version 4.20.0. So loading JSON should work by default from the Webpack core (v >= 2). But i'm always getting compile errors like **This relative module was not found.**

My theory is that the build process of Encore doesn't copy the json files.

Even if importing JSON files should work by default i have tried to install the json-loader node module and use it the old way like described [here](https://github.com/webpack-contrib/json-loader). I have added to the loaders in Encore-Style like described [here](https://symfony.com/doc/current/frontend/encore/custom-loaders-plugins.html). But same result. It's not working.

Is that a bug or did i anything wrong?

**Comment by Lyrkan** [comment]
Hi @bitterdev,

I just tested it and it seems to work fine by default:

```js
// webpack.config.js
const Encore = require('@symfony/webpack-encore');

Encore
  .setOutputPath('build/')
  .setPublicPath('/')
  .enableSingleRuntimeChunk()
  .addEntry('app', './src/app.js')
  .cleanupOutputBeforeBuild()
;

module.exports = Encore.getWebpackConfig();
```

```js
// app.js
import * as data from './test.json';

console.warn(data);
```

```js
// test.json (excluding this line)
{
  "foo": "bar"
}
```

```
$ ./node_modules/.bin/encore production
Running webpack ...

 DONE  Compiled successfully in 1549ms

 I  2 files written to build
Entrypoint app = runtime.js app.js
Done in 2.65s.

$ cat build/app.js
(window.webpackJsonp=window.webpackJsonp||[]).push([["app"],{ng4s:function(n,s,o){"use strict";o.r(s);o("sIkd");var p=o.t("sIkd",1);console.warn(p)},sIkd:function(n){n.exports=JSON.parse('{"foo":"bar"}')}},[["ng4s","runtime"]]]);%
```

Would you be able to share a repro?

**Comment by bitterdev** [comment]
@Lyrkan this is strange. Your code is working and after i have removed all composer + node files in my project and reinstall them everything was working in my project too. I can't tell you what the problem was. I will close now. Thank you & Sorry.
