### ISSUE TITLE
[DX] Conditional asset referencing

### ISSUE THREAD

**Issue by scaytrase** [symfony/webpack-encore#7]
Consider the following part of the documentation:

http://symfony.com/doc/current/frontend/encore/simple-example.html#requiring-css-files-from-javascript

If we have a chain of requirements (i.e maybe including 3rd-parties) and some of the link in this chain requires a stylesheet - the stylesheet would be created, but we cannot know it until investigated the whole chain of requirements (or find out that `app.css` was generated occasionally). 

To resolve this some kind of `asset_exist` function could be introduced to check, whether the `app.css` file was generated and include it.

```patch
<link rel="stylesheet" href="{{ asset('build/global.css') }}">
+ {% if asset_exist('build/app.css') %}
+   <link rel="stylesheet" href="{{ asset('build/app.css') }}">
+ {% endif %}
```

This would allow to include this snippet unconditionally and when the file appears - it will work automatically

I'm know that this can be reported to Asset or TwigBridge component, but since I'm referencing the Encore documentation, I post it here first, maybe another solution would be suggested.

**Comment by stof** [comment]
you are asking for a feature in the Symfony Asset component. So this is the wrong place to ask. webpack-encore is a node.js package. It cannot provide a Twig function.

and btw, you're referencing the symfony documentation. This repo does not contain the frontend chapter of this doc either

**Comment by weaverryan** [comment]
I've thought about this exact Twig function for this exact reason. So, it at least has some merit :). Could you create an issue here: https://github.com/symfony/symfony and link to it from this issue?

Thanks!

**Comment by scaytrase** [comment]
@stof I've wrote the last paragraph especially for this comment, I was just suggesting a solution, a real solution could be be something else  not within Asset component

@weaverryan I'm glad that proposed idea is good, here is the issue https://github.com/symfony/symfony/issues/23163

**Comment by stof** [comment]
@scaytrase in any case, this cannot be solved in Encore. Twig runs in PHP and Encore is written in Node.js
