### ISSUE TITLE
Webpack Encore requires version ^5.3.0 of ts-loader. Your version 6.2.1 is too new. 

### ISSUE THREAD

**Issue by seyfer** [symfony/webpack-encore#703]
This issue is a proposal/request to update supported version for `ts-loader`

When using `ts-loader` in my webpack + encore setup
Getting this warning on webpack build

```
Webpack Encore requires version ^5.3.0 of ts-loader. Your version 6.2.1 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
```

**Expected**: Webpack Encore works with `ts-loader` v6+ without warnings.

**Comment by NikoGrano** [comment]
I've been running 7.0.5 without any problems.
