### ISSUE TITLE
Moderate vulnerability in JS dependency acorn <7.1.1

### ISSUE THREAD

**Issue by thibaut-decherit** [symfony/webpack-encore#706]
Regular Expression Denial of Service (as usual...)

https://www.npmjs.com/advisories/1488

**Comment by Kocal** [comment]
acorn is not a direct dependency of Encore, so I'm not sure we can/should do something about it.

**Comment by aarongerig** [comment]
For reference: https://github.com/webpack/webpack/issues/10516

**Comment by thibaut-decherit** [comment]
Upgrading to 6.4.1 (e.g. through `npm audit fix`) fixes the vulnerability.
I am therefore closing this issue.
