### ISSUE TITLE
Slow build with "yarn dev-server"

### ISSUE THREAD

**Issue by urkob** [symfony/webpack-encore#707]
Hi guys

I have also the problem with a slow build with `yarn dev-server`.
I believe it's the same or similar to #476 and #662 ...
Based on this two issues and the feedback of Lyrkan, I make a really simple reproducer (also with my events.json from ProfilingPlugin): https://github.com/urkob/slow_encore

<img width="571" alt="Screenshot" src="https://user-images.githubusercontent.com/59163427/76240876-4265a300-6234-11ea-8b82-5f5b332ce0b2.png">

It's that normal, that for so a relativ simple setup with a small admin template, the build time is around 12 or 13 seconds? When you say yes, it's okay. But when a project is growing... 

On my current project with this similar setup with 4 entrypoints (only one with the admin template) it needs 20 seconds.

Let me know if you need more information.

Thanks.

**Comment by Lyrkan** [comment]
Hi @urkob,

I think it is indeed a duplicate of #476. 

Your build time doesn't strike me as *really* odd though.

You have a full React + Material UI app there, which involves a lot of modules and files to read/parse/...

It doesn't really matter if you only have a few screens, the "big" dependencies you use have to be processed anyway.

You could probably gain some time by disabling source maps or changing their type (they currently account for 1/5th of your build time based on the events.json file) but you'll have to weight the pros and cons before doing so.

Also your screenshot only shows the first build, the next ones (for that same command) should probably be faster.

**Comment by urkob** [comment]
Hi @Lyrkan 

Thanks for your fast feedback, this is fine for me. 
So I'm on the right way and make nothing directly wrong.

So I know that a project with this dependencies are normal.

And yes, the next builds after the first ist really faster between 1000 and 5000ms.

I tried to read the events.json in Chrome, but I didn't get wiser :-) 
I will try and play a littel bit with the source maps and other types.

Thanks again!
