### ISSUE TITLE
addEntry with a core.js file will not compile as expected

### ISSUE THREAD

**Issue by DaPo** [symfony/webpack-encore#708]
Hi team,

I think I have a nice and lovely bug there. I'm not sure it's related to Webpack Encore itself but hey, why not.

So I have this file called core.js that I try to add to an entry as following:

```js
// webpack.config.js
var Encore = require('@symfony/webpack-encore');
Encore
    .addEntry('core-tracking', [
        './assets/frontend/js/tracking.js',
        './assets/frontend/js/core.js',
    ])
…
```

In the core.js I have some events on buttons and all. The weird part is that when I compile for my dev env everything with `$ encore dev` those events will not be attached to my elements as you can see:

![ss_ 1401](https://user-images.githubusercontent.com/1059657/76509723-c2685480-6450-11ea-85f1-9b366697787b.jpg)

But with the production compilation (`$ encore production --progress`) I see them

![ss_ 1402](https://user-images.githubusercontent.com/1059657/76509778-d6ac5180-6450-11ea-9401-7be40b51008a.jpg)

So I added some `console.log()` on my `core.js` and the fun fact is that I've never seen them on local but in prod they showed as expected.

And then a friend of mine suggested me to rename `core.js` into something else, so I did it:

```js
    .addEntry('legacy-tracking', [
        './assets/frontend/js/tracking.js',
        './assets/frontend/js/legacy.js',
    ])
```

And it works fine! 🎉 

So my guess is that Webpack is trying to compile `core-js` from node_modules in a first place and not my `core.js` file and that's why I've never seen my `console.log` in my dev environement.

I hope this issue is clear enough, please do tell me if you need more informations.

Cheers!

**Comment by Lyrkan** [comment]
Hi @DaPo,

That's... weird.
I tried to reproduce your issue with a minimal setup, but without any success:

```js
// webpack.config.js
const Encore = require('@symfony/webpack-encore');

Encore
  .disableSingleRuntimeChunk()
  .setOutputPath('build/')
  .setPublicPath('/')
  .addEntry('main', ['./assets/js/app.js', './assets/js/core.js'])
  .cleanupOutputBeforeBuild()
  .enableSourceMaps(false)
  .enableVersioning(Encore.isProduction())
  .configureBabel(() => {}, {
    useBuiltIns: 'usage',
    corejs: 3
  })
;
```

```js
// assets/js/app.js
console.log('app');
```

```js
// assets/js/core.js
console.log('core');
```

```
$ ./node_modules/.bin/encore dev
Running webpack ...

 DONE  Compiled successfully in 276ms

 I  1 files written to build
Entrypoint main = main.js

$ node build/main.js
app
core

$ ./node_modules/.bin/encore prod
Running webpack ...

 DONE  Compiled successfully in 951ms

 I  1 files written to build
Entrypoint main = main.09290499.js

$ node build/main.09290499.js
app
core
```

Would you be able to share your full `webpack.config.js` file, or even better, a repro?

**Comment by DaPo** [comment]
Hi @Lyrkan and thank you for your answer.

I think I have found something, please tell me if you can reproduce it on your side.

```js
// core.js
console.log('core file')
```

❌ `core-tracking` entry is not working as I don't see the console.log
```html
{{ encore_entry_script_tags('core-tracking', null, 'frontend') }}
```
```js
// webpack.config.js
    .addEntry('core-tracking', [
        './assets/frontend/js/core.js',
    ])
```

✅ `core` entry do work as I see the console.log
```html
{{ encore_entry_script_tags('core', null, 'frontend') }}
```
```js
// webpack.config.js
    .addEntry('core', [
        './assets/frontend/js/core.js',
    ])
```

Entries `core-pouet`, `internet-tracking`, `tracking-core` are working but not `core-tracking` at all.

🤔 

Please find my webpack.config.js [here](https://gist.github.com/DaPo/60f036c4081999db529100a579c85203).

**Comment by DaPo** [comment]
🙄 🙄 🙄 🙄 🙄 

I feel a little bit shamefull. It's ublock that is blocking the `core-tracking` file.

F*** me.

Please do accept my apologies as I wasted your time like this.

AFK buying a shame bell and do some GoT cosplay.

**Comment by Lyrkan** [comment]
No worries, I'm glad you figured it out :)
