### ISSUE TITLE
Concate and minify JS files

### ISSUE THREAD

**Issue by ZhuJo** [symfony/webpack-encore#712]
Hi, I'm using **webpack-merge-and-include-globally** (https://github.com/markshapiro/webpack-merge-and-include-globally) plugin in Encore to concate JS files as I need to use many variables globally which is not possible with webpack modules.

Anyway, this plugin works nicely for concatenating, but I'm not able at all to minify finalized JS file.
It has an option 'transform' to use minification plugin but Terser doesn't seem to work at all with it like:
`tranform: {
                'myfile.js': code => new TerserPlugin({include: 'myfile.js'}).minify(code).code
            }`

Is there any way to postpone minification until all plugins have finished their job and run Terser on generated JS file, while also renaming it with a hash in production?

**Comment by weaverryan** [comment]
Hey @ZhuJo!

I'm not sure :). But to help, you can see that Encore isn't doing anything particularly interesting with respect to JavaScript minimization. We're setting the `optimization.minimizer` option directly on Webpack (when you're building for production): https://github.com/symfony/webpack-encore/blob/bdf8ba46cc447c84ed2f4daf80c16122be191189/lib/config-generator.js#L491-L494 - the related function it calls doesn't set too many options: https://github.com/symfony/webpack-encore/blob/bdf8ba46cc447c84ed2f4daf80c16122be191189/lib/plugins/terser.js#L21-L25

So, I don't know :). But hopefully this might help you dive in and see what's going on :).

Good luck!
