### ISSUE TITLE
Configuring Preactjs in webpack.encore.js

### ISSUE THREAD

**Issue by DennisOluoch** [symfony/webpack-encore#716]
Hi guys! How can I enable this configuration from preactjs' webpack documentation in my webpack.config.js file? I've been trying to make preact to work but with no avail. Any information on how to work with preact js on symfony will highly be appreciated

`{
  "plugins": [
    ["@babel/plugin-transform-react-jsx", {
      "pragma": "h",
      "pragmaFrag": "Fragment",
    }]
  ]
}`

**Comment by Kocal** [comment]
Hi, you can use [`Encore.enablePreactPreset()`](https://github.com/symfony/webpack-encore/blob/master/index.js#L981-L1003)

**Comment by weaverryan** [comment]
Let us know if that helps!

**Comment by DennisOluoch** [comment]
> Hi, you can use [`Encore.enablePreactPreset()`](https://github.com/symfony/webpack-encore/blob/master/index.js#L981-L1003)
Apologies for the late reply but thanks! It worked

**Comment by Lyrkan** [comment]
Note that we currently don't set `pragmaFrag` though:

https://github.com/symfony/webpack-encore/blob/e773ddaf64d17c025559ca815aaa4e6ea0268e19/lib/loaders/babel.js#L84-L87
