### ISSUE TITLE
Alternative for method svgRule.uses.clear().

### ISSUE THREAD

**Issue by PatrykMaternicki** [symfony/webpack-encore#723]
Hi Hey Hello. In my project I use the CK Editor with Vue component. Of course I found the old post "How to merge vue configuration (this is needed to customize the ck editor) using encore methods". The encore works corectly. It create / loaded css file, svg etc. But i have problem with one plugin.
"ContextualBalloon"
Of course I found resolve. I have to add svgRule.uses.clear to my webpack config file. But there is alternative method in the encore? When I checked core i culdnt't find her.  Buti I wonder, is there an alternative method inside encore.

**Comment by Kocal** [comment]
Hi,

If you need to setup CKEditor (5 ?) with Webpack Encore, you can use read [this guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#webpack-encore).
It will maybe help you.

**Comment by PatrykMaternicki** [comment]
Thx man, now is working. But before I decide which library to use. I will try vue2editor. But, At first glance it easy to customize.
