### ISSUE TITLE
Error: webpack-cli tried to access webpack

### ISSUE THREAD

**Issue by fishbone1** [symfony/webpack-encore#730]
`yarn encore dev` crashes with this error:

```
Error: webpack-cli tried to access webpack (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: webpack (via "webpack")
Required by: webpack-cli@virtual:dc3fc578bfa5e06182a4d2be39ede0bc5b74940b1ffe0d70c26892ab140a4699787750fba175dc306292e80b4aa2c8c5f68c2a821e69b2c37e360c0dff36ff66#npm:3.3.11 (via /.../.yarn/$$virtual/webpack-cli-virtual-75e5f04c0a/0/cache/webpack-c
li-npm-3.3.11-f5481479b7-2.zip/node_modules/webpack-cli/bin/utils/)
```

I'm trying to setup webpack encore in a Symfony 4.4 project which is updated from 3.4. It doesn't use Flex yet.I followed the steps from the docs (https://symfony.com/doc/3.4/frontend/encore/installation.html)

```
composer require symfony/webpack-encore-bundle
yarn install
```` 

Of course this won't work, because there is no package.json. So I created a minimalistic package.json.

I also added webpack.config.js and continued:
```
yarn add @symfony/webpack-encore --dev
yarn encore dev
```

On the first run it requested to install "webpack-cli" and I confirmed:
```
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "yarn" to install the CLI via "yarn add -D".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'yarn add -D webpack-cli')...
```

After that and on subsequent runs it crashes with the error above.

Final package.json:

```
{
  "license": "UNLICENSED",
  "private": true,
  "devDependencies": {
    "@symfony/webpack-encore": "^0.28.3",
    "webpack-cli": "^3.3.11"
  }
}
```

**Comment by stof** [comment]
We should not require `webpack-cli` in your own project. `@symfony/webpack-encore` already requires it.

**Comment by Kocal** [comment]
That's really weird, I never had to install `webpack-cli` to use Encore...

Here is the `package.json` used by WebpackEncoreBundle recipe, if it can help you: https://github.com/symfony/recipes/blob/master/symfony/webpack-encore-bundle/1.0/package.json

You don't have to install `webpack-cli` yourself.

**Comment by weaverryan** [comment]
We take some shortcuts with our dependencies in Encore - requiring some packages *for* you so that you don't need to (this has pros and cons). 

What version of yarn are you using? Is it v1 or v2? It could be related

**Comment by fishbone1** [comment]
@Kocal The recipe's package.json causes the same effect.

@weaverryan I use v2 locally and v1 globally as recommended by yarn.

Do you install webpack-cli globally before? I don't and maybe this is the problem?

**Comment by stof** [comment]
This might be caused by the usage of yarn 2.

**Comment by Lyrkan** [comment]
@fishbone1 Do you also have an issue if you create a `.yarnrc.yml` file with the following content before running `yarn install`?

```
nodeLinker: node-modules
```

**Comment by fishbone1** [comment]
@stof You are right. It works with yarn 1. Maybe we should add a hint in the docs? I didn't realize that yarn 2 is new and it seems yarn 1 is still mainly used.

@Lyrkan I also tried your suggestion and it worked as well. But effectively it changes yarn to v1 as well. The original (non working) `.yarnrc.yml` looked like this:

```
yarnPath: ".yarn/releases/yarn-berry.js"
```

Thanks for your help!

**Comment by Lyrkan** [comment]
> I also tried your suggestion and it worked as well. But effectively it changes yarn to v1 as well. The original (non working) .yarnrc.yml looked like this:
> ```
> yarnPath: ".yarn/releases/yarn-berry.js"
> ```

You should be able to keep that `yarnPath` and use Yarn 2 with the `node-modules` plugin.
The issue is that Encore is not compatible with PnP yet (see https://github.com/symfony/webpack-encore/issues/655).

**Comment by DiFuks** [comment]
In pnp mode this can be solved by adding the following lines to yarnrc.yml

```yml
packageExtensions:
  webpack-dev-middleware@*:
    dependencies:
      webpack: "*"
```

**Comment by Kocal** [comment]
Can be closed.

**Comment by Nek-** [comment]
Hello, I just tried to install Encore v4 with yarn 3.0 and I got this error on build:

```
Error: @symfony/webpack-encore tried to access @babel/core (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.

Required package: @babel/core
Required by: @symfony/webpack-encore@virtual:dc3fc578bfa5e06182a4d2be39ede0bc5b74940b1ffe0d70c26892ab140a4699787750fba175dc306292e80b4aa2c8c5f68c2a821e69b2c37e360c0dff36ff66#npm:4.0.0 (via /home/manager-app/.yarn/__virtual__/@symfony-webpack-encore-virtual-7daadf3271/0/cache/@symfony-webpack-encore-npm-4.0.0-bf3fd0b2b4-03b2ac9391.zip/node_modules/@symfony/webpack-encore/lib/config/)
Ancestor breaking the chain: root-workspace-0b6124@workspace:.
```

**Comment by stof** [comment]
Encore v4 has a peer dependency on `@babel/core`, so yarn 3.0 would have shown you a warning during the installation if you did not include `@babel/core` in your dependencies as well.
