### ISSUE TITLE
Using SVG in scss becomes [object Module] in the build css file

### ISSUE THREAD

**Issue by lsv** [symfony/webpack-encore#735]
When I build with `npm run build`

My builded `build/app.css` file becomes `.foo{background-image:url([object Module])}`

And my `build/images/github.svg` file becomes

`module.exports = "data:image/svg+xml,%3Csvg width='155' height='155' xmlns='http://www.w3.org/2000/svg'%3E %3Cmetadata id='metadata8'%3....rule='nonzero' fill='%23ffffff'/%3E %3C/g%3E %3C/g%3E %3C/g%3E %3C/g%3E %3C/svg%3E"` 

Im not sure why this is happening.

I have tried with a complete default encore webpack config, then I tried some inline svg and then a svg-url-loader and added the respective loaders in the configuration for these, but all the time I have gotten `[object Module]` im not even sure if its a encore or a webpack problem.

I'm not getting any webpack build errors, so its only possible to see the error when you open the css file in the browser (or in the public/build folder)

* NPM: 6.14.4 
* @symfony/webpack-encore: 0.28.3
* Webpack: 4.42.1

My app.js file

```js
import '../css/app.scss';
```

and the scss file

```scss
.foo {
    background-image: url("../img/github.svg")
}
```

My assets structure

* assets/css/app.scss
* assets/js/app.js
* assets/img/github.svg

webpack.config.js

```js
var Encore = require('@symfony/webpack-encore');
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .addEntry('app', './assets/js/app.js')
    .splitEntryChunks()
    .enableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .configureBabelPresetEnv((config) => {
        config.useBuiltIns = 'usage';
        config.corejs = 3;
    })
    .enableSassLoader()
    .enableIntegrityHashes(Encore.isProduction())
    .addLoader({
        test: /\.svg$/,
        use: [
            {
                loader: 'svg-url-loader',
                options: {
                    limit: 10000,
                },
            },
        ],
    })
;

module.exports = Encore.getWebpackConfig();
```

**Comment by lsv** [comment]
I now tried adding a png to my scss file.

```scss
.foo {
    background-image: url("../img/github.svg")
}

.bar {
    background-image: url("../img/GitHub-Mark.png")
}
```

and it becomes

```
.bar,.foo{background-image:url([object Module])}
```

**Comment by Lyrkan** [comment]
Hi @lsv,

I'd say that's because `svg-url-loader` installs a recent version of `file-loader` when Encore 0.28 expects an old one.

You can either:

* Upgrade Encore to 0.29 since it is now shipped with `file-loader@6`
* Set the `esModule` option of `file-loader`/`url-loader` to `false` using `configureUrlLoader(...)`

**Comment by lsv** [comment]
Thanks, changed package.json to `"@symfony/webpack-encore": "^0.29"`
And now everything works.

**Comment by brettdorrans** [comment]
@Lyrkan I see the same issue using `@symfony/webpack-encore@^0.29` when loading fonts via a css import:

```
@font-face {
  src: url([object Module]);
}
```

`package-lock.json` has no reference to `file-loader` < 6.0 so I suspect this is BC break. Downgrading to `0.28` resolves the issue. The provided solution of switching `esModule` to false is non-ideal.

**Comment by Lyrkan** [comment]
@brettdorrans Would you be able to share your `package.json` file?

**Comment by brettdorrans** [comment]
@Lyrkan Sure, below:

```
"devDependencies": {
    "@fullhuman/postcss-purgecss": "^2.1.2",
    "@symfony/webpack-encore": "^0.29.0",
    "autoprefixer": "^9.7.6",
    "css-loader": "^2.1.1",
    "nodemon": "^2.0.3",
    "postcss-flexibility": "^2.0.0",
    "postcss-loader": "^3.0.0",
    "vue-loader": "^15.9.1",
    "vue-template-compiler": "^2.6.11",
    "webpack-notifier": "^1.8.0",
    "webpack-watch-files-plugin": "^1.0.3"
  },
  "dependencies": {
    "@fortawesome/fontawesome-pro": "^5.13.0",
    "axios": "^0.19.2",
    "regenerator-runtime": "^0.13.3",
    "tailwindcss": "^1.2.0",
    "vue": "^2.6.11",
    "vue-router": "^3.1.6",
    "vuex": "^3.2.0",
    "vuex-map-fields": "^1.4.0"
  }
```

**Comment by Lyrkan** [comment]
> Gonna try upgrading css-loader, this may be the solution now I look at this.

That's probably the issue yes... you are not supposed to have it in your `package.json` though since it is already provided by Encore.
