### ISSUE TITLE
mini-css-extract-plugin is totally outdated

### ISSUE THREAD

**Issue by stof** [symfony/webpack-encore#742]
We currently force installing at most mini-css-extract-plugin@0.4.2, which is from 2018. Latest version is 0.9.0.

**Comment by Lyrkan** [comment]
I already tried to update it in https://github.com/symfony/webpack-encore/pull/564 but for some reason it came with inconsistent hashes in filenames.

It seems to be fixed when used with Webpack 5 so it will probably be updated once https://github.com/symfony/webpack-encore/pull/645 is released.

**Comment by stof** [comment]
this has been updated in the meantime
