### ISSUE TITLE
Error on installing webpack-encore SYMFONY 5.0.8

### ISSUE THREAD

**Issue by Pillouhabsom** [symfony/webpack-encore#745]
When trying to install , i'm getting this error !
Can anyone explain what this means ?

> Using version ^1.7 for symfony/webpack-encore-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

> 
>   Problem 1
>     - The requested package symfony/asset (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/asset[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 2
>     - The requested package symfony/console (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/console[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 3
>     - The requested package symfony/dotenv (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/dotenv[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 4
>     - The requested package symfony/expression-language (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/expression-language[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 5
>     - The requested package symfony/form (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/form[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 6
>     - The requested package symfony/framework-bundle (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/framework-bundle[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 7
>     - The requested package symfony/process (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/process[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 8
>     - The requested package symfony/security-bundle (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/security-bundle[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 9
>     - The requested package symfony/translation (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/translation[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 10
>     - The requested package symfony/twig-bundle (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/twig-bundle[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 11
>     - The requested package symfony/validator (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/validator[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 12
>     - The requested package symfony/web-link (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/web-link[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 13
>     - The requested package symfony/yaml (locked at v5.0.8, required as 4.0.*) is satisfiable by symfony/yaml[v5.0.8] but these conflict with your requirements or minimum-stability.
>   Problem 14
>     - The requested package symfony/web-server-bundle (locked at v4.4.8, required as 4.0.*) is satisfiable by symfony/web-server-bundle[v4.4.8] but these conflict with your requirements or minimum-stability.
>   Problem 15
>     - doctrine/doctrine-bundle 2.0.8 requires symfony/console ^3.4.30|^4.3.3|^5.0 -> satisfiable by symfony/console[3.4.x-dev, 4.3.x-dev, 4.4.x-dev, 5.0.x-dev, 5.1.x-dev, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.40, v4.3.10, v4.3.11, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8] but these conflict with your requirements or minimum-stability.
>     - doctrine/doctrine-bundle 2.0.8 requires symfony/console ^3.4.30|^4.3.3|^5.0 -> satisfiable by symfony/console[3.4.x-dev, 4.3.x-dev, 4.4.x-dev, 5.0.x-dev, 5.1.x-dev, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.40, v4.3.10, v4.3.11, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8] but these conflict with your requirements or minimum-stability.
>     - doctrine/doctrine-bundle 2.0.8 requires symfony/console ^3.4.30|^4.3.3|^5.0 -> satisfiable by symfony/console[3.4.x-dev, 4.3.x-dev, 4.4.x-dev, 5.0.x-dev, 5.1.x-dev, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.40, v4.3.10, v4.3.11, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8] but these conflict with your requirements or minimum-stability.
>     - Installation request for doctrine/doctrine-bundle (locked at 2.0.8) -> satisfiable by 

> doctrine/doctrine-bundle[2.0.8].

**Comment by weaverryan** [comment]
Hi!

I'm not sure what the problem is - but I'm pretty sure it's not relate to Encore. The problem is happening when you install the bundle - https://github.com/symfony/webpack-encore-bundle - but it's dependency requirements are *very* loose. The `locked at v5.0.8, required as 4.0.` looks VERY strange to me.

Cheers!
