### ISSUE TITLE
sass-loader image uri with fragment identifier is cut off

### ISSUE THREAD

**Issue by ampaze** [symfony/webpack-encore#755]
I have a problem with the path replacement in sass/scss files and I have no idea which part of the sass handling is actually messing up. 

In my SCSS/CSS I have the line

```scss
background: url('../../frontend/img/icons.svg#css-r-arrow-fcfcfc');
```
When using `.enableSassLoader()` and a scss file, the above line is turned into

```css
background: url(/build/images/icons.f3ff22ad.svg);
```

which is wrong, as the fragment identifier **#css-r-arrow-fcfcfc** is needed.

When not using sass (e.g. a css file) the replacement is actually correct

```css
background: url(/build/images/icons.f3ff22ad.svg#css-r-arrow-fcfcfc);
```
so apparently sass-loader is doing something different with replacements?

I don't know if this is a encore, webpack, node-sass or sass-loader problem, so any help would be appreciated.

----
package.json
```json
    "devDependencies": {
        "@symfony/webpack-encore": "^0.29.1",
        "node-sass": "^4.14.1",
        "sass-loader": "^7.3.1"
    },
```

**Comment by Lyrkan** [comment]
Hi @ampaze,

Could you try this?

```js
Encore.enableSassLoader(() => {}, {
  resolveUrlLoaderOptions: {
    keepQuery: true
  }
});
```

**Comment by ampaze** [comment]
Hi @Lyrkan,

this works! Thank you.

----

Maybe the name of the option should be changed to **keepQueryAndFragment** 🤔

**Comment by Lyrkan** [comment]
> Maybe the name of the option should be changed to keepQueryAndFragment 🤔

That would have to be a suggestion for the [`resolve-url-loader`](https://github.com/bholloway/resolve-url-loader/blob/master/packages/resolve-url-loader/README.md#options) ^^'
