### ISSUE TITLE
React + TypeScript + CSS modules

### ISSUE THREAD

**Issue by plashenkov** [symfony/webpack-encore#766]
Hi!

I'm trying to use Encore + TypeScript + React + CSS modules. Everything works if to use the syntax:
```ts
const styles = require('./index.scss'); // Works
```
But it's not possible to use this syntax:
```ts
import styles from './index.scss'; // Not working :'(
```
I get the error: `TS2307: Cannot find module './index.scss'.`

What can be done to solve the issue? I will be glad of any even a little information. Thank you!

---

For reference.
This is my `tsconfig.json`:
```json
{
    "compilerOptions": {
        "jsx": "react",
        "esModuleInterop": true
    }
}
```

This is my `webpack.config.js`:
```js
const Encore = require('@symfony/webpack-encore');

if (!Encore.isRuntimeEnvironmentConfigured()) {
  Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

function newEncore(reset = true) {
  reset && Encore.reset();

  return Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .splitEntryChunks()
    .enableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .enableTypeScriptLoader()
    .enableSassLoader()
    .configureCssLoader(config => {
      config.modules = true;
    })
    .configureBabelPresetEnv(config => {
      config.useBuiltIns = 'usage';
      config.corejs = 3;
    });
}

module.exports = [
  newEncore(false)
    .addEntry('website/layout', './assets/js/website/layout.tsx')
    .addEntry('website/pages/index', './assets/js/website/pages/index.tsx')
    // ...
    .getWebpackConfig(),

  newEncore()
    .addEntry('admin/admin', './assets/js/admin/admin.tsx')
    .getWebpackConfig(),
];
```

**Comment by Kocal** [comment]
Hi!
I don't really know how CSS Modules really works with Scss/CSS in Encore, but I remember I had to use `import styles from `./index.scss?module` - without updating the default Encore configuration - to make them working when using Vue+JSX.

Does it work for you?

**Comment by weaverryan** [comment]
I don't know much about this specific situation either, but it seems like a bug, or at least "not ideal user experience".

**Comment by plashenkov** [comment]
Thanks for your replies!

> I had to use import styles from ./index.scss?module - without updating the default Encore configuration - to make them working when using Vue+JSX.

This works for JS and JSX, but not for TypeScript. It seems like TypeScript uses its own `import` mechanism and we need to consider its features.

I've found these two libraries which are addressed to fix this behavior:
- https://github.com/Jimdo/typings-for-css-modules-loader
- https://github.com/TeamSupercell/typings-for-css-modules-loader

They should be used instead of webpack css-loader in order to CSS modules be processed in TypeScript via `import`. But I haven't found the easy way to substitute css-loader in Encore with this custom loader. It looks it is hardcoded inside Encore. I've also tried to update webpack config (after `Encore.getWebpackConfig()`) but it looks it's not easy as well.

But here is another library:
- https://github.com/mrmckeb/typescript-plugin-css-modules

It acts as a TypeScript plugin. You need to:
1. Install it:
   ```bash
   npm install -D typescript-plugin-css-modules`
   ```
2. Turn on this plugin inside `tsconfig.json`:
   ```json
   {
     "compilerOptions": {
       "plugins": [
         { "name": "typescript-plugin-css-modules" }
       ]
     }
   }
   ```
3. Add custom definitions (`custom.d.ts`) file somewhere inside your project:
   ```typescript
   declare module '*.module.css' {
     const classes: { [key: string]: string };
     export default classes;
   }

   declare module '*.module.scss' {
     const classes: { [key: string]: string };
     export default classes;
   }
   ```
4. Use `filename.module.css` name for CSS files you use as CSS modules (this naming can be configured inside `tsconfig.json`).

And it seems everything works.
But custom definitions work like magic for me. I think this is due to I am new to TypeScript. The custom definitions file can be named freely: `custom.d.ts`, `global.d.ts` or even `woohoo.d.ts`. And even `*.d.ts` extension is not necessary and you can use simply `*.ts`. The following thing looks like black magic to me: this file can be placed in any subfolder of your project. For example, I can place it under `var/log` of Symfony project or event any other deep directory (I tried to move it deep inside `vendor` directory, it's an inappropriate place for this file) — and it works somehow. If to delete this file, it doesn't. I do not know how this works. It looks like TypeScript scans all the directory tree of the project. Hm...

**Comment by plashenkov** [comment]
Okay, it looks like it is a good idea to add to `tsconfig.json`:
```js
{
    // ...
    "include": [
        "assets/**/*"
    ]
}
```
Since all our frontend sources are located inside `assets` folder we do not need TypeScript to search files through all project directories. This will narrow down searching only inside `assets` folder. It's a good idea to make folder `types` or `@types` somewhere inside `assets` and place all custom definitions there. Since many JS (not TS) libs do not have custom definitions and sometimes you may want to write them manually, it's a good idea to separate them into files named after concrete libraries. If we add definitions for `typescript-plugin-css-modules`, we can name the file `typescript-plugin-css-modules.d.ts` and place it under `assets/@types` directory.

Let's close this issue now. I hope the above information will be useful for users who search about using CSS modules with TypeScript and Encore.
