### ISSUE TITLE
--watch failed detect modification on shared mount folder

### ISSUE THREAD

**Issue by filoucrackeur** [symfony/webpack-encore#767]
i'm in VM my symfony folder is shared mount folder when i modify a file from host it is well modify inside mounted volume in VM but the watcher not detect any modifications

i want live reload in my VM when i save file on host

command line is executed from VM 

 yarn encore dev-server --https --host=localhost --watch

**Comment by Kocal** [comment]
You need to enable polling to make watching mode working in a VM.

See https://symfony.com/doc/current/frontend/encore/virtual-machine.html#file-watching-issues

**Comment by stof** [comment]
I'm closing this issue, as the solution has been given.
