### ISSUE TITLE
Provide a possibility to configure resolve.modules

### ISSUE THREAD

**Issue by plashenkov** [symfony/webpack-encore#768]
Hi!

We already have a possibility to configure `resolve.aliases` by using `Encore.addAliases()` method. But we do not have a method to configure `resolve.modules`.

Why `resolve.modules` are useful? They allow us to use non-relative paths in imports. For example, we import some JS component from current JS file and use a relative path for that:

```js
import MyComponent from '../../../components/MyComponent';
```

But if we move this current file to another folder, we have to respectively update all these paths in imports, which can be pity. But if we add our `assets` folder to `resolve.modules`, we can easily write:

```js
import MyComponent from 'components/MyComponent';
```

Which is more simple and clear.

Currently we can use this code as a workaround:

```js
const config = Encore.getWebpackConfig();
config.resolve.modules = ['assets', 'node_modules'];
module.exports = config;
```

But something like this would be nicer:

```js
Encore.addResolveDirs(['assets']);
```

**Comment by plashenkov** [comment]
In case you will find this idea sensible, some thoughts:

It would be even great to have `assets` folder already included in `resolve.modules` by default. But... Encore can be used outside of Symfony and frontend sources dir can be any... so maybe it's not possible. Also adding `assets` by default can break BC because if `assets` folder is specified before `node_modules`, dependencies which exist inside both `assets` and `node_modules` and have similar path will be imported from the first one, `assets`.

The second note: it's better to use absolute paths here:
```js
const path = require('path');
resolve.modules = [path.resolve(__dirname, 'assets'), 'node_modules'];
```
Since absolute and relative paths behave differently (https://webpack.js.org/configuration/resolve/#resolvemodules).

Thanks, hope this will be useful.

**Comment by Kocal** [comment]
Hi!

I don't really understand the issue, or maybe why you don't want to use an alias.

Does the following configuration not working for you?:
```js
const path = require('path');

Encore
  .addAliases({
    '@components': path.resolve(__dirname, 'assets/components') 
  })
```

and use imports like this:
```js
import MyComponent from '@components/MyComponent';
```

?

**Comment by plashenkov** [comment]
We can have many folders, not just one. Do you suggest to add all of them manually? :)

**Comment by Kocal** [comment]
Yup, or add a _generic_ alias `@app` and use `@app/components`, IDK.

**Comment by plashenkov** [comment]
Yep, thank you, the second option will definitely work, though it's not exactly the same thing.

When using TypeScript (I haven't tested for JS case) IDE (PhpStorm in my case) cannot resolve these paths. But there is a similar option in `tsconfig.json`:

```json
{
    "compilerOptions": {
        "baseUrl": "./assets"
    }
}
```

Combining `compilerOptions.baseUrl` with `resolve.modules` of Webpack gives exactly the right result.

Well, adding or not adding `Encore.addResolveDirs()` (or something like that) to Encore interface is up to you for sure. My task is to share the idea. So... :)

**Comment by plashenkov** [comment]
Well, I've found similar option for aliases. `tsconfig.json`:

```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@app/*": ["assets/*"]
        }
    }
}
```

**Comment by plashenkov** [comment]
I've found one more absolutely beautiful way:

```bash
npm install -D tsconfig-paths-webpack-plugin
```

Then in `webpack.config.js`:

```js
const Encore = require('@symfony/webpack-encore');
const TSConfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

// Setting Encore options here

const config = Encore.getWebpackConfig();
config.resolve.plugins = [new TSConfigPathsPlugin];

module.exports = config;
```

This wonderful plugin automatically copies all `tsconfig.json` `compilerOptions.paths` to Webpack `resolve.aliases`, as well as adds `tsconfig.json` `compilerOptions.baseUrl` to Webpack `resolve.modules`. I.e. it does everything we need.

**Comment by plashenkov** [comment]
Thank you for your attention @Kocal, I'll close this issue. It looks that adding special methods for managing WebPack `resolve.modules` is unnecessary now.
