### ISSUE TITLE
Add Symfony Flex Recipe

### ISSUE THREAD

**Issue by weaverryan** [symfony/webpack-encore#77]
https://github.com/symfony/recipes

**Comment by stof** [comment]
this looks weird to me, as webpack-encore has nothing to do with composer. It is installed through Yarn or npm.

**Comment by javiereguiluz** [comment]
I guess the idea is to create a package that creates the initial `package.json` requiring Webpack Encore, an empty `assets/` dir and a minimal initial `webpack.config.js` file. After the installation, a message would explain you to execute some yarn/npm command to complete the Encore installation.

**Comment by javiereguiluz** [comment]
A proposal of this recipe has been created: https://github.com/symfony/recipes/pull/108
