### ISSUE TITLE
Error: Missing class properties transform.

### ISSUE THREAD

**Issue by Rmy5** [symfony/webpack-encore#777]
Hi,

I have a very simple class:

```
class AbstractClass {

    _myProperty;

    myMethod() {
          // do something
    }
}

export default AbstractClass;
```
 And another class that extends the first one:

```
import AbstractClass from "./AbstractClass";


class ChildClass extends AbstractClass {

    constructor() {
        super();
        // this._myProperty = 'my shiny property';
    }
}

export default ChildClass;
```

But I'm getting this error:

bootstrap 4e4ad9c501ef5a98a3b1:62 Uncaught Error: Module build failed: SyntaxError: Missing class properties transform.

[0m [90m 3 | [39m[36mclass[39m [33mAbstractStatsModel[39m {
 [90m 4 | [39m
[31m[1m>[22m[39m[90m 5 | [39m    _statsUrl[33m;[39m
 [90m   | [39m    [31m[1m^[22m[39m
 [90m 6 | [39m
 [90m 7 | [39m    constructor() {
 [90m 8 | [39m        [90m// if (this.constructor === AbstractStatsModel) {[39m[0m

    at Object../assets/js/AbstractStatsModel.js (bootstrap 4e4ad9c501ef5a98a3b1:62)
    at __webpack_require__ (bootstrap 4e4ad9c501ef5a98a3b1:19)
    at Object../assets/js/SspModel.js (bootstrap 4e4ad9c501ef5a98a3b1:62)
    at __webpack_require__ (bootstrap 4e4ad9c501ef5a98a3b1:19)
    at Object../assets/js/ssp.js (ssp.js:1)
    at __webpack_require__ (bootstrap 4e4ad9c501ef5a98a3b1:19)
    at bootstrap 4e4ad9c501ef5a98a3b1:62
    at bootstrap 4e4ad9c501ef5a98a3b1:62
./assets/js/AbstractStatsModel.js @ bootstrap 4e4ad9c501ef5a98a3b1:62
__webpack_require__ @ bootstrap 4e4ad9c501ef5a98a3b1:19
./assets/js/SspModel.js @ bootstrap 4e4ad9c501ef5a98a3b1:62
__webpack_require__ @ bootstrap 4e4ad9c501ef5a98a3b1:19
./assets/js/ssp.js @ ssp.js:1
__webpack_require__ @ bootstrap 4e4ad9c501ef5a98a3b1:19
(anonymous) @ bootstrap 4e4ad9c501ef5a98a3b1:62
(anonymous) @ bootstrap 4e4ad9c501ef5a98a3b1:62

Which I don't really understand.
It looks like I'm missing class property transform ?

I have the same message in encore dev --watch console:

<img width="648" alt="cap" src="https://user-images.githubusercontent.com/30668074/82891544-398c8f80-9f4e-11ea-932f-b9965d4f086f.png">

This is my webpack config:

```
var Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')


    .addEntry('js/ssp', './assets/js/ssp.js')
    .addStyleEntry('css/app', ['./assets/scss/app/app.scss'])


    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())

    .enableVersioning(Encore.isProduction())


    .enableSassLoader()

;
module.exports = Encore.getWebpackConfig();
```

The only info I found about this error was a Babel related error, but I don't have that in my dependencies.

**Comment by Kocal** [comment]
Encore is using Babel to transpile your files, so the error is legit.

If you want to use class properties, you must install [`@babel/plugin-proposal-class-properties`](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) and configure Babel:

```js
Encore
  // ...
  
  .configureBabel((config) => {
    config.plugins.push('@babel/plugin-proposal-class-properties')
  })
```

**Comment by Rmy5** [comment]
Ah I see.

If I install  [@babel/plugin-proposal-class-properties](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) only encore seems to be missing https://babeljs.io/docs/en/babel-plugin-proposal-class-properties '@babel/core'. So I guess I have to install '@babel/core' to ?

**Comment by Rmy5** [comment]
This solved it in my case:

`yarn add --dev babel-plugin-transform-class-properties babel-plugin-transform-object-rest-spread`

```
Encore
// ...

.configureBabel(function(babelConfig) {
    //This is needed.
    babelConfig.plugins = ["transform-object-rest-spread","transform-class-properties"]
})
```

Then Babel also handles assignment of arrow functions: `const someHandler = () => {};`

**Comment by Kocal** [comment]
Hum, which version of Encore do you use?

**Comment by Rmy5** [comment]
From yarn dependencies => @symfony/webpack-encore: 0.20.1
From composer dependencies => symfony/webpack-encore-bundle: 1.5

**Comment by Kocal** [comment]
Ah! That's very old, it has been released [more than 2 years ago](https://github.com/symfony/webpack-encore/releases/tag/v0.20.1) :(

**Comment by stof** [comment]
The latest encore release is 0.30.2

**Comment by Rmy5** [comment]
Mmh, yes. I am planning on upgrading my Symfony app to LTS version 4.4 (now on 4.2). I'm not sure wether I can upgrade only the Webpack-Encore bundle to latest, or even only the yarn dependency. I'll have a try.
