### ISSUE TITLE
Trying to use @babel/plugin-proposal-decorators but getting an error

### ISSUE THREAD

**Issue by dingo-d** [symfony/webpack-encore#778]
I'm trying to use [decko](https://github.com/developit/decko) package in my JS files, but I was getting an error that pointed to the `@bind` decorator. So I tried installing `@babel/plugin-proposal-decorators`, and in my `webpack.config.js` I've added

```js
.configureBabel(function (babelConfig) {
  babelConfig.plugins.push('@babel/plugin-proposal-decorators');
})
```

But I'm getting an error

```bash
Syntax Error: Error: [BABEL] /symfony-project/assets/js/app.js: The decorators plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you want to use the legacy decorators semantics, you can set the 'legacy: true' option. (While processing: "/symfony-project/node_modules/@babel/plugin-proposal-decorators/lib/index.js")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at cachedFunction.next (<anonymous>)
    at loadPluginDescriptor.next (<anonymous>)
    at recurseDescriptors.next (<anonymous>)
    at loadFullConfig.next (<anonymous>)
    at transform.next (<anonymous>)
```

But adding options after the callback doesn't work, as it only allows `exclude`, `useBuiltIns`, `corejs`, `includeNodeModules` as keys.

How can I pass options to the plugin, without adding a `.babelrc` file or `babel.config.js` file (trying to avoid [this issue](https://symfony.com/doc/current/frontend/encore/babel.html#creating-a-babelrc-file))?

**Comment by Kocal** [comment]
I think you can use this:
```js
.configureBabel(function (babelConfig) {
  babelConfig.plugins.push(['@babel/plugin-proposal-decorators', {
    decoratorsBeforeExport: true or false
  }]);
})
```

**Comment by dingo-d** [comment]
Yup, just tried this myself and it worked 😅  

Thanks for the answer 👍
