### ISSUE TITLE
Add ability to set esModule option for url-loader and file-loader

### ISSUE THREAD

**Issue by a-menshchikov** [symfony/webpack-encore#779]
Without `esModule: false` there is not ability to use relative paths or paths with aliases in vue templates, e.g. `<img src="@/images/file.png">` where `@` is an alias for /assets directory.

**Comment by Kocal** [comment]
That's weird, I thought this was supported. :thinking: 

You can use:
```js
Encore
  .configureUrlLoader({
    images: {
      esModule: false
    }
  })
```

See #743 for more information

**Comment by a-menshchikov** [comment]
@Kocal thanks, you are right. That's my mistake.
