### ISSUE TITLE
Cannot find module 'pkg-up'

### ISSUE THREAD

**Issue by UtechtDustin** [symfony/webpack-encore#783]
Hello,

today i created a new project and i added the encore module.
I just followed the [instructions](https://symfony.com/doc/current/frontend/encore/installation.html) (composer require symfony/webpack-encore-bundle && yarn install).

But if i try to use the watch command (`yarn encore watch`), i get the following error message:

```
yarn run v1.22.4
$ /home/dustin/git/domain.de/public/vendor/.bin/encore watch
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module 'pkg-up'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/dustin/git/domain.de/public/vendor/@symfony/webpack-encore/lib/config/parse-runtime.js:13:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
I get this error after run yarn encore watch . I installed encore some minutes ago. (bearbeitet) 
```

I already tried to install the pkg-up module via yarn, but i still get the same error message.
Also i deleted the node_module folder (or in my case the vendor folder (moved to the public folder)) and reinstalled it, but i still get the same error.

My package.json looks like that:

```
{
    "devDependencies": {
        "@symfony/webpack-encore": "^0.30.0",
        "core-js": "^3.0.0",
        "regenerator-runtime": "^0.13.2",
        "webpack-notifier": "^1.6.0"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production --progress"
    },
    "dependencies": {
        "bootstrap": "^4.5.0",
        "font-awesome": "^4.7.0",
        "jquery": "^3.5.1",
        "popper.js": "^1.16.1",
        "tether": "^1.4.7"
    }
}
```

Btw. i already asked on the symfony slack, but nobody could help me :/

**Comment by Kocal** [comment]
Are you behing a firewall or something?

**Comment by UtechtDustin** [comment]
@Kocal No im not :-)

**Comment by Kocal** [comment]
What happens if you run `yarn why pkg-up`? 
What's inside in your `yarn.lock`? Does `pkg-up` appear?

**Comment by UtechtDustin** [comment]
Yes he found it.

`yarn why pkg-up`
```
yarn why v1.22.4
[1/4] Why do we have the module "pkg-up"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "pkg-up@3.1.0"
info Reasons this module exists
   - "@symfony#webpack-encore" depends on it
   - Hoisted from "@symfony#webpack-encore#pkg-up"
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "36KB"
info Disk size with transitive dependencies: "124KB"
info Number of shared dependencies: 6
=> Found "browserslist#pkg-up@2.0.0"
info This module exists because "@symfony#webpack-encore#@babel#preset-env#browserslist" depends on it.
info Disk size without dependencies: "16KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "120KB"
info Number of shared dependencies: 6
Done in 0.33s.
```

The part of the yarn.lock:
```
pkg-up@^3.1.0:
  version "3.1.0"
  resolved "https://registry.yarnpkg.com/pkg-up/-/pkg-up-3.1.0.tgz#100ec235cc150e4fd42519412596a28512a0def5"
  integrity sha512-nDywThFk1i4BQK4twPQ6TA4RT8bDY96yeuCVBWL3ePARCiEKDRSrNGbFIgUJpLp+XeIR65v8ra7WuJOFUBtkMA==
  dependencies:
    find-up "^3.0.0"
```

**Comment by UtechtDustin** [comment]
@Kocal I found out why i get that error.
I use a `.yarnrc` file to move the node_modules folder to the public folder.

`.yarnrc`
```
--modules-folder public/vendor
```

Is there a way to use `--modules-folder` with encore ?

**Comment by UtechtDustin** [comment]
Yea i also think i can remove the `.yarnrc` file.
On other projects which are older and dont use webpack, i often move the folder to the public folder so i can access the files directly.

Thanks for your help :+1:

**Comment by stof** [comment]
exposing all node_modules dependencies to the web might not be a good idea (even though web servers won't automatically run JS files with node, so I don't think it is as critical as exposing the composer `vendor` folder holding PHP files)

**Comment by UtechtDustin** [comment]
Dont worry about that, i know it.
The most of my project are privat projects so the exposed node_modules folder is no critial security issue :-)

But thanks for the information.
