### ISSUE TITLE
"webpack not installed" error, assets not compiling

### ISSUE THREAD

**Issue by opdavies** [symfony/webpack-encore#787]
I've tried switching my Drupal theme configuration to use Encore. According to my `package-lock.json` I have `0.30.2` installed.

When I try and run `npm run dev` aka `encore dev`, I get the following error:

```plain
> encore dev

Running webpack ...

webpack not installed

Install webpack to start bundling: 
  $ npm install --save-dev webpack
```

I don't recall needing to add webpack itself as a dependency when I've used Encore previously.

I've removed my `package-lock.json` file and get the same after another `npm install`.

I also get the same when trying with yarn.

If I do add webpack manually as the error suggests, then I get this warning but the assets do compile:

```plain
> encore dev

Running webpack ...

  WARNING   Webpack is already provided by Webpack Encore, also adding it to your package.json file may cause issues.
```

Is this a bug in Encore, or something wrong in the way that I've set it up this time?

**Comment by Kocal** [comment]
Did you try to remove your `node_modules/` too?
What is inside your `package.json`?

**Comment by opdavies** [comment]
> Did you try to remove your node_modules/ too?

I did at some point during my debugging, though I've just ran `rm -fr package-lock.json node_modules` again and it seems to be working after another `npm i && npm run dev`. Strange!

> What is inside your package.json?

```json
{
  "private": true,
  "scripts": {
    "dev": "encore dev",
    "prod": "NODE_ENV=production encore production",
    "watch": "encore dev --watch"
  },
  "devDependencies": {
    "@symfony/webpack-encore": "^0.30.2",
    "alpinejs": "^2.3.5",
    "autoprefixer": "^9.8.0",
    "highlightjs": "^9.16.2",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^3.0.0",
    "postcss-nested": "^4.2.1",
    "tailwindcss": "^1.4.6"
  }
}
```

I'll close the issue, and re-open if I see it again.

**Comment by opdavies** [comment]
Thanks @Kocal.
