### ISSUE TITLE
Make UglifyJsPlugin optional/configurable

### ISSUE THREAD

**Issue by allfreelancers** [symfony/webpack-encore#79]
HI!
// todo - options here should be configurable
new webpack.optimize.UglifyJsPlugin({
      sourceMap: this.webpackConfig.useSourceMaps
})

Can you make it optional/configurable? I have an error:
app.b452c69496e2c9f0cbd2.js from UglifyJs

**Comment by stof** [comment]
what is the error message you get ?

**Comment by allfreelancers** [comment]
Error :
app.8eaba82891470d4ca570.js from UglifyJs
Unexpected token: punc (() [app.8eaba82891470d4ca570.js:204,8]


The solution of the problem is possible:
https://github.com/webpack/webpack/issues/1542

**Comment by stof** [comment]
yeah, UglifyJS currently does not support minifying ES6 code. You need to transpile it to ES5 with Babel first.

**Comment by weaverryan** [comment]
Closing - see #139 also for more details

**Comment by Goatfried** [comment]
For anyone else that comes here looking for a solution:
If you use babel-preset-env, set the option [targets.uglify](https://babeljs.io/docs/plugins/preset-env/#optionstargets-uglify) to true in your babel presets.
