### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by Romaixn** [symfony/webpack-encore#792]
Hello,
I have a error after upgrading to the latest version of webpack-encore and Symfony.

This error : 
```
application/node_modules/assets-webpack-plugin/node_modules/camelcase/index.js:69
		.replace(/[_.\- ]+([\p{Alpha}\p{N}_]|$)/gu, (_, p1) => p1.toLocaleUpperCase())
		^
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape
```

Has anyone ever made that error before?

**Comment by stof** [comment]
Which version of Node are you using ?

**Comment by Romaixn** [comment]
> Which version of Node are you using ?

`v8.14.0`

**Comment by Kocal** [comment]
Encore does not support Node 8 anymore, it [supports Node >= 10.13.0](https://github.com/symfony/webpack-encore/blob/master/package.json#L24).

**Comment by felipe-NR** [comment]
BEIJO
