### ISSUE TITLE
Add ability to add 'tsx?' in test option for eslint rule

### ISSUE THREAD

**Issue by a-menshchikov** [symfony/webpack-encore#794]
Now there is the only one way to add 'tsx?' test option for eslint rule — by the following code:
```
.configureLoaderRule('eslint', rule => {
    rule.test = new RegExp(`\\.(${['jsx?', 'tsx?', 'vue'].join('|')})$`)
})
```

I think it should be an option similar to `lintVue`.

**Comment by Kocal** [comment]
Closing, as ESLint integration has been removed in #1309 for the next major version of Encore (5).
