### ISSUE TITLE
"Webpack Encore requires version ^8.0.0 of sass-loader" warning on sass-loader v9.0

### ISSUE THREAD

**Issue by shmshd** [symfony/webpack-encore#797]
sass build works fine without any issue, though the warning annoys. 

Full warning:
```
Webpack Encore requires version ^8.0.0 of sass-loader. Your version 9.0.1 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
```

**Comment by weaverryan** [comment]
That warning is because Encore isn't tested using the version yet. We need a PR to update this line - https://github.com/symfony/webpack-encore/blob/master/package.json#L88

Then... the tests will validate that it works and we'll be good. If you'd like to open that PR, it'd be awesome!
