### ISSUE TITLE
Confusing error message when trying to override a Sass variable

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/webpack-encore#80]
I'm trying to fix an issue with the Symfony Demo app (https://github.com/symfony/symfony-demo/issues/590) which requires to override the value of a Sass variable defined in one of our dependencies.

The original `assets/app.scss` file that works starts like this:

```sass
@import "~bootswatch/flatly/variables";
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
@import "~bootswatch/flatly/bootswatch";
@import "~font-awesome/scss/font-awesome.scss";
// ...
```

I need to override this variable which is defined in `~bootswatch/flatly/bootswatch`:

```sass
$web-font-path: "https://fonts.googleapis.com/css?family=Lato:400,700,400italic" !default;
```

The fix that I'm trying to apply is defining the variable before importing the file using it:

```sass
$web-font-path: '';

@import "~bootswatch/flatly/variables";
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
@import "~bootswatch/flatly/bootswatch";
@import "~font-awesome/scss/font-awesome.scss";
// ...
```

But I see this confusing error message:

```
$ ./node_modules/.bin/encore dev

Running webpack ...

 ERROR  Failed to compile with 1 errors

This dependency was not found:

* -!../../node_modules/css-loader/index.js!./ in ./~/css-loader!./~/resolve-url-loader!./~/
sass-loader/lib/loader.js?{"sourceMap":true}!./assets/scss/app.scss

To install it, you can run: npm install --save -!../../node_modules/css-loader/index.js!./
    + 190 hidden modules
```

**Comment by stof** [comment]
I think the issue is that your change will turn the CSS into `@import url('')`, which causes weird issue when webpack will try to rewrite the CSS import (and anyway, it would cause weird issues when the browser loads the CSS otherwise).

**Comment by stof** [comment]
I think the main confusion here is related to the fact that the dependency being looked for is the empty string, and this does not appear properly in the message (as there is no delimiter around it)

**Comment by javiereguiluz** [comment]
That's right. When I read your first comment I could finally understand the problem ... but reading the original error messages was really confusing 😊

**Comment by stof** [comment]
So next question is: where does this message comes from ? Is it from webpack itself, from the friendly-error-plugin, or from Encore itself ?
@weaverryan do you have an idea ?

**Comment by weaverryan** [comment]
This is coming from friendly-errors-webpack-plugin. I have another issue - #57 - with a different issue, but related because it's coming from the same error transformer that's included in that library:  https://github.com/geowarin/friendly-errors-webpack-plugin/blob/master/src/formatters/moduleNotFound.js

We need to see if there's a way to "fix" that in our library, or possibly fix it upstream, but it's not well-maintained currently.

**Comment by weaverryan** [comment]
#224 might be another example of bad error messages, or the same issue as this.

**Comment by Rodrigo001-de** [comment]
Project made with TypeScript, react.Js, React-native. Recycling day design

https://github.com/Rodrigo001-de/Projeto-Ecoleta-advanced

**Comment by javiereguiluz** [comment]
Let's close this old issue as no longer relevant. Thanks.
