### ISSUE TITLE
less-loader 6.2.0 is too new

### ISSUE THREAD

**Issue by derrabus** [symfony/webpack-encore#803]
We're running Webpack Encore with the latest version of the less-loader package in our project. This results in a warning:

```
Webpack Encore requires version ^4.1.0 of less-loader. Your version 6.2.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
```

The suggested version is more than two years old. Also, the current version seems to work fine, at least in our project.

I'd like to get rid of the warning without downgrading to an ancient release. Are there any known issues with less-loader > 4 that need to be resolved?

**Comment by Kocal** [comment]
Hi,

According to [the changelog](https://github.com/webpack-contrib/less-loader/blob/master/CHANGELOG.md), there is no breaking changes that can affect Encore: 
- [in 5.0.0](https://github.com/webpack-contrib/less-loader/blob/master/CHANGELOG.md#500-2019-04-29):
  - they removed the deprecated `compress` option, Encore does not use it
  - they dropped node < 6.9 and webpack < 4, Encore supports Node >= 10.13 and webpack 4
- [in 6.0.0](https://github.com/webpack-contrib/less-loader/blob/master/CHANGELOG.md#600-2020-04-24):
  - they dropped node < 10.13, Encore supports Node >= 10.13
  - the minimum supported version of `less` is 3 (2 dropped), Encore use [`less@^3.9.0` as dev dependency](https://github.com/symfony/webpack-encore/blob/master/package.json#L80) but the package [is not listed in Encore features packages](https://github.com/symfony/webpack-encore/blob/master/lib/features.js#L28-L32)... but I don't think this will be a problem.
  - ⚠️ less-specific options has been moved under `lessOptions` object. 

That means that if an Encore user used:
```js
const CleanCSSPlugin = require('less-plugin-clean-css');

Encore.enableLessLoader(options => {
  // less-loader specific options
  options.implementation = require('custom-implementation-of-less');

  // less specific options
  options.relativeUrls = true;
  options.plugins = [
    new CleanCSSPlugin({ advanced: true }),
  ]
});
``` 

He will have to update his code to this:
```js
const CleanCSSPlugin = require('less-plugin-clean-css');

Encore.enableLessLoader(options => {
  // less-loader specific options
  options.implementation = require('custom-implementation-of-less');

  // less specific options
  options.lessOptions = {
    relativeUrls: true,
    plugins: [
      new CleanCSSPlugin({ advanced: true })
    ]
  };
});
``` 

However, it should not be a problem if we release a new major version (0.31) and we list breaking changes, like it was did in [0.30](https://github.com/symfony/webpack-encore/releases/tag/v0.30.0).

**Comment by derrabus** [comment]
Thank you very much for your detailed research. We are already using `lessOptions` in our configuration.

I've bumped `less-loader` and opened #804. Is there anything else I need to do?

**Comment by Kocal** [comment]
No problem! :)

I think it's fine. Maybe don't update `less` package? This way we can continue to cover a wider range of version, from `3.9.0` to `latest`, instead of `3.11.3` to `latest` (see [CI jobs](https://github.com/symfony/webpack-encore/blob/master/.travis.yml#L11-L29)).
@Lyrkan, what do you think?

Also, if you can document somewhere (in the PR description?) that the only possible breaking changes for Encore users is the new option `lessOptions`, it will be easier for @weaverryan when he will write the changelog. 👍

**Comment by derrabus** [comment]
> Maybe don't update `less` package? This way we can continue to cover a wider range of version, from `3.9.0` to `latest`, instead of `3.11.3` to `latest`

`less-loader` 6.2.0 requires `"less": "^3.11.3"`. I simply adopted the constraint.
 
> Also, if you can document somewhere (in the PR description?)

Will do.

**Comment by Kocal** [comment]
Oh you're right, sorry! 😅

**Comment by derrabus** [comment]
I've added a small piece of documentation to the PR that can be added to the changelog when creating a new release.
