### ISSUE TITLE
assets-webpack-plugin must be upgraded to v5

### ISSUE THREAD

**Issue by stof** [symfony/webpack-encore#806]
We currently use the v3 of assets-webpack-plugin, which depends on a vulnerable version of lodash. This is fixed in their v5 release (there is no actual v4).
the BC break between v3 and v5 is dropping support for Node 8, which does not impact Encore as our minimum version is already Node 10.13.

**Comment by Lyrkan** [comment]
Will be fixed by https://github.com/symfony/webpack-encore/pull/801

**Comment by stof** [comment]
hmm, I searched for existing issues, but I forgot to check existing PRs.
