### ISSUE TITLE
Strange code analyzing of webpack.config.js in PhpStorm

### ISSUE THREAD

**Issue by yura3d** [symfony/webpack-encore#815]
Hi!

I have fresh installation of webpack-encore-bundle and it works fine, but I see some strange things when I open `webpack.config.js` in PhpStorm.

Some methods of Encore object (like `isRuntimeEnvironmentConfigured()`, `configureRuntimeEnvironment()`, `setOutputPath()`) are highlighted as unresolved, but some others (`setPublicPath()`, `addEntry()`) are resolved correctly:

![image](https://user-images.githubusercontent.com/10958696/89219010-b3d53200-d5d7-11ea-91e8-fb010d656c95.png)

The strangest thing is that if I swap `setOutputPath()` and `setPublicPath()`, so after that `setPublicPath()` becomes unresolved (was resolved) and `setOutputPath()` is resolved (was unresolved):

![image](https://user-images.githubusercontent.com/10958696/89219459-7b822380-d5d8-11ea-9f4a-82f3555ae6fd.png)

Windows 10 x64 1909
PhpStorm 2020.2 (JavaScript version is set to ECMAScript 6+ in settings)
Node.JS 14.7.0
Installed devDependencies:
```
"@symfony/webpack-encore": "^0.30.0",
"core-js": "^3.0.0",
"regenerator-runtime": "^0.13.2",
"webpack-notifier": "^1.6.0"
```

This issue is very similar to #151 and #236, but I didn't find the solution there.

**Comment by stof** [comment]
My analysis would be that direct calls on `Encore` are marked as unresolved, while chained calls are marked as resolved (or maybe as unknown due to the unresolved calls).

I just tried that. PHPStorm 2020.1 was working fine. After upgrading to PHPStorm 2020.2, I get this issue as well. So I would say that this is a PHPStorm issue rather than a webpack-encore one.

**Comment by stof** [comment]
I would say that the new version of PHPStorm does not recognize the type annotation of the export anymore: https://github.com/symfony/webpack-encore/blob/4038860f8c34da1db4e22b4461d88690ba6bc030/index.js#L1650-L1655

**Comment by yura3d** [comment]
@stof It seems PhpStorm 2020.2 can still recognize the type annotation for export:

![image](https://user-images.githubusercontent.com/10958696/89226251-55fb1700-d5e4-11ea-829e-b708bb940254.png)

But it can't use it later, in code expressions.
I've just found workaround to fix code highlighting and autocompletion (by calling `getEncore()`):

![image](https://user-images.githubusercontent.com/10958696/89225623-2f88ac00-d5e3-11ea-8769-d7967d457211.png)

But it doesn't look perfect. It seems it's time to create an issue on PhpStorm/WebStorm tracker.

**Comment by stof** [comment]
This definitely look like a bug in PhpStorm/WebStorm if using such callback works

**Comment by yura3d** [comment]
The issue on PhpStorm Tracker: https://youtrack.jetbrains.com/issue/WI-54625

**Comment by stof** [comment]
thanks for doing that report.

**Comment by Alphamplyer** [comment]
Replace `var Encore = require('@symfony/webpack-encore');` by `import Encore from '@symfony/webpack-encore';`, seems to fix the problem. 
No need to use code such `const getEncore = () => Encore;`
But PHPStorm always display such of error
![image](https://user-images.githubusercontent.com/42153930/95203480-1a96e780-07e3-11eb-8314-b0b3745604ef.png)

**Comment by Alphamplyer** [comment]
just add doc over Encore require 
![image](https://user-images.githubusercontent.com/42153930/95204090-e53ec980-07e3-11eb-96a2-672fd3a49e28.png)

**Comment by yura3d** [comment]
@Alphamplyer I tried this yet before writing my previous post and caught strange behavior. When I add `@type` everything is fine, but after restarting PhpStorm this doesn't work: only removing `@type` and bringing it back returns me code analysis and autocompletion. But this solution is not for me as it requires additional action every time.

**Comment by Alphamplyer** [comment]
I'm agree, that's a temporary solution.

**Comment by zek0faws** [comment]
@yura3d Thanks for the report on PhpStorm Tracker.
It seems they are waiting for an answer from you, they want a repo with the issue. So I created a basic one. 
Since it's your issue on their tracker they may need only you to answer.
You can use this repo: https://github.com/zek0faws/phpstorm-webpack-encore-issue

Hope that help.

**Comment by yura3d** [comment]
@zek0faws Thank you so much, I haven't enough time last months to make it by myself, so it's cool that you've done it. I've just left a comment about it in PhpStorm tracker.

**Comment by yura3d** [comment]
It seems everything is fine after updating to PhpStorm 2020.3, as the JetBrains staff said before on Tracker. So this issue may be closed.
