### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Cryde** [symfony/webpack-encore#819]
Hello 

Sorry to bother you but is it normal ?
![image](https://user-images.githubusercontent.com/1662950/89514926-c7022080-d7d6-11ea-88d4-71ffd599aa6d.png)

I also had this error while trying to update my JS deps   
```
> npm outdated
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@symfony%2fwebpack-encore - Not found
npm ERR! 404 
npm ERR! 404  '@symfony/webpack-encore@^0.30.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

Thanks for you great works :D !

**Comment by muspelheim** [comment]
same

**Comment by stof** [comment]
The package is definetely registered in the registry, and visible on https://www.npmjs.com/package/@symfony/webpack-encore
But they have an issue right now according to their status website: https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by svitozarboosta** [comment]
same

**Comment by stof** [comment]
@svitozarboosta please see my comment. Commenting `same` does not help. the npm registry has an issue right now breaking installation of scoped packages. There is nothing the Encore team can do to change that except waiting for Npm Inc. to solve the issue.
