### ISSUE TITLE
Deactivate code splitting to have just one file

### ISSUE THREAD

**Issue by FabianSchmick** [symfony/webpack-encore#836]
I am using Webpack Encore in a non symfony environment. So I don't have the typical twig functions to auto generate the javascript and link tags.

```js
const Encore = require('@symfony/webpack-encore');

Encore.setOutputPath("./public/assets")
    .setPublicPath("/assets")
    .cleanupOutputBeforeBuild()
    .autoProvidejQuery()
    .enableSassLoader()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(true)
    .addEntry("js/app", "./assets/js/frontend.js")
    .addStyleEntry("css/app", "./assets/sass/frontend.sass")
    .disableSingleRuntimeChunk()
    .configureBabel(() => {}, {
        useBuiltIns: 'usage',
        corejs: 3,
        exclude: /node_modules/
    })
    .enableBuildNotifications();

module.exports = Encore.getWebpackConfig();
```

`encore dev` creates the following files:

```json
{
  "assets/0.fd6ffc6e.js": "/assets/0.fd6ffc6e.js",
  "assets/1.9e29cdd1.js": "/assets/1.9e29cdd1.js",
  "assets/css/app.css": "/assets/css/app.98ccae96.css",
  "assets/js/app.js": "/assets/js/app.d7d7fa58.js"
}
```

In my php template I'm reading the `manifest.json` and want to include my compiled JavaScript file. But I am missing the `0.fd6ffc6e.js` and `1.9e29cdd1.js` files, because these strings contains the version hash already.

```php
<?php
    $json = file_get_contents(__DIR__ . "/assets/manifest.json");
    $assets = json_decode($json, true);
?>

<script type="text/javascript" src="<?php echo $assets['assets/js/app.js'] ?>"></script>
```

I don't need the `0.js` & `1.js` files in my opionon. I simply wan't one `.js` and one `.css` file to include and nothing special or splitted. So how do I deactivate this feature?

**Comment by stof** [comment]
Based on this config, I would say that 0.js and 1.js are related to dynamic imports, in which case you don't need to reference them in your HTML. Having splits for entrypoint files should require an opt-in with `splitEntryChunks()`.

You can check this with the entrypoints.json file which is generated.

**Comment by FabianSchmick** [comment]
Yes that's correct. I am using dynamic imports and in the entrypoints.json the 0.js and 1.js files doesn't appear. 
Ok If these files are not necessary for me, I will ignore them. It seems to work without it, too.

**Comment by jdreesen** [comment]
Webpack takes care of loading these chunks automatically. :+1:
