### ISSUE TITLE
.configureDefinePlugin() not providing "process" variable to js entrypoint

### ISSUE THREAD

**Issue by StephenBeirlaen** [symfony/webpack-encore#839]
I am attempting to install a service worker using @vue/cli-plugin-pwa. This generates the following file into the project: [registerServiceWorker.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-pwa/generator/template/src/registerServiceWorker.js).
This file contains the line(s) `process.env.NODE_ENV`.

I included this file in the main js entrypoint (`/assets/vue/index.js`):

```
import Vue from "vue";
import App from "./App";
import router from "./router";
import store from "./store";
import './registerServiceWorker';

new Vue({
  components: { App },
  template: "<App/>",
  router,
  store
}).$mount("#app");
```

Unfortunately, when running `encore dev` the following error appears:

```
/nodeapp/assets/vue/registerServiceWorker.js
5:5   error  'process' is not defined  no-undef
6:15  error  'process' is not defined  no-undef
```

My webpack.config.js looks like this:

```
var Encore = require('@symfony/webpack-encore');

// Manually configure the runtime environment if not already configured yet by the "encore" command.
// It's useful when you use tools that rely on webpack.config.js file.
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    
    .addEntry('app', './assets/vue/index.js')

    .splitEntryChunks()

    .disableSingleRuntimeChunk()

    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())

    .addLoader({
        enforce: 'pre',
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        exclude: /node_modules/,
        options: {
            fix: true,
            emitError: true,
            emitWarning: true,
        },
    })

    .configureBabel((babelConfig) => {
        babelConfig.plugins.push('@babel/plugin-transform-runtime');
    }, {
        useBuiltIns: 'usage',
        corejs: 3
    })

    .enableVueLoader()

    .enableIntegrityHashes(Encore.isProduction())
    .configureDefinePlugin(options => {
        options['process.env'].NODE_ENV = JSON.stringify(process.env.NODE_ENV);
    })
;

module.exports = Encore.getWebpackConfig();
```

The configureDefinePlugin() in the bottom of the webpack.config.js seems to have no effect. The process variable is not available regardless of this line.

This problem is probably not VueJS or @vue/cli-plugin-pwa specific, the `process` variable is not available in index.js itself too.

Is this expected behaviour, or a bug? Did I forget to enable something?

Versions:

- node: 12.15.0
- npm: 6.13.4
- yarn: 1.19.2
- @symfony/webpack-encore (yarn.lock): 0.31.0
- symfony/webpack-encore-bundle (composer.lock): 1.7.3

**Comment by Kocal** [comment]
Hi,

You are confusing the webpack `DefinePlugin` plugin and ESLint warnings, the following lines are emitted by ESLint:
```
/nodeapp/assets/vue/registerServiceWorker.js
5:5   error  'process' is not defined  no-undef
6:15  error  'process' is not defined  no-undef
```

`process.env.NODE_ENV` is correctly replaced in your code, but ESLint does not know about `process` because you need to configure it. You can use `env: { node: true }` ([`env` documentation](https://eslint.org/docs/user-guide/configuring#specifying-environments)) to fix your issue.

Also, note that it's preferable for you to use `.enableEslintLoader()` instead of `.addLoader()` for adding ESLint support. You can use it like this:
```js
Encore.enableEslintLoader(() => {}, {
  lintVue: true
});
```

**Comment by StephenBeirlaen** [comment]
Hello,
Thank you for your fast response, and the heads-up about ESLint!
I have modified my .eslintrc.json file as follows:

```
{
  "root": true,
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "parser": "babel-eslint"
  },
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:vue/recommended"
  ],
  "rules": {
    "indent": ["error", 2]
  }
}
```

I have also replaced addLoader() with enableEslintLoader() as you suggested. Yet I still receive the same errors, it looks as if the .eslintrc.json file is not in use... It lives in the root of my project, next to the webpack.config.js file.

**Comment by StephenBeirlaen** [comment]
Adding `/* eslint-disable no-process-env */` to the top of the file seems to allow using process.*. But is this the preferable approach? Shouldn't I be able to configure this through .eslintrc.json?
