### ISSUE TITLE
sass-loader outdated

### ISSUE THREAD

**Issue by pavrip** [symfony/webpack-encore#840]
Hi I am desperately trying to update the webpack-encore bundle inside a Symfony application but its not working,

I have tried npm update sass-loader,
npm update,
composer update symphony/webpack-encore-bundle,

As well as manually changing the version in the package.json file and running composer.update,

I still get this message:

  WARNING   Webpack Encore requires version ^9.0.1 of sass-loader, but your version (8.0.2) is too old. The related feature will probably *not* work correctly.
  WARNING   Webpack Encore requires version ^9.0.1 of sass-loader, but your version (8.0.2) is too old. The related feature will probably *not* work correctly.

And no its not working correctly, I have to keep deleting the browser cache and quitting the browser everytime I make a change, its not possible to really work with this,

How could this be updated properly?

Thanks

**Comment by Kocal** [comment]
Hi, your issue is not related to the bundle but to how to manage your node.js dependencies.

Since you probably have a `sass-loader: ^8.0.2` version constraint, `npm update` will only update `sass-loader` to the latest version matching your constraint, I guess. It won't upgrade to a new major version.

You can run `npm install --save-dev @symfony/webapck-encore sass-loader@^9.0.0` it should do the job.

**Comment by pavrip** [comment]
Hello, thank you for that,
But it says that is not in the npm registry, I tried literally ever other way to upgrade it, maybe I will just reinstall the whole thing, and keep my configuration files

**Comment by Kocal** [comment]
That's weird because version 9.0.0 (and higher) are present on npm registry: https://www.npmjs.com/package/sass-loader/v/9.0.0

Are you behing a proxy or something similar?

**Comment by zek0faws** [comment]
@pavrip try this : 
`npm install --save-dev @symfony/webpack-encore sass-loader@^9.0.0`

@Kocal 
You just made a mistake : webapck instead of webpack ;)

For me it works fine

**Comment by Kocal** [comment]
I think this can be closed since it's _now_ possible to use sass-loader 9 (#799), 10 (#865) and 11 (#928.
