### ISSUE TITLE
[Feature request] Minify JS file without wrapping it with webpack

### ISSUE THREAD

**Issue by TimWerdin** [symfony/webpack-encore#841]
If I create a symfony-bundle and have javascript and css in it I want to provide minified JS and CSS files in the Resources/public folder. But the javascript should not be wrapped with webpack as I can not be sure that everyone who uses the bundle is also using webpack. I want to have a plain js file that is just minified and in an optimal solution also has a '.min' extension.

I tried to google for a solution with encore but was not able to find something.

**Comment by stof** [comment]
well, that's out of scope of webpack-encore, as Encore is a configuration layer for webpack.

There are several minifiers out there. If all you want is minifying a file, use one of them directly.
