### ISSUE TITLE
Easily alter existing rule? (trying to use linaria in Encore)

### ISSUE THREAD

**Issue by jaydiablo** [symfony/webpack-encore#846]
I was experimenting with linaria (https://github.com/callstack/linaria) and webpack encore, but ran into an issue that I wanted to ask about, and possibly suggest a feature if there's no existing convenient solution.

linaria recommends this webpack config so that linaria runs before Babel does:

```javascript
{
  test: /\.js$/,
  use: [
    { loader: 'babel-loader' },
    {
      loader: 'linaria/loader',
      options: {
        sourceMap: process.env.NODE_ENV !== 'production',
      },
    }
  ],
}
```
I can add the linaria loader to encore by doing this:

```javascript
.addLoader({
        test: /\.(jsx?)$/,
        loader: 'linaria/loader',
        exclude: /node_modules/
    })
```
However, that just adds a new rule to the webpack config (now I have two `test: /\.(jsx?)$/,` rules) and I get an error in the built app that the `css` helper that linaria provides is being used in runtime, which it's not supposed to be (the linaria loader is supposed to extract the CSS that can then be extracted as any other CSS content would be).

I believe the issue is that I can't insert the linaria loader where it needs to go (so that it runs before Babel does), the other rule with the same `test` looks like this:

```json
{
   "test":"/\\.(jsx?)$/",
   "exclude":"/(node_modules|bower_components)/",
   "use":[
      {
         "loader":"node_modules/babel-loader/lib/index.js",
         "options":[
            ...
         ]
      }
   ]
}
```

Short of looping through the rules and inspecting the `test` property of each rule (which could possibly change depending if React is enabled, or an Encore update changes the regex), is there a way to insert such a loader into the same rule that Babel runs?

I was able to make this work with some additions to `webpack.config.js`:

```javascript
const config = Encore.getWebpackConfig();

config.module.rules.forEach(rule => {
    if (rule.test.toString() == /\.tsx?$/.toString()) {
        rule.use.splice(1, 0, { loader: 'linaria/loader' });
    }
});

module.exports = config;
```

(I actually need to insert linaria between typescript and babel, but the concept is similar. If not using typescript, I could've just used `rule.use.push` instead of splicing).

This works, but it feels a bit brittle since it depends on the regex matching, and the number/order of loaders on that rule.

Is there any sort of way to specify the priority of loaders when using `addLoader`?  How would I specify which rule the loader should be a part of?  Any thoughts on providing an API to do this sort of thing, or is it just something that will have to be managed through the raw webpack config?  I like not having to configure babel/typescript, since the Encore defaults here work well for the app (hence the `forEach` loop to add the loader to the existing config that Encore builds), but I understand that Encore can't fit every possible need since Webpack can get complex quickly.

Thanks for your work on this library, let me know your thoughts, and apologies if this has been brought up already, I poked around in the issues but didn't see the same thing brought up.

**Comment by Kocal** [comment]
I think you can use `Encore.configureLoaderRule`, please see  https://symfony.com/doc/current/frontend/encore/advanced-config.html#having-the-full-control-on-loaders-rules

**Comment by jaydiablo** [comment]
@Kocal Nice, I wasn't aware of that option.

For the record, I was able to change this:

```javascript
const config = Encore.getWebpackConfig();

config.module.rules.forEach(rule => {
    if (rule.test.toString() == /\.tsx?$/.toString()) {
        rule.use.splice(1, 0, { loader: 'linaria/loader' });
    }
});

module.exports = config;
```

to this:

```javascript
Encore.configureLoaderRule('typescript', loaderRule => {
    loaderRule.use.splice(1, 0, {
        loader: 'linaria/loader',
        options: { sourceMap: true }
    });
});
```

Using that method. It should be noted that this method has to be called before `Encore.getWebpackConfig()`, otherwise it doesn't seem to find the loaders by the user friendly names.

I think that's much less brittle for this use-case than looking at that regex.

**Comment by stof** [comment]
well, if you call it after `getWebpackConfig`, it won't affect the previously generated config object. But it would still work for the future calls to `getWebpackConfig`

**Comment by Kocal** [comment]
> Using that method. It should be noted that this method has to be called before `Encore.getWebpackConfig()`, otherwise it doesn't seem to find the loaders by the user friendly names.

Well, like every `Encore.*` methods I think. Calling `Encore.getWebpackConfig()` will generate the plain config for webpack, and it can not be altered back. `Encore.getWebpackConfig()` is the last method you can call.

**Comment by stof** [comment]
yeah, exactly (unless you do weird things like generating multiple webpack configs).
