### ISSUE TITLE
How should image assets be handled?

### ISSUE THREAD

**Issue by MPLLC** [symfony/webpack-encore#85]
I have a couple image files that are referenced by CSS.  How should I handle these with Webpack Encore, if at all?  The documentation doesn't say anything about image assets.  Can I use `addEntry`?  Or will they be automatically detected/handled if they're in a location like `/path/to/project/app/Resources/assets/images`?

It's just a bit confusing coming from using Assetic in all my old projects.

**Comment by davidmpaz** [comment]
Maybe this is a duplicate of #24 ? Could you confirm @MPLLC? Work is done in that direction, not yet ready though.

**Comment by MPLLC** [comment]
Ah, didn't see #24.  Yes, my question/issue is more or less the same.

**Comment by weaverryan** [comment]
Closing as a duplicate - thanks for your question! It's one of our top issues to clarify for people :)
