### ISSUE TITLE
Support for Webpack 5

### ISSUE THREAD

**Issue by Pierstoval** [symfony/webpack-encore#851]
Webpack 5 was released last month, and it both improves performances and contains interesting new features.

Is there any plan on migrating to it?

A solution could also be to declare Webpack as a _peer dependency_ (check [this doc](https://nodejs.org/es/blog/npm/peer-dependencies/) for more info on this) on Webpack 4 and 5, so people could require it themselves and test it on their project.

**Comment by stof** [comment]
See #645 for the in-progress work

**Comment by Pierstoval** [comment]
Thanks for the hint! Didn't see this draft 👍

**Comment by leevigraham** [comment]
@stof @weaverryan This can be closed now.
