### ISSUE TITLE
How to use with vagrant or docker

### ISSUE THREAD

**Issue by scuben** [symfony/webpack-encore#86]
It would be good (and help me) to have a how to article in the docs on how to use encore within a vagrant or docker setup.

**Comment by weaverryan** [comment]
Since Encore builds on top of Node tools, I'd be most interested in using or documenting something existing. Obviously, the easier we can make things the better - but the Vagrant or Docker requirements for Encore are very non-unique (which is good!)

**Comment by stof** [comment]
the main things about Vagrant or docker are this:

- making the dev server URL working (see #59 about that)
- configuring the watch mode to use polling (see #35)

I don't think we need anything else (except documentation to have the info in 1 place)

**Comment by scuben** [comment]
I close this issue in favour of #126.
