### ISSUE TITLE
Vuejs 3 support 

### ISSUE THREAD

**Issue by xama** [symfony/webpack-encore#860]
Hello and thank you for the new npm package releated to this great module.

I'd like to know please if you planning to add support for Vuejs 3 ?

Thank you

**Comment by weaverryan** [comment]
Hi!

We already have it with an option :) https://github.com/symfony/webpack-encore/blob/main/index.js#L1178

It may need to be updated, it was last tested with a beta Vue version, so let me know if you have any issues.

Cheers!

**Comment by xama** [comment]
Oh didn't know about this. that's cool, I'll try this ;)

Thank you Ryan
