### ISSUE TITLE
Respect order when adding package to package.json

### ISSUE THREAD

**Issue by garak** [symfony/webpack-encore#875]
I installed a bundle using the recent feature of Symfony UX, and now I see a new package in `devDependencies` section of my package.json file.
It would be possible to get such new package added by respecting existing alphabetical order?

Example of what I get now:
```json
{
  "name": "mySuperCoolProject",
  "dependencies": {
    "bootstrap-sass": "^3.4.1",
    "jquery": "^3.5.1"
  },
  "devDependencies": {
    "@symfony/webpack-encore": "^0.33.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^9.0.1",
    "@symfony/ux-chartjs": "file:vendor/symfony/ux-chartjs/Resources/assets"
  }
}
```

What I would like to get instead: 

```json
{
  "name": "mySuperCoolProject",
  "dependencies": {
    "bootstrap-sass": "^3.4.1",
    "jquery": "^3.5.1"
  },
  "devDependencies": {
    "@symfony/ux-chartjs": "file:vendor/symfony/ux-chartjs/Resources/assets",
    "@symfony/webpack-encore": "^0.33.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^9.0.1"
  }
}
```

**Comment by Kocal** [comment]
Hi, this issue is not related to Webpack Encore itself but to Symfony flex which modify your `package.json` when needed (imlemented here https://github.com/symfony/flex/pull/723). 

Please open an issue of Symfony Flex repository instead.

Thanks

**Comment by garak** [comment]
Thank you @Kocal, I'll do it!
