### ISSUE TITLE
I don't know in which subfolder my app will live

### ISSUE THREAD

**Issue by SimonMellerin** [symfony/webpack-encore#882]
Hi,

Here is my use case:

I package [a Symfony app](https://gitlab.com/aeneria/aeneria-app). 

- The app can be install by anyone
- An instance of this app can live at `example.com` and another at `example.com/foo`,
- I want to release the app with assets & dependencies 
(final user who will install it do not have to use yarn or composer)

The problem is: `webpack.config.js` ask me to configure my public path before I compile, but I can't know it at this time. 

I can't find such a use case in Symfony documentation, or in readme here. 

Is there a way to tell Symonfy or Webpack Encore with a Symfony parameter that my app lives in a subfolder ?

Not sure if I'm clear here :/

Cheers
Simon

**Comment by stof** [comment]
As soon as there is a dynamic import involved in the webpack output, webpack needs to know that path.

If there is no dynamic import, it *might* be possible to find a trick to let symfony/asset manage the subfolder prefix, but I never tried that.

**Comment by SimonMellerin** [comment]
Thanks for your answer,

After looking at issues in [webpack-encore-bundle](https://github.com/symfony/webpack-encore-bundle), I think I will find a solution compiling infos from https://github.com/symfony/webpack-encore-bundle/issues/19 and https://github.com/symfony/webpack-encore/issues/88
