### ISSUE TITLE
.enableVersioning how to change contenthash to date?

### ISSUE THREAD

**Issue by aegladkikh** [symfony/webpack-encore#890]
Hi, there is a need to generate a hash as a date and not a set of letters, how can I do this?

For example app.20210127.js

**Comment by weaverryan** [comment]
Hey @aegladkikh!

Check out `configureFilenames()`: https://github.com/symfony/webpack-encore/blob/46a8c5996afc4e3d3ec8a0a5756b267584d675bd/index.js#L1379-L1409

Cheers!
