### ISSUE TITLE
copyFiles() error after 1.0 upgrade

### ISSUE THREAD

**Issue by mbabker** [symfony/webpack-encore#894]
I upgraded a project which uses `FOSCKEditorBundle` to use Encore 1.0, and for the most part the upgrade went pretty smoothly.  Except for one issue with copying files.

We have a config that matches [the documentation](https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/2.x/docs/installation.rst#using-webpack-encore) for using the bundle and Encore, and the process fails out while copying the editor files from `node_modules` to `public/build`.  It only affects the plugins directory in that list of configs (commenting that one config out allows the build to succeed, minus all those files), and it looks like it has to do with the fact the various plugins have image files.

```sh
(node:29135) UnhandledPromiseRejectionWarning: TypeError: Expected a SourceNode, string, or an array of SourceNodes and strings. Got export default __webpack_public_path__ + "ckeditor/plugins/about/dialogs/hidpi/logo_ckeditor.png";
    at SourceNode_add [as add] (<project>/node_modules/webpack/node_modules/source-map/lib/source-node.js:184:11)
    at new SourceNode (<project>/node_modules/webpack/node_modules/source-map/lib/source-node.js:43:29)
    at RawSource.node (<project>/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:49:10)
    at exports.getNode (<project>/node_modules/webpack/node_modules/webpack-sources/lib/helpers.js:54:17)
    at ReplaceSource.node (<project>/node_modules/webpack/node_modules/webpack-sources/lib/ReplaceSource.js:125:16)
    at <project>/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:105:54
    at Array.map (<anonymous>)
    at ConcatSource.node (<project>/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:104:19)
    at exports.getSourceAndMap (<project>/node_modules/webpack/node_modules/webpack-sources/lib/helpers.js:20:27)
    at ConcatSource.sourceAndMap (<project>/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:95:10)
    at CachedSource.sourceAndMap (<project>/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:158:35)
    at <project>/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:106:31
    at Array.map (<anonymous>)
    at ConcatSource.node (<project>/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:104:19)
    at exports.getSourceAndMap (<project>/node_modules/webpack/node_modules/webpack-sources/lib/helpers.js:20:27)
    at ConcatSource.sourceAndMap (<project>/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:95:10)
```

Even stranger is our full `copyFiles()` config actually does explicitly copy over a few image files, and that does work OK.

```js
const Encore = require('@symfony/webpack-encore');

Encore
    .copyFiles([
        {from: './node_modules/ckeditor4/', to: 'ckeditor/[path][name].[ext]', pattern: /\.(js|css)$/, includeSubdirectories: false},
        {from: './node_modules/ckeditor4/adapters', to: 'ckeditor/adapters/[path][name].[ext]'},
        {from: './node_modules/ckeditor4/lang', to: 'ckeditor/lang/[path][name].[ext]'},
        {from: './node_modules/ckeditor4/plugins', to: 'ckeditor/plugins/[path][name].[ext]'},
        {from: './node_modules/ckeditor4/skins', to: 'ckeditor/skins/[path][name].[ext]'},
        {from: './node_modules/ckeditor4/vendor', to: 'ckeditor/vendor/[path][name].[ext]'},
        {from: './assets/images', to: (!Encore.isProduction() ? 'images/[path][name].[ext]' : 'images/[path][name].[hash:8].[ext]'), pattern: /\.(svg)$/},
        {from: './assets/images', to: (!Encore.isProduction() ? 'images/[path][name].[ext]' : 'images/[path][name].[hash:8].[ext]'), pattern: /loading\.gif$/},
    ])
```

**Comment by weaverryan** [comment]
I'll have to check into this - but it sounds legitimate. Webpack 5 (and Encore 1.0) uses the new "Asset Modules", which basically means: there *are* some differences in how images are handled. But yes, this behavior is odd - why the images would copy correctly in one spot but not another...

**Comment by kniziol** [comment]
Same problem here. Details below.

**package.json**

```javascript
{
    "devDependencies": {
        "@babel/preset-react": "^7.0.0",
        "@symfony/stimulus-bridge": "^1.1.0",
        "@symfony/webpack-encore": "^1.0.0",
        "core-js": "^3.0.0",
        "file-loader": "^6.0.0",
        "regenerator-runtime": "^0.13.2",
        "sass": "^1.32.5",
        "sass-loader": "^10.0.0",
        "stimulus": "^2.0.0",
        "webpack-notifier": "^1.6.0"
    },
    // ...
    "dependencies": {
        "ckeditor": "^4.12.1",
        // ...
    }
}
```

**webpack.config.js**

```javascript
    .copyFiles([
        // ...
        {from: './node_modules/ckeditor/plugins', to: 'ckeditor/plugins/[path][name].[ext]'},
        {from: './node_modules/ckeditor/skins', to: 'ckeditor/skins/[path][name].[ext]'}
    ])
```

The error `TypeError: Expected a SourceNode, string, or an array of SourceNodes and strings. Got export default __webpack_public_path__ + "ckeditor/skins/kama/icons.png”;` occurs when those 2 lines are enabled in `copyFiles()`. Otherwise - everything works fine.

What’s the reason?

**Comment by weaverryan** [comment]
Unfortunately, I have no idea what could be causing this yet :/

**Comment by kniziol** [comment]
### Workaround

If you’re using Symfony-based application and [FOSCKEditorBundle](https://github.com/FriendsOfSymfony/FOSCKEditorBundle):

1. Remove all `./node_modules/ckeditor/` paths from `.copyFiles()` in `webpack.config.js`
2. Run `bin/console ckeditor:install` command to install CKEditor
3. Run `bin/console assets:install` command to install assets (and CKEditor) in `public` directory

**Comment by Gemorroj** [comment]
workaraund for me
```bash
yarn add copy-webpack-plugin
```

webpack.config.js:
```js
const CopyPlugin = require('copy-webpack-plugin');

...

    /*.copyFiles({
        from: './assets/resources/',
        to: 'resources/[path][name].[ext]',
    })*/
    .addPlugin(
        new CopyPlugin({
            patterns: [{
                from: './assets/resources/',
                to: 'resources/[path][name].[ext]',
            }],
        })
    )
```

**Comment by Lyrkan** [comment]
Hey there,

As Ryan said that bug is caused by some kind of conflict between how `Encore.copyFiles()` works and the new `asset/resource` module type used for images/fonts imports.

Could someone confirm that [the following fix](https://github.com/symfony/webpack-encore/compare/main...Lyrkan:fix-copy-files-asset-resource) works ?

```
$ yarn remove @symfony/webpack-encore
$ yarn add git://github.com/lyrkan/webpack-encore.git#fix-copy-files-asset-resource
```

Note that if you are using `configureLoaderRule('images', ...)` or `configureLoaderRule('fonts', ...)` this introduces a small breaking change.

**Comment by mpiot** [comment]
Hi @Lyrkan, I've just test your branch and it works wel for me.

**Comment by kniziol** [comment]
@Lyrkan Works fine. It solves the problem.

**Comment by sovetski** [comment]
I still get the same error with Symfony 6...
