### ISSUE TITLE
Symfony developer expirience improvement request 

### ISSUE THREAD

**Issue by TheCelavi** [symfony/webpack-encore#90]
Currently, path to encore command is: 

    ./node_modules/.bin/encore [ENV]

We (Symfony devs) are kinda used to use bin/[NAME OF THE COMMAND].

Request is trivial: it would be very convenient if there is alias in bin directory so we could execute encore as:

    bin/encore [ENV]

Thanks.

**Comment by weaverryan** [comment]
Hey @TheCelavi!

I basically agree. We can accomplish this with a Flex recipe: https://github.com/symfony/recipes/pull/108.

What we should do is add a script to `package.json`, so we would likely have something like this:

```
npm run encore dev
npm run encore dev --watch
npm run encore production
```

or

```
npm run dev
npm run watch
npm run production
```

I'm not totally convinced about `bin/encore`. The `npm run` way is standard, and being standard is always good :). But it *is* very familiar to Symfony peeps. Either way, it should be done in the Flex recipe.

**Comment by TheCelavi** [comment]
Ok, I will settle for `npm run xxx`, close enough... Thanks.
