### ISSUE TITLE
Abnormal CPU usage after upgrade to Node 15

### ISSUE THREAD

**Issue by Romitou** [symfony/webpack-encore#906]
Hi,

I use Webpack Encore very regularly for my Symfony projects.
Since the upgrade to Node 15, build uses abnormally a lot of CPU, memory and disk usage, which was not the case with Node 14.
For example, CPU usage reaches 100% on my only two cores during the build, RAM usage increases by one or two GB, and disk usage reaches 200 MiB. The build never finishes and I am forced to stop it.

Here is all the useful information for my problem:

<details>
  <summary>webpack.config.js</summary>
  
```js
const Encore = require('@symfony/webpack-encore');

if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore.setOutputPath('public/build/')
    .setPublicPath('/build')
    .addEntry('app', './assets/app.js')
    .splitEntryChunks()
    .enableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .enableSassLoader()
    .copyFiles({
        from: './assets/images',
        to: 'images/[path][name].[ext]',
        pattern: /\.(png|jpg|jpeg|ico)$/
    })
;

module.exports = Encore.getWebpackConfig();
```
</details>
<details>
  <summary>package.json</summary>
  
```
{
    "devDependencies": {
        "@symfony/webpack-encore": "^1.0.3",
        "core-js": "^3.8.3",
        "file-loader": "^6.2.0",
        "node-sass": "^5.0.0",
        "regenerator-runtime": "^0.13.2",
        "sass-loader": "^10.1.1",
        "webpack-notifier": "^1.12.0"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production --progress"
    }
}
```
</details>
<details>
  <summary>Host informations</summary>
  
```
Virtualization: lxc
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 5.4.73-1-pve
Architecture: x86-64
```
</details>

Node : `v15.7.0`
Yarn : `1.22.5`
@symfony/webpack-encore : `1.0.3`

Thank you for your help,
Do not hesitate if you need further information.

**Comment by stof** [comment]
this should probably be reported to webpack, as Encore is a configuration layer on top of it but al the compilation logic is in webpack

**Comment by Romitou** [comment]
Thank you for your response. Indeed, after double checking, it is definitely a problem with Webpack. Sorry, I am closing this issue as it is not from Encore.
