### ISSUE TITLE
Possibility to hide warnings about too new versions

### ISSUE THREAD

**Issue by iquito** [symfony/webpack-encore#909]
Since using Webpack Encore, I have often been using versions of dependencies that are too new according to Webpack Encore, and warnings are shown each time I run Webpack (especially `postcss-loader` and `less-loader`, currently the newest versions are once again too new).

While I appreciate the information once, as there could be a problem when using a new version, currently these warnings take up quite a bit of space in the output of running Webpack Encore, and they are shown each time I run it. Having the possibility to hide these warnings would greatly improve my user experience in these cases, in order to focus on new warnings / errors that can occur.

Another thing about the warnings is that I have a lot of repeats, maybe that is a bug - below is the output when running it for two webpack encore configurations (in one webpack.config.js), with 8 warnings about `postcss-loader` and 4 warnings about `less-loader` (I am using the newest versions for all libraries):

```
WARNING  Webpack Encore requires version ^4.0.0 of postcss-loader. Your version 5.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^4.0.0 of postcss-loader. Your version 5.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^7.0.0 of less-loader. Your version 8.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^4.0.0 of postcss-loader. Your version 5.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^7.0.0 of less-loader. Your version 8.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^4.0.0 of postcss-loader. Your version 5.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^4.0.0 of postcss-loader. Your version 5.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^4.0.0 of postcss-loader. Your version 5.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^7.0.0 of less-loader. Your version 8.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^4.0.0 of postcss-loader. Your version 5.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^7.0.0 of less-loader. Your version 8.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
WARNING  Webpack Encore requires version ^4.0.0 of postcss-loader. Your version 5.0.0 is too new. The related feature *may* still work properly. If you have issues, try downgrading the library, or upgrading Encore.
```

Otherwise version 1.0 with the support for Webpack 5 is great by the way, thanks for releasing it!

**Comment by weaverryan** [comment]
Hey @iquito!

This makes me laugh... in a depressed way :p. It's not your issue - that's totally legit! It's that I upgraded ALL of the dependencies for Encore less than 1 week ago. And already there are 2 loaders with new major version 🤯 .

Anyways, I'd say this:

1) Unrelated to your issue, we should allow these new versions in our `package.json` so that we can verify Encore works with them (via the tests) and remove these warnings. 
2) It would also probably make sense to make sure these warnings aren't duplicated. 
3) About the warning... idk - I don't love having more options for stuff. I'd prefer that we keep our dependencies up to date so that you don't see the warnings AND it's because you're using a version of Encore that's proven to work with those.

Cheers!

**Comment by iquito** [comment]
Yeah I get what you mean - I noticed a few times in the past that Webpack Encore updated its dependency versions, only for some of them to do a major new version shortly after that. I would prefer 1. and 2. of your suggestions in general, I mainly suggest possibly ignoring such warnings because it has happened so often in the past - although one can hope that now with Webpack 5 and PostCSS 8 all the crazy version jumps will decrease a bit ;-) If it continues happening, it might be a worthwhile option to keep in mind.

**Comment by weaverryan** [comment]
#918 to bump the dependencies

**Comment by weaverryan** [comment]
I'm going to close this for now - we have now bumped the dependencies.

Cheers!
