### ISSUE TITLE
Webpack 3.1 deprecation warning

### ISSUE THREAD

**Issue by weaverryan** [symfony/webpack-encore#91]
#53 moved us to Webpack 3.1 without any issues.

But, we do have 1 deprecation we should fix before releasing:

> (node:32501) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

This comes from the `addStyleEntry .js files are removed` functional test.

**Comment by weaverryan** [comment]
See: https://github.com/alexindigo/webpack-chunk-hash/pull/9

**Comment by garak** [comment]
It looks like related PR was merged... what about encore?

**Comment by stof** [comment]
Well, they merged the PR, but they have not released the fix. And npm does not use dev versions like Composer allows you to do (which is totally logical given that the npm registry also stores the code, not only the metadata).
So as far as npm is concerned, the bugfix does not exist yet.

**Comment by binarious** [comment]
It has been released: https://github.com/alexindigo/webpack-chunk-hash/pull/9#issuecomment-334870331

**Comment by Lyrkan** [comment]
@weaverryan Reopening: the current version range declared in the `package.json` file for `webpack-chunk-hash` (`^0.4.0`) does not allow to install the new version (`0.5.0`).
