### ISSUE TITLE
Error: Unknown option '--disable-host-check'

### ISSUE THREAD

**Issue by thewalkingcoder** [symfony/webpack-encore#916]
**version(s) affected:** 
symfony/webpack-encore-bundle 1.9.0
webpack-encore 1.0.4
webpack-dev-server@^4.0.0-beta.0

**Description**

Since v1.0.0 when configure encore dev-server like that

```bash

"dev-server": "encore dev-server --port 8081 --host 0.0.0.0 --public http://mydomain.dev:8081 --disable-host-check"

```

i have

![image](https://user-images.githubusercontent.com/10476280/106909294-6fe6f500-6700-11eb-9669-a9d225323420.png)

**Possible Solution**

I think **webpack-dev-server@^4.0.0-beta.0** is the problem

No problem for my second project create 3 weeks ago.

symfony/webpack-encore-bundle 1.9.0
@symfony/webpack-encore@0.32.1
webpack-dev-server@^3.1.14

**Comment by lokiloq** [comment]
I do not know if it is related but I have the same type of issue.

<img width="830" alt="Screenshot 2021-02-04 at 16 12 52" src="https://user-images.githubusercontent.com/5801805/106913028-e20d0900-6703-11eb-85fb-3bcb4420d594.png">

I am using the webpack-dev-server@^4.0.0-beta.0 as well.

I was working well with v3.4.1

**Comment by Lyrkan** [comment]
Some options changed/disappeared in webpack-dev-server@4 (full list here: https://github.com/webpack/webpack-dev-server/blob/08a83a65f5c500a648c12faa2fa03122ee380c8b/CHANGELOG.md#400-beta0-2020-11-27)

@thewalkingcoder `--disable-host-check` and `--allowed-hosts` got merged into a single `--firewall` option 

@lokiloq `--pfx` was moved to `--https.pfx`

**Comment by lokiloq** [comment]
Hi @Lyrkan 

Thanks for your answer but I still have the same error:
<img width="676" alt="Screenshot 2021-02-04 at 16 54 21" src="https://user-images.githubusercontent.com/5801805/106918619-a6753d80-6709-11eb-9525-5c76d121db59.png">

Here is my config:
<img width="667" alt="Screenshot 2021-02-04 at 16 55 03" src="https://user-images.githubusercontent.com/5801805/106918725-bf7dee80-6709-11eb-8b65-313cb0c5d26f.png">

I am using  "@symfony/webpack-encore": "^1.0.4"

**Comment by caseyjhol** [comment]
Specifically, `--disable-host-check` was replaced with `--firewall false`.

**Comment by weaverryan** [comment]
The docs are being updated here: https://github.com/symfony/symfony-docs/pull/14895

Cheers!

**Comment by dritter** [comment]
For the records: `--disable-host-check` is replaced with `--no-firewall` (see https://github.com/webpack/webpack-dev-server). `--firewall false` did not work for me.

**Comment by Kocal** [comment]
Oh, thanks! I've also tried `--firewall false` but like you but it didn't work. 
Thanks for sharing this!

**Comment by pierres** [comment]
Note: for webpack-dev-server 4.1 you have to set `--allowed-hosts all`. See https://webpack.js.org/configuration/dev-server/#devserverallowedhosts
