### ISSUE TITLE
Unique ports must be specified for each devServer option in your webpack configuration.

### ISSUE THREAD

**Issue by jkabat** [symfony/webpack-encore#923]
Any suggestion how to use Encore 1.0 + Webpack 5.0 with multiple configurations?

Full error message:
```javascript
Error: Unique ports must be specified for each devServer option in your webpack configuration. Alternatively, run only 1 devServer config using the --config-name flag to specify your desired config.
encore_1       |     at Object.startDevServer [as default] (/app/node_modules/@webpack-cli/serve/lib/startDevServer.js:94:23)
encore_1       |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
encore_1       |     at async Command.<anonymous> (/app/node_modules/@webpack-cli/serve/lib/index.js:93:27)
encore_1       |     at async Promise.all (index 1)
encore_1       |     at async Command.<anonymous> (/app/node_modules/webpack-cli/lib/webpack-cli.js:1120:13)
encore_1       | error Command failed with exit code 2.
encore_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by jkabat** [comment]
It seems like webpack-dev-server likes only one devServer config, so I'm getting rid of it in dirty way in second configuration.

```javascript
let config = Encore.getWebpackConfig();
delete config.devServer;

module.exports = config;
```

**Comment by jkabat** [comment]
Build now runs, but there is still way too lot of work ahead... I'm afraid I have to downgrade. But it was a nice exercise for a backend guy though.

Just to mention few obstacles:
* copyFiles bites with ckeditor (issue is already here)
* introducing webpack copy plugin brings an issues with wrong keys in manifest.json (@weaverryan seems to be working on it already)
* watchOptions are ignored, in webpack5 they have to be populated in devServerOption.static key
* maybe more I was able fixed easy way

**Comment by weaverryan** [comment]
Hey @jkabat!

Thanks for opening the issue!

> copyFiles bites with ckeditor (issue is already here)

Working on that, as you know, and I think we're pretty close to fixing it :). 

> introducing webpack copy plugin brings an issues with wrong keys in manifest.json (@weaverryan seems to be working on it already)

✅  I finally crushed it last not (was an npm + Windows bug that made things tough in the end 🤦 ). It should land soon

> watchOptions are ignored, in webpack5 they have to be populated in devServerOption.static key

Were you trying this type:

```
Encore.configureWatchOptions(function(watchOptions) {
        // enable polling and check for changes every 250ms
        // polling is useful when running Encore inside a Virtual Machine
        watchOptions.poll = 250;
    });
```

Or the `Encore.configureDevServerOptions` style? My understanding (but I could be wrong, so please tell me) is that you should be able to use `Encore.configureWatchOptions()`. However, I did change some config in this area related to devServer, so please let me know.

Cheers!

**Comment by jkabat** [comment]
I think I was not able to set polling option using your method (was done that way on Encore 0.33). Finally I made it to work using this snippet:

```javascript
.configureDevServerOptions(devServerOptions => {
    devServerOptions.firewall = ['.docker', '.info', 'localhost'];
    devServerOptions.static = Object.assign(devServerOptions.static, {
        watch: {
            poll: 5000, // check for changes every 5 seconds
        },
    });
})
```
After a second though may be that during miscellaneous tests I was by accident overwriting "static" key... the trick was to merge it.

I faced also several issues with importing/requiring libraries and with the order of them (but this seems to be a webpack5 related problem).

Good job with getting Encore on board with Webpack I guess I was just too impatient and have to wait a little bit longer.

**Comment by weaverryan** [comment]
Hey @jkabat!

According to this snippet - https://github.com/webpack/webpack-dev-server/blob/788f2ba7d9152610ba0d3024f0079c98aad86991/lib/utils/normalizeOptions.js#L10-L24 (I know, not the easiest to read), the `static.watch` options default to whatever the top-level `watchOptions` are in Webpack, which is what is set by calling `Encore.configureWatchOptions`.

So, if I'm reading things correctly, this should work:

```js
    Encore.configureWatchOptions(function(watchOptions) {
        // enable polling and check for changes every 250ms
        // polling is useful when running Encore inside a Virtual Machine
        watchOptions.poll = 250;
    });
```

However: (1) I could be reading the code wrong and (2) I believe that if you set the `devServerOptions.static.watch`, then you are completely replacing the default config from `watchOptions`.

If you have a chance to try the above code block (only) again, and let me know if it works, I'd appreciate that. I'm not convinced there is a bug here... but I'm also not convinced that there is... NOT a bug ;).

**Comment by pcarballeda** [comment]
I have exactly the same problem. I solved the problem by passing different port to each configuration. 

`.configureDevServerOptions(options => {
            options.port = port
        })`

But after fixing this I have a ton of other different problems.

**Comment by pcarballeda** [comment]
I have exactly the same problem. Can't upgrade to Encore latest version with webpack 5 because I am using multiple configurations. 

Reduced webpack.config.js working before upgrading.
```
function getConfig({ outputPath, publicPath, name, color, enableVue, enableCkEditor, entries }) {
    // Make sure we start fresh
    Encore.reset();

    Encore
        // Set paths
        .setOutputPath(outputPath)
        .setPublicPath(publicPath)

        // Cleanup build folder
        .cleanupOutputBeforeBuild(['*.html', '*.css', '*.js*', 'entrypoints.json', 'manifest.js', 'manifest.json'], (options) => {
            options.exclude = ['public/build/common/*'];
            return options;
        })

        // Create aliases for assets
        .addAliases({
            '@': path.resolve(__dirname, 'assets', 'js'),
            styles: path.resolve(__dirname, 'assets', 'scss'),
            fonts: path.resolve(__dirname, 'assets', 'fonts'),
        })

        // Enable Features
        .enableSingleRuntimeChunk()
        .enableBuildNotifications()
        .enableSourceMaps(!Encore.isProduction())
        .enableVersioning(Encore.isProduction())

        // Enable Loaders
        .enableSassLoader()
        .enablePostCssLoader()

        // Autoprovide jQuery
        .autoProvidejQuery()

        // Provide Variables
        .autoProvideVariables({
            moment: 'moment',
        })

        // Configure Terser for JS optimization
        .configureTerserPlugin((options) => {
            options.terserOptions = {
                output: {
                    comments: false,
                },
                compress: {
                    drop_console: true,
                },
            };
        })

        // Plugins
        .addPlugin(new MomentLocalesPlugin({
            localesToKeep: locales,
        }))

        .addPlugin(new WebpackBar({
            name,
            color,
        }));

    // Enable CkEditor if needed
    if (enableCkEditor) {
        Encore
            .addPlugin(new CKEditorWebpackPlugin({
                language: 'en',
                addMainLanguageTranslationsToAllAssets: true,
            }))
            .addLoader({
                test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
                loader: 'postcss-loader',
                options: {
                    postcssOptions: styles.getPostCssConfig({
                        themeImporter: {
                            themePath: require.resolve(
                                '@ckeditor/ckeditor5-theme-lark',
                            ),
                        },
                        minify: true,
                    }),
                },
            })
            // Configure other image loaders to exclude CKEditor 5 SVG files.
            .configureLoaderRule('images', loader => {
                loader.exclude = /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/;
            })
            // Use raw-loader for CKEditor 5 SVG files.
            .addRule({
                test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
                loader: 'raw-loader',
            });
    }

    // Enable Vue if needed
    if (enableVue) {
        Encore.enableVueLoader();
    }

    // Loop entries object
    for (const name in entries) {
        Encore.addEntry(name, entries[name]);
    }

    const config = Encore.getWebpackConfig();
    config.name = name;
    return config;
}

// FRONTEND CONFIGURATION
const frontend = getConfig({
    name: 'Frontend',
    color: 'blue',
    outputPath: 'public/compiled/frontend/',
    publicPath: '/compiled/frontend',
    enableVue: true,
    enableCkEditor: false,
    entries: {
        'frontend': './assets/entries/frontend/frontend.js',
    },
});

// EXTRANET CONFIGURATION
const extranet = getConfig({
    name: 'Extranet',
    color: 'yellow',
    outputPath: 'public/compiled/extranet/',
    publicPath: '/compiled/extranet',
    enableVue: false,
    enableCkEditor: false,
    entries: {
        'extranet': './assets/entries/extranet/extranet.js',
    },
});

module.exports = [frontend, extranet];
```

This is my dev-server script in package.json that worked before upgrade.

`"dev-server": "encore dev-server --hot --host '0.0.0.0' --public dev.xxxxxxxx.com.intranet:8080"`

And this is the error:

![image](https://user-images.githubusercontent.com/4659020/107944012-d0422600-6f8d-11eb-81c0-24cd007b47e9.png)

**Comment by jkabat** [comment]
Seems like most of the issues has been nailed with 1.2 release. Good job @weaverryan 

Closing.

**Comment by mkrauser** [comment]
For all who find this issue via google: In my case the problem was, that I specified the config-file to use as cli-option like this:

`yarn run dev-server  -c some-webpack-config.js`

But the dev-server command in the packages.json already provided the config-file. So in the end the -c option was duplicated, which caused the issue. 

@weaverryan Would it be possible to output a warning if the same config-file is provided more than once?
