### ISSUE TITLE
enablePostCssLoader options

### ISSUE THREAD

**Issue by picks44** [symfony/webpack-encore#924]
Hi there,

I'm using the latest version of postCSS (see my package.json below). SInce the upgrade, I can't use the config described [in the Symfony documentation](https://symfony.com/doc/current/frontend/encore/postcss.html) to configure the the directory where the postcss.config.js file is stored (see below too), here is the warning that I get. Can anybody help?

**package.json**
```
"devDependencies": {
        "@symfony/stimulus-bridge": "^2.0.0",
        "@symfony/webpack-encore": "^1.0.0",
        "autoprefixer": "^10.2.3",
        "bootstrap": "^4.5.0",
        "core-js": "^3.0.0",
        "file-loader": "^6.0.0",
        "jquery": "^3.5.1",
        "node-sass": "^5.0.0",
        "popper.js": "^1.16.1",
        "postcss": "^8.2.4",
        "postcss-loader": "^4.2.0",
        "regenerator-runtime": "^0.13.2",
        "sass-loader": "^10.1.1",
        "stimulus": "^2.0.0",
        "webpack-notifier": "^1.12.0"
    },
```

**webpack.config.js**
```
    .enablePostCssLoader((options) => {
        options.config = {
            // the directory where the postcss.config.js file is stored
        path: 'postcss.config.js'
        };
    })

```
**warning (after yarn dev)**
```
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'config'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }
```

**Comment by stof** [comment]
the Symfony doc is outdated due to migration to postcssLoader 4+. the `config` option is a child of `postcssOptions`, not a top-level key

**Comment by weaverryan** [comment]
Hi!

I updated the docs over at https://github.com/symfony/symfony-docs/pull/14948

Thanks for opening the issue!

Cheers!

**Comment by picks44** [comment]
Thanks @weaverryan !
