### ISSUE TITLE
Getting `Unknown option '--disable-host-check'` when trying to run encore dev --hot

### ISSUE THREAD

**Issue by kauffmanes** [symfony/webpack-encore#926]
I tried to upgrade webpack-encore and I'm getting two error messages when I try to run `encore dev-server --hot --disable-host-check`.

Here's the relevant section in my config:
```
 .configureDevServerOptions((options) => {
        options.contentBase = join(__dirname, 'web/build');
    });
```

Here are the messages:
```
$ encore dev-server --hot --disable-host-check
Running webpack-dev-server ...

[webpack-cli] Error: Unknown option '--disable-host-check'
[webpack-cli] Run 'webpack --help' to see available commands and options
error Command failed with exit code 2.
```

If I remove the `--disable-host-check` line, I get this:
```
$ encore dev-server --hot
Running webpack-dev-server ...

[webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'contentBase'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, injectClient?, injectHot?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, openPage?, overlay?, port?, proxy?, public?, setupExitSignals?, static?, stdin?, transportMode?, useLocalIp? }
error Command failed with exit code 2.
```

I'm sure I'm just doing something dumb, but I appreciate any help! I've had the previous config working for a while and didn't really make any other changes other than upgrading Encore. Let me know if you need more of the config.

**Comment by caseyjhol** [comment]
https://github.com/symfony/webpack-encore/issues/916

**Comment by kauffmanes** [comment]
Thanks! I swear I searched before posting...closing!

**Comment by kauffmanes** [comment]
Actually, any feedback on the contentBase issue as well?

**Comment by Kocal** [comment]
Given https://github.com/webpack/webpack-dev-server/blob/08a83a65f5c500a648c12faa2fa03122ee380c8b/CHANGELOG.md#400-beta0-2020-11-27, the option `contentBase` has been removed in favor of option `static`.

Also, I'm curious why you need to configure it 👀
