### ISSUE TITLE
I can't find a way to keep image in original directory

### ISSUE THREAD

**Issue by ph-il** [symfony/webpack-encore#937]
I don't want my image to move from asset to /build/images. They are already in public/img or public/svg . It was working before. Now, It need to find the image in CSS or SCSS, and if I do I get a "Syntax Error: ModuleParseError: Module parse failed: Maximum call stack size exceeded".

Who can I go back to the beta version behavoir?

**Comment by weaverryan** [comment]
Hey there!

thanks for the report!

Hmm. I have a few questions to figure out what’s going on:

1) can you give me an example of when you reference on of the images from a css file? Including the location of the css and image?

2) when you reference an image from css, you get this module parse failed error?

3) it seems that you’re saying that in the old version of encore, if you referenced an image in a css file that it did *not* move it into the public/build directory? Is this accurate? And are you totally sure - this is not the behavior I would have expected for any encore version.

cheers!

**Comment by ph-il** [comment]
Yes, in the css it's /img/image1.png, and /svg/image.svg
The CSS are in assets/css and SCSS in assets/scss . The /img/ and /svg/ are in /public/
It did work before. Now I got : 
Error: Can't resolve '/svg/unicode/2049.svg' in '/Users/Philippe.gamache/Projects/lapageamelkor.org/assets/scss'
    at runMicrotasks (<anonymous>)

If I correct the url for something like this I got :  ../../public/svg/unicode/2049.svg (did all of them) ...

Rerunning Encore I have this error : 

Syntax Error: ModuleParseError: Module parse failed: Maximum call stack size exceeded
File was processed with these loaders:
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/resolve-url-loader/index.js
 * ./node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
RangeError: Maximum call stack size exceeded

on joypixels-awesome.scss (it's open source), but very big. As it translate all Emoji into images (and I do have another one very big.

**Comment by Lyrkan** [comment]
I don't know about the "Maximum call stack size exceeded" error but you seem to be passing root-relative URLs (starting with a `/`) to the `url()` function in your CSS files.

The `css-loader` was updated from v3 to v5 when Encore 1.0.0 was released.

In `css-loader@3` those kinds of URLs were **not** resolving (so the file they referenced wouldn't go through any loader), but this behavior was changed in `css-loader@4` (see https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#400-2020-07-25).

One workaround could be to disable resolving for those files by passing a function to the `url` option of that same loader (see https://github.com/webpack-contrib/css-loader/blob/master/README.md#function).

**Comment by ph-il** [comment]
Thanks @weaverryan  and @Lyrkan.

So, when removing the resolve of the url, it did work like before and stop the "Maximum Call Stack Size Exceeded". 

The solution (coming partly by Lyrkan answer) was by adding this line: 

    .configureCssLoader(options => { options.url = false; })

It might be something interesting to write into the documentation.

**Comment by Lyrkan** [comment]
> It might be something interesting to write into the documentation.

Well, usually you don't want to disable this since it allows you to also version/process images/fonts that you require from your CSS files. Not sure why they changed the behavior for root-relative/absolute URLs in `css-loader` though...
