### ISSUE TITLE
encore_entry_link_tags fail

### ISSUE THREAD

**Issue by grekpg** [symfony/webpack-encore#964]
When i get files example for ckeditor 

`{{ encore_entry_link_tags('css/app',null,'front' }}`

then 

`{{ encore_entry_link_tags('css/app',null,'front', {'mea-selector':'app_css'}) }}`

second response is empty - so this is error. 

Please add example 

encore_entry_link_tags_if_not_fired like was in old php inlude_once - this have sense.

or extra parameter reset. Now i think this is error. I ask for files two times and have diferent results 

What if i in one request prepare template and example iframe content ? i cannot get assets ? 

And is realy many work to override EntryFilesTwigExtension, off corse is Final class, use private services .... 

What happens to this world, it seems to you that you are never wrong? 

i create {{ encore_reset('front') }} but i think This should not be spent

**Comment by weaverryan** [comment]
Hi!

This is a known bug... or really, we do this in purpose, but (as you can see) it doesn't work in all cases. Here is some more information: https://github.com/symfony/webpack-encore-bundle/pull/91

Cheers!
