### ISSUE TITLE
Custom loader ignored

### ISSUE THREAD

**Issue by AlexandreCln** [symfony/webpack-encore#971]
Hello ! I'm trying to inlines svg files, in order to store them in a svg sprite. 
I use `svg-inline-loader` for this, and it works fine in an other project (Vue / webpack). 

According to [webpack doc](https://webpack.js.org/concepts/loaders/#inline) I tried to configure the loader with inline config :

> - Prefixing with ! will disable all configured normal loaders

> - Prefixing with !! will disable all configured loaders (preLoaders, loaders, postLoaders)

but neither of them worked :
```
const svgContext = require.context(
    '!svg-inline-loader?' + 
    ... // rules
    '!@/icons', 
    true,
    /\w+\.svg$/i
)

const symbols = svgContext.keys().map(path => {
    console.log(path); // ./icon.svg
    console.log(svgContext(path)) // '/build/images/icon.123.svg' <- I get path instead of file content 
})
```
I've also tried with `raw-loader` as `svg-inline-loader` is abandoned :
```
import sendIcon from '!raw-loader!@/icons/send.svg'
console.log(sendIcon); // /build/images/send.1a6385d2.svg
```
It looks like `file-loader` goes before `svg-inline-loader`, so I tried to configure it in `webpack.config.js` 

with [addLoader()](https://symfony.com/doc/current/frontend/encore/custom-loaders-plugins.html#adding-custom-loaders), my svg are no longer handled by `file-loader` so using them with ` <img src="...">` don't work, but when i import them in js files i get a /build path :

```
.addLoader({
    test: /\.svg$/,
    loader: 'svg-inline-loader',
  })
```

with **.addRule()** (found example [here](https://github.com/symfony/webpack-encore/issues/349#issuecomment-464158324)) :

```
.addLoader({
    test: /\.svg$/,
    loader: 'svg-inline-loader',
  })
.addRule({
    test: /\.svg$/,
    use: [
      {
        loader: 'svg-inline-loader',
      },
      {
        loader: 'file-loader',
        options: {
          name: 'images/[name].[hash:8].[ext]',
          publicPath: '/build'
        }
      },
    ]
  })
```
but I get a /build path which is generated by the default loader `file-loader`, isn't it ?

Using [configureImageRule()](https://symfony.com/doc/current/frontend/encore/advanced-config.html#having-the-full-control-on-loaders-rules) seems to disable `file-loader` globally and broke all images.

```
.configureImageRule({
  type: 'asset/source',
})
```

```
//...
const symbols = svgContext.keys().map(path => {
    console.log(path); // ./icon.svg
    console.log(svgContext(path)) // module.exports = "<svg viewBox=\"0 0 192 192\" ...
})
```
How can I specify `svg-inline-loader` by prefixing with `!` or only for svg in my icons directory ? 

Version : **@symfony/webpack-encore": "^1.0.0"**
Full **webpack.config.js**  : 
```
Encore
.setOutputPath('public/build/')
.setPublicPath('/build')
.copyFiles({
    from: './assets/images',
  })
.enableVueLoader()
.addEntry('app', './assets/js/app.js')
.splitEntryChunks()
.enableSingleRuntimeChunk()
.cleanupOutputBeforeBuild()
  .enableBuildNotifications()
  .enableSourceMaps(!Encore.isProduction())
  .enableVersioning(Encore.isProduction())

  .configureBabel((config) => {
    config.plugins.push('@babel/plugin-proposal-class-properties');
  })
.configureBabelPresetEnv((config) => {
    config.useBuiltIns = 'usage';
    config.corejs = 3;
  })
.enableSassLoader()
.addAliases({
    '@': `${__dirname}/assets/js`,
    ` Style`: `${__dirname}/assets/scss`,
    Images': `${__dirname}/assets/images`,
  })
;

module.exports = Encore.getWebpackConfig();
```
Thanks !
Best regards

**Comment by AlexandreCln** [comment]
Hello, thank you for these explanations about loaders !

I first tried to add the rule at the end with `push()` and indeed it didn't works.  
As you said, the rule must be added before the default ones :

```
.configureImageRule({}, function(rule) {
    rule.oneOf.unshift({
      test: /\.svg$/i,
      include: /assets\/icons/,
      loader: 'svg-inline-loader',
      options: {
        removeTags: true,
        removeSVGTagAttrs: true, 
        removingTagAttrs: 'fill',
      }
    })
  })
```
I begin with javascript and webpack so I tried to configure it the right way, please let me know if this is not the case. 
Thank you so much!

**Comment by AlexandreCln** [comment]
Hello @Lyrkan, thank you for these explanations about loaders !

I first tried to add the rule at the end with `push()` and indeed it didn't works.  
As you said, the rule must be added before the default ones :

```
.configureImageRule({}, function(rule) {
    rule.oneOf.unshift({
      test: /\.svg$/i,
      include: /assets\/icons/,
      loader: 'svg-inline-loader',
      options: {
        removeTags: true,
        removeSVGTagAttrs: true, 
        removingTagAttrs: 'fill',
      }
    })
  })
```
I begin with javascript and webpack so I tried to configure it the right way, please let me know if this is not the case. 
Thank you so much!

**Comment by Lyrkan** [comment]
Your code looks good to me, does it work as expected?
It's kind of a hack since it relies on how Encore works internally but it shouldn't break anytime soon.

And yes your rule must be placed before the default one since `oneOf` stops as soon as it finds a matching rule 🙂 

The only issue I could see with placing it first would occur if you tried to copy SVG files from `assets/icons` using `Encore.copyFiles(...)` (since your rule would be used instead of the "copy-files-loader" rule). If that happens you could fix it by slightly moving the new rule to the right in the `oneOf` array, or by adding some condition to it (for instance, a [`resourceQuery`](https://webpack.js.org/configuration/module/#ruleresourcequery)).

**Comment by AlexandreCln** [comment]
@Lyrkan thanks for the warning about `copyFiles()` I now have a better understanding of what is going on in the background.
This solution is fine for my purpose.

Regards
