### ISSUE TITLE
Can't import node modules

### ISSUE THREAD

**Issue by mi6th** [symfony/webpack-encore#974]
With Webpack 1.x importing any NodeJs module is impossible:

```javascript
// ./assets/some_file.js
const path = require('path');

// The rest of the file
```

or
```javascript
// ./assets/some_file.js
import {} from 'path';

// The rest of the file
```

The compilation fails with the following error:

> ERROR  Failed to compile with 1 errors
> 
> Module build failed: Module not found:
> "./assets/some_file.js" contains a reference to the file "path".
This file can not be found, please check it for typos or update it if the file got moved.

Tried with NodeJS 12/14/15/16 and with `path`/`os` modules.

---

# Steps to reproduce
1. Install Symfony (`--full --version=stable`).
2. Install Webpack Encore.
3. Edit e.g. `./assets/app.js` file and add: `const path = require('path');` or `import 'os';` or any other node core module.
4. Compile assets with `yarn encore dev`, `yarn dev` or `npm run dev`.

**Comment by weaverryan** [comment]
Hi!

I believe this was a change in Webpack 5 - I think these are the details: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

Cheers!

**Comment by mi6th** [comment]
The link provided by @weaverryan is the cause of the issue.

Here is my solution:

1. Install `webpack`: `yarn add --dev webpack`. You'll get a warnigs during compilation:
    > WARNING  Webpack is already provided by Webpack Encore, also adding it to your package.json file may cause issues.
2. Install node modules you need, e.g. if you're going to use [`path`](https://www.npmjs.com/package/path) install `path` & [`process`](https://www.npmjs.com/package/process) (see below).
3. Add `process` as [custom plugin](https://symfony.com/doc/current/frontend/encore/custom-loaders-plugins.html) because `path` relies on this module.
4. Compile with `yarn encore dev`.
