### ISSUE TITLE
Removal of empty js files (get rid of DeleteUnusedEntriesJSPlugin?)

### ISSUE THREAD

**Issue by sattes-faction** [symfony/webpack-encore#980]
I'm having a project where I use addEntries to automatically collect a bunch of entries by looking through folders instead of adding them manually in the webpack.config.js. Some of those entries have an index.js which only includes a scss file (which seems also be the recommended way to do it). And because I'm just globbing all files within a folder I was not able to use addStyleSheetEntry instead, if an index.js file is missing.

````
const chalk = require('chalk');
const glob = require("glob");
const path = require('path');

// [...]

// add all components recursively as Encore entry
const entryPoints = glob.sync('**/index.js', {
  'cwd': './your/entrypoints/folder'
});

entryPoints.forEach((file) => {
  const filePath = './your/entrypoints/folder/' + file;
  const name = file.replace(/\/index\.js/, '');
  console.log(`adding entry ${chalk.green(name)} located at ${chalk.green(filePath)}`);
  Encore.addEntry(name, filePath);
});
````

However, this results in some empty index.js files. It would be great if those files could be removed afterwards. 

I noticed, the mini css extract plugin does support this when setting the type in the cacheGroups config, as shown here:
https://webpack.js.org/plugins/mini-css-extract-plugin/#extracting-all-css-in-a-single-file

*Note that type should be used instead of test in Webpack 5, or else an extra .js file can be generated besides the .css file. *

````

module.exports = {
  optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {
          name: 'styles',
          type: 'css/mini-extract',
          chunks: 'all',
          enforce: true,
        },
      },
    },
  },
````

Unfortunately I was not able to play around with the generated webpack config afterwards to add this. Maybe it would be possible to implement this approach and the encore plugin DeleteUnusedEntriesJSPlugin might not be needed anymore.

But I'm lacking some deeper knowledge here, so I'm not sure if it's possible ;-)

**Comment by weaverryan** [comment]
Hi!

> Maybe it would be possible to implement this approach and the encore plugin DeleteUnusedEntriesJSPlugin might not be needed anymore

It's possible - but I'm also not familiar with that part of MiniCssExtractPlugin, so I can't say. If someone wants to do some research, that would be awesome. Otherwise, the current solution works well enough :).

Sorry I can't help more - this stuff is complex and my time is short.

Cheers!
