### ISSUE TITLE
`sass-load` is way too slow

### ISSUE THREAD

**Issue by CyrilKrylatov** [symfony/webpack-encore#981]
Hello everyone,

It seems like this subject is coming back on the issues every now and then but I can't find an answer that really suits me.

You can see my webpack.config.js [right here](https://gist.github.com/CyrilKrylatov/900812073b3c4f2eecb8f241cec9224c).

I'm working with those versions:

```
"@symfony/webpack-encore": "1.3.0",
"node-sass": "6.0.0",
"sass-loader": "11.1.1",
```

So, as you can see:

```
 WAIT  Compiling...                                                                           4:03:21 PM

 DONE  Compiled successfully in 11909ms                                                       4:03:33 PM

351 files written to public/built/frontend
frontend:
  frontend compiled successfully
```

sass-loader takes almost 12 seconds to compile my files. That's quite a lot.

I know that's sass-loader because of [speed-measure-webpack-plugin](https://www.npmjs.com/package/speed-measure-webpack-plugin) that telling me it:

``` 
SMP  ⏱
General output time took 21.18 secs

 SMP  ⏱  Loaders
mini-css-extract-plugin, and
css-loader, and
resolve-url-loader, and
sass-loader took 11.95 secs
  module count = 12
css-loader, and
resolve-url-loader, and
sass-loader took 11.31 secs
  module count = 12
babel-loader took 2.56 secs
  module count = 63
modules with no loaders took 2.43 secs
  module count = 641
mini-css-extract-plugin, and
css-loader took 1.35 secs
  module count = 1
@symfony/webpack-encore took 0.944 secs
  module count = 292
css-loader took 0.168 secs
  module count = 1
```
  
So I tried to use `fast-sass-loader` instead of `sass-load` like [this gist](https://gist.github.com/aaronadal/863b3a647ddf8bb0f92fbf052a83429e) but if I add this in my config file I have the following error:

> Syntax Error: Error: You forgot to add ‘mini-css-extract-plugin’ plugin (i.e. { plugins: [new MiniCssExtractPlugin()] }), please read https://github.com/webpack-contrib/mini-css-extract-plugin#getting-started

If I add 
```
  .addPlugin(new MiniCssExtractPlugin({
    filename: 'index.[hash].css'
  }))
```
  
to resolve this, I have the following error: 
  
> [webpack-cli] Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered

Anyway I tried a lot of thing to remove `sass-loader` but I can't manage to make something work.

Does anyone have some tips to help me out?

Thank you! 🙏

**Comment by Kocal** [comment]
Can you try using `sass` instead of `node-sass`?

**Comment by CyrilKrylatov** [comment]
Sure, here we go:
```
-        "node-sass": "6.0.0",
+        "sass": "^1.32.13",
```

``` 
SMP  ⏱
General output time took 24.16 secs

 SMP  ⏱  Loaders
mini-css-extract-plugin, and
css-loader, and
resolve-url-loader, and
sass-loader took 16.77 secs
  module count = 12
css-loader, and
resolve-url-loader, and
sass-loader took 16.069 secs
  module count = 12
modules with no loaders took 4.71 secs
  module count = 641
babel-loader took 3.14 secs
  module count = 63
mini-css-extract-plugin, and
css-loader took 1.11 secs
  module count = 1
@symfony/webpack-encore took 1.048 secs
  module count = 292
css-loader took 0.183 secs
  module count = 1
  ```
  
  Without SMP:
  
  ```
 WAIT  Compiling...                                                                           4:26:20 PM

 DONE  Compiled successfully in 10987ms                                                       4:26:31 PM

351 files written to public/built/frontend
frontend:
  frontend compiled successfully
 WAIT  Compiling...                                                                           4:26:56 PM

 DONE  Compiled successfully in 10502ms                                                       4:27:07 PM

351 files written to public/built/frontend
frontend:
  frontend compiled successfully
```

That doesn't seems to change anything.

**Comment by giero** [comment]
There is also [dart sass](https://sass-lang.com/dart-sass) - maybe this one will work faster?

**Comment by weaverryan** [comment]
`dart-sass` === `sass` :) 

Btw, this doesn't look that slow to me - it's about 10 seconds and it's dumping 351 files. Nobody wants to wait 10 seconds, but it's not that slow, really.

**Comment by CyrilKrylatov** [comment]
> There is also [dart sass](https://sass-lang.com/dart-sass) - maybe this one will work faster?

dart sass is JavaScript-based so it's not faster than node-sass that is written in C++ (I hope I'm not making any mistakes here).

Anyway I tried and nope, the problem is really coming from sass-loader that is known to be slow.

**Comment by CyrilKrylatov** [comment]
> `dart-sass` === `sass` :)
> 
> Btw, this doesn't look that slow to me - it's about 10 seconds and it's dumping 351 files. Nobody wants to wait 10 seconds, but it's not that slow, really.

[fast-sass-loader](https://www.npmjs.com/package/fast-sass-loader) seems to have better performances but I didn't managed to make it work as you can see in my original message. 😞

**Comment by weaverryan** [comment]
> fast-sass-loader seems to have better performances but I didn't managed to make it work as you can see in my original message. 

I'm not familiar with this library - but it looks popular and promising. If someone can figure out what changes need to be made to the config to make it work, I'd be very happy to support it :). I'm not sure what the issue is - `MiniCssExtractPlugin` IS already a plugin that we use in all cases. https://github.com/symfony/webpack-encore/blob/972c8827500f3095dbaff06895a47ac0621bf28e/lib/plugins/mini-css-extract.js#L53-L61

**Comment by CyrilKrylatov** [comment]
Mmmmh, interesting, thank you for your interest (and your work in Webpack Encore 😀).

I tried to follow this gist https://gist.github.com/aaronadal/863b3a647ddf8bb0f92fbf052a83429e by replacing `.enableSassLoader()` with the content of said gist and I had various issues.

I [updated my own gist](https://gist.github.com/CyrilKrylatov/900812073b3c4f2eecb8f241cec9224c) that contains my webpack.config.js with the `.addLoader()` thing.

So you'll need those packages: `yarn add -D mini-css-extract-plugin fast-sass-loader sass@1.32.13` and remove those: `yarn remove sass-loader`

Then I have those following errors:

```
❯ yarn dev
yarn run v1.22.5
$ encore dev
Running webpack ...

 ERROR  Failed to compile with 2 errors                                                                              4:35:22 PM

 error  in ./assets/frontend/css/components/video-room.scss

ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'minimize'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, esModule? }


 error  in ./assets/frontend/css/imports/contact.scss

ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'minimize'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, esModule? }


frontend:
  frontend compiled with 28 errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

and I absolutely don't know why, even after Googling for a long time now.

Sooooo, I hope you'll do better than me on that. 😭

**Comment by weaverryan** [comment]
My guess is that the original gist you're following is for an older version of `css-loader`. The error is basically telling you to take out the `minimize` option, as it doesn't exist. You don't need that anymore, as other tools do the minimization.

**Comment by stof** [comment]
Note that `fast-sass-loader` is not without drawbacks: as it does not actually compile your original sass sources, it is incompatible with modern sass features like modules

**Comment by CyrilKrylatov** [comment]
So I managed to make the `css-loader` working, thank you @weaverryan for your advice and everything's working. I updated my gist with the configuration to make [Webpack Encore with fast-sass-loader and mini-css-extract-plugin](https://gist.github.com/CyrilKrylatov/900812073b3c4f2eecb8f241cec9224c) working together.

Anyway I don't think my performances issues on the watch are coming from here.

I made several tests:

## Bootrstrap compilation + copyfiles
```
 WAIT  Compiling...                                                                                                           

 DONE  Compiled successfully in 9867ms                                                                                        

351 files written to public/built/frontend
frontend:
  frontend compiled successfully
```

## Without Bootstrap
```
 WAIT  Compiling...                                                                                                           

 DONE  Compiled successfully in 8516ms                                                                                       

351 files written to public/built/frontend
frontend:
  frontend compiled successfully
```

## Without Bootrstrap, without CopyFiles
```
 WAIT  Compiling...                                                                                                           

 DONE  Compiled successfully in 8384ms                                                                                        

77 files written to public/built/frontend
frontend:
  frontend compiled successfully
``` 

I'll try to remove some things around and see where is the bottleneck.

Since it's not an issue with sass-load, neither with Webpack Encore, I'm closing this issue and I'll keep updating this comments with what I found, if that can help anyone in any way.

Thank you again for your time!
