### ISSUE TITLE
--no-live-reload gives no result in dev-server

### ISSUE THREAD

**Issue by BaHeK1994** [symfony/webpack-encore#991]
I start dev-server with the --no-live-reload parameter, but the page is still automatically updated after changes in the code.

System information
```
$ npm -v
7.14.0
$ nodejs -v
v14.17.0
$ yarn -v
1.22.5
$ node_modules/webpack-dev-server/bin/webpack-dev-server.js -v
@webpack-cli/serve 1.4.0
webpack 5.37.1
webpack-cli 4.7.0
webpack-dev-server 4.0.0-beta.3

**Comment by Kocal** [comment]
Encore already configure [`liveReload: false`](https://github.com/symfony/webpack-encore/blob/972c8827500f3095dbaff06895a47ac0621bf28e/lib/config-generator.js#L605) which is equivalent to `--no-live-reload` I guess.

What behaviour do you expect when running the dev server?

**Comment by BaHeK1994** [comment]
I need css/js to compile automatically when changed, but at the same time that the page does not update itself.

**Comment by stof** [comment]
To me, this looks like you want the behavior of `encore dev --watch` rather than `encore dev-server`
