### ISSUE TITLE
Support ts-loader 9

### ISSUE THREAD

**Issue by bobvandevijver** [symfony/webpack-encore#993]
ts-loader v9 is currently not supported.

**Comment by Kocal** [comment]
Breaking changes: https://github.com/TypeStrong/ts-loader/blob/main/CHANGELOG.md#v900

What should we do about the Node.js version? Since Encore provides support for Node.js 10. 
But since Node.js 10 is not maintened anymore, maybe we can drop its support...
WDYT?

**Comment by bobvandevijver** [comment]
It can still be supported as with #983, so once that has been merged allowing v9 for ts-loader doesn't seem like a problem. 

Dropping Node 10 was not the favorite option of @weaverryan due to Ubuntu LTS (see the discussing in #983).

**Comment by Kocal** [comment]
> Dropping Node 10 was not the favorite option of @weaverryan due to Ubuntu LTS (see the discussing in #983).

Hum, it reminds me the discussion on #912... I still don't understand why we would prefer to get stuck with an outdated Node.js version offered by Ubuntu (LTS or not), instead of using the PPA from Node.js, or nvm, or n... 😞  w/e

**Comment by weaverryan** [comment]
It's more: we want people using Ubuntu's LTS to be able to easily use Symfony or Encore, without needing to go outside the normal package manager to install a newer version of PHP or Node.

However, I also recognize that Node is especially tricky, since we seem to be an outlier in doing this - most packages drop Node support ASAP :)

**Comment by bobvandevijver** [comment]
Note that this no longer holds for Symfony 6 as that requires at least PHP 8, which is not available (without PPA) in Ubuntu LTS or the next stable Debian... I know that the choice was done for technical reasons as PHP 8 has several benefits, but dropping an officially unsupported version seems to be a similar choice.
